import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const root=process.cwd(); const read=(p:string)=>readFileSync(join(root,p),'utf8');

describe('MRP unit 10 manufacturing analytics contract',()=>{
  it('has official doc and checklist',()=>{expect(read('docs/mrp/10-manufacturing-analytics.md')).toContain('Manufacturing Analytics'); const c=read('docs/mrp/10-manufacturing-analytics-technical-checklist.md'); for(const term of ['KPI Targets','Executive','Bottleneck','Root Cause','Reports']) expect(c).toContain(term);});
  it('0228 migration implements analytics dashboards alerts RCA reports and exports',()=>{const sql=read('supabase/migrations/0228_mrp_manufacturing_analytics.sql'); for(const obj of ['mrp_manufacturing_kpi_targets','mrp_manufacturing_kpi_snapshots','mrp_manufacturing_analytics_alerts','mrp_manufacturing_predictive_insights','mrp_manufacturing_root_cause_analyses','mrp_manufacturing_report_runs','mrp_manufacturing_export_requests','mrp_manufacturing_executive_dashboard','mrp_production_performance_dashboard','mrp_oee_trend_report','mrp_schedule_attainment_report','mrp_bottleneck_analysis','mrp_quality_cost_dashboard','mrp_cost_variance_dashboard','mrp_maintenance_reliability_dashboard','mrp_manufacturing_kpi_scorecard','mrp_predictive_alert_queue','mrp_root_cause_analysis_board','mrp_manufacturing_report_center','mrp_manufacturing_export_queue']) expect(sql).toContain(obj); for(const fn of ['upsert_mrp_manufacturing_kpi_target','refresh_mrp_manufacturing_kpi_snapshots','generate_mrp_manufacturing_predictive_alerts','close_mrp_manufacturing_analytics_alert','create_mrp_manufacturing_root_cause_analysis','close_mrp_manufacturing_root_cause_analysis','generate_mrp_manufacturing_periodic_report','request_mrp_manufacturing_report_export']) expect(sql).toContain(fn); const ux=read('supabase/migrations/0239_mrp_analytics_ux_actions.sql'); for(const fn of ['update_mrp_manufacturing_kpi_target_status','update_mrp_manufacturing_analytics_alert_status','update_mrp_manufacturing_rca_status','cancel_mrp_manufacturing_report_run','update_mrp_manufacturing_export_status']) expect(ux).toContain(fn); expect(sql).toContain('tenant_id=public.current_user_tenant_id()'); expect(sql).not.toContain('p_tenant_id');});
  it('exports SDK and app pages/routes/sidebar/hybrid/admin catalog',()=>{expect(read('src/services/sdk/MrpAnalyticsService.ts')).toContain('mrpManufacturingAnalyticsService'); expect(read('src/services/sdk/index.ts')).toContain('mrpManufacturingAlertService'); expect(read('src/router/AppRouter.tsx')).toContain('path="analytics/root-cause"'); expect(read('src/router/legacyRedirect.ts')).toContain('mrp-analytics-kpi-targets'); expect(read('src/shared/components/dashboard/Sidebar.tsx')).toContain('mrp-analytics'); expect(read('src/pages/hybridportal/hybridPagesCatalog.ts')).toContain('mrp-analytics-cost-variance'); expect(read('src/pages/admin/AdminEmployeesPage.tsx')).toContain('mrp-analytics-reports');});
});
