import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const root=process.cwd(); const read=(p:string)=>readFileSync(join(root,p),'utf8');

describe('MRP unit 03 production planning/work orders contract',()=>{
  it('has official doc and checklist',()=>{expect(read('docs/mrp/03-production-planning-work-orders.md')).toContain('Work Orders'); expect(read('docs/mrp/03-production-planning-work-orders-technical-checklist.md')).toContain('Critical Ratio');});
  it('0221 migration implements MRP runs planned orders work orders routing copies scheduling reservations and alerts',()=>{const sql=read('supabase/migrations/0221_mrp_production_planning_work_orders.sql'); for(const obj of ['mrp_runs','mrp_planned_orders','mrp_work_orders','mrp_work_order_materials','mrp_work_order_operations','mrp_work_order_reservations','mrp_production_schedules','mrp_dispatch_list','mrp_work_order_alerts','mrp_planning_dashboard','mrp_planned_order_review_queue','mrp_work_order_dashboard','mrp_work_order_material_status','mrp_work_order_operation_status','mrp_production_schedule_board','mrp_dispatch_queue','mrp_work_order_alert_queue','mrp_production_planning_kpis']) expect(sql).toContain(obj); for(const fn of ['run_mrp_from_mps','review_planned_order','create_mrp_work_order','convert_planned_order_to_work_order','schedule_mrp_work_order','release_mrp_work_order','issue_mrp_work_order_material','start_mrp_work_order','complete_mrp_work_order_operation','complete_mrp_work_order','close_mrp_work_order','refresh_mrp_work_order_critical_ratio','generate_mrp_work_order_alerts']) expect(sql).toContain(fn); const ux=read('supabase/migrations/0232_mrp_planning_work_orders_ux_actions.sql'); for(const fn of ['hold_mrp_work_order','resume_mrp_work_order','cancel_mrp_work_order','create_mrp_dispatch_item','update_mrp_dispatch_status','close_mrp_work_order_alert']) expect(ux).toContain(fn); expect(sql).toContain('reserve_inventory'); expect(sql).toContain('post_inventory_movement'); expect(sql).not.toContain('p_tenant_id');});
  it('exports SDK and pages/routes',()=>{expect(read('src/services/sdk/MrpPlanningService.ts')).toContain('mrpWorkOrderService'); expect(read('src/services/sdk/index.ts')).toContain('mrpPlanningAnalyticsService'); expect(read('src/router/AppRouter.tsx')).toContain('path="planning/work-orders"'); expect(read('src/router/legacyRedirect.ts')).toContain('mrp-work-orders'); expect(read('src/shared/components/dashboard/Sidebar.tsx')).toContain('mrp-planning'); for(const p of ['PlanningDashboard','MrpRunsPage','PlannedOrdersPage','WorkOrdersPage','WorkOrderMaterialsPage','WorkOrderOperationsPage','ProductionSchedulingPage','DispatchPage','WorkOrderAlertsPage','PlanningReportsPage']) expect(read(`src/pages/app/mrp/planning/${p}.tsx`)).toContain('MrpPlanningPage');});
});
