import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const root=process.cwd(); const read=(p:string)=>readFileSync(join(root,p),'utf8');

describe('MRP unit 05 procurement integration contract',()=>{
  it('has official doc and checklist',()=>{expect(read('docs/mrp/05-procurement-supplier-management.md')).toContain('Procurement'); expect(read('docs/mrp/05-procurement-integration-technical-checklist.md')).toContain('Procure-to-Pay');});
  it('0223 migration implements recommendations PR conversion TCO supplier scorecard statuses and alerts',()=>{const sql=read('supabase/migrations/0223_mrp_procurement_integration.sql'); for(const obj of ['mrp_procurement_recommendations','mrp_procurement_links','mrp_supplier_tco_evaluations','mrp_procurement_alerts','mrp_procurement_dashboard','mrp_procurement_recommendation_queue','mrp_procurement_pr_status','mrp_procurement_po_status','mrp_procurement_gr_status','mrp_procurement_invoice_match_status','mrp_supplier_scorecard','mrp_procurement_contract_alerts','mrp_procurement_kpis','mrp_procurement_alert_queue']) expect(sql).toContain(obj); for(const fn of ['create_mrp_procurement_recommendation','generate_mrp_procurement_recommendations_from_shortages','convert_mrp_recommendation_to_pr','add_mrp_supplier_tco_candidate','generate_mrp_procurement_alerts']) expect(sql).toContain(fn); const ux=read('supabase/migrations/0234_mrp_procurement_ux_actions.sql'); for(const fn of ['review_mrp_procurement_recommendation','award_mrp_supplier_tco_candidate','close_mrp_procurement_alert']) expect(ux).toContain(fn); expect(sql).toContain('create_purchase_requisition_full'); expect(sql).not.toContain('p_tenant_id');});
  it('exports SDK and pages/routes',()=>{expect(read('src/services/sdk/MrpProcurementService.ts')).toContain('mrpProcurementRecommendationService'); expect(read('src/services/sdk/index.ts')).toContain('mrpProcurementAnalyticsService'); expect(read('src/router/AppRouter.tsx')).toContain('path="procurement/recommendations"'); expect(read('src/router/legacyRedirect.ts')).toContain('mrp-procurement'); expect(read('src/shared/components/dashboard/Sidebar.tsx')).toContain('mrp-procurement');});
});
