import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const root=process.cwd(); const read=(p:string)=>readFileSync(join(root,p),'utf8');

describe('MRP unit 06 quality management contract',()=>{
  it('has official doc and checklist',()=>{expect(read('docs/mrp/06-quality-management.md')).toContain('Quality Management'); expect(read('docs/mrp/06-quality-management-technical-checklist.md')).toContain('AQL');});
  it('0224 migration implements IQC IPQC OQC AQL NCR CAPA calibration SPC quarantine and KPIs',()=>{const sql=read('supabase/migrations/0224_mrp_quality_management.sql'); for(const obj of ['mrp_quality_inspection_plans','mrp_quality_inspection_points','mrp_quality_checklist_templates','mrp_quality_checklist_items','mrp_quality_aql_rules','mrp_quality_inspections','mrp_quality_inspection_results','mrp_quality_ncrs','mrp_quality_capa_actions','mrp_quality_measurement_devices','mrp_quality_calibration_events','mrp_quality_spc_measurements','mrp_quality_quarantine_decisions','mrp_quality_dashboard','mrp_quality_inspection_queue','mrp_quality_ncr_dashboard','mrp_quality_capa_dashboard','mrp_quality_calibration_due','mrp_quality_spc_alerts','mrp_quality_quarantine_queue','mrp_quality_kpis']) expect(sql).toContain(obj); for(const fn of ['create_mrp_quality_inspection_plan','calculate_mrp_aql_sample','start_mrp_quality_inspection','record_mrp_quality_result','complete_mrp_quality_inspection','create_mrp_quality_ncr','decide_mrp_quality_ncr','create_mrp_capa','close_mrp_capa','record_mrp_calibration_event','record_mrp_spc_measurement']) expect(sql).toContain(fn); const ux=read('supabase/migrations/0235_mrp_quality_ux_actions.sql'); for(const fn of ['create_mrp_quality_checklist_template','add_mrp_quality_checklist_item','create_mrp_quality_inspection_point','cancel_mrp_quality_inspection','upsert_mrp_quality_measurement_device','create_mrp_quality_quarantine_decision']) expect(ux).toContain(fn); expect(sql).toContain('IQC'); expect(sql).toContain('IPQC'); expect(sql).toContain('OQC'); expect(sql).not.toContain('p_tenant_id');});
  it('exports SDK and pages/routes',()=>{expect(read('src/services/sdk/MrpQualityService.ts')).toContain('mrpQualityPlanService'); expect(read('src/services/sdk/index.ts')).toContain('mrpQualityAnalyticsService'); expect(read('src/router/AppRouter.tsx')).toContain('path="quality/inspections"'); expect(read('src/router/legacyRedirect.ts')).toContain('mrp-quality'); expect(read('src/shared/components/dashboard/Sidebar.tsx')).toContain('mrp-quality');});
});
