import { useEffect, useState } from 'react';
import { ItemLookup, SupplierLookup } from '../../inventory/shared/InventoryLookups';
import { InventoryRecordTools } from '../../inventory/shared/InventoryRecordTools';
import { mrpLookupService, mrpBomAnalyticsService, mrpBomAvailabilityService, mrpBomExportRequestService, mrpBomExplosionService, mrpBomHeaderService, mrpBomImportBatchService, mrpBomLineService, mrpBomVersionService, mrpEcoService, mrpEcrService } from '../../../../services/sdk';
import { MrpUnitNav } from '../shared/MrpUnitNav';

type Row=Record<string,unknown>; type Form=Record<string,string>;
type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void,type='text'){return <label className="text-xs font-bold"><span>{l}</span><input type={type} value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function area(l:string,n:string,f:Form,set:(p:Form)=>void){return <label className="text-xs font-bold md:col-span-3"><span>{l}</span><textarea value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1" rows={3}/></label>}
function select(l:string,n:string,f:Form,set:(p:Form)=>void,ops:string[]){return <label className="text-xs font-bold"><span>{l}</span><select value={f[n]||ops[0]} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1 bg-white">{ops.map(o=><option key={o}>{o}</option>)}</select></label>}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 rounded-xl p-2">{msg}</div>:null}

function BomVersionLookup({value,onChange,label='BOM Version'}:{value?:string;onChange:(id:string)=>void;label?:string}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('bomVersionDetailed').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>{label}</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String((r.mrp_bom_headers as Row)?.bom_code||'BOM')} — v{String(r.version_no)} — {String(r.status)}</option>)}</select></label>}
function BomLineLookup({value,onChange,label='Parent Line'}:{value?:string;onChange:(id:string)=>void;label?:string}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('bomLine').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>{label}</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- بدون --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>Line {String(r.line_no)} — {String(r.id).slice(0,8)}…</option>)}</select></label>}
function EcrLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('ecr').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>ECR</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.ecr_number)} — {String(r.status)} — {String(r.reason).slice(0,40)}</option>)}</select></label>}
function EcoLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('eco').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>ECO</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.eco_number)} — {String(r.status)} — {String(r.effectivity_date||'')}</option>)}</select></label>}

const cfgs:Record<string,Config>={
 dashboard:{title:'BOM & Engineering Change',subtitle:'إدارة BOM، الإصدارات، التفجير، التوافر، ECR/ECO.',load:()=>mrpBomAnalyticsService.dashboard() as Promise<Row[]>,columns:[{key:'bom_count',label:'BOMs'},{key:'effective_versions',label:'فعالة'},{key:'open_ecr',label:'ECR مفتوحة'},{key:'open_eco',label:'ECO مفتوحة'}]},
 headers:{title:'BOM Headers',subtitle:'EBOM/MBOM/SBOM/Sales BOM',load:()=>mrpBomHeaderService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'bom',columns:[{key:'bom_code',label:'الكود'},{key:'bom_type',label:'النوع'},{key:'structure_type',label:'الهيكل'},{key:'status',label:'الحالة'}]},
 versions:{title:'BOM Versions',subtitle:'الإصدارات والاعتماد والفعالية',load:()=>mrpBomVersionService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'version',columns:[{key:'version_no',label:'الإصدار'},{key:'status',label:'الحالة'},{key:'effective_from',label:'من'},{key:'effective_to',label:'إلى'}]},
 builder:{title:'Visual BOM Builder',subtitle:'هيكل شجري متعدد المستويات لبنود BOM',load:()=>mrpBomAnalyticsService.tree() as Promise<Row[]>,action:'line',columns:[{key:'level_no',label:'المستوى'},{key:'line_no',label:'السطر'},{key:'item_code',label:'الصنف'},{key:'quantity_per',label:'Qty/Unit'},{key:'scrap_percent',label:'Scrap %'},{key:'supply_type',label:'المصدر'}]},
 lines:{title:'BOM Lines',subtitle:'بنود BOM الكاملة',load:()=>mrpBomLineService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'line',columns:[{key:'line_no',label:'السطر'},{key:'component_item_id',label:'الصنف'},{key:'quantity_per',label:'Qty'},{key:'scrap_percent',label:'Scrap'},{key:'supply_type',label:'المصدر'}]},
 explosion:{title:'BOM Explosion',subtitle:'تفجير BOM وحساب المتطلبات',load:()=>mrpBomAnalyticsService.explosion() as Promise<Row[]>,action:'explode',columns:[{key:'run_number',label:'Run'},{key:'demand_quantity',label:'الطلب'},{key:'line_count',label:'بنود'},{key:'total_required',label:'إجمالي'},{key:'total_shortage',label:'نقص'}]},
 availability:{title:'Availability Check',subtitle:'فحص توفر المواد قبل أمر الإنتاج',load:()=>mrpBomAnalyticsService.shortages() as Promise<Row[]>,action:'availability',columns:[{key:'check_number',label:'الفحص'},{key:'item_code',label:'الصنف'},{key:'required_quantity',label:'مطلوب'},{key:'available_quantity',label:'متاح'},{key:'shortage_quantity',label:'نقص'},{key:'recommendation',label:'توصية'}]},
 ecr:{title:'ECR',subtitle:'طلبات التغيير الهندسي',load:()=>mrpEcrService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'ecr',columns:[{key:'ecr_number',label:'ECR'},{key:'request_source',label:'المصدر'},{key:'reason',label:'السبب'},{key:'status',label:'الحالة'}]},
 eco:{title:'ECO',subtitle:'أوامر التغيير الهندسي وEffectivity',load:()=>mrpBomAnalyticsService.eco() as Promise<Row[]>,action:'eco',columns:[{key:'eco_number',label:'ECO'},{key:'ecr_number',label:'ECR'},{key:'effectivity_date',label:'تاريخ التطبيق'},{key:'status',label:'الحالة'}]},
 importExport:{title:'استيراد/تصدير BOM',subtitle:'طلبات Excel/CSV وملفات الاستيراد',load:()=>mrpBomExportRequestService.findAll({orderBy:'requested_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'export',columns:[{key:'request_number',label:'الطلب'},{key:'export_type',label:'النوع'},{key:'status',label:'الحالة'},{key:'file_url',label:'ملف'}]},
 reports:{title:'BOM KPIs',subtitle:'دقة واكتمال BOM وECO',load:()=>mrpBomAnalyticsService.kpis() as Promise<Row[]>,columns:[{key:'bom_count',label:'BOMs'},{key:'effective_bom_percent',label:'فعالية %'},{key:'bom_completeness_percent',label:'اكتمال %'},{key:'open_ecr_count',label:'ECR مفتوحة'}]},
};
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({bom_type:'MBOM',structure_type:'multi_level',version_no:'1.0',material_type:'raw',supply_type:'buy',uom:'PCS',quantity_per:'1',line_no:'10',demand_quantity:'1',request_source:'manual',export_type:'excel'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r||'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='bom')return <Box title="إنشاء BOM"><div className="grid md:grid-cols-3 gap-3"><ItemLookup label="المنتج النهائي" value={f.item_id} onChange={id=>set({item_id:id})} required />{inp('BOM Code اختياري','bom_code',f,set)}{select('BOM Type','bom_type',f,set,['EBOM','MBOM','SBOM','SALES'])}{select('Structure','structure_type',f,set,['single_level','multi_level'])}{inp('Name','name_ar',f,set)}{inp('Version','version_no',f,set)}<button onClick={()=>void run(()=>mrpBomHeaderService.createBom(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create BOM</button><Msg msg={msg}/></div></Box>;
 if(type==='version')return <Box title="اعتماد/نسخ إصدار"><div className="grid md:grid-cols-3 gap-3"><BomVersionLookup value={f.bom_version_id} onChange={id=>set({bom_version_id:id})}/>{inp('Effective From','effective_from',f,set,'date')}<button onClick={()=>void run(()=>mrpBomVersionService.submitForApproval(f.bom_version_id))} className="bg-amber-600 text-white rounded-xl p-2">تقديم للاعتماد</button><button onClick={()=>void run(()=>mrpBomVersionService.approve(f.bom_version_id,f.effective_from))} className="bg-emerald-600 text-white rounded-xl p-2">Approve Effective</button>{inp('New Version','new_version_no',f,set)}{inp('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpBomVersionService.duplicate(f.bom_version_id,f.new_version_no,f.reason))} className="bg-indigo-600 text-white rounded-xl p-2">Duplicate</button><Msg msg={msg}/></div></Box>;
 if(type==='line')return <Box title="إضافة بند BOM"><div className="grid md:grid-cols-3 gap-3"><BomVersionLookup value={f.bom_version_id} onChange={id=>set({bom_version_id:id})}/><BomLineLookup value={f.parent_line_id} onChange={id=>set({parent_line_id:id})}/>{inp('Line No','line_no',f,set)}<ItemLookup label="المكون" value={f.component_item_id} onChange={id=>set({component_item_id:id})} required />{inp('Qty per','quantity_per',f,set)}{inp('UOM','uom',f,set)}{inp('Scrap %','scrap_percent',f,set)}{select('Material Type','material_type',f,set,['raw','component','subassembly','packaging','phantom','service','byproduct','coproduct'])}{select('Supply Type','supply_type',f,set,['buy','make','subcontract','transfer'])}{area('Notes','notes',f,set)}<button onClick={()=>void run(()=>mrpBomLineService.addLine(f))} className="bg-indigo-600 text-white rounded-xl p-2">Add Line</button><BomLineLookup label="BOM Line للبديل/المورد" value={f.bom_line_id} onChange={id=>set({bom_line_id:id})}/><ItemLookup label="صنف بديل" value={f.substitute_item_id} onChange={id=>set({substitute_item_id:id})}/>{inp('Priority','priority',f,set,'number')}{inp('Conversion Factor','conversion_factor',f,set,'number')}<button onClick={()=>void run(()=>mrpBomLineService.addSubstitute(f))} className="bg-slate-700 text-white rounded-xl p-2">Add Substitute</button><SupplierLookup label="مورد البند" value={f.supplier_id} onChange={id=>set({supplier_id:id})}/>{inp('Supplier Part No','supplier_part_number',f,set)}{inp('Lead Time Days','lead_time_days',f,set,'number')}{inp('Unit Price','unit_price',f,set,'number')}<button onClick={()=>void run(()=>mrpBomLineService.addSupplier(f))} className="bg-emerald-600 text-white rounded-xl p-2">Add Supplier</button><Msg msg={msg}/></div></Box>;
 if(type==='explode'||type==='availability')return <Box title={type==='explode'?'تفجير BOM':'فحص التوافر'}><div className="grid md:grid-cols-3 gap-3"><BomVersionLookup value={f.bom_version_id} onChange={id=>set({bom_version_id:id})}/>{inp('Demand Qty','demand_quantity',f,set)}<button onClick={()=>void run(()=>type==='explode'?mrpBomExplosionService.explode(f.bom_version_id,Number(f.demand_quantity||1)):mrpBomAvailabilityService.check(f.bom_version_id,Number(f.demand_quantity||1)))} className="bg-indigo-600 text-white rounded-xl p-2">Run</button><Msg msg={msg}/></div></Box>;
 if(type==='ecr')return <Box title="إنشاء/إغلاق ECR"><div className="grid md:grid-cols-3 gap-3">{select('Source','request_source',f,set,['engineering','production','quality','procurement','customer','manual'])}{inp('Reason','reason',f,set)}{area('Proposed Change','proposed_change',f,set)}<button onClick={()=>void run(()=>mrpEcrService.createEcr(f.reason,f.proposed_change,f.request_source))} className="bg-indigo-600 text-white rounded-xl p-2">Create ECR</button><EcrLookup value={f.ecr_id} onChange={id=>set({ecr_id:id})}/>{select('Close Status','ecr_status',f,set,['approved_for_eco','rejected','closed'])}{inp('Close Reason','close_reason',f,set)}<button onClick={()=>void run(()=>mrpEcrService.close(f.ecr_id,f.ecr_status,f.close_reason))} className="bg-emerald-600 text-white rounded-xl p-2">Close/Approve ECR</button><Msg msg={msg}/></div></Box>;
 if(type==='eco')return <Box title="إنشاء/تطبيق ECO"><div className="grid md:grid-cols-3 gap-3"><EcrLookup value={f.ecr_id} onChange={id=>set({ecr_id:id})}/><BomVersionLookup value={f.bom_version_id} onChange={id=>set({bom_version_id:id})}/>{inp('Effectivity Date','effectivity_date',f,set,'date')}{area('Impact Summary','impact_summary',f,set)}{area('Implementation Plan','implementation_plan',f,set)}<button onClick={()=>void run(()=>mrpEcoService.createEco(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create ECO</button><EcoLookup value={f.eco_id} onChange={id=>set({eco_id:id})}/><button onClick={()=>void run(()=>mrpEcoService.implement(f.eco_id))} className="bg-emerald-600 text-white rounded-xl p-2">Implement</button><Msg msg={msg}/></div></Box>;
 if(type==='export')return <Box title="استيراد/تصدير BOM"><div className="grid md:grid-cols-3 gap-3"><BomVersionLookup value={f.bom_version_id} onChange={id=>set({bom_version_id:id})}/>{select('Export Type','export_type',f,set,['excel','csv','json'])}<button onClick={()=>void run(()=>mrpBomExportRequestService.request(f.bom_version_id,f.export_type))} className="bg-indigo-600 text-white rounded-xl p-2">Request Export</button>{inp('Import File Name','file_name',f,set)}{inp('File URL','file_url',f,set)}{select('Import Type','import_type',f,set,['excel','csv','api'])}<button onClick={()=>void run(()=>mrpBomImportBatchService.createBatch(f))} className="bg-slate-700 text-white rounded-xl p-2">Create Import Batch</button><Msg msg={msg}/></div></Box>;
 return null}
export function MrpBomPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{type==='dashboard'&&<MrpUnitNav unit="bom" />}{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
