import { useEffect, useState } from 'react';
import { InventoryRecordTools } from '../shared/InventoryRecordTools';
import { AlertLookup, ReportRunLookup, WarehouseLookup } from '../shared/InventoryLookups';
import { inventoryAnalyticsAlertRuleService, inventoryAnalyticsAlertService, inventoryAnalyticsKpiSnapshotService, inventoryAnalyticsKpiTargetService, inventoryOperatingCostEntryService, inventoryPeriodicReportRunService, inventoryPeriodicReportScheduleService, inventoryReportExportService, inventoryRootCauseAnalysisService, inventoryWarehouseAnalyticsService } from '../../../../services/sdk';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
const today=()=>new Date().toISOString().slice(0,10);
const cfgs:Record<string,Config>={
 executive:{title:'لوحة المؤشرات التنفيذية',subtitle:'قيمة المخزون، IRA، استغلال المساحة، Perfect Order، الاتجاهات والتنبيهات',load:()=>inventoryWarehouseAnalyticsService.executive() as Promise<Row[]>,action:'refresh',columns:[{key:'inventory_value',label:'قيمة المخزون'},{key:'inventory_accuracy_percent',label:'دقة المخزون %'},{key:'space_utilization_percent',label:'استغلال المساحة %'},{key:'perfect_order_rate',label:'Perfect Order %'},{key:'urgent_alerts',label:'عاجل'}]},
 operations:{title:'لوحة مدير المستودع',subtitle:'تحديث تشغيلي: المهام، الإنتاجية، الأرصفة، والأوامر الحرجة خلال ساعتين',load:()=>inventoryWarehouseAnalyticsService.operations() as Promise<Row[]>,columns:[{key:'completed_tasks_today',label:'منجزة اليوم'},{key:'active_tasks_today',label:'نشطة'},{key:'team_productivity_percent',label:'إنتاجية الفريق %'},{key:'waiting_tasks',label:'انتظار'},{key:'active_dock_appointments',label:'أرصفة نشطة'}]},
 supervisor:{title:'لوحة مشرف الوردية',subtitle:'وقت فعلي: الموظفون، الخمول، انتظار التعبئة، والمهام العاجلة',load:()=>inventoryWarehouseAnalyticsService.supervisor() as Promise<Row[]>,columns:[{key:'idle_workers_8min',label:'خاملون +8د'},{key:'packing_queue',label:'انتظار تعبئة'},{key:'urgent_open_tasks',label:'مهام عاجلة'},{key:'employees_now',label:'الموظفون الآن'}]},
 scorecard:{title:'KPI Scorecard',subtitle:'مقارنة فورية بالهدف وترميز أخضر/أصفر/أحمر',load:()=>inventoryWarehouseAnalyticsService.scorecard() as Promise<Row[]>,action:'targets',columns:[{key:'kpi_group',label:'المجموعة'},{key:'name_ar',label:'المؤشر'},{key:'kpi_value',label:'القيمة'},{key:'unit',label:'الوحدة'},{key:'color_status',label:'اللون'}]},
 trends:{title:'تحليل الاتجاهات',subtitle:'سجل تاريخي لكل KPI مع delta لفهم التحسن أو التراجع',load:()=>inventoryWarehouseAnalyticsService.trends() as Promise<Row[]>,action:'refresh',columns:[{key:'snapshot_date',label:'التاريخ'},{key:'name_ar',label:'المؤشر'},{key:'kpi_value',label:'القيمة'},{key:'previous_value',label:'السابق'},{key:'delta_value',label:'التغير'}]},
 heatmap:{title:'خريطة حرارة المستودع',subtitle:'Hot/Warm/Cold حسب حركة المواقع وسعة التخزين',load:()=>inventoryWarehouseAnalyticsService.heatmap() as Promise<Row[]>,columns:[{key:'location_code',label:'الموقع'},{key:'aisle_code',label:'الممر'},{key:'movement_count',label:'الحركات'},{key:'capacity_percent',label:'السعة %'},{key:'heat_level',label:'Heat'}]},
 seasonal:{title:'الأنماط الموسمية',subtitle:'تحليل حركة المخزون خلال 24 شهراً لتغذية ROP/MRP',load:()=>inventoryWarehouseAnalyticsService.seasonal() as Promise<Row[]>,columns:[{key:'item_code',label:'الصنف'},{key:'quarter_no',label:'الربع'},{key:'month_name',label:'الشهر'},{key:'outbound_qty',label:'الخروج'},{key:'avg_quarter_qty',label:'متوسط الربع'}]},
 rootcause:{title:'تحليل جذر السبب التلقائي',subtitle:'عند انحراف KPI: مناطق/أصناف/وردية/موظفون وتوصية قابلة للتنفيذ',load:()=>inventoryWarehouseAnalyticsService.rootCause() as Promise<Row[]>,action:'rootcause',columns:[{key:'analysis_number',label:'التحليل'},{key:'kpi_code',label:'KPI'},{key:'most_affected_area',label:'منطقة'},{key:'root_cause_summary',label:'الخلاصة'},{key:'status',label:'الحالة'}]},
 alerts:{title:'التنبيهات الاستباقية',subtitle:'Urgent / Warning / Info: stockout, capacity, IRA, productivity, expiry, slow moving',load:()=>inventoryWarehouseAnalyticsService.alerts() as Promise<Row[]>,action:'alerts',columns:[{key:'severity',label:'الشدة'},{key:'alert_category',label:'الفئة'},{key:'title',label:'العنوان'},{key:'current_value',label:'القيمة'},{key:'status',label:'الحالة'}]},
 reports:{title:'التقارير الدورية',subtitle:'Daily Operations / Weekly Performance / Monthly Review مع Payload جاهز للإرسال',load:()=>inventoryWarehouseAnalyticsService.reports() as Promise<Row[]>,action:'report',columns:[{key:'report_number',label:'التقرير'},{key:'report_type',label:'النوع'},{key:'period_start',label:'من'},{key:'period_end',label:'إلى'},{key:'delivery_status',label:'الإرسال'}]},
 exports:{title:'تصدير التقارير',subtitle:'طلبات Excel/PDF/CSV/JSON بضغطة واحدة؛ توليد الملف Runtime لاحقاً',load:()=>inventoryReportExportService.findAll({orderBy:'requested_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'export',columns:[{key:'report_run_id',label:'Report Run'},{key:'export_type',label:'النوع'},{key:'status',label:'الحالة'},{key:'file_url',label:'رابط'},{key:'requested_at',label:'تاريخ'}]},
 costs:{title:'لوحة تكاليف التشغيل',subtitle:'عمالة + شحن + صيانة + إعادة عمل + إجمالي/وحدة',load:()=>inventoryWarehouseAnalyticsService.costs() as Promise<Row[]>,action:'cost',columns:[{key:'cost_date',label:'التاريخ'},{key:'cost_category',label:'الفئة'},{key:'total_amount',label:'الإجمالي'},{key:'units_handled',label:'الوحدات'},{key:'cost_per_unit',label:'تكلفة/وحدة'}]},
 targets:{title:'أهداف المؤشرات',subtitle:'إعداد أهداف KPI واتجاهات higher/lower/range عبر seed افتراضي',load:()=>inventoryAnalyticsKpiTargetService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'targets',columns:[{key:'kpi_code',label:'KPI'},{key:'green_min',label:'Green Min'},{key:'green_max',label:'Green Max'},{key:'yellow_min',label:'Yellow Min'},{key:'yellow_max',label:'Yellow Max'}]}
};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void){return <label className="text-xs font-bold"><span>{l}</span><input value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({snapshot_date:today(),from:today(),to:today(),report_type:'daily_operations',export_type:'excel',cost_category:'maintenance',amount:'0',units_handled:'0',schedule_cron:'0 8 * * *'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r||'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='refresh')return <Box title="تحديث KPI Snapshots"><div className="grid md:grid-cols-3 gap-3">{inp('Snapshot Date','snapshot_date',f,set)}<button onClick={()=>void run(()=>inventoryAnalyticsKpiSnapshotService.refresh(f.snapshot_date))} className="bg-indigo-600 text-white rounded-xl p-2">Refresh KPIs</button><Msg msg={msg}/></div></Box>;
 if(type==='targets')return <Box title="أهداف KPI"><div className="grid md:grid-cols-3 gap-3">{inp('Warehouse ID اختياري','warehouse_id',f,set)}<button onClick={()=>void run(()=>inventoryAnalyticsKpiTargetService.seed(f.warehouse_id||undefined))} className="bg-indigo-600 text-white rounded-xl p-2">Seed Targets</button><Msg msg={msg}/></div></Box>;
 if(type==='rootcause')return <Box title="تشغيل Root Cause"><div className="grid md:grid-cols-3 gap-3">{inp('KPI Code','kpi_code',f,set)}{inp('From','from',f,set)}{inp('To','to',f,set)}<button onClick={()=>void run(()=>inventoryRootCauseAnalysisService.run(f.kpi_code,f.from,f.to))} className="bg-indigo-600 text-white rounded-xl p-2">Run RCA</button><Msg msg={msg}/></div></Box>;
 if(type==='alerts')return <Box title="تنبيهات استباقية"><div className="grid md:grid-cols-3 gap-3"><button onClick={()=>void run(()=>inventoryAnalyticsAlertRuleService.seed())} className="bg-slate-700 text-white rounded-xl p-2">Seed Rules</button><button onClick={()=>void run(()=>inventoryAnalyticsAlertService.generate())} className="bg-indigo-600 text-white rounded-xl p-2">Generate Alerts</button><AlertLookup label="اختر التنبيه" value={f.alert_id} onChange={(id)=>set({alert_id:id})} /><button onClick={()=>void run(()=>inventoryAnalyticsAlertService.acknowledge(f.alert_id,'acknowledged'))} className="bg-emerald-600 text-white rounded-xl p-2">Acknowledge</button><Msg msg={msg}/></div></Box>;
 if(type==='report')return <Box title="جدولة/توليد تقرير"><div className="grid md:grid-cols-3 gap-3">{inp('Report Type','report_type',f,set)}{inp('Cron','schedule_cron',f,set)}{inp('Recipients comma','recipients',f,set)}<button onClick={()=>void run(()=>inventoryPeriodicReportScheduleService.upsert(f.report_type,f.schedule_cron,(f.recipients||'').split(',').filter(Boolean)))} className="bg-slate-700 text-white rounded-xl p-2">Save Schedule</button>{inp('From','from',f,set)}{inp('To','to',f,set)}<button onClick={()=>void run(()=>inventoryPeriodicReportRunService.generate(f.report_type,f.from,f.to))} className="bg-indigo-600 text-white rounded-xl p-2">Generate Report</button><Msg msg={msg}/></div></Box>;
 if(type==='export')return <Box title="طلب تصدير"><div className="grid md:grid-cols-3 gap-3"><ReportRunLookup label="اختر تشغيل التقرير" value={f.report_run_id} onChange={(id)=>set({report_run_id:id})} />{inp('Export Type excel/pdf/csv/json','export_type',f,set)}<button onClick={()=>void run(()=>inventoryReportExportService.request(f.report_run_id,f.export_type))} className="bg-indigo-600 text-white rounded-xl p-2">Request Export</button><Msg msg={msg}/></div></Box>;
 if(type==='cost')return <Box title="تسجيل تكلفة تشغيل"><div className="grid md:grid-cols-3 gap-3"><WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} />{inp('Cost Date','cost_date',f,set)}{inp('Category','cost_category',f,set)}{inp('Amount','amount',f,set)}{inp('Units','units_handled',f,set)}{inp('Notes','notes',f,set)}<button onClick={()=>void run(()=>inventoryOperatingCostEntryService.record({...f,amount:Number(f.amount||0),units_handled:Number(f.units_handled||0)}))} className="bg-indigo-600 text-white rounded-xl p-2">Record Cost</button><Msg msg={msg}/></div></Box>;
 return null}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 p-2 rounded-xl">{msg}</div>:null}
export function AnalyticsPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3 max-w-md truncate">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
