import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { supabase } from '../../../services/supabase/supabase';
import Button from '../../../shared/components/ui/Button';
import Input from '../../../shared/components/ui/Input';

type Line = { po_line_item_id: string; item_code: string; description: string; quantity: number; unit_price: number };
const emptyLine = (): Line => ({ po_line_item_id: '', item_code: '', description: '', quantity: 1, unit_price: 0 });

export default function SupplierInvoicePortalPage() {
  const { token } = useParams();
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [done,setDone]=useState(false);
  const [supplier,setSupplier]=useState<any>(null); const [pos,setPos]=useState<any[]>([]);
  const [form,setForm]=useState({po_id:'',invoice_number:'',invoice_date:new Date().toISOString().slice(0,10),amount_before_tax:0,tax_rate:15,currency_code:'SAR',payment_due_date:'',payment_terms:'Net45',bank_account:'',lines:[emptyLine()]});
  const load=async()=>{setLoading(true);setError('');try{const {data,error:e}=await supabase.functions.invoke('procurement-supplier-invoice',{body:{action:'verify',token}});if(e)throw e;if(data?.error)throw new Error(data.error);setSupplier(data.supplier);setPos(data.pos||[])}catch(e:any){setError(e.message||'تعذر فتح بوابة الفواتير')}finally{setLoading(false)}};
  useEffect(()=>{load()},[token]);
  const update=(i:number,p:Partial<Line>)=>{const lines=[...form.lines];lines[i]={...lines[i],...p};setForm({...form,lines,amount_before_tax:lines.reduce((s,l)=>s+Number(l.quantity||0)*Number(l.unit_price||0),0)})};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const lines=form.lines.filter(l=>l.description);const {data,error:e}=await supabase.functions.invoke('procurement-supplier-invoice',{body:{action:'submit',token,...form,lines}});if(e)throw e;if(data?.error)throw new Error(data.error);setDone(true)}catch(err:any){setError(err.message||'تعذر رفع الفاتورة')}finally{setSaving(false)}};
  if(loading)return <div className="min-h-screen grid place-items-center bg-slate-50" dir="rtl">جاري فتح بوابة الفواتير...</div>;
  if(error&&!supplier)return <div className="min-h-screen grid place-items-center bg-slate-50 p-6" dir="rtl"><div className="bg-white border rounded-2xl p-8 text-center"><h1 className="font-black text-red-700">رابط غير صالح</h1><p>{error}</p></div></div>;
  if(done)return <div className="min-h-screen grid place-items-center bg-slate-50 p-6" dir="rtl"><div className="bg-white border rounded-2xl p-8 text-center"><h1 className="font-black text-2xl">تم رفع الفاتورة</h1><p className="text-slate-500 mt-2">ستتم مراجعتها وتشغيل المطابقة الثلاثية.</p></div></div>;
  return <div className="min-h-screen bg-slate-50 py-8 px-4" dir="rtl"><div className="max-w-5xl mx-auto space-y-5"><div className="bg-white border rounded-3xl p-6"><h1 className="text-3xl font-black">بوابة رفع فواتير المورد</h1><p className="text-slate-500">المورد: {supplier?.legal_name}</p>{error&&<div className="mt-3 bg-red-50 text-red-700 p-3 rounded-xl">{error}</div>}</div><form onSubmit={submit} className="bg-white border rounded-3xl p-6 space-y-4"><div className="grid md:grid-cols-4 gap-3"><select value={form.po_id} onChange={e=>setForm({...form,po_id:e.target.value})} className="border rounded-xl p-2.5 text-sm"><option value="">اختر PO إن وجد</option>{pos.map(p=><option key={p.id} value={p.id}>{p.po_number} — {p.status}</option>)}</select><Input required placeholder="رقم الفاتورة" value={form.invoice_number} onChange={e=>setForm({...form,invoice_number:e.target.value})}/><Input type="date" value={form.invoice_date} onChange={e=>setForm({...form,invoice_date:e.target.value})}/><Input type="date" value={form.payment_due_date} onChange={e=>setForm({...form,payment_due_date:e.target.value})}/></div><div className="grid md:grid-cols-3 gap-3"><Input placeholder="حساب/IBAN" value={form.bank_account} onChange={e=>setForm({...form,bank_account:e.target.value})}/><Input type="number" value={form.tax_rate} onChange={e=>setForm({...form,tax_rate:Number(e.target.value)})}/><div className="border rounded-xl p-2.5 bg-slate-50 font-bold">قبل الضريبة: {form.amount_before_tax.toLocaleString()}</div></div><div className="space-y-2"><h3 className="font-bold">البنود</h3>{form.lines.map((l,i)=><div key={i} className="grid grid-cols-12 gap-2"><Input className="col-span-2" placeholder="كود" value={l.item_code} onChange={e=>update(i,{item_code:e.target.value})}/><Input className="col-span-5" required placeholder="وصف" value={l.description} onChange={e=>update(i,{description:e.target.value})}/><Input className="col-span-2" type="number" value={l.quantity} onChange={e=>update(i,{quantity:Number(e.target.value)})}/><Input className="col-span-2" type="number" value={l.unit_price} onChange={e=>update(i,{unit_price:Number(e.target.value)})}/><button type="button" className="col-span-1 text-red-600" onClick={()=>setForm({...form,lines:form.lines.filter((_,idx)=>idx!==i)})}>✕</button></div>)}<Button type="button" variant="secondary" onClick={()=>setForm({...form,lines:[...form.lines,emptyLine()]})}>+ بند</Button></div><Button type="submit" loading={saving} fullWidth>رفع الفاتورة</Button></form></div></div>;
}
