import { useEffect, useState } from 'react';
import { InventoryRecordTools } from '../shared/InventoryRecordTools';
import { CarrierLookup, ManifestLookup, PackageLookup, ShipmentLookup, WarehouseLookup } from '../shared/InventoryLookups';
import { PackageIdsBuilder } from '../shared/InventoryLineBuilders';
import { inventoryCarrierRateQuoteService, inventoryCarrierService, inventoryCarrierWebhookEventService, inventoryLoadingManifestService, inventoryPackageService, inventoryRateShoppingRuleService, inventoryShipmentService, inventoryShippingAnalyticsService, inventoryShippingDocumentService } from '../../../../services/sdk';

type Row=Record<string,unknown>; type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string}; type Form=Record<string,string>;
const cfgs:Record<string,Config>={
 dashboard:{title:'الشحن والعمليات الصادرة',subtitle:'Packing, Rate Shopping, Staging, Loading, Tracking',load:()=>inventoryShippingAnalyticsService.dashboard(),columns:[{key:'total_shipments',label:'الشحنات'},{key:'open_shipments',label:'مفتوحة'},{key:'shipped',label:'مشحونة'},{key:'delivered',label:'مسلمة'},{key:'delayed',label:'متأخرة'}]},
 packages:{title:'محطة التعبئة والطرود',subtitle:'إنشاء الطرد، مسح التحقق، الوزن الفعلي والحجمي',load:()=>inventoryPackageService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'package',columns:[{key:'package_number',label:'الطرد'},{key:'package_barcode',label:'الباركود'},{key:'actual_weight_kg',label:'الوزن'},{key:'dimensional_weight_kg',label:'الحجمي'},{key:'status',label:'الحالة'}]},
 shipments:{title:'الشحنات',subtitle:'إنشاء الشحنة وربط الطرود والتتبع',load:()=>inventoryShipmentService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'shipment',columns:[{key:'shipment_number',label:'الشحنة'},{key:'consignee_name',label:'المستلم'},{key:'tracking_number',label:'التتبع'},{key:'shipping_cost',label:'التكلفة'},{key:'status',label:'الحالة'}]},
 carriers:{title:'شركات الشحن',subtitle:'Carrier API foundation وRate Shopping',load:()=>inventoryCarrierService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,columns:[{key:'carrier_code',label:'الكود'},{key:'name_ar',label:'الناقل'},{key:'provider',label:'المزود'},{key:'api_mode',label:'الوضع'}]},
 quotes:{title:'Rate Shopping',subtitle:'مقارنة أسعار شركات الشحن واختيار الأنسب',load:()=>inventoryCarrierRateQuoteService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'rate',columns:[{key:'shipment_id',label:'الشحنة'},{key:'carrier_id',label:'الناقل'},{key:'quoted_cost',label:'التكلفة'},{key:'estimated_delivery_date',label:'الوصول'},{key:'selected',label:'مختار'}]},
 rateRules:{title:'قواعد اختيار الناقل',subtitle:'cheapest / fastest / cheapest_on_time / preferred_carrier',load:()=>inventoryRateShoppingRuleService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,columns:[{key:'rule_code',label:'الكود'},{key:'name_ar',label:'الاسم'},{key:'strategy',label:'الاستراتيجية'},{key:'max_delivery_days',label:'أيام قصوى'},{key:'is_active',label:'نشط'}]},
 documents:{title:'وثائق الشحن',subtitle:'Label, Packing List, BOL, Commercial Invoice, COO, MSDS, Customs',load:()=>inventoryShippingDocumentService.findAll({orderBy:'generated_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'document',columns:[{key:'document_number',label:'الوثيقة'},{key:'document_type',label:'النوع'},{key:'status',label:'الحالة'}]},
 manifests:{title:'Manifest والتحميل',subtitle:'إضافة الطرود، مسح التحميل، منع الإغلاق قبل اكتمال التحميل',load:()=>inventoryLoadingManifestService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'manifest',columns:[{key:'manifest_number',label:'Manifest'},{key:'truck_number',label:'الشاحنة'},{key:'driver_name',label:'السائق'},{key:'status',label:'الحالة'}]},
 manifestCompletion:{title:'اكتمال Manifest',subtitle:'نسبة تحميل الطرود قبل إقفال الشاحنة',load:()=>inventoryShippingAnalyticsService.manifestCompletion(),columns:[{key:'manifest_number',label:'Manifest'},{key:'package_count',label:'الطرود'},{key:'loaded_count',label:'محملة'},{key:'completion_percent',label:'%'}]},
 tracking:{title:'تتبع الشحنات',subtitle:'Timeline داخلي لكل شحنة مع أحداث الناقل',load:()=>inventoryShippingAnalyticsService.trackingTimeline(),action:'tracking',columns:[{key:'shipment_number',label:'الشحنة'},{key:'tracking_number',label:'التتبع'},{key:'event_status',label:'الحالة'},{key:'event_time',label:'الوقت'},{key:'details',label:'التفاصيل'}]},
 webhooks:{title:'Carrier Webhooks',subtitle:'استقبال أحداث الناقلين وتحديث الشحنات',load:()=>inventoryCarrierWebhookEventService.findAll({orderBy:'received_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'webhook',columns:[{key:'carrier_id',label:'الناقل'},{key:'tracking_number',label:'التتبع'},{key:'event_status',label:'الحدث'},{key:'processed',label:'معالج'}]},
 kpis:{title:'KPIs الشحن',subtitle:'On-Time, Perfect Order, Carrier Performance, Cost',load:()=>inventoryShippingAnalyticsService.kpis(),columns:[{key:'total_shipments',label:'الشحنات'},{key:'on_time_shipping_rate',label:'On-Time %'},{key:'perfect_order_foundation_rate',label:'Perfect %'},{key:'shipping_cost_per_order',label:'تكلفة/أمر'}]},
};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void){return <label className="text-xs font-bold"><span>{l}</span><input value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({package_ids:'[]',document_type:'shipping_label',event_status:'in_transit'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r||'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='package')return <Box title="إنشاء/إغلاق طرد"><div className="grid md:grid-cols-3 gap-3">{inp('Packing Session ID','packing_session_id',f,set)}{inp('Packaging Material ID','packaging_material_id',f,set)}<button onClick={()=>void run(()=>inventoryPackageService.createPackage(f.packing_session_id,f.packaging_material_id||undefined))} className="bg-indigo-600 text-white rounded-xl p-2">Create Package</button>{inp('Actual Weight KG','actual_weight_kg',f,set)}{inp('L','length_cm',f,set)}{inp('W','width_cm',f,set)}{inp('H','height_cm',f,set)}<button onClick={()=>void run(()=>inventoryPackageService.close({...f,actual_weight_kg:Number(f.actual_weight_kg||0),length_cm:Number(f.length_cm||0),width_cm:Number(f.width_cm||0),height_cm:Number(f.height_cm||0)}))} className="bg-emerald-600 text-white rounded-xl p-2">Close Package</button><Msg msg={msg}/></div></Box>;
 if(type==='shipment')return <Box title="إنشاء شحنة"><div className="grid md:grid-cols-3 gap-3">{inp('Source Type','source_type',f,set)}{inp('Consignee','consignee_name',f,set)}{inp('Address','consignee_address',f,set)}{inp('City','destination_city',f,set)}<PackageIdsBuilder value={f.package_ids} onChange={(json)=>set({package_ids:json})} /><button onClick={()=>void run(()=>inventoryShipmentService.createShipment({...f,package_ids:JSON.parse(f.package_ids||'[]')}))} className="bg-indigo-600 text-white rounded-xl p-2">Create</button><Msg msg={msg}/></div></Box>;
 if(type==='rate')return <Box title="Rate Shopping"><div className="grid md:grid-cols-3 gap-3"><ShipmentLookup label="اختر الشحنة" value={f.shipment_id} onChange={(id)=>set({shipment_id:id})} />{inp('Rule ID','rule_id',f,set)}<button onClick={()=>void run(()=>inventoryShipmentService.rateShop(f.shipment_id))} className="bg-indigo-600 text-white rounded-xl p-2">Get Quotes</button><button onClick={()=>void run(()=>inventoryShipmentService.selectBestQuote(f.shipment_id,f.rule_id||undefined))} className="bg-emerald-600 text-white rounded-xl p-2">Select Best</button><Msg msg={msg}/></div></Box>;
 if(type==='document')return <Box title="توليد وثيقة"><div className="grid md:grid-cols-3 gap-3"><ShipmentLookup label="اختر الشحنة" value={f.shipment_id} onChange={(id)=>set({shipment_id:id})} /><PackageLookup label="اختر الطرد" value={f.package_id} onChange={(id)=>set({package_id:id})} />{inp('Document Type','document_type',f,set)}<button onClick={()=>void run(()=>inventoryShipmentService.document(f.shipment_id,f.document_type,f.package_id))} className="bg-indigo-600 text-white rounded-xl p-2">Generate</button><Msg msg={msg}/></div></Box>;
 if(type==='manifest')return <Box title="Manifest"><div className="grid md:grid-cols-3 gap-3"><WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} /><CarrierLookup label="اختر الناقل" value={f.carrier_id} onChange={(id)=>set({carrier_id:id})} />{inp('Truck','truck_number',f,set)}{inp('Driver','driver_name',f,set)}<button onClick={()=>void run(()=>inventoryLoadingManifestService.createManifest(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create Manifest</button><ManifestLookup label="اختر Manifest" value={f.manifest_id} onChange={(id)=>set({manifest_id:id})} /><PackageLookup label="اختر الطرد" value={f.package_id} onChange={(id)=>set({package_id:id})} /><button onClick={()=>void run(()=>inventoryLoadingManifestService.addPackage(f.manifest_id,f.package_id))} className="bg-slate-700 text-white rounded-xl p-2">Add Package</button>{inp('Package Barcode','package_barcode',f,set)}<button onClick={()=>void run(()=>inventoryLoadingManifestService.scan(f.manifest_id,f.package_barcode))} className="bg-indigo-600 text-white rounded-xl p-2">Scan Load</button><button onClick={()=>void run(()=>inventoryLoadingManifestService.close(f.manifest_id))} className="bg-emerald-600 text-white rounded-xl p-2">Close</button><Msg msg={msg}/></div></Box>;
 if(type==='tracking')return <Box title="تسجيل تتبع"><div className="grid md:grid-cols-3 gap-3"><ShipmentLookup label="اختر الشحنة" value={f.shipment_id} onChange={(id)=>set({shipment_id:id})} />{inp('Event Status','event_status',f,set)}{inp('Details','details',f,set)}<button onClick={()=>void run(()=>inventoryShipmentService.tracking(f.shipment_id,f.event_status,f.details))} className="bg-indigo-600 text-white rounded-xl p-2">Record</button><Msg msg={msg}/></div></Box>;
 if(type==='webhook')return <Box title="Carrier Webhook"><div className="grid md:grid-cols-3 gap-3"><CarrierLookup label="اختر الناقل" value={f.carrier_id} onChange={(id)=>set({carrier_id:id})} />{inp('Tracking #','tracking_number',f,set)}{inp('Event Status','event_status',f,set)}<button onClick={()=>void run(()=>inventoryCarrierWebhookEventService.receive(f.carrier_id,f.tracking_number,f.event_status,{}))} className="bg-indigo-600 text-white rounded-xl p-2">Receive</button><Msg msg={msg}/></div></Box>;
 return null}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 p-2 rounded-xl">{msg}</div>:null}
export function ShippingPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[type,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
