import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { MrpUnitNav } from '../shared/MrpUnitNav';
import { ItemLookup, WorkerLookup } from '../../inventory/shared/InventoryLookups';
import { InventoryRecordTools } from '../../inventory/shared/InventoryRecordTools';
import { mrpAnnualShutdownService, mrpConditionMonitoringService, mrpMaintenanceAnalyticsService, mrpMaintenanceAssetService, mrpMaintenanceSparePartService, mrpMaintenanceWorkOrderService, mrpPmPlanService } from '../../../../services/sdk';
import { supabase } from '../../../../services/supabase/supabase';

type Row = Record<string, unknown>; type Form = Record<string, string>; type Option = { id: string; code: string; name?: string; meta?: string };
type Config = { title: string; subtitle: string; load: () => Promise<Row[]>; columns: { key: string; label: string }[]; action?: string };
const unitRoutes = [['assets','سجل الأصول'],['criticality','الأهمية'],['pm-plans','خطط PM'],['pm-calendar','تقويم الصيانة'],['work-orders','أوامر الصيانة'],['spare-parts','قطع الغيار'],['condition','قراءات الحالة'],['breakdowns','بلاغات أرضية المصنع'],['shutdowns','التوقف السنوي'],['reports','التقارير']];
function input(label:string,name:string,f:Form,set:(p:Form)=>void,type='text'){return <label className="text-xs font-bold text-slate-600"><span>{label}</span><input type={type} value={f[name]||''} onChange={e=>set({[name]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function select(label:string,name:string,f:Form,set:(p:Form)=>void,opts:string[]){return <label className="text-xs font-bold text-slate-600"><span>{label}</span><select value={f[name]||opts[0]} onChange={e=>set({[name]:e.target.value})} className="w-full border rounded-xl p-2 mt-1 bg-white">{opts.map(o=><option key={o} value={o}>{o}</option>)}</select></label>}
function Box({title,children}:{title:string;children:ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 rounded-xl p-2 whitespace-pre-wrap">{msg}</div>:null}
function useOptions(table:string, cols:string, map:(r:Row)=>Option){const[rows,setRows]=useState<Option[]>([]);const[loading,setLoading]=useState(false);const[q,setQ]=useState('');useEffect(()=>{let ok=true;const load=async()=>{setLoading(true);try{const db=supabase as unknown as {from:(t:string)=>{select:(c:string)=>{limit:(n:number)=>Promise<{data:unknown[]|null}>}}};const{data}=await db.from(table).select(cols).limit(500);if(ok)setRows(((data||[]) as Row[]).map(map))}finally{if(ok)setLoading(false)}};void load();return()=>{ok=false}},[table,cols]);const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return(!s?rows:rows.filter(o=>`${o.code} ${o.name||''} ${o.meta||''}`.toLowerCase().includes(s))).slice(0,80)},[rows,q]);return{filtered,loading,q,setQ}}
function Lookup({label,table,cols,map,value,onChange}:{label:string;table:string;cols:string;map:(r:Row)=>Option;value?:string;onChange:(id:string)=>void}){const{filtered,loading,q,setQ}=useOptions(table,cols,map);return <label className="text-xs font-bold text-slate-600 space-y-1 block"><span>{label}</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالكود أو الاسم..." className="w-full border rounded-xl p-2"/><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 bg-white"><option value="">{loading?'جاري التحميل...':'-- اختر --'}</option>{filtered.map(o=><option key={o.id} value={o.id}>{o.code}{o.name?` — ${o.name}`:''}{o.meta?` — ${o.meta}`:''}</option>)}</select></label>}
const WorkCenterLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="مركز العمل" table="work_centers" cols="id,work_center_code,name_ar,status" map={r=>({id:String(r.id),code:String(r.work_center_code||''),name:String(r.name_ar||''),meta:String(r.status||'')})}{...p}/>;
const ManufacturingAssetLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="أصل التصنيع" table="manufacturing_assets" cols="id,asset_code,name_ar,status" map={r=>({id:String(r.id),code:String(r.asset_code||''),name:String(r.name_ar||''),meta:String(r.status||'')})}{...p}/>;
const MaintenanceAssetLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="أصل CMMS" table="mrp_maintenance_assets" cols="id,asset_number,name_ar,status" map={r=>({id:String(r.id),code:String(r.asset_number||''),name:String(r.name_ar||''),meta:String(r.status||'')})}{...p}/>;
const PmPlanLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="خطة PM" table="mrp_pm_plans" cols="id,plan_code,plan_name,status" map={r=>({id:String(r.id),code:String(r.plan_code||''),name:String(r.plan_name||''),meta:String(r.status||'')})}{...p}/>;
const MaintenanceWoLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="أمر صيانة" table="mrp_maintenance_work_orders" cols="id,maintenance_wo_number,title,status" map={r=>({id:String(r.id),code:String(r.maintenance_wo_number||''),name:String(r.title||''),meta:String(r.status||'')})}{...p}/>;
const SparePartLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="قطعة غيار" table="mrp_maintenance_spare_parts" cols="id,spare_part_code,name_ar,current_stock_qty" map={r=>({id:String(r.id),code:String(r.spare_part_code||''),name:String(r.name_ar||''),meta:String(r.current_stock_qty||'')})}{...p}/>;
const WoPartLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="سطر قطعة أمر الصيانة" table="mrp_maintenance_work_order_parts" cols="id,required_qty,issued_qty,status" map={r=>({id:String(r.id),code:String(r.id||'').slice(0,8),name:String(r.status||''),meta:`${String(r.issued_qty||0)}/${String(r.required_qty||0)}`})}{...p}/>;
const ShopfloorRequestLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="طلب صيانة من أرضية المصنع" table="mrp_shopfloor_maintenance_requests" cols="id,request_number,severity,status" map={r=>({id:String(r.id),code:String(r.request_number||''),name:String(r.severity||''),meta:String(r.status||'')})}{...p}/>;
const ShutdownLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="خطة توقف سنوي" table="mrp_annual_shutdown_plans" cols="id,shutdown_number,title,status" map={r=>({id:String(r.id),code:String(r.shutdown_number||''),name:String(r.title||''),meta:String(r.status||'')})}{...p}/>;
const ConditionAlertLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="تنبيه حالة" table="mrp_condition_alert_lookup" cols="id,alert_number,severity,status,title" map={r=>({id:String(r.id),code:String(r.alert_number||''),name:String(r.severity||''),meta:String(r.status||'')})}{...p}/>;
const ShutdownTaskLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="مهمة توقف سنوي" table="mrp_shutdown_task_lookup" cols="id,sequence_no,task_text,status" map={r=>({id:String(r.id),code:`Task-${String(r.sequence_no||'')}`,name:String(r.task_text||''),meta:String(r.status||'')})}{...p}/>;

const cfgs:Record<string,Config>={
 dashboard:{title:'إدارة الصيانة CMMS',subtitle:'أصول، PM، أوامر صيانة، قطع غيار، PdM/CBM، MTBF/MTTR وتكامل أرضية المصنع.',load:()=>mrpMaintenanceAnalyticsService.dashboard() as Promise<Row[]>,columns:[{key:'assets_down_or_maintenance',label:'أصول متوقفة/صيانة'},{key:'open_work_orders',label:'أوامر مفتوحة'},{key:'pm_due_7_days',label:'PM خلال 7 أيام'},{key:'open_condition_alerts',label:'تنبيهات حالة'},{key:'spare_parts_to_reorder',label:'قطع لإعادة الطلب'}]},
 assets:{title:'سجل أصول CMMS',subtitle:'بطاقة الأصل: الصانع، الموديل، السيريال، الضمان، المواصفات والربط بالإنتاج.',load:()=>mrpMaintenanceAnalyticsService.assets() as Promise<Row[]>,action:'asset',columns:[{key:'asset_number',label:'الأصل'},{key:'name_ar',label:'الاسم'},{key:'manufacturer',label:'الصانع'},{key:'model',label:'الموديل'},{key:'criticality_class',label:'الأهمية'},{key:'status',label:'الحالة'}]},
 criticality:{title:'Criticality Matrix',subtitle:'أثر توقف الإنتاج × احتمالية العطل + السلامة والجودة لتحديد A/B/C.',load:()=>mrpMaintenanceAnalyticsService.assets() as Promise<Row[]>,action:'criticality',columns:[{key:'asset_number',label:'الأصل'},{key:'name_ar',label:'الاسم'},{key:'criticality_class',label:'الفئة'},{key:'last_criticality_assessment',label:'آخر تقييم'}]},
 pmPlans:{title:'خطط الصيانة الوقائية PM',subtitle:'يومي/أسبوعي/شهري/سنوي مع مهام SOP وتوليد أوامر تلقائياً.',load:()=>mrpPmPlanService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'pm',columns:[{key:'plan_code',label:'الخطة'},{key:'plan_name',label:'الاسم'},{key:'frequency_type',label:'التكرار'},{key:'next_due_date',label:'الاستحقاق'},{key:'status',label:'الحالة'}]},
 pmCalendar:{title:'تقويم الصيانة',subtitle:'مواعيد PM المقبلة وتأثيرها على مركز العمل والطاقة.',load:()=>mrpMaintenanceAnalyticsService.pmCalendar() as Promise<Row[]>,columns:[{key:'plan_code',label:'الخطة'},{key:'asset_number',label:'الأصل'},{key:'plan_name',label:'الاسم'},{key:'frequency_type',label:'التكرار'},{key:'next_due_date',label:'الاستحقاق'},{key:'work_center_code',label:'مركز العمل'}]},
 workOrders:{title:'أوامر عمل الصيانة',subtitle:'جديد → مخصص → قيد التنفيذ → مكتمل → مغلق.',load:()=>mrpMaintenanceAnalyticsService.workOrders() as Promise<Row[]>,action:'wo',columns:[{key:'maintenance_wo_number',label:'الأمر'},{key:'asset_number',label:'الأصل'},{key:'maintenance_type',label:'النوع'},{key:'priority',label:'الأولوية'},{key:'status',label:'الحالة'},{key:'total_cost',label:'التكلفة'}]},
 spareParts:{title:'قطع الغيار',subtitle:'Insurance/Consumable/Emergency spares مع نقاط إعادة طلب وتوصيات شراء.',load:()=>mrpMaintenanceAnalyticsService.spareParts() as Promise<Row[]>,action:'spares',columns:[{key:'spare_part_code',label:'الكود'},{key:'name_ar',label:'القطعة'},{key:'spare_part_type',label:'النوع'},{key:'current_stock_qty',label:'المخزون'},{key:'reorder_point',label:'نقطة الطلب'},{key:'stock_status',label:'الحالة'}]},
 condition:{title:'PdM / CBM قراءات الحالة',subtitle:'اهتزاز، حرارة، زيت، ضغط؛ تتجاوز الحدود فتفتح تنبيه/أمر صيانة.',load:()=>mrpMaintenanceAnalyticsService.condition() as Promise<Row[]>,action:'condition',columns:[{key:'asset_number',label:'الأصل'},{key:'reading_type',label:'القراءة'},{key:'reading_value',label:'القيمة'},{key:'unit',label:'الوحدة'},{key:'status',label:'الحالة'},{key:'measured_at',label:'الوقت'}]},
 breakdowns:{title:'بلاغات العطل من أرضية المصنع',subtitle:'تحويل طلب Unit 07 إلى أمر صيانة CMMS فعلي.',load:()=>mrpMaintenanceAnalyticsService.integrations() as Promise<Row[]>,action:'breakdown',columns:[{key:'shopfloor_bridge_available',label:'جسر الأرضية'},{key:'production_capacity_calendar_available',label:'تقويم الطاقة'},{key:'inventory_spares_available',label:'المخزون'},{key:'procurement_recommendation_available',label:'المشتريات'},{key:'cmms_available',label:'CMMS'}]},
 shutdowns:{title:'التوقف السنوي',subtitle:'خطة توقف كبرى، مهام، قطع غيار، فني خارجي وتنسيق الإنتاج.',load:()=>mrpMaintenanceAnalyticsService.shutdowns() as Promise<Row[]>,action:'shutdown',columns:[{key:'shutdown_number',label:'الخطة'},{key:'title',label:'العنوان'},{key:'start_date',label:'البداية'},{key:'end_date',label:'النهاية'},{key:'task_count',label:'المهام'},{key:'status',label:'الحالة'}]},
 reports:{title:'تقارير ومؤشرات الصيانة',subtitle:'PM Compliance، 80/20، MTBF/MTTR، تكلفة الصيانة لكل أصل.',load:()=>mrpMaintenanceAnalyticsService.kpis() as Promise<Row[]>,columns:[{key:'pm_compliance_percent',label:'PM Compliance'},{key:'proactive_maintenance_percent',label:'Proactive %'},{key:'reactive_maintenance_percent',label:'Reactive %'},{key:'avg_mttr_minutes',label:'MTTR'},{key:'total_maintenance_cost',label:'التكلفة'}]},
};
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({frequency_type:'monthly',interval_value:'1',estimated_minutes:'60',maintenance_type:'preventive',priority:'medium',spare_part_type:'consumable',current_stock_qty:'0',reorder_point:'0',min_qty:'0',max_qty:'0',lead_time_days:'0',unit_cost:'0',production_impact:'3',failure_likelihood:'3',safety_impact:'1',quality_impact:'1',reading_type:'vibration',unit:'mm/s',generate_work_order:'true'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم التنفيذ: '+String(r??'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='asset')return <Box title="إنشاء/تحديث أصل CMMS"><div className="grid md:grid-cols-3 gap-3">{input('Asset Number اختياري','asset_number',f,set)}{input('اسم الأصل','name_ar',f,set)}<ManufacturingAssetLookup value={f.manufacturing_asset_id} onChange={id=>set({manufacturing_asset_id:id})}/><WorkCenterLookup value={f.work_center_id} onChange={id=>set({work_center_id:id})}/>{input('الصانع','manufacturer',f,set)}{input('الموديل','model',f,set)}{input('Serial','serial_number',f,set)}{input('Purchase Date','purchase_date',f,set,'date')}{input('Warranty End','warranty_end_date',f,set,'date')}{input('Original Value','original_value',f,set,'number')}<button onClick={()=>void run(()=>mrpMaintenanceAssetService.upsert(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ الأصل</button><MaintenanceAssetLookup value={f.maintenance_asset_id} onChange={id=>set({maintenance_asset_id:id})}/>{select('Status','asset_status',f,set,['active','down','maintenance','retired'])}{input('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpMaintenanceAssetService.updateStatus(f.maintenance_asset_id,f.asset_status,f.reason))} className="bg-slate-700 text-white rounded-xl p-2">تحديث حالة الأصل</button><Msg msg={msg}/></div></Box>;
 if(type==='criticality')return <Box title="تقييم الأهمية"><div className="grid md:grid-cols-3 gap-3"><MaintenanceAssetLookup value={f.maintenance_asset_id} onChange={id=>set({maintenance_asset_id:id})}/>{input('Production Impact 1-5','production_impact',f,set,'number')}{input('Failure Likelihood 1-5','failure_likelihood',f,set,'number')}{input('Safety Impact 1-5','safety_impact',f,set,'number')}{input('Quality Impact 1-5','quality_impact',f,set,'number')}{input('Rationale','rationale',f,set)}<button onClick={()=>void run(()=>mrpMaintenanceAssetService.assessCriticality(f))} className="bg-indigo-600 text-white rounded-xl p-2">احسب A/B/C</button><Msg msg={msg}/></div></Box>;
 if(type==='pm')return <Box title="خطة PM ومهامها"><div className="grid md:grid-cols-3 gap-3"><MaintenanceAssetLookup value={f.maintenance_asset_id} onChange={id=>set({maintenance_asset_id:id})}/>{input('Plan Code اختياري','plan_code',f,set)}{input('Plan Name','plan_name',f,set)}{select('Maintenance Type','maintenance_type',f,set,['preventive','predictive','condition_based','inspection','calibration'])}{select('Frequency','frequency_type',f,set,['daily','weekly','monthly','quarterly','yearly','meter_based','condition_based'])}{input('Interval','interval_value',f,set,'number')}{input('Estimated Minutes','estimated_minutes',f,set,'number')}{input('Next Due','next_due_date',f,set,'date')}{input('SOP URL','sop_url',f,set)}<button onClick={()=>void run(()=>mrpPmPlanService.createPlan(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ خطة PM</button><PmPlanLookup value={f.pm_plan_id} onChange={id=>set({pm_plan_id:id})}/>{input('Task Seq','sequence_no',f,set,'number')}{input('Task Text','task_text',f,set)}{input('Expected Result','expected_result',f,set)}<button onClick={()=>void run(()=>mrpPmPlanService.addTask(f))} className="bg-slate-700 text-white rounded-xl p-2">إضافة مهمة</button>{input('Generate Until','until_date',f,set,'date')}<button onClick={()=>void run(()=>mrpPmPlanService.generate(f.until_date))} className="bg-emerald-600 text-white rounded-xl p-2">توليد أوامر PM</button>{select('PM Status','pm_status',f,set,['draft','active','paused','archived'])}{input('Status Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpPmPlanService.updateStatus(f.pm_plan_id,f.pm_status,f.reason))} className="bg-orange-600 text-white rounded-xl p-2">تحديث خطة PM</button><Msg msg={msg}/></div></Box>;
 if(type==='wo')return <Box title="أمر صيانة"><div className="grid md:grid-cols-3 gap-3"><MaintenanceAssetLookup value={f.maintenance_asset_id} onChange={id=>set({maintenance_asset_id:id})}/>{select('Type','maintenance_type',f,set,['reactive','breakdown','preventive','predictive','condition_based','shutdown','inspection'])}{select('Priority','priority',f,set,['low','medium','high','urgent','critical'])}{input('Title','title',f,set)}{input('Description','description',f,set)}{input('Scheduled Start','scheduled_start_at',f,set,'datetime-local')}{input('Scheduled End','scheduled_end_at',f,set,'datetime-local')}<WorkerLookup label="الفني" value={f.assigned_to} onChange={id=>set({assigned_to:id})}/><button onClick={()=>void run(()=>mrpMaintenanceWorkOrderService.createWorkOrder(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء أمر</button><MaintenanceWoLookup value={f.maintenance_wo_id} onChange={id=>set({maintenance_wo_id:id})}/><WorkerLookup label="تخصيص إلى" value={f.assign_to} onChange={id=>set({assign_to:id})}/><button onClick={()=>void run(()=>mrpMaintenanceWorkOrderService.assign(f.maintenance_wo_id,f.assign_to))} className="bg-slate-700 text-white rounded-xl p-2">تخصيص</button><button onClick={()=>void run(()=>mrpMaintenanceWorkOrderService.start(f.maintenance_wo_id))} className="bg-yellow-600 text-white rounded-xl p-2">بدء</button>{input('Actual Minutes','actual_minutes',f,set,'number')}{input('Labor Cost','labor_cost',f,set,'number')}{input('Other Cost','other_cost',f,set,'number')}{input('Completion Notes','completion_notes',f,set)}<button onClick={()=>void run(()=>mrpMaintenanceWorkOrderService.complete(f))} className="bg-emerald-600 text-white rounded-xl p-2">إكمال</button>{input('Close Reason','close_reason',f,set)}<button onClick={()=>void run(()=>mrpMaintenanceWorkOrderService.close(f.maintenance_wo_id,f.close_reason))} className="bg-red-600 text-white rounded-xl p-2">إغلاق</button><button onClick={()=>void run(()=>mrpMaintenanceWorkOrderService.hold(f.maintenance_wo_id,f.close_reason))} className="bg-yellow-600 text-white rounded-xl p-2">تعليق</button><button onClick={()=>void run(()=>mrpMaintenanceWorkOrderService.cancel(f.maintenance_wo_id,f.close_reason))} className="bg-rose-700 text-white rounded-xl p-2">إلغاء</button><Msg msg={msg}/></div></Box>;
 if(type==='spares')return <Box title="قطع الغيار"><div className="grid md:grid-cols-3 gap-3">{input('Spare Code اختياري','spare_part_code',f,set)}{input('اسم القطعة','name_ar',f,set)}<ItemLookup label="صنف المخزون" value={f.item_id} onChange={id=>set({item_id:id})}/><MaintenanceAssetLookup value={f.maintenance_asset_id} onChange={id=>set({maintenance_asset_id:id})}/>{select('Type','spare_part_type',f,set,['insurance','consumable','emergency','repairable','tool'])}{input('Stock','current_stock_qty',f,set,'number')}{input('Reorder Point','reorder_point',f,set,'number')}{input('Min','min_qty',f,set,'number')}{input('Max','max_qty',f,set,'number')}{input('Lead Time Days','lead_time_days',f,set,'number')}{input('Unit Cost','unit_cost',f,set,'number')}<button onClick={()=>void run(()=>mrpMaintenanceSparePartService.upsert(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ قطعة</button><MaintenanceWoLookup value={f.maintenance_wo_id} onChange={id=>set({maintenance_wo_id:id})}/><SparePartLookup value={f.spare_part_id} onChange={id=>set({spare_part_id:id})}/>{input('Required Qty','required_qty',f,set,'number')}<button onClick={()=>void run(()=>mrpMaintenanceSparePartService.addToWorkOrder(f))} className="bg-slate-700 text-white rounded-xl p-2">ربط بالأمر</button><WoPartLookup value={f.work_order_part_id} onChange={id=>set({work_order_part_id:id})}/>{input('Issued Qty','issued_qty',f,set,'number')}<button onClick={()=>void run(()=>mrpMaintenanceSparePartService.issue(f.work_order_part_id,Number(f.issued_qty||0)))} className="bg-emerald-600 text-white rounded-xl p-2">صرف</button><button onClick={()=>void run(()=>mrpMaintenanceSparePartService.reorder())} className="bg-orange-600 text-white rounded-xl p-2">توصيات شراء للنواقص</button>{select('Spare Status','spare_status',f,set,['active','inactive','obsolete'])}{input('Status Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpMaintenanceSparePartService.updateStatus(f.spare_part_id,f.spare_status,f.reason))} className="bg-slate-700 text-white rounded-xl p-2">تحديث حالة القطعة</button><Msg msg={msg}/></div></Box>;
 if(type==='condition')return <Box title="قراءة حالة الأصل"><div className="grid md:grid-cols-3 gap-3"><MaintenanceAssetLookup value={f.maintenance_asset_id} onChange={id=>set({maintenance_asset_id:id})}/>{select('Reading Type','reading_type',f,set,['vibration','temperature','oil_tan','oil_viscosity','oil_water','pressure','current','runtime_hours','other'])}{input('Value','reading_value',f,set,'number')}{input('Unit','unit',f,set)}{input('Warning Threshold','warning_threshold',f,set,'number')}{input('Critical Threshold','critical_threshold',f,set,'number')}{select('Generate Work Order','generate_work_order',f,set,['true','false'])}<button onClick={()=>void run(()=>mrpConditionMonitoringService.record({...f,generate_work_order:f.generate_work_order==='true'}))} className="bg-indigo-600 text-white rounded-xl p-2">تسجيل القراءة</button><ConditionAlertLookup value={f.condition_alert_id} onChange={id=>set({condition_alert_id:id})}/>{select('Alert Status','condition_alert_status',f,set,['resolved','dismissed'])}{input('Close Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpConditionMonitoringService.closeAlert(f.condition_alert_id,f.condition_alert_status,f.reason))} className="bg-emerald-600 text-white rounded-xl p-2">إغلاق تنبيه الحالة</button><Msg msg={msg}/></div></Box>;
 if(type==='breakdown')return <Box title="تحويل بلاغ أرضية المصنع"><div className="grid md:grid-cols-3 gap-3"><ShopfloorRequestLookup value={f.shopfloor_request_id} onChange={id=>set({shopfloor_request_id:id})}/><WorkerLookup label="الفني" value={f.assigned_to} onChange={id=>set({assigned_to:id})}/><button onClick={()=>void run(()=>mrpMaintenanceWorkOrderService.convertShopfloorRequest(f.shopfloor_request_id,f.assigned_to))} className="bg-indigo-600 text-white rounded-xl p-2">تحويل إلى أمر صيانة</button><Msg msg={msg}/></div></Box>;
 if(type==='shutdown')return <Box title="خطة توقف سنوي"><div className="grid md:grid-cols-3 gap-3">{input('Title','title',f,set)}{input('Start Date','start_date',f,set,'date')}{input('End Date','end_date',f,set,'date')}{input('Production Buffer Plan','production_buffer_plan',f,set)}{input('External Vendor Plan','external_vendor_plan',f,set)}<button onClick={()=>void run(()=>mrpAnnualShutdownService.createPlan(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء خطة</button><ShutdownLookup value={f.shutdown_plan_id} onChange={id=>set({shutdown_plan_id:id})}/>{input('Task Seq','sequence_no',f,set,'number')}{input('Task Text','task_text',f,set)}<MaintenanceAssetLookup value={f.task_asset_id} onChange={id=>set({task_asset_id:id})}/>{input('Required Spares','required_spares',f,set)}{input('Planned Date','planned_date',f,set,'date')}<button onClick={()=>void run(()=>mrpAnnualShutdownService.addTask({...f,maintenance_asset_id:f.task_asset_id}))} className="bg-slate-700 text-white rounded-xl p-2">إضافة مهمة</button>{select('Plan Status','shutdown_status',f,set,['draft','planned','in_progress','completed','cancelled'])}{input('Status Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpAnnualShutdownService.updatePlanStatus(f.shutdown_plan_id,f.shutdown_status,f.reason))} className="bg-indigo-700 text-white rounded-xl p-2">تحديث الخطة</button><ShutdownTaskLookup value={f.shutdown_task_id} onChange={id=>set({shutdown_task_id:id})}/>{select('Task Status','shutdown_task_status',f,set,['planned','in_progress','completed','cancelled'])}<button onClick={()=>void run(()=>mrpAnnualShutdownService.updateTaskStatus(f.shutdown_task_id,f.shutdown_task_status,f.reason))} className="bg-emerald-600 text-white rounded-xl p-2">تحديث المهمة</button><Msg msg={msg}/></div></Box>;
 return null}
export function MrpMaintenancePage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[refresh,setRefresh]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,refresh]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{type==='dashboard'&&<MrpUnitNav unit="maintenance" />}{c.action&&<Action type={c.action} onDone={()=>setRefresh(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(col=><th key={col.key} className="p-3 text-right">{col.label}</th>)}<th className="p-3 text-right">أدوات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(col=><td key={col.key} className="p-3 max-w-[220px] truncate">{String(row[col.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات حتى الآن</td></tr>}</tbody></table></div></div>}
