import { useEffect, useState } from 'react';
import { ItemLookup } from '../../inventory/shared/InventoryLookups';
import { InventoryRecordTools } from '../../inventory/shared/InventoryRecordTools';
import { mrpAqlService, mrpCalibrationService, mrpCapaService, mrpNcrService, mrpQualityAnalyticsService, mrpQualityChecklistService, mrpQualityInspectionService, mrpQualityPlanService, mrpQuarantineService, mrpSpcService } from '../../../../services/sdk';
import { supabase } from '../../../../services/supabase/supabase';
import { MrpUnitNav } from '../shared/MrpUnitNav';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void,type='text'){return <label className="text-xs font-bold"><span>{l}</span><input type={type} value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function select(l:string,n:string,f:Form,set:(p:Form)=>void,ops:string[]){return <label className="text-xs font-bold"><span>{l}</span><select value={f[n]||ops[0]} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1 bg-white">{ops.map(o=><option key={o}>{o}</option>)}</select></label>}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 rounded-xl p-2">{msg}</div>:null}
function PlanLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_quality_inspection_plans').select('id,plan_code,name_ar,inspection_stage,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Inspection Plan</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.plan_code)} — {String(r.name_ar)} — {String(r.inspection_stage)}</option>)}</select></label>}
function InspectionLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_quality_inspections').select('id,inspection_number,inspection_stage,status,decision').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Inspection</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.inspection_number)} — {String(r.inspection_stage)} — {String(r.status)}</option>)}</select></label>}
function NcrLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_quality_ncrs').select('id,ncr_number,defect_class,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>NCR</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.ncr_number)} — {String(r.defect_class)} — {String(r.status)}</option>)}</select></label>}
function DeviceLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_quality_measurement_devices').select('id,device_code,name_ar,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Measurement Device</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.device_code)} — {String(r.name_ar)} — {String(r.status)}</option>)}</select></label>}
function TemplateLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_quality_checklist_templates').select('id,template_code,name_ar,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Checklist Template</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.template_code)} — {String(r.name_ar)} — {String(r.status)}</option>)}</select></label>}
function InspectionPointLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_quality_inspection_point_lookup').select('id,point_code,name_ar,inspection_stage').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Inspection Point</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.point_code)} — {String(r.name_ar)} — {String(r.inspection_stage)}</option>)}</select></label>}
function WorkOrderLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_work_orders').select('id,work_order_number,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Work Order</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.work_order_number)} — {String(r.status)}</option>)}</select></label>}
function WoOperationLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_work_order_operations').select('id,sequence_no,operation_name,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>WO Operation</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.sequence_no)} — {String(r.operation_name)} — {String(r.status)}</option>)}</select></label>}
function LotLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('inventory_lots').select('id,lot_number,status,quality_status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Lot</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.lot_number)} — {String(r.status)} — {String(r.quality_status)}</option>)}</select></label>}
const cfgs:Record<string,Config>={
 dashboard:{title:'إدارة الجودة',subtitle:'IQC/IPQC/OQC، AQL، NCR/CAPA، Calibration، SPC.',load:()=>mrpQualityAnalyticsService.dashboard() as Promise<Row[]>,columns:[{key:'open_inspections',label:'فحوصات مفتوحة'},{key:'open_ncr',label:'NCR مفتوحة'},{key:'open_capa',label:'CAPA'},{key:'calibration_due',label:'معايرة'}]},
 plans:{title:'خطط الفحص',subtitle:'IQC/IPQC/OQC',load:()=>mrpQualityPlanService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'plan',columns:[{key:'plan_code',label:'الخطة'},{key:'name_ar',label:'الاسم'},{key:'inspection_stage',label:'المرحلة'},{key:'status',label:'الحالة'}]},
 checklists:{title:'قوائم الفحص الرقمية',subtitle:'Templates/items foundation',load:()=>mrpQualityAnalyticsService.checklists() as Promise<Row[]>,action:'checklist',columns:[{key:'template_code',label:'القالب'},{key:'name_ar',label:'الاسم'},{key:'inspection_stage',label:'المرحلة'},{key:'item_count',label:'عدد البنود'},{key:'status',label:'الحالة'}]},
 inspections:{title:'الفحوصات',subtitle:'تنفيذ IQC/IPQC/OQC',load:()=>mrpQualityAnalyticsService.inspections() as Promise<Row[]>,action:'inspection',columns:[{key:'inspection_number',label:'الفحص'},{key:'inspection_stage',label:'المرحلة'},{key:'item_code',label:'الصنف'},{key:'batch_qty',label:'الدفعة'},{key:'decision',label:'القرار'},{key:'status',label:'الحالة'}]},
 aql:{title:'AQL Engine',subtitle:'حساب حجم العينة والقبول/الرفض',load:()=>mrpAqlService.findAll({limit:100}) as unknown as Promise<Row[]>,action:'aql',columns:[{key:'aql_code',label:'AQL'},{key:'lot_min',label:'من'},{key:'lot_max',label:'إلى'},{key:'sample_size',label:'العينة'},{key:'accept_number',label:'قبول'},{key:'reject_number',label:'رفض'}]},
 ncr:{title:'NCR',subtitle:'عدم المطابقة والتخليص',load:()=>mrpQualityAnalyticsService.ncr() as Promise<Row[]>,action:'ncr',columns:[{key:'ncr_number',label:'NCR'},{key:'defect_class',label:'الفئة'},{key:'defect_type',label:'العيب'},{key:'disposition',label:'التخليص'},{key:'status',label:'الحالة'}]},
 capa:{title:'CAPA',subtitle:'إجراءات تصحيحية ووقائية',load:()=>mrpQualityAnalyticsService.capa() as Promise<Row[]>,action:'capa',columns:[{key:'capa_number',label:'CAPA'},{key:'ncr_number',label:'NCR'},{key:'capa_type',label:'النوع'},{key:'root_cause_category',label:'السبب'},{key:'status',label:'الحالة'}]},
 calibration:{title:'المعايرة',subtitle:'أجهزة القياس والاستحقاقات',load:()=>mrpQualityAnalyticsService.calibration() as Promise<Row[]>,action:'calibration',columns:[{key:'device_code',label:'الجهاز'},{key:'name_ar',label:'الاسم'},{key:'next_calibration_date',label:'القادمة'},{key:'status',label:'الحالة'}]},
 spc:{title:'SPC',subtitle:'قياسات الرقابة الإحصائية',load:()=>mrpQualityAnalyticsService.spc() as Promise<Row[]>,action:'spc',columns:[{key:'point_code',label:'النقطة'},{key:'measured_value',label:'القيمة'},{key:'ucl',label:'UCL'},{key:'lcl',label:'LCL'},{key:'measured_at',label:'وقت'}]},
 quarantine:{title:'الحجر الصحي',subtitle:'قرارات التخليص والحجر',load:()=>mrpQualityAnalyticsService.quarantine() as Promise<Row[]>,action:'quarantine',columns:[{key:'ncr_number',label:'NCR'},{key:'item_code',label:'الصنف'},{key:'lot_number',label:'Lot'},{key:'quantity',label:'الكمية'},{key:'decision',label:'القرار'}]},
 reports:{title:'تقارير الجودة',subtitle:'FPY/Scrap/Rework/NCR/COPQ foundation',load:()=>mrpQualityAnalyticsService.kpis() as Promise<Row[]>,columns:[{key:'fpy_percent',label:'FPY'},{key:'scrap_rate_percent',label:'Scrap'},{key:'rework_rate_percent',label:'Rework'},{key:'avg_ncr_close_days',label:'NCR Days'}]},
};
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({inspection_stage:'IQC',batch_qty:'100',pass_fail:'pass',decision:'accepted',defect_class:'major',capa_type:'corrective',root_cause_method:'5_whys',result:'pass'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r||'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='plan')return <Box title="إنشاء خطة/نقطة فحص"><div className="grid md:grid-cols-3 gap-3"><ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})}/>{inp('Plan Code','plan_code',f,set)}{select('Stage','inspection_stage',f,set,['IQC','IPQC','OQC','FINAL'])}{inp('Name','name_ar',f,set)}{inp('AQL','aql_level',f,set)}<button onClick={()=>void run(()=>mrpQualityPlanService.createPlan(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create Plan</button><PlanLookup value={f.plan_id} onChange={id=>set({plan_id:id})}/>{inp('Point Code','point_code',f,set)}{inp('Point Name','point_name_ar',f,set)}{inp('Specification','specification',f,set)}{inp('Target','target_value',f,set,'number')}{inp('LSL','lower_spec_limit',f,set,'number')}{inp('USL','upper_spec_limit',f,set,'number')}<button onClick={()=>void run(()=>mrpQualityPlanService.createPoint(f))} className="bg-slate-700 text-white rounded-xl p-2">Add Inspection Point</button><Msg msg={msg}/></div></Box>;
 if(type==='checklist')return <Box title="قالب/بنود قائمة فحص"><div className="grid md:grid-cols-3 gap-3">{inp('Template Code','template_code',f,set)}{inp('Template Name','name_ar',f,set)}{select('Stage','inspection_stage',f,set,['IQC','IPQC','OQC','FINAL'])}<button onClick={()=>void run(()=>mrpQualityChecklistService.createTemplate(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create Template</button><TemplateLookup value={f.template_id} onChange={id=>set({template_id:id})}/>{inp('Sequence','sequence_no',f,set,'number')}{inp('Check Text','check_text',f,set)}{select('Response Type','response_type',f,set,['pass_fail','numeric','text','select','photo'])}{inp('LSL','lower_spec_limit',f,set,'number')}{inp('USL','upper_spec_limit',f,set,'number')}<button onClick={()=>void run(()=>mrpQualityChecklistService.addItem(f))} className="bg-slate-700 text-white rounded-xl p-2">Add Checklist Item</button><Msg msg={msg}/></div></Box>;
 if(type==='inspection')return <Box title="فحص جودة"><div className="grid md:grid-cols-3 gap-3"><PlanLookup value={f.plan_id} onChange={id=>set({plan_id:id})}/>{select('Stage','inspection_stage',f,set,['IQC','IPQC','OQC','FINAL'])}<ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})}/>{inp('Batch Qty','batch_qty',f,set,'number')}<button onClick={()=>void run(()=>mrpQualityInspectionService.start(f))} className="bg-indigo-600 text-white rounded-xl p-2">Start</button><InspectionLookup value={f.inspection_id} onChange={id=>set({inspection_id:id})}/>{select('Pass/Fail','pass_fail',f,set,['pass','fail','na'])}{inp('Numeric','numeric_value',f,set,'number')}{inp('Result','result_value',f,set)}{select('Decision','decision',f,set,['accepted','conditional_accept','rejected','rework_required','scrap_required'])}<button onClick={()=>void run(()=>mrpQualityInspectionService.recordResult(f))} className="bg-slate-700 text-white rounded-xl p-2">Record Result</button><button onClick={()=>void run(()=>mrpQualityInspectionService.complete(f.inspection_id,f.decision))} className="bg-emerald-600 text-white rounded-xl p-2">Complete</button>{inp('Cancel Reason','cancel_reason',f,set)}<button onClick={()=>void run(()=>mrpQualityInspectionService.cancel(f.inspection_id,f.cancel_reason))} className="bg-red-600 text-white rounded-xl p-2">Cancel Inspection</button><Msg msg={msg}/></div></Box>;
 if(type==='aql')return <Box title="حساب AQL"><div className="grid md:grid-cols-3 gap-3">{inp('Lot Size','lot_size',f,set,'number')}{inp('AQL Code','aql_code',f,set)}{select('Defect Class','defect_class',f,set,['critical','major','minor','observation'])}<button onClick={()=>void run(()=>mrpAqlService.sample(Number(f.lot_size||0),f.aql_code||'AQL_1_0',f.defect_class))} className="bg-indigo-600 text-white rounded-xl p-2">Calculate</button><Msg msg={msg}/></div></Box>;
 if(type==='ncr')return <Box title="NCR"><div className="grid md:grid-cols-3 gap-3"><InspectionLookup value={f.inspection_id} onChange={id=>set({inspection_id:id})}/><ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})}/>{select('Defect Class','defect_class',f,set,['critical','major','minor','observation'])}{inp('Defect Type','defect_type',f,set)}{inp('Description','description',f,set)}{inp('Affected Qty','affected_qty',f,set,'number')}<button onClick={()=>void run(()=>mrpNcrService.createNcr(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create NCR</button><NcrLookup value={f.ncr_id} onChange={id=>set({ncr_id:id})}/>{select('Disposition','disposition',f,set,['rtv','use_as_is','rework','scrap','sort','hold'])}{inp('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpNcrService.decide(f.ncr_id,f.disposition,f.reason))} className="bg-emerald-600 text-white rounded-xl p-2">Decide</button><Msg msg={msg}/></div></Box>;
 if(type==='capa')return <Box title="CAPA"><div className="grid md:grid-cols-3 gap-3"><NcrLookup value={f.ncr_id} onChange={id=>set({ncr_id:id})}/>{select('Type','capa_type',f,set,['corrective','preventive','both'])}{select('Method','root_cause_method',f,set,['5_whys','fishbone','pareto','other'])}{select('Category','root_cause_category',f,set,['materials','machines','methods','man','environment','measurement','unknown'])}{inp('Root Cause','root_cause_text',f,set)}{inp('Corrective','corrective_action',f,set)}{inp('Preventive','preventive_action',f,set)}{inp('Due','due_date',f,set,'date')}<button onClick={()=>void run(()=>mrpCapaService.createCapa(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create CAPA</button>{inp('CAPA ID','capa_id',f,set)}{inp('Close reason','reason',f,set)}<button onClick={()=>void run(()=>mrpCapaService.close(f.capa_id,f.reason))} className="bg-emerald-600 text-white rounded-xl p-2">Close</button><Msg msg={msg}/></div></Box>;
 if(type==='calibration')return <Box title="أجهزة القياس والمعايرة"><div className="grid md:grid-cols-3 gap-3">{inp('Device Code','device_code',f,set)}{inp('Device Name','name_ar',f,set)}{inp('Device Type','device_type',f,set)}{inp('Standard Ref','standard_reference',f,set)}{inp('Frequency Days','calibration_frequency_days',f,set,'number')}<button onClick={()=>void run(()=>mrpCalibrationService.upsertDevice(f))} className="bg-slate-700 text-white rounded-xl p-2">Save Device</button><DeviceLookup value={f.device_id} onChange={id=>set({device_id:id})}/>{inp('Date','calibration_date',f,set,'date')}{select('Result','result',f,set,['pass','fail','conditional'])}{inp('Next Due','next_due_date',f,set,'date')}{inp('Certificate URL','certificate_url',f,set)}<button onClick={()=>void run(()=>mrpCalibrationService.recordEvent(f))} className="bg-indigo-600 text-white rounded-xl p-2">Record Calibration</button><Msg msg={msg}/></div></Box>;
 if(type==='spc')return <Box title="SPC Measurement"><div className="grid md:grid-cols-3 gap-3"><InspectionPointLookup value={f.inspection_point_id} onChange={id=>set({inspection_point_id:id})}/><WorkOrderLookup value={f.work_order_id} onChange={id=>set({work_order_id:id})}/><WoOperationLookup value={f.operation_id} onChange={id=>set({operation_id:id})}/>{inp('Measured','measured_value',f,set,'number')}{inp('Center','center_line',f,set,'number')}{inp('UCL','ucl',f,set,'number')}{inp('LCL','lcl',f,set,'number')}<button onClick={()=>void run(()=>mrpSpcService.record(f))} className="bg-indigo-600 text-white rounded-xl p-2">Record</button><Msg msg={msg}/></div></Box>;
 if(type==='quarantine')return <Box title="قرار حجر/تخليص"><div className="grid md:grid-cols-3 gap-3"><NcrLookup value={f.ncr_id} onChange={id=>set({ncr_id:id})}/><ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})}/><LotLookup value={f.lot_id} onChange={id=>set({lot_id:id})}/>{inp('Quantity','quantity',f,set,'number')}{select('Decision','decision',f,set,['release','conditional_release','reject','rtv','scrap','rework'])}{inp('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpQuarantineService.decide(f))} className="bg-indigo-600 text-white rounded-xl p-2">Save Decision</button><Msg msg={msg}/></div></Box>;
 return null}
export function MrpQualityPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{type==='dashboard'&&<MrpUnitNav unit="quality" />}{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
