import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { MrpUnitNav } from '../shared/MrpUnitNav';
import { InventoryRecordTools } from '../../inventory/shared/InventoryRecordTools';
import { supabase } from '../../../../services/supabase/supabase';
import { mrpManufacturingAlertService, mrpManufacturingAnalyticsService, mrpManufacturingKpiTargetService, mrpManufacturingRcaService, mrpManufacturingReportService, mrpManufacturingSnapshotService } from '../../../../services/sdk';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
const routes=[['executive','التنفيذية'],['operations','التشغيلية'],['scorecard','KPI Scorecard'],['oee','OEE Trends'],['schedule','Schedule'],['bottlenecks','Bottlenecks'],['quality-cost','Quality Cost'],['cost-variance','Cost Variance'],['maintenance','Maintenance'],['alerts','Alerts'],['root-cause','Root Cause'],['reports','Reports'],['exports','Exports'],['kpi-targets','KPI Targets']];
function input(l:string,n:string,f:Form,set:(p:Form)=>void,type='text'){return <label className="text-xs font-bold text-slate-600"><span>{l}</span><input type={type} value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function select(l:string,n:string,f:Form,set:(p:Form)=>void,opts:string[]){return <label className="text-xs font-bold text-slate-600"><span>{l}</span><select value={f[n]||opts[0]} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1 bg-white">{opts.map(o=><option key={o}>{o}</option>)}</select></label>}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 rounded-xl p-2 whitespace-pre-wrap">{msg}</div>:null}
function SimpleLookup({label,table,cols,value,onChange}:{label:string;table:string;cols:string;value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{const db=supabase as unknown as {from:(t:string)=>{select:(c:string)=>{limit:(n:number)=>Promise<{data:unknown[]|null}>}}};db.from(table).select(cols).limit(200).then(({data})=>setRows((data||[]) as Row[]))},[table,cols]);return <label className="text-xs font-bold text-slate-600"><span>{label}</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map((r,i)=><option key={String(r.id||i)} value={String(r.id)}>{String(r.code||r.target_code||r.alert_number||r.rca_number||r.report_number||r.export_number||r.kpi_key||r.title||r.id)} — {String(r.status||r.report_type||r.export_format||'')}</option>)}</select></label>}
const cfgs:Record<string,Config>={
 dashboard:{title:'تحليلات التصنيع',subtitle:'Dashboards، KPI، تنبيهات تنبؤية، Root Cause، Reports/Exports.',load:()=>mrpManufacturingAnalyticsService.executive() as Promise<Row[]>,columns:[{key:'active_work_orders',label:'أوامر نشطة'},{key:'completed_today',label:'مكتمل اليوم'},{key:'avg_oee_24h',label:'OEE 24h'},{key:'avg_cost_variance',label:'فرق تكلفة'},{key:'open_analytics_alerts',label:'تنبيهات'}]},
 executive:{title:'Executive Dashboard',subtitle:'نظرة إدارة عليا لكل التصنيع.',load:()=>mrpManufacturingAnalyticsService.executive() as Promise<Row[]>,columns:[{key:'active_work_orders',label:'أوامر نشطة'},{key:'completed_today',label:'مكتمل اليوم'},{key:'avg_oee_24h',label:'OEE'},{key:'open_ncr',label:'NCR'},{key:'open_maintenance_wo',label:'صيانة'}]},
 operations:{title:'Production Performance',subtitle:'تقدم أوامر العمل والإنتاج.',load:()=>mrpManufacturingAnalyticsService.operations() as Promise<Row[]>,columns:[{key:'work_order_number',label:'أمر العمل'},{key:'item_code',label:'الصنف'},{key:'quantity_to_produce',label:'المطلوب'},{key:'quantity_completed',label:'المنتج'},{key:'progress_percent',label:'التقدم'},{key:'status',label:'الحالة'}]},
 scorecard:{title:'KPI Scorecard',subtitle:'لقطات KPI مقابل الأهداف.',load:()=>mrpManufacturingAnalyticsService.scorecard() as Promise<Row[]>,action:'snapshot',columns:[{key:'snapshot_date',label:'التاريخ'},{key:'kpi_key',label:'KPI'},{key:'actual_value',label:'فعلي'},{key:'target_value',label:'هدف'},{key:'variance_value',label:'فرق'},{key:'status',label:'الحالة'}]},
 oee:{title:'OEE Trends',subtitle:'اتجاهات OEE حسب مركز العمل.',load:()=>mrpManufacturingAnalyticsService.oee() as Promise<Row[]>,columns:[{key:'work_date',label:'التاريخ'},{key:'work_center_code',label:'مركز العمل'},{key:'avg_oee',label:'OEE'},{key:'availability',label:'Availability'},{key:'performance',label:'Performance'},{key:'quality',label:'Quality'}]},
 schedule:{title:'Schedule Attainment',subtitle:'إنجاز الجدولة مقابل المطلوب.',load:()=>mrpManufacturingAnalyticsService.schedule() as Promise<Row[]>,columns:[{key:'work_order_count',label:'عدد الأوامر'},{key:'completed_orders',label:'مكتملة'},{key:'schedule_attainment_percent',label:'Schedule %'}]},
 bottlenecks:{title:'Bottleneck Analysis',subtitle:'مراكز العمل ذات العمليات المفتوحة والتوقفات.',load:()=>mrpManufacturingAnalyticsService.bottlenecks() as Promise<Row[]>,columns:[{key:'work_center_code',label:'مركز العمل'},{key:'work_center_name',label:'الاسم'},{key:'open_operation_count',label:'عمليات مفتوحة'},{key:'downtime_minutes',label:'توقفات'},{key:'avg_oee_7d',label:'OEE 7d'}]},
 qualityCost:{title:'Quality Cost',subtitle:'أثر الجودة على التكلفة.',load:()=>mrpManufacturingAnalyticsService.qualityCost() as Promise<Row[]>,columns:[{key:'open_ncr',label:'NCR مفتوحة'},{key:'affected_qty',label:'كمية متأثرة'},{key:'scrap_rework_cost',label:'Scrap/Rework Cost'}]},
 costVariance:{title:'Cost Variance Dashboard',subtitle:'فروقات التكلفة حسب الفئة والنوع.',load:()=>mrpManufacturingAnalyticsService.costVariance() as Promise<Row[]>,columns:[{key:'cost_category',label:'الفئة'},{key:'variance_type',label:'النوع'},{key:'variance_count',label:'عدد'},{key:'total_variance',label:'إجمالي الفرق'},{key:'max_severity',label:'الشدة'}]},
 maintenance:{title:'Maintenance Reliability',subtitle:'MTBF/MTTR وموثوقية الأصول.',load:()=>mrpManufacturingAnalyticsService.maintenance() as Promise<Row[]>,columns:[{key:'asset_number',label:'الأصل'},{key:'asset_name',label:'الاسم'},{key:'failure_count',label:'أعطال'},{key:'mttr_minutes',label:'MTTR'},{key:'mtbf_hours_proxy',label:'MTBF'}]},
 alerts:{title:'Predictive Alerts',subtitle:'تنبيهات OEE/تكلفة/جودة/صيانة.',load:()=>mrpManufacturingAnalyticsService.alerts() as Promise<Row[]>,action:'alerts',columns:[{key:'alert_number',label:'التنبيه'},{key:'alert_type',label:'النوع'},{key:'severity',label:'الشدة'},{key:'title',label:'العنوان'},{key:'status',label:'الحالة'}]},
 rootCause:{title:'Root Cause Analysis',subtitle:'تحليل جذري مرتبط بمصدر بيانات.',load:()=>mrpManufacturingAnalyticsService.rca() as Promise<Row[]>,action:'rca',columns:[{key:'rca_number',label:'RCA'},{key:'source_type',label:'المصدر'},{key:'title',label:'العنوان'},{key:'root_cause_category',label:'الفئة'},{key:'status',label:'الحالة'}]},
 reports:{title:'Report Center',subtitle:'تقارير دورية تنفيذية وتشغيلية.',load:()=>mrpManufacturingAnalyticsService.reports() as Promise<Row[]>,action:'report',columns:[{key:'report_number',label:'التقرير'},{key:'report_type',label:'النوع'},{key:'period_start',label:'من'},{key:'period_end',label:'إلى'},{key:'status',label:'الحالة'}]},
 exports:{title:'Export Queue',subtitle:'طلبات تصدير التقارير.',load:()=>mrpManufacturingAnalyticsService.exports() as Promise<Row[]>,action:'export',columns:[{key:'export_number',label:'التصدير'},{key:'export_format',label:'الصيغة'},{key:'status',label:'الحالة'},{key:'file_url',label:'الرابط'}]},
 targets:{title:'KPI Targets',subtitle:'أهداف KPI قابلة للتخصيص.',load:()=>mrpManufacturingKpiTargetService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'target',columns:[{key:'target_code',label:'الهدف'},{key:'kpi_key',label:'KPI'},{key:'target_value',label:'القيمة'},{key:'direction',label:'الاتجاه'},{key:'status',label:'الحالة'}]},
};
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({period_type:'daily',report_type:'executive',export_format:'xlsx',source_type:'manual',method:'5_whys',direction:'higher_better',scope_type:'enterprise'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r??'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='snapshot')return <Box title="تحديث KPI Snapshots"><div className="grid md:grid-cols-3 gap-3">{input('Snapshot Date','snapshot_date',f,set,'date')}{select('Period','period_type',f,set,['daily','weekly','monthly','quarterly'])}<button onClick={()=>void run(()=>mrpManufacturingSnapshotService.refresh(f))} className="bg-indigo-600 text-white rounded-xl p-2">Refresh KPIs</button><Msg msg={msg}/></div></Box>;
 if(type==='alerts')return <Box title="تنبيهات"><div className="grid md:grid-cols-3 gap-3"><button onClick={()=>void run(()=>mrpManufacturingAlertService.generate())} className="bg-indigo-600 text-white rounded-xl p-2">Generate Predictive Alerts</button><SimpleLookup label="Alert" table="mrp_analytics_alert_lookup" cols="id,alert_number,alert_type,severity,title,status" value={f.alert_id} onChange={id=>set({alert_id:id})}/>{select('Alert Status','alert_status',f,set,['acknowledged','closed','dismissed'])}{input('Close Reason','close_reason',f,set)}<button onClick={()=>void run(()=>mrpManufacturingAlertService.updateStatus(f.alert_id,f.alert_status,f.close_reason))} className="bg-emerald-600 text-white rounded-xl p-2">Update Alert</button><Msg msg={msg}/></div></Box>;
 if(type==='rca')return <Box title="Root Cause"><div className="grid md:grid-cols-3 gap-3">{select('Source','source_type',f,set,['downtime','quality','cost_variance','late_order','maintenance','manual'])}{input('Source ID','source_id',f,set)}{input('Title','title',f,set)}{input('Problem','problem_statement',f,set)}{select('Method','method',f,set,['5_whys','fishbone','pareto','8d','other'])}{input('Root Cause Category','root_cause_category',f,set)}{input('Corrective Action','corrective_action',f,set)}{input('Due Date','due_date',f,set,'date')}<button onClick={()=>void run(()=>mrpManufacturingRcaService.createRca(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create RCA</button><SimpleLookup label="RCA" table="mrp_analytics_rca_lookup" cols="id,rca_number,source_type,title,status" value={f.rca_id} onChange={id=>set({rca_id:id})}/>{select('RCA Status','rca_status',f,set,['open','in_progress','verified','closed','cancelled'])}<button onClick={()=>void run(()=>mrpManufacturingRcaService.updateStatus(f.rca_id,f.rca_status,f.root_cause_text))} className="bg-emerald-600 text-white rounded-xl p-2">Update RCA</button><Msg msg={msg}/></div></Box>;
 if(type==='report')return <Box title="Generate Report"><div className="grid md:grid-cols-3 gap-3">{select('Report Type','report_type',f,set,['executive','production_performance','oee','cost_variance','quality','maintenance','schedule','custom'])}{input('Period Start','period_start',f,set,'date')}{input('Period End','period_end',f,set,'date')}<button onClick={()=>void run(()=>mrpManufacturingReportService.generate(f))} className="bg-indigo-600 text-white rounded-xl p-2">Generate</button><SimpleLookup label="Report Run" table="mrp_analytics_report_lookup" cols="id,report_number,report_type,status" value={f.report_run_id} onChange={id=>set({report_run_id:id})}/>{input('Cancel Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpManufacturingReportService.cancel(f.report_run_id,f.reason))} className="bg-red-600 text-white rounded-xl p-2">Cancel Report</button><Msg msg={msg}/></div></Box>;
 if(type==='export')return <Box title="Request Export"><div className="grid md:grid-cols-3 gap-3"><SimpleLookup label="Report Run" table="mrp_analytics_report_lookup" cols="id,report_number,report_type,status" value={f.report_run_id} onChange={id=>set({report_run_id:id})}/>{select('Format','export_format',f,set,['xlsx','csv','pdf','json'])}<button onClick={()=>void run(()=>mrpManufacturingReportService.export(f))} className="bg-indigo-600 text-white rounded-xl p-2">Request Export</button><SimpleLookup label="Export Request" table="mrp_analytics_export_lookup" cols="id,export_number,export_format,status" value={f.export_id} onChange={id=>set({export_id:id})}/>{select('Export Status','export_status',f,set,['queued','processing','ready','failed','cancelled'])}{input('File URL','file_url',f,set)}<button onClick={()=>void run(()=>mrpManufacturingReportService.updateExport(f))} className="bg-emerald-600 text-white rounded-xl p-2">Update Export</button><Msg msg={msg}/></div></Box>;
 if(type==='target')return <Box title="KPI Target"><div className="grid md:grid-cols-3 gap-3">{input('Target Code اختياري','target_code',f,set)}{input('KPI Key','kpi_key',f,set)}{input('Target Value','target_value',f,set,'number')}{select('Scope','scope_type',f,set,['enterprise','plant','line','work_center','item'])}{select('Direction','direction',f,set,['higher_better','lower_better','between'])}{input('Warning','warning_threshold',f,set,'number')}{input('Critical','critical_threshold',f,set,'number')}<button onClick={()=>void run(()=>mrpManufacturingKpiTargetService.upsert(f))} className="bg-indigo-600 text-white rounded-xl p-2">Save Target</button><SimpleLookup label="KPI Target" table="mrp_manufacturing_kpi_target_lookup" cols="id,target_code,kpi_key,status" value={f.target_id} onChange={id=>set({target_id:id})}/>{select('Target Status','target_status',f,set,['active','inactive','archived'])}{input('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpManufacturingKpiTargetService.updateStatus(f.target_id,f.target_status,f.reason))} className="bg-slate-700 text-white rounded-xl p-2">Update Target</button><Msg msg={msg}/></div></Box>;
 return null}
export function MrpAnalyticsPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[refresh,setRefresh]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,refresh]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{type==='dashboard'&&<MrpUnitNav unit="analytics" />}{c.action&&<Action type={c.action} onDone={()=>setRefresh(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(col=><th key={col.key} className="p-3 text-right">{col.label}</th>)}<th className="p-3 text-right">أدوات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(col=><td key={col.key} className="p-3 max-w-[220px] truncate">{String(row[col.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات حتى الآن</td></tr>}</tbody></table></div></div>}
