import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { MrpUnitNav } from '../shared/MrpUnitNav';
import { ItemLookup, WorkerLookup } from '../../inventory/shared/InventoryLookups';
import { InventoryRecordTools } from '../../inventory/shared/InventoryRecordTools';
import {
  mrpAndonService,
  mrpDowntimeReasonService,
  mrpDowntimeService,
  mrpLaborAssignmentService,
  mrpMaintenanceBridgeService,
  mrpOeeService,
  mrpShopFloorAnalyticsService,
  mrpShopFloorExecutionService,
  mrpTerminalSessionService,
  mrpWorkstationService,
} from '../../../../services/sdk';
import { supabase } from '../../../../services/supabase/supabase';

type Row = Record<string, unknown>;
type Form = Record<string, string>;
type Option = { id: string; code: string; name?: string; meta?: string };
type Config = { title: string; subtitle: string; load: () => Promise<Row[]>; columns: { key: string; label: string }[]; action?: string };
const unitRoutes = [
  ['workstations', 'محطات العمل الرقمية'], ['terminals', 'جلسات الطرفيات'], ['tracking', 'تتبع الإنتاج'], ['consumption', 'الاستهلاك الفعلي'], ['oee', 'OEE'], ['downtime', 'التوقفات'], ['pareto', 'Downtime Pareto'], ['work-order-progress', 'تقدم أوامر العمل'], ['labor-shifts', 'العمالة والورديات'], ['andon', 'Andon'], ['supervisor', 'لوحة المشرف'], ['manager', 'لوحة مدير الإنتاج'], ['maintenance', 'جسر الصيانة'], ['reports', 'التقارير']
];

function input(label: string, name: string, f: Form, set: (p: Form) => void, type = 'text') {
  return <label className="text-xs font-bold text-slate-600"><span>{label}</span><input type={type} value={f[name] || ''} onChange={e => set({ [name]: e.target.value })} className="w-full border rounded-xl p-2 mt-1" /></label>;
}
function select(label: string, name: string, f: Form, set: (p: Form) => void, opts: string[]) {
  return <label className="text-xs font-bold text-slate-600"><span>{label}</span><select value={f[name] || opts[0]} onChange={e => set({ [name]: e.target.value })} className="w-full border rounded-xl p-2 mt-1 bg-white">{opts.map(o => <option key={o} value={o}>{o}</option>)}</select></label>;
}
function Box({ title, children }: { title: string; children: ReactNode }) { return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>; }
function Msg({ msg }: { msg: string }) { return msg ? <div className="md:col-span-3 text-xs bg-slate-100 rounded-xl p-2 whitespace-pre-wrap">{msg}</div> : null; }

function useOptions(table: string, selectCols: string, map: (r: Row) => Option) {
  const [rows, setRows] = useState<Option[]>([]); const [loading, setLoading] = useState(false); const [q, setQ] = useState('');
  useEffect(() => {
    let ok = true;
    const load = async () => {
      setLoading(true);
      try {
        const db = supabase as unknown as { from: (t: string) => { select: (c: string) => { limit: (n: number) => Promise<{ data: unknown[] | null }> } } };
        const { data } = await db.from(table).select(selectCols).limit(500);
        if (ok) setRows(((data || []) as Row[]).map(map));
      } finally {
        if (ok) setLoading(false);
      }
    };
    void load();
    return () => { ok = false; };
  }, [table, selectCols]);
  const filtered = useMemo(() => { const s = q.trim().toLowerCase(); return (!s ? rows : rows.filter(o => `${o.code} ${o.name || ''} ${o.meta || ''}`.toLowerCase().includes(s))).slice(0, 80); }, [rows, q]);
  return { filtered, loading, q, setQ };
}
function Lookup({ label, table, cols, map, value, onChange }: { label: string; table: string; cols: string; map: (r: Row) => Option; value?: string; onChange: (id: string) => void }) {
  const { filtered, loading, q, setQ } = useOptions(table, cols, map);
  return <label className="text-xs font-bold text-slate-600 space-y-1 block"><span>{label}</span><input value={q} onChange={e => setQ(e.target.value)} placeholder="ابحث بالكود أو الاسم..." className="w-full border rounded-xl p-2" /><select value={value || ''} onChange={e => onChange(e.target.value)} className="w-full border rounded-xl p-2 bg-white"><option value="">{loading ? 'جاري التحميل...' : '-- اختر --'}</option>{filtered.map(o => <option key={o.id} value={o.id}>{o.code}{o.name ? ` — ${o.name}` : ''}{o.meta ? ` — ${o.meta}` : ''}</option>)}</select></label>;
}
const WorkCenterLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="مركز العمل" table="work_centers" cols="id,work_center_code,name_ar,status" map={r => ({ id: String(r.id), code: String(r.work_center_code || ''), name: String(r.name_ar || ''), meta: String(r.status || '') })} {...p} />;
const AssetLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="الأصل/الآلة" table="manufacturing_assets" cols="id,asset_code,name_ar,status" map={r => ({ id: String(r.id), code: String(r.asset_code || ''), name: String(r.name_ar || ''), meta: String(r.status || '') })} {...p} />;
const ShiftLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="الوردية" table="manufacturing_shifts" cols="id,shift_code,name_ar,status" map={r => ({ id: String(r.id), code: String(r.shift_code || ''), name: String(r.name_ar || ''), meta: String(r.status || '') })} {...p} />;
const WorkstationLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="محطة العمل" table="mrp_shop_floor_workstations" cols="id,workstation_code,name_ar,current_status" map={r => ({ id: String(r.id), code: String(r.workstation_code || ''), name: String(r.name_ar || ''), meta: String(r.current_status || '') })} {...p} />;
const OperationLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="عملية أمر العمل" table="mrp_work_order_operations" cols="id,sequence_no,operation_name,status" map={r => ({ id: String(r.id), code: `OP-${String(r.sequence_no || '')}`, name: String(r.operation_name || ''), meta: String(r.status || '') })} {...p} />;
const WorkOrderLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="أمر العمل" table="mrp_work_orders" cols="id,work_order_number,status,quantity_to_produce" map={r => ({ id: String(r.id), code: String(r.work_order_number || ''), name: String(r.status || ''), meta: String(r.quantity_to_produce || '') })} {...p} />;
const ReasonLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="سبب التوقف" table="mrp_downtime_reason_codes" cols="id,reason_code,name_ar,reason_type" map={r => ({ id: String(r.id), code: String(r.reason_code || ''), name: String(r.name_ar || ''), meta: String(r.reason_type || '') })} {...p} />;
const DowntimeLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="حدث توقف" table="mrp_downtime_events" cols="id,downtime_number,status,duration_minutes" map={r => ({ id: String(r.id), code: String(r.downtime_number || ''), name: String(r.status || ''), meta: String(r.duration_minutes || '') })} {...p} />;
const ProductionEventLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="حدث إنتاج" table="mrp_production_events" cols="id,event_number,event_type,good_qty" map={r => ({ id: String(r.id), code: String(r.event_number || ''), name: String(r.event_type || ''), meta: String(r.good_qty || '') })} {...p} />;
const MaterialLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="مادة أمر العمل" table="mrp_work_order_materials" cols="id,item_id,required_qty,status" map={r => ({ id: String(r.id), code: String(r.id || '').slice(0, 8), name: String(r.status || ''), meta: String(r.required_qty || '') })} {...p} />;
const AssignmentLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="تعيين عامل" table="mrp_labor_assignments" cols="id,assignment_number,status,labor_role" map={r => ({ id: String(r.id), code: String(r.assignment_number || ''), name: String(r.status || ''), meta: String(r.labor_role || '') })} {...p} />;
const AndonLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="إشارة Andon" table="mrp_andon_signals" cols="id,andon_number,status,color" map={r => ({ id: String(r.id), code: String(r.andon_number || ''), name: String(r.status || ''), meta: String(r.color || '') })} {...p} />;
const TerminalSessionLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="جلسة طرفية" table="mrp_shopfloor_terminal_session_lookup" cols="id,session_number,status,workstation_code" map={r => ({ id: String(r.id), code: String(r.session_number || ''), name: String(r.status || ''), meta: String(r.workstation_code || '') })} {...p} />;
const MaintenanceRequestLookup = (p: { value?: string; onChange: (id: string) => void }) => <Lookup label="طلب صيانة أرضية" table="mrp_shopfloor_maintenance_requests" cols="id,request_number,severity,status" map={r => ({ id: String(r.id), code: String(r.request_number || ''), name: String(r.severity || ''), meta: String(r.status || '') })} {...p} />;

const cfgs: Record<string, Config> = {
  dashboard: { title: 'تحكم أرضية المصنع MES/SFC', subtitle: 'محطات رقمية، تنفيذ لحظي، OEE، توقفات، Andon، عمالة ولوحات مشرفين.', load: () => mrpShopFloorAnalyticsService.dashboard() as Promise<Row[]>, columns: [{ key: 'active_workstations', label: 'محطات نشطة' }, { key: 'work_orders_in_progress', label: 'أوامر جارية' }, { key: 'open_downtime_events', label: 'توقفات مفتوحة' }, { key: 'active_andon_signals', label: 'Andon نشط' }, { key: 'avg_oee_24h', label: 'OEE 24h' }] },
  workstations: { title: 'محطات العمل الرقمية', subtitle: 'تعريف شاشات/تابلت/HMI أرضية المصنع مع SOP وتعليمات التشغيل.', load: () => mrpShopFloorAnalyticsService.workstations() as Promise<Row[]>, action: 'workstation', columns: [{ key: 'workstation_code', label: 'الكود' }, { key: 'name_ar', label: 'المحطة' }, { key: 'device_type', label: 'الجهاز' }, { key: 'work_center_code', label: 'مركز العمل' }, { key: 'current_status', label: 'الحالة' }] },
  terminals: { title: 'جلسات الطرفيات', subtitle: 'تسجيل دخول/خروج العامل إلى محطة العمل وربط الوردية.', load: () => mrpTerminalSessionService.findAll({ orderBy: 'opened_at', ascending: false, limit: 100 }) as unknown as Promise<Row[]>, action: 'terminal', columns: [{ key: 'session_number', label: 'الجلسة' }, { key: 'workstation_id', label: 'المحطة' }, { key: 'shift_id', label: 'الوردية' }, { key: 'status', label: 'الحالة' }, { key: 'opened_at', label: 'الفتح' }] },
  tracking: { title: 'تتبع الإنتاج اللحظي', subtitle: 'بدء العمليات وتسجيل الوحدات والخردة وإبلاغ عيوب الجودة.', load: () => mrpShopFloorAnalyticsService.tracking() as Promise<Row[]>, action: 'tracking', columns: [{ key: 'event_number', label: 'الحدث' }, { key: 'event_type', label: 'النوع' }, { key: 'work_order_number', label: 'أمر العمل' }, { key: 'operation_name', label: 'العملية' }, { key: 'good_qty', label: 'جيد' }, { key: 'scrap_qty', label: 'خردة' }] },
  consumption: { title: 'الاستهلاك الفعلي مقابل BOM', subtitle: 'تسجيل استهلاك المواد وفروقات actual vs standard.', load: () => mrpShopFloorAnalyticsService.consumption() as Promise<Row[]>, action: 'consumption', columns: [{ key: 'consumption_number', label: 'الاستهلاك' }, { key: 'work_order_number', label: 'أمر العمل' }, { key: 'item_code', label: 'الصنف' }, { key: 'standard_qty', label: 'قياسي' }, { key: 'actual_qty', label: 'فعلي' }, { key: 'variance_percent', label: 'الفرق%' }] },
  oee: { title: 'OEE', subtitle: 'حساب التوافر × الأداء × الجودة لكل مركز عمل وفترة.', load: () => mrpShopFloorAnalyticsService.oee() as Promise<Row[]>, action: 'oee', columns: [{ key: 'snapshot_number', label: 'اللقطة' }, { key: 'work_center_code', label: 'مركز العمل' }, { key: 'availability_percent', label: 'Availability' }, { key: 'performance_percent', label: 'Performance' }, { key: 'quality_percent', label: 'Quality' }, { key: 'oee_percent', label: 'OEE' }, { key: 'oee_classification', label: 'التصنيف' }] },
  downtime: { title: 'إدارة التوقفات', subtitle: 'أسباب وتسجيل وفتح/إغلاق التوقفات المخططة وغير المخططة.', load: () => mrpShopFloorAnalyticsService.downtime() as Promise<Row[]>, action: 'downtime', columns: [{ key: 'downtime_number', label: 'التوقف' }, { key: 'reason_name', label: 'السبب' }, { key: 'category', label: 'التصنيف' }, { key: 'work_center_code', label: 'مركز العمل' }, { key: 'live_duration_minutes', label: 'دقائق' }, { key: 'status', label: 'الحالة' }] },
  pareto: { title: 'Downtime Pareto', subtitle: 'تحليل 20/80 لأسباب التوقفات حسب الدقائق.', load: () => mrpShopFloorAnalyticsService.pareto() as Promise<Row[]>, columns: [{ key: 'reason_code', label: 'الكود' }, { key: 'reason_name', label: 'السبب' }, { key: 'event_count', label: 'عدد' }, { key: 'total_minutes', label: 'دقائق' }, { key: 'percent_of_total', label: '%' }, { key: 'cumulative_percent', label: 'تراكمي%' }] },
  progress: { title: 'حالة تنفيذ أوامر العمل', subtitle: 'المطلوب/المنتج/المتبقي/CR/التوقفات لكل أمر عمل.', load: () => mrpShopFloorAnalyticsService.workOrders() as Promise<Row[]>, columns: [{ key: 'work_order_number', label: 'أمر العمل' }, { key: 'item_code', label: 'الصنف' }, { key: 'quantity_to_produce', label: 'المطلوب' }, { key: 'quantity_completed', label: 'المنتج' }, { key: 'remaining_qty', label: 'المتبقي' }, { key: 'progress_percent', label: 'التقدم%' }, { key: 'status', label: 'الحالة' }] },
  labor: { title: 'العمالة والورديات', subtitle: 'توزيع العمال على العمليات وقياس الإنتاجية.', load: () => mrpShopFloorAnalyticsService.labor() as Promise<Row[]>, action: 'labor', columns: [{ key: 'assignment_number', label: 'التعيين' }, { key: 'shift_name', label: 'الوردية' }, { key: 'work_order_number', label: 'أمر العمل' }, { key: 'labor_role', label: 'الدور' }, { key: 'direct_minutes', label: 'دقائق مباشرة' }, { key: 'units_per_hour', label: 'وحدة/ساعة' }, { key: 'status', label: 'الحالة' }] },
  andon: { title: 'Andon الرقمي', subtitle: 'إشارات خضراء/صفراء/حمراء/زرقاء/بيضاء مع إقرار وحل.', load: () => mrpShopFloorAnalyticsService.andon() as Promise<Row[]>, action: 'andon', columns: [{ key: 'andon_number', label: 'Andon' }, { key: 'color', label: 'اللون' }, { key: 'signal_type', label: 'النوع' }, { key: 'severity', label: 'الشدة' }, { key: 'title', label: 'العنوان' }, { key: 'status', label: 'الحالة' }, { key: 'age_minutes', label: 'العمر/دقيقة' }] },
  supervisor: { title: 'لوحة المشرف', subtitle: 'OEE والوحدات والتوقفات وAndon لكل مركز عمل خلال 24 ساعة.', load: () => mrpShopFloorAnalyticsService.supervisor() as Promise<Row[]>, columns: [{ key: 'work_center_code', label: 'مركز العمل' }, { key: 'oee_24h', label: 'OEE 24h' }, { key: 'good_qty_24h', label: 'وحدات 24h' }, { key: 'downtime_minutes_24h', label: 'توقفات/دقيقة' }, { key: 'active_andon', label: 'Andon نشط' }] },
  manager: { title: 'لوحة مدير الإنتاج', subtitle: 'نظرة شاملة على الأوامر وOEE والتوقفات والصيانة والجودة.', load: () => mrpShopFloorAnalyticsService.manager() as Promise<Row[]>, columns: [{ key: 'active_work_orders', label: 'أوامر نشطة' }, { key: 'completed_today', label: 'مكتمل اليوم' }, { key: 'avg_oee_24h', label: 'OEE 24h' }, { key: 'open_downtime', label: 'توقفات مفتوحة' }, { key: 'open_maintenance_requests', label: 'طلبات صيانة' }, { key: 'open_quality_ncr', label: 'NCR مفتوحة' }] },
  maintenance: { title: 'جسر الصيانة', subtitle: 'بلاغ عطل من أرضية المصنع يتحول لاحقاً إلى أمر صيانة في CMMS Unit 08.', load: () => mrpShopFloorAnalyticsService.maintenance() as Promise<Row[]>, action: 'maintenance', columns: [{ key: 'request_number', label: 'الطلب' }, { key: 'asset_code', label: 'الأصل' }, { key: 'work_center_code', label: 'مركز العمل' }, { key: 'severity', label: 'الشدة' }, { key: 'problem_description', label: 'الوصف' }, { key: 'status', label: 'الحالة' }] },
  reports: { title: 'تقارير ومؤشرات أرضية المصنع', subtitle: 'OEE، Schedule Attainment، Cycle Time، MTBF/MTTR proxies.', load: () => mrpShopFloorAnalyticsService.kpis() as Promise<Row[]>, columns: [{ key: 'avg_oee_30d', label: 'OEE 30d' }, { key: 'schedule_attainment_percent', label: 'Schedule Attainment' }, { key: 'avg_cycle_time_seconds', label: 'Cycle Time sec' }, { key: 'mttr_minutes_proxy', label: 'MTTR proxy' }, { key: 'mtbf_minutes_proxy', label: 'MTBF proxy' }] },
};

function Action({ type, onDone }: { type: string; onDone: () => void }) {
  const [f, setF] = useState<Form>({ device_type: 'tablet', event_type: 'unit_completed', good_qty: '1', scrap_qty: '0', rework_qty: '0', category: 'unplanned', reason_type: 'machine_breakdown', color: 'yellow', signal_type: 'attention', severity: 'urgent' });
  const [msg, setMsg] = useState(''); const set = (p: Form) => setF(x => ({ ...x, ...p }));
  const run = async (fn: () => Promise<unknown>) => { try { const r = await fn(); setMsg(`تم التنفيذ: ${String(r || 'ok')}`); onDone(); } catch (e) { setMsg(e instanceof Error ? e.message : String(e)); } };
  if (type === 'workstation') return <Box title="إنشاء/تحديث محطة رقمية"><div className="grid md:grid-cols-3 gap-3">{input('Workstation Code اختياري', 'workstation_code', f, set)}{input('اسم المحطة', 'name_ar', f, set)}{select('Device Type', 'device_type', f, set, ['tablet', 'kiosk', 'industrial_pc', 'mobile', 'hmi', 'api'])}<WorkCenterLookup value={f.work_center_id} onChange={id => set({ work_center_id: id })} /><AssetLookup value={f.asset_id} onChange={id => set({ asset_id: id })} />{input('SOP URL', 'sop_url', f, set)}{input('تعليمات العمل', 'work_instructions', f, set)}<button onClick={() => void run(() => mrpWorkstationService.upsert(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ المحطة</button><WorkstationLookup value={f.workstation_id} onChange={id => set({ workstation_id: id })} />{select('Status', 'workstation_status', f, set, ['active', 'locked', 'down', 'maintenance', 'retired'])}{input('Reason', 'reason', f, set)}<button onClick={() => void run(() => mrpWorkstationService.updateStatus(f.workstation_id, f.workstation_status, f.reason))} className="bg-slate-700 text-white rounded-xl p-2">تحديث حالة المحطة</button><Msg msg={msg} /></div></Box>;
  if (type === 'terminal') return <Box title="جلسة طرفية"><div className="grid md:grid-cols-3 gap-3"><WorkstationLookup value={f.workstation_id} onChange={id => set({ workstation_id: id })} /><ShiftLookup value={f.shift_id} onChange={id => set({ shift_id: id })} />{input('ملاحظات', 'notes', f, set)}<button onClick={() => void run(() => mrpTerminalSessionService.open(f))} className="bg-indigo-600 text-white rounded-xl p-2">فتح جلسة</button><TerminalSessionLookup value={f.session_id} onChange={id => set({ session_id: id })} /><button onClick={() => void run(() => mrpTerminalSessionService.close(f.session_id, f.notes))} className="bg-emerald-600 text-white rounded-xl p-2">إغلاق جلسة</button>{input('سبب إغلاق إجباري', 'force_reason', f, set)}<button onClick={() => void run(() => mrpTerminalSessionService.forceClose(f.session_id, f.force_reason))} className="bg-red-600 text-white rounded-xl p-2">إغلاق إجباري</button><Msg msg={msg} /></div></Box>;
  if (type === 'tracking') return <Box title="تنفيذ إنتاج"><div className="grid md:grid-cols-3 gap-3"><OperationLookup value={f.operation_id} onChange={id => set({ operation_id: id })} /><WorkstationLookup value={f.workstation_id} onChange={id => set({ workstation_id: id })} />{select('Event Type', 'event_type', f, set, ['unit_completed', 'batch_completed', 'setup_start', 'setup_end', 'scrap', 'rework', 'quality_issue'])}{input('Good Qty', 'good_qty', f, set, 'number')}{input('Scrap Qty', 'scrap_qty', f, set, 'number')}{input('Rework Qty', 'rework_qty', f, set, 'number')}{input('Cycle Time Seconds', 'cycle_time_seconds', f, set, 'number')}{input('Lot Code', 'lot_code', f, set)}{input('ملاحظات', 'notes', f, set)}<button onClick={() => void run(() => mrpShopFloorExecutionService.startOperation(f.operation_id, f.workstation_id))} className="bg-slate-700 text-white rounded-xl p-2">بدء العملية</button><button onClick={() => void run(() => mrpShopFloorExecutionService.recordProduction(f))} className="bg-indigo-600 text-white rounded-xl p-2">سجل إنتاج</button><WorkOrderLookup value={f.work_order_id} onChange={id => set({ work_order_id: id })} /><ItemLookup label="الصنف للعيب" value={f.item_id} onChange={id => set({ item_id: id })} />{input('وصف عيب الجودة', 'description', f, set)}{input('Affected Qty', 'affected_qty', f, set, 'number')}<button onClick={() => void run(() => mrpShopFloorExecutionService.raiseQualityIssue(f))} className="bg-red-600 text-white rounded-xl p-2">فتح NCR من الأرضية</button><ProductionEventLookup value={f.production_event_id} onChange={id => set({ production_event_id: id })} />{input('سبب عكس/إلغاء الحدث', 'cancel_reason', f, set)}<button onClick={() => void run(() => mrpShopFloorExecutionService.cancelProductionEvent(f.production_event_id, f.cancel_reason))} className="bg-rose-700 text-white rounded-xl p-2">عكس حدث إنتاج</button><Msg msg={msg} /></div></Box>;
  if (type === 'consumption') return <Box title="تسجيل استهلاك فعلي"><div className="grid md:grid-cols-3 gap-3"><ProductionEventLookup value={f.production_event_id} onChange={id => set({ production_event_id: id })} /><MaterialLookup value={f.work_order_material_id} onChange={id => set({ work_order_material_id: id })} />{input('Actual Qty', 'actual_qty', f, set, 'number')}{input('Standard Qty اختياري', 'standard_qty', f, set, 'number')}{input('ملاحظات', 'notes', f, set)}<button onClick={() => void run(() => mrpShopFloorExecutionService.recordConsumption(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ الاستهلاك</button><Msg msg={msg} /></div></Box>;
  if (type === 'oee') return <Box title="حساب OEE"><div className="grid md:grid-cols-3 gap-3"><WorkCenterLookup value={f.work_center_id} onChange={id => set({ work_center_id: id })} />{input('Period Start', 'period_start', f, set, 'datetime-local')}{input('Period End', 'period_end', f, set, 'datetime-local')}<ShiftLookup value={f.shift_id} onChange={id => set({ shift_id: id })} /><WorkOrderLookup value={f.work_order_id} onChange={id => set({ work_order_id: id })} /><button onClick={() => void run(() => mrpOeeService.calculate(f))} className="bg-indigo-600 text-white rounded-xl p-2">احسب OEE</button><Msg msg={msg} /></div></Box>;
  if (type === 'downtime') return <Box title="أسباب وتوقفات"><div className="grid md:grid-cols-3 gap-3">{input('Reason Code', 'reason_code', f, set)}{input('اسم السبب', 'name_ar', f, set)}{select('Category', 'category', f, set, ['unplanned', 'planned'])}{select('Reason Type', 'reason_type', f, set, ['machine_breakdown', 'material_shortage', 'quality_issue', 'changeover', 'planned_maintenance', 'labor_absence', 'power_outage', 'meeting_break', 'setup', 'other'])}{select('Triggers Maintenance', 'triggers_maintenance', f, set, ['false', 'true'])}<button onClick={() => void run(() => mrpDowntimeReasonService.upsert({ reason_code: f.reason_code, name_ar: f.name_ar, category: f.category, reason_type: f.reason_type, triggers_maintenance: f.triggers_maintenance === 'true' }))} className="bg-slate-700 text-white rounded-xl p-2">حفظ سبب توقف</button><ReasonLookup value={f.reason_id} onChange={id => set({ reason_id: id })} /><OperationLookup value={f.operation_id} onChange={id => set({ operation_id: id })} /><WorkstationLookup value={f.workstation_id} onChange={id => set({ workstation_id: id })} />{input('ملاحظات', 'notes', f, set)}<button onClick={() => void run(() => mrpDowntimeService.start(f))} className="bg-red-600 text-white rounded-xl p-2">بدء توقف</button><DowntimeLookup value={f.downtime_event_id} onChange={id => set({ downtime_event_id: id })} />{input('سبب الإغلاق/الحل', 'resolution_notes', f, set)}<button onClick={() => void run(() => mrpDowntimeService.end(f.downtime_event_id, f.resolution_notes))} className="bg-emerald-600 text-white rounded-xl p-2">إنهاء توقف</button><Msg msg={msg} /></div></Box>;
  if (type === 'labor') return <Box title="تعيين عامل"><div className="grid md:grid-cols-3 gap-3"><WorkerLookup label="العامل" value={f.worker_id} onChange={id => set({ worker_id: id })} /><OperationLookup value={f.operation_id} onChange={id => set({ operation_id: id })} /><ShiftLookup value={f.shift_id} onChange={id => set({ shift_id: id })} /><WorkstationLookup value={f.workstation_id} onChange={id => set({ workstation_id: id })} />{select('Labor Role', 'labor_role', f, set, ['operator', 'helper', 'setter', 'quality', 'maintenance', 'supervisor'])}{input('Skill Code', 'skill_code', f, set)}<button onClick={() => void run(() => mrpLaborAssignmentService.assign(f))} className="bg-indigo-600 text-white rounded-xl p-2">تعيين</button><AssignmentLookup value={f.assignment_id} onChange={id => set({ assignment_id: id })} />{input('Good Qty', 'close_good_qty', f, set, 'number')}{input('Scrap Qty', 'close_scrap_qty', f, set, 'number')}<button onClick={() => void run(() => mrpLaborAssignmentService.close(f.assignment_id, Number(f.close_good_qty || 0), Number(f.close_scrap_qty || 0), f.notes))} className="bg-emerald-600 text-white rounded-xl p-2">إغلاق التعيين</button><Msg msg={msg} /></div></Box>;
  if (type === 'andon') return <Box title="إشارة Andon"><div className="grid md:grid-cols-3 gap-3"><WorkstationLookup value={f.workstation_id} onChange={id => set({ workstation_id: id })} /><WorkOrderLookup value={f.work_order_id} onChange={id => set({ work_order_id: id })} /><OperationLookup value={f.operation_id} onChange={id => set({ operation_id: id })} />{select('Color', 'color', f, set, ['green', 'yellow', 'red', 'blue', 'white'])}{select('Signal Type', 'signal_type', f, set, ['normal', 'attention', 'stop', 'material_required', 'quality_issue', 'maintenance_required', 'capacity_full', 'other'])}{input('Title', 'title', f, set)}{input('Description', 'description', f, set)}{select('Create Downtime?', 'create_downtime', f, set, ['false', 'true'])}<ReasonLookup value={f.reason_id} onChange={id => set({ reason_id: id })} /><button onClick={() => void run(() => mrpAndonService.raise(f))} className="bg-red-600 text-white rounded-xl p-2">رفع Andon</button><AndonLookup value={f.signal_id} onChange={id => set({ signal_id: id })} /><button onClick={() => void run(() => mrpAndonService.acknowledge(f.signal_id))} className="bg-yellow-600 text-white rounded-xl p-2">إقرار</button>{input('Resolution Notes', 'resolution_notes', f, set)}<button onClick={() => void run(() => mrpAndonService.resolve(f.signal_id, f.resolution_notes))} className="bg-emerald-600 text-white rounded-xl p-2">حل وإغلاق</button><Msg msg={msg} /></div></Box>;
  if (type === 'maintenance') return <Box title="طلب صيانة من عطل"><div className="grid md:grid-cols-3 gap-3"><DowntimeLookup value={f.downtime_event_id} onChange={id => set({ downtime_event_id: id })} /><AssetLookup value={f.asset_id} onChange={id => set({ asset_id: id })} /><WorkCenterLookup value={f.work_center_id} onChange={id => set({ work_center_id: id })} />{select('Severity', 'severity', f, set, ['info', 'warning', 'urgent', 'critical'])}{input('وصف المشكلة', 'description', f, set)}<button onClick={() => void run(() => mrpMaintenanceBridgeService.createBreakdown(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء طلب صيانة جسري</button><MaintenanceRequestLookup value={f.request_id} onChange={id => set({ request_id: id })} />{select('Status', 'request_status', f, set, ['open', 'triaged', 'converted_to_cmms', 'resolved', 'cancelled'])}{input('Reason', 'reason', f, set)}<button onClick={() => void run(() => mrpMaintenanceBridgeService.updateStatus(f.request_id, f.request_status, f.reason))} className="bg-emerald-600 text-white rounded-xl p-2">تحديث الطلب</button><Msg msg={msg} /></div></Box>;
  return null;
}

export function MrpShopFloorPage({ type }: { type: keyof typeof cfgs }) {
  const c = cfgs[type]; const [rows, setRows] = useState<Row[]>([]); const [refresh, setRefresh] = useState(0);
  useEffect(() => { c.load().then(setRows).catch(() => setRows([])); }, [c, refresh]);
  return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{type==='dashboard'&&<MrpUnitNav unit="shopfloor" />}{c.action && <Action type={c.action} onDone={() => setRefresh(x => x + 1)} />}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(col => <th key={col.key} className="p-3 text-right">{col.label}</th>)}<th className="p-3 text-right">أدوات</th></tr></thead><tbody>{rows.map((row, i) => <tr key={String(row.id ?? i)} className="border-t">{c.columns.map(col => <td key={col.key} className="p-3 max-w-[220px] truncate">{String(row[col.key] ?? '—')}</td>)}<td className="p-3"><InventoryRecordTools row={row} /></td></tr>)}{!rows.length && <tr><td colSpan={c.columns.length + 1} className="p-10 text-center text-slate-400">لا توجد بيانات حتى الآن</td></tr>}</tbody></table></div></div>;
}
