import { useEffect, useState } from 'react';
import { InventoryRecordTools } from '../shared/InventoryRecordTools';
import { LaborInterleavingSuggestionLookup, LaborTaskLookup, WarehouseLookup, WorkerLookup } from '../shared/InventoryLookups';
import { inventoryLaborAnalyticsService, inventoryLaborDispatchTaskService, inventoryLaborIncentiveProgramService, inventoryLaborInterleavingService, inventoryLaborLeaderboardService, inventoryLaborReportRunService, inventoryLaborSafetyIncidentService, inventoryLaborSkillService, inventoryLaborStandardService, inventoryLaborTimeLogService, inventoryLaborWorkforcePlanService, inventoryWorkerAvailabilityService, inventoryWorkerSkillService } from '../../../../services/sdk';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
const today=()=>new Date().toISOString().slice(0,10);
const cfgs:Record<string,Config>={
 dashboard:{title:'إدارة العمالة والإنتاجية',subtitle:'LMS: المعايير، التخطيط، التوزيع، الوقت، الحوافز، وKPIs',load:()=>inventoryLaborAnalyticsService.dashboard() as Promise<Row[]>,columns:[{key:'overall_productivity_percent',label:'الإنتاجية %'},{key:'utilization_rate_percent',label:'Utilization %'},{key:'unexplained_time_percent',label:'Unexplained %'},{key:'labor_cost_per_unit',label:'تكلفة/وحدة'},{key:'active_tasks',label:'مهام نشطة'},{key:'available_workers',label:'عمال متاحون'}]},
 standards:{title:'تعريف معايير الإنتاجية',subtitle:'Engineered/Historical standards لكل نوع مهمة مع وقت قياسي قابل للتعديل',load:()=>inventoryLaborStandardService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'standard',columns:[{key:'standard_code',label:'الكود'},{key:'task_type',label:'المهمة'},{key:'task_subtype',label:'النوع'},{key:'standard_minutes',label:'الدقائق'},{key:'standard_basis',label:'الأساس'}]},
 planning:{title:'تخطيط القوى العاملة',subtitle:'عبء العمل المتوقع مقابل الطاقة المتاحة يومياً/أسبوعياً/شهرياً',load:()=>inventoryLaborAnalyticsService.workloadCapacity() as Promise<Row[]>,action:'plan',columns:[{key:'plan_number',label:'الخطة'},{key:'plan_date',label:'التاريخ'},{key:'horizon',label:'الأفق'},{key:'expected_workload_minutes',label:'عبء العمل'},{key:'effective_capacity_minutes',label:'الطاقة'},{key:'capacity_status',label:'الحالة'}]},
 availability:{title:'توفر العمال والورديات',subtitle:'الطاقة = العمال × دقائق الوردية × عامل الكفاءة',load:()=>inventoryWorkerAvailabilityService.findAll({orderBy:'work_date',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'availability',columns:[{key:'worker_id',label:'العامل'},{key:'work_date',label:'التاريخ'},{key:'shift_code',label:'الوردية'},{key:'planned_minutes',label:'دقائق'},{key:'efficiency_factor',label:'كفاءة'},{key:'status',label:'الحالة'}]},
 dispatch:{title:'التوزيع الذكي للمهام',subtitle:'Task Dispatching بناءً على الأولوية والموقع والمهارة والحمل',load:()=>inventoryLaborAnalyticsService.dispatchQueue() as Promise<Row[]>,action:'dispatch',columns:[{key:'task_number',label:'المهمة'},{key:'task_type',label:'النوع'},{key:'priority',label:'الأولوية'},{key:'required_skill_code',label:'مهارة'},{key:'assigned_to',label:'مكلف'},{key:'status',label:'الحالة'}]},
 interleaving:{title:'Task Interleaving',subtitle:'دمج المهام في رحلة واحدة لتقليل التنقل الفارغ',load:()=>inventoryLaborInterleavingService.suggestions() as Promise<Row[]>,action:'interleaving',columns:[{key:'worker_id',label:'العامل'},{key:'reason',label:'السبب'},{key:'estimated_dead_travel_saved_meters',label:'متر موفر'},{key:'estimated_minutes_saved',label:'دقائق موفرة'},{key:'status',label:'الحالة'}]},
 time:{title:'تتبع الوقت',subtitle:'Direct / Indirect / Personal / Unexplained مع إعادة تصنيف الوقت غير المفسر',load:()=>inventoryLaborTimeLogService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'time',columns:[{key:'worker_id',label:'العامل'},{key:'time_category',label:'التصنيف'},{key:'reason_code',label:'السبب'},{key:'actual_minutes',label:'الدقائق'},{key:'standard_minutes',label:'قياسي'}]},
 employee:{title:'لوحة الموظف الفردي',subtitle:'المهام المكتملة، الوقت الفعلي/القياسي، الإنتاجية، الأخطاء، والوقت غير المفسر',load:()=>inventoryLaborAnalyticsService.employeePerformance() as Promise<Row[]>,columns:[{key:'full_name',label:'الموظف'},{key:'completed_tasks',label:'مهام'},{key:'actual_minutes',label:'فعلي'},{key:'standard_minutes',label:'قياسي'},{key:'productivity_percent',label:'إنتاجية %'},{key:'error_count',label:'أخطاء'}]},
 manager:{title:'لوحة المدير والوردية',subtitle:'أداء الفريق، متوسط الإنتاجية، الطاقة، والمهام النشطة',load:()=>inventoryLaborAnalyticsService.managerDashboard() as Promise<Row[]>,action:'leaderboard',columns:[{key:'warehouse_id',label:'المستودع'},{key:'work_date',label:'التاريخ'},{key:'shift_code',label:'الوردية'},{key:'available_workers',label:'عمال'},{key:'active_tasks',label:'نشطة'},{key:'avg_productivity_percent',label:'متوسط %'}]},
 nonproductive:{title:'تحليل الوقت غير المنتج',subtitle:'Waiting / Dead Travel / Searching / Rework / Equipment Wait مع إجراء مقترح',load:()=>inventoryLaborAnalyticsService.nonProductive() as Promise<Row[]>,action:'nonproductive',columns:[{key:'non_productive_category',label:'الفئة'},{key:'reason_name',label:'السبب'},{key:'total_minutes',label:'الدقائق'},{key:'recommended_action',label:'الإجراء'}]},
 skills:{title:'المهارات والتدريب',subtitle:'Skill matrix يمنع التوزيع لمن لا يملك شهادة/تأهيل مطلوب',load:()=>inventoryLaborAnalyticsService.skillMatrix() as Promise<Row[]>,action:'skill',columns:[{key:'full_name',label:'الموظف'},{key:'skill_code',label:'المهارة'},{key:'name_ar',label:'الوصف'},{key:'skill_level',label:'المستوى'},{key:'currently_qualified',label:'مؤهل'}]},
 incentives:{title:'الحوافز والأداء',subtitle:'85-95 قياسي، 95-105 جيد، 105-115 ممتاز، 115+ استثنائي بشرط أخطاء < 0.5%',load:()=>inventoryLaborAnalyticsService.incentives() as Promise<Row[]>,action:'incentive',columns:[{key:'program_name',label:'البرنامج'},{key:'incentive_tier',label:'المستوى'},{key:'worker_count',label:'عدد'},{key:'total_awards',label:'المكافآت'},{key:'avg_productivity',label:'متوسط %'}]},
 reports:{title:'تقارير الإنتاجية',subtitle:'تقارير يومية/أسبوعية/شهرية للاتجاهات والتحليلات',load:()=>inventoryLaborReportRunService.findAll({orderBy:'generated_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'report',columns:[{key:'report_number',label:'التقرير'},{key:'report_type',label:'النوع'},{key:'period_start',label:'من'},{key:'period_end',label:'إلى'},{key:'generated_at',label:'تاريخ'}]},
 safety:{title:'السلامة وKPIs العمالة',subtitle:'TRIR، دوران العمالة، تكلفة العمالة/وحدة، ونسبة الوقت غير المفسر',load:()=>inventoryLaborAnalyticsService.kpis() as Promise<Row[]>,action:'safety',columns:[{key:'overall_productivity_percent',label:'Productivity %'},{key:'utilization_rate_percent',label:'Utilization %'},{key:'labor_cost_per_unit',label:'Cost/Unit'},{key:'trir',label:'TRIR'},{key:'turnover_rate_percent',label:'Turnover %'}]},
 leaderboard:{title:'Shift Leaderboard',subtitle:'ترتيب الوردية: الذهب/الفضة/البرونز ومتوسط الفريق',load:()=>inventoryLaborAnalyticsService.leaderboard() as Promise<Row[]>,columns:[{key:'rank_no',label:'الترتيب'},{key:'medal',label:'وسام'},{key:'full_name',label:'الموظف'},{key:'completed_tasks',label:'مهام'},{key:'productivity_percent',label:'إنتاجية %'},{key:'error_count',label:'أخطاء'}]}
};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void){return <label className="text-xs font-bold"><span>{l}</span><input value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({work_date:today(),plan_date:today(),horizon:'daily',shift_code:'day',efficiency_factor:'0.85',hourly_cost:'0',standard_basis:'engineered',task_type:'picking',priority:'50',time_category:'indirect',report_type:'daily',target:'90'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r||'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='standard')return <Box title="إعداد المعايير"><div className="grid md:grid-cols-3 gap-3"><WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} /><button onClick={()=>void run(()=>inventoryLaborStandardService.seedTemplates(f.warehouse_id||undefined))} className="bg-slate-700 text-white rounded-xl p-2">Seed Templates</button>{inp('Standard Code','standard_code',f,set)}{inp('Task Type','task_type',f,set)}{inp('Task Subtype','task_subtype',f,set)}{inp('Name AR','name_ar',f,set)}{inp('Standard Minutes','standard_minutes',f,set)}{inp('Basis','standard_basis',f,set)}{inp('Required Skill','required_skill_code',f,set)}<button onClick={()=>void run(()=>inventoryLaborStandardService.upsert({...f,standard_minutes:Number(f.standard_minutes||0)}))} className="bg-indigo-600 text-white rounded-xl p-2">Upsert</button><Msg msg={msg}/></div></Box>;
 if(type==='plan')return <Box title="توليد خطة عمالة"><div className="grid md:grid-cols-3 gap-3">{inp('Plan Date','plan_date',f,set)}<WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} />{inp('Horizon daily/weekly/monthly','horizon',f,set)}<button onClick={()=>void run(()=>inventoryLaborWorkforcePlanService.generate(f.plan_date,f.warehouse_id||undefined,f.horizon||'daily'))} className="bg-indigo-600 text-white rounded-xl p-2">Generate Plan</button><Msg msg={msg}/></div></Box>;
 if(type==='availability')return <Box title="تسجيل توفر عامل"><div className="grid md:grid-cols-3 gap-3"><WorkerLookup label="اختر الموظف" value={f.worker_id} onChange={(id)=>set({worker_id:id})} /><WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} />{inp('Work Date','work_date',f,set)}{inp('Shift Code','shift_code',f,set)}{inp('Shift Start ISO','shift_start',f,set)}{inp('Shift End ISO','shift_end',f,set)}{inp('Efficiency','efficiency_factor',f,set)}{inp('Hourly Cost','hourly_cost',f,set)}<button onClick={()=>void run(()=>inventoryWorkerAvailabilityService.record({...f,efficiency_factor:Number(f.efficiency_factor||0.85),hourly_cost:Number(f.hourly_cost||0)}))} className="bg-indigo-600 text-white rounded-xl p-2">Record</button><Msg msg={msg}/></div></Box>;
 if(type==='dispatch')return <Box title="إنشاء/توزيع/إنهاء مهمة"><div className="grid md:grid-cols-3 gap-3"><WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} />{inp('Task Type','task_type',f,set)}{inp('Task Subtype','task_subtype',f,set)}{inp('Priority 1-100','priority',f,set)}{inp('Required Skill','required_skill_code',f,set)}{inp('Units','units',f,set)}<button onClick={()=>void run(()=>inventoryLaborDispatchTaskService.createLaborTask({...f,priority:Number(f.priority||50),units:Number(f.units||1)}))} className="bg-indigo-600 text-white rounded-xl p-2">Create</button><LaborTaskLookup label="اختر مهمة العمالة" value={f.task_id} onChange={(id)=>set({task_id:id})} /><WorkerLookup label="اختر الموظف اختياري" value={f.worker_id} onChange={(id)=>set({worker_id:id})} /><button onClick={()=>void run(()=>inventoryLaborDispatchTaskService.dispatch(f.task_id||undefined,f.worker_id||undefined))} className="bg-slate-700 text-white rounded-xl p-2">Dispatch</button><button onClick={()=>void run(()=>inventoryLaborDispatchTaskService.start(f.task_id))} className="bg-amber-600 text-white rounded-xl p-2">Start</button>{inp('Errors','errors',f,set)}<button onClick={()=>void run(()=>inventoryLaborDispatchTaskService.complete(f.task_id,Number(f.units||1),Number(f.errors||0)))} className="bg-emerald-600 text-white rounded-xl p-2">Complete</button><Msg msg={msg}/></div></Box>;
 if(type==='interleaving')return <Box title="Task Interleaving"><div className="grid md:grid-cols-3 gap-3"><WorkerLookup label="اختر الموظف اختياري" value={f.worker_id} onChange={(id)=>set({worker_id:id})} /><button onClick={()=>void run(()=>inventoryLaborInterleavingService.generate(f.worker_id||undefined))} className="bg-indigo-600 text-white rounded-xl p-2">Generate Suggestions</button><LaborInterleavingSuggestionLookup label="اختر اقتراح الدمج" value={f.suggestion_id} onChange={(id)=>set({suggestion_id:id})} /><button onClick={()=>void run(()=>inventoryLaborInterleavingService.accept(f.suggestion_id))} className="bg-emerald-600 text-white rounded-xl p-2">Accept</button><Msg msg={msg}/></div></Box>;
 if(type==='time')return <Box title="تسجيل/تصنيف الوقت"><div className="grid md:grid-cols-3 gap-3"><WorkerLookup label="اختر الموظف" value={f.worker_id} onChange={(id)=>set({worker_id:id})} /><WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} />{inp('Category direct/indirect/personal/unexplained','time_category',f,set)}{inp('Reason Code','reason_code',f,set)}{inp('Start ISO','start_at',f,set)}{inp('End ISO','end_at',f,set)}<button onClick={()=>void run(()=>inventoryLaborTimeLogService.record(f))} className="bg-indigo-600 text-white rounded-xl p-2">Record Time</button>{inp('Time Log ID','time_log_id',f,set)}{inp('New Category','new_category',f,set)}<button onClick={()=>void run(()=>inventoryLaborTimeLogService.classify(f.time_log_id,f.reason_code,f.new_category||'indirect',f.notes))} className="bg-emerald-600 text-white rounded-xl p-2">Classify</button><Msg msg={msg}/></div></Box>;
 if(type==='leaderboard')return <Box title="توليد Leaderboard"><div className="grid md:grid-cols-3 gap-3"><WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} />{inp('Work Date','work_date',f,set)}{inp('Shift Code','shift_code',f,set)}{inp('Target %','target',f,set)}<button onClick={()=>void run(()=>inventoryLaborLeaderboardService.generate(f.warehouse_id||undefined,f.work_date,f.shift_code,Number(f.target||90)))} className="bg-indigo-600 text-white rounded-xl p-2">Generate</button><Msg msg={msg}/></div></Box>;
 if(type==='nonproductive')return <Box title="أسباب الوقت غير المنتج"><div className="grid md:grid-cols-3 gap-3"><button onClick={()=>void run(()=>inventoryLaborTimeLogService.seedNonProductiveReasons())} className="bg-indigo-600 text-white rounded-xl p-2">Seed Reasons</button><Msg msg={msg}/></div></Box>;
 if(type==='skill')return <Box title="مهارة/تدريب"><div className="grid md:grid-cols-3 gap-3"><button onClick={()=>void run(()=>inventoryLaborSkillService.seedCatalog())} className="bg-slate-700 text-white rounded-xl p-2">Seed Skill Catalog</button><WorkerLookup label="اختر الموظف" value={f.worker_id} onChange={(id)=>set({worker_id:id})} />{inp('Skill Code','skill_code',f,set)}{inp('Skill Name AR','name_ar',f,set)}{inp('Level','skill_level',f,set)}{inp('Expires At','expires_at',f,set)}<button onClick={()=>void run(()=>inventoryWorkerSkillService.upsert(f.worker_id,f.skill_code,f.name_ar,f.skill_level||'certified',f.expires_at||undefined))} className="bg-indigo-600 text-white rounded-xl p-2">Upsert Skill</button><Msg msg={msg}/></div></Box>;
 if(type==='incentive')return <Box title="احتساب الحوافز"><div className="grid md:grid-cols-3 gap-3">{inp('Program ID','program_id',f,set)}<button onClick={()=>void run(()=>inventoryLaborIncentiveProgramService.calculate(f.program_id))} className="bg-indigo-600 text-white rounded-xl p-2">Calculate</button><Msg msg={msg}/></div></Box>;
 if(type==='report')return <Box title="تقرير إنتاجية"><div className="grid md:grid-cols-3 gap-3">{inp('Type daily/weekly/monthly','report_type',f,set)}{inp('From','from',f,set)}{inp('To','to',f,set)}<WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} /><button onClick={()=>void run(()=>inventoryLaborReportRunService.generate(f.report_type||'daily',f.from,f.to,f.warehouse_id||undefined))} className="bg-indigo-600 text-white rounded-xl p-2">Generate Report</button><Msg msg={msg}/></div></Box>;
 if(type==='safety')return <Box title="تسجيل حادث سلامة"><div className="grid md:grid-cols-3 gap-3"><WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} /><WorkerLookup label="اختر الموظف" value={f.worker_id} onChange={(id)=>set({worker_id:id})} />{inp('Incident Date','incident_date',f,set)}{inp('Incident Type','incident_type',f,set)}{inp('Recordable true/false','recordable',f,set)}{inp('Description','description',f,set)}<button onClick={()=>void run(()=>inventoryLaborSafetyIncidentService.record({...f,recordable:f.recordable==='true'}))} className="bg-indigo-600 text-white rounded-xl p-2">Record Incident</button><Msg msg={msg}/></div></Box>;
 return null}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 p-2 rounded-xl">{msg}</div>:null}
export function LaborPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
