import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { ItemLookup } from '../../inventory/shared/InventoryLookups';
import { InventoryRecordTools } from '../../inventory/shared/InventoryRecordTools';
import { mrpAnalyticsService, mrpAreaService, mrpAssetService, mrpCalendarService, mrpCapacityService, mrpLineService, mrpNumberingService, mrpOperationService, mrpPlantService, mrpResourceService, mrpRoutingService, mrpShiftService, mrpWorkCenterService } from '../../../../services/sdk';
import { supabase } from '../../../../services/supabase/supabase';
import { MrpUnitNav } from './MrpUnitNav';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Option={id:string;code:string;name?:string;meta?:string};
type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
const cfgs:Record<string,Config>={
 dashboard:{title:'الأساس التقني للتصنيع',subtitle:'مصانع، مناطق، خطوط، مراكز عمل، طاقة، عمليات، Routing وتكاملات.',load:()=>mrpAnalyticsService.dashboard() as Promise<Row[]>,columns:[{key:'active_plants',label:'مصانع نشطة'},{key:'active_lines',label:'خطوط نشطة'},{key:'active_work_centers',label:'مراكز عمل'},{key:'effective_routings',label:'Routing فعال'}]},
 plants:{title:'المصانع',subtitle:'تعريف منشآت التصنيع',load:()=>mrpPlantService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'plant',columns:[{key:'plant_code',label:'الكود'},{key:'name_ar',label:'الاسم'},{key:'plant_type',label:'النوع'},{key:'status',label:'الحالة'}]},
 areas:{title:'مناطق المصنع',subtitle:'مناطق الإنتاج والجودة والصيانة',load:()=>mrpAreaService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'area',columns:[{key:'area_code',label:'الكود'},{key:'name_ar',label:'الاسم'},{key:'area_type',label:'النوع'},{key:'status',label:'الحالة'}]},
 lines:{title:'خطوط الإنتاج',subtitle:'خطوط discrete/process/assembly/packaging',load:()=>mrpLineService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'line',columns:[{key:'line_code',label:'الكود'},{key:'name_ar',label:'الاسم'},{key:'line_type',label:'النوع'},{key:'status',label:'الحالة'}]},
 workCenters:{title:'مراكز العمل',subtitle:'الطاقة والتكلفة والقيود',load:()=>mrpWorkCenterService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'workCenter',columns:[{key:'work_center_code',label:'الكود'},{key:'name_ar',label:'الاسم'},{key:'work_center_type',label:'النوع'},{key:'status',label:'الحالة'}]},
 resources:{title:'الموارد',subtitle:'عمالة/أدوات/آلات/خدمات خارجية وربطها بمراكز العمل',load:()=>mrpResourceService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'resource',columns:[{key:'resource_code',label:'الكود'},{key:'name_ar',label:'الاسم'},{key:'resource_type',label:'النوع'},{key:'status',label:'الحالة'}]},
 assets:{title:'الأصول الإنتاجية',subtitle:'ربط المعدات بمراكز العمل والصيانة',load:()=>mrpAssetService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'asset',columns:[{key:'asset_code',label:'الكود'},{key:'name_ar',label:'الأصل'},{key:'criticality',label:'الأهمية'},{key:'status',label:'الحالة'}]},
 calendars:{title:'تقويمات التصنيع',subtitle:'التقويمات الإنتاجية',load:()=>mrpCalendarService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'calendar',columns:[{key:'calendar_code',label:'الكود'},{key:'name_ar',label:'الاسم'},{key:'timezone',label:'المنطقة'},{key:'status',label:'الحالة'}]},
 shifts:{title:'الورديات',subtitle:'ورديات التصنيع',load:()=>mrpShiftService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'shift',columns:[{key:'shift_code',label:'الكود'},{key:'name_ar',label:'الاسم'},{key:'starts_at_time',label:'البداية'},{key:'ends_at_time',label:'النهاية'}]},
 capacity:{title:'طاقة مراكز العمل',subtitle:'تقويم الطاقة والحمل',load:()=>mrpAnalyticsService.capacity() as Promise<Row[]>,action:'capacity',columns:[{key:'work_center_code',label:'مركز العمل'},{key:'work_date',label:'التاريخ'},{key:'available_minutes',label:'المتاح'},{key:'reserved_load_minutes',label:'المحجوز'},{key:'status',label:'الحالة'}]},
 operations:{title:'كتالوج العمليات',subtitle:'قص/ثني/لحام/فحص/تعبئة...',load:()=>mrpOperationService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'operation',columns:[{key:'operation_code',label:'الكود'},{key:'name_ar',label:'العملية'},{key:'operation_type',label:'النوع'},{key:'status',label:'الحالة'}]},
 routings:{title:'Routing Foundation',subtitle:'تسلسل العمليات ومراكز العمل',load:()=>mrpAnalyticsService.routings() as Promise<Row[]>,action:'routing',columns:[{key:'routing_code',label:'الكود'},{key:'version_no',label:'الإصدار'},{key:'status',label:'الحالة'},{key:'operation_count',label:'العمليات'}]},
 numbering:{title:'ترقيم التصنيع',subtitle:'قواعد ترقيم MRP',load:()=>mrpNumberingService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'numbering',columns:[{key:'entity_type',label:'الكيان'},{key:'prefix',label:'Prefix'},{key:'next_number',label:'التالي'},{key:'is_default',label:'افتراضي'}]},
 audit:{title:'سجل تدقيق التصنيع',subtitle:'كل تعديل وإغلاق بسبب',load:()=>mrpAnalyticsService.audit() as Promise<Row[]>,columns:[{key:'unit_key',label:'الوحدة'},{key:'entity_table',label:'الجدول'},{key:'action',label:'الإجراء'},{key:'reason',label:'السبب'},{key:'created_at',label:'التاريخ'}]},
 integrations:{title:'صحة التكاملات',subtitle:'Inventory/Procurement/Finance/HR/Quality',load:()=>mrpAnalyticsService.integrations() as Promise<Row[]>,columns:[{key:'inventory_available',label:'المخزون'},{key:'procurement_available',label:'المشتريات'},{key:'finance_available',label:'المالية'},{key:'hr_available',label:'HR'},{key:'quality_foundation_available',label:'الجودة'}]},
};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void,type='text'){return <label className="text-xs font-bold text-slate-600"><span>{l}</span><input type={type} value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function select(l:string,n:string,f:Form,set:(p:Form)=>void,ops:string[]){return <label className="text-xs font-bold text-slate-600"><span>{l}</span><select value={f[n]||ops[0]} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1 bg-white">{ops.map(o=><option key={o} value={o}>{o}</option>)}</select></label>}
function Box({title,children}:{title:string;children:ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 rounded-xl p-2 whitespace-pre-wrap">{msg}</div>:null}
function useOptions(table:string,cols:string,map:(r:Row)=>Option){const[rows,setRows]=useState<Option[]>([]);const[loading,setLoading]=useState(false);const[q,setQ]=useState('');useEffect(()=>{let ok=true;const load=async()=>{setLoading(true);try{const db=supabase as unknown as {from:(t:string)=>{select:(c:string)=>{limit:(n:number)=>Promise<{data:unknown[]|null}>}}};const{data}=await db.from(table).select(cols).limit(500);if(ok)setRows(((data||[]) as Row[]).map(map))}finally{if(ok)setLoading(false)}};void load();return()=>{ok=false}},[table,cols]);const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return(!s?rows:rows.filter(o=>`${o.code} ${o.name||''} ${o.meta||''}`.toLowerCase().includes(s))).slice(0,80)},[rows,q]);return{filtered,loading,q,setQ}}
function Lookup({label,table,cols,map,value,onChange}:{label:string;table:string;cols:string;map:(r:Row)=>Option;value?:string;onChange:(id:string)=>void}){const{filtered,loading,q,setQ}=useOptions(table,cols,map);return <label className="text-xs font-bold text-slate-600 space-y-1 block"><span>{label}</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالكود أو الاسم..." className="w-full border rounded-xl p-2"/><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 bg-white"><option value="">{loading?'جاري التحميل...':'-- اختر --'}</option>{filtered.map(o=><option key={o.id} value={o.id}>{o.code}{o.name?` — ${o.name}`:''}{o.meta?` — ${o.meta}`:''}</option>)}</select></label>}
const PlantLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="المصنع" table="manufacturing_plants" cols="id,plant_code,name_ar,status" map={r=>({id:String(r.id),code:String(r.plant_code||''),name:String(r.name_ar||''),meta:String(r.status||'')})}{...p}/>;
const AreaLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="المنطقة" table="manufacturing_areas" cols="id,area_code,name_ar,area_type" map={r=>({id:String(r.id),code:String(r.area_code||''),name:String(r.name_ar||''),meta:String(r.area_type||'')})}{...p}/>;
const LineLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="خط الإنتاج" table="production_lines" cols="id,line_code,name_ar,line_type" map={r=>({id:String(r.id),code:String(r.line_code||''),name:String(r.name_ar||''),meta:String(r.line_type||'')})}{...p}/>;
const WorkCenterLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="مركز العمل" table="work_centers" cols="id,work_center_code,name_ar,work_center_type" map={r=>({id:String(r.id),code:String(r.work_center_code||''),name:String(r.name_ar||''),meta:String(r.work_center_type||'')})}{...p}/>;
const ResourceLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="المورد" table="manufacturing_resources" cols="id,resource_code,name_ar,resource_type" map={r=>({id:String(r.id),code:String(r.resource_code||''),name:String(r.name_ar||''),meta:String(r.resource_type||'')})}{...p}/>;
const CalendarLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="التقويم" table="manufacturing_calendars" cols="id,calendar_code,name_ar,status" map={r=>({id:String(r.id),code:String(r.calendar_code||''),name:String(r.name_ar||''),meta:String(r.status||'')})}{...p}/>;
const ShiftLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="الوردية" table="manufacturing_shifts" cols="id,shift_code,name_ar,status" map={r=>({id:String(r.id),code:String(r.shift_code||''),name:String(r.name_ar||''),meta:String(r.status||'')})}{...p}/>;
const OperationLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="عملية من الكتالوج" table="manufacturing_operation_catalog" cols="id,operation_code,name_ar,operation_type" map={r=>({id:String(r.id),code:String(r.operation_code||''),name:String(r.name_ar||''),meta:String(r.operation_type||'')})}{...p}/>;
const RoutingLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="Routing" table="routing_headers" cols="id,routing_code,version_no,status" map={r=>({id:String(r.id),code:String(r.routing_code||''),name:String(r.version_no||''),meta:String(r.status||'')})}{...p}/>;
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({plant_type:'manufacturing',area_type:'production',line_type:'discrete',work_center_type:'machine',resource_type:'labor_skill',criticality:'B',operation_type:'production',routing_type:'manufacturing',entity_type:'work_order',prefix:'WO',padding:'4',next_number:'1',starts_at_time:'08:00',ends_at_time:'16:00',break_minutes:'0',available_minutes:'480'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r??'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='plant')return <Box title="إنشاء مصنع"><div className="grid md:grid-cols-3 gap-3">{inp('Plant Code اختياري','plant_code',f,set)}{inp('الاسم','name_ar',f,set)}{select('النوع','plant_type',f,set,['manufacturing','assembly','packaging','repair','mixed'])}{inp('العنوان','address',f,set)}<button onClick={()=>void run(()=>mrpPlantService.createPlant(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء مصنع</button><Msg msg={msg}/></div></Box>;
 if(type==='area')return <Box title="إنشاء منطقة"><div className="grid md:grid-cols-3 gap-3"><PlantLookup value={f.plant_id} onChange={id=>set({plant_id:id})}/>{inp('Area Code اختياري','area_code',f,set)}{inp('اسم المنطقة','name_ar',f,set)}{select('نوع المنطقة','area_type',f,set,['production','warehouse','quality','maintenance','utility','office'])}<button onClick={()=>void run(()=>mrpAreaService.createArea(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء منطقة</button><Msg msg={msg}/></div></Box>;
 if(type==='line')return <Box title="إنشاء خط إنتاج"><div className="grid md:grid-cols-3 gap-3"><PlantLookup value={f.plant_id} onChange={id=>set({plant_id:id})}/><AreaLookup value={f.area_id} onChange={id=>set({area_id:id})}/>{inp('Line Code اختياري','line_code',f,set)}{inp('اسم الخط','name_ar',f,set)}{select('نوع الخط','line_type',f,set,['discrete','process','packaging','assembly','mixed'])}<button onClick={()=>void run(()=>mrpLineService.createLine(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء خط</button><Msg msg={msg}/></div></Box>;
 if(type==='workCenter')return <Box title="إنشاء مركز عمل"><div className="grid md:grid-cols-3 gap-3"><PlantLookup value={f.plant_id} onChange={id=>set({plant_id:id})}/><LineLookup value={f.line_id} onChange={id=>set({line_id:id})}/>{inp('Code اختياري','work_center_code',f,set)}{inp('الاسم','name_ar',f,set)}{select('النوع','work_center_type',f,set,['machine','labor','cell','inspection','packaging','external'])}<button onClick={()=>void run(()=>mrpWorkCenterService.createWorkCenter(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء مركز عمل</button><Msg msg={msg}/></div></Box>;
 if(type==='resource')return <Box title="إنشاء/ربط مورد"><div className="grid md:grid-cols-3 gap-3">{inp('Resource Code اختياري','resource_code',f,set)}{inp('الاسم','name_ar',f,set)}{select('النوع','resource_type',f,set,['labor_skill','tool','fixture','machine','inspection_device','external_service'])}{inp('Capacity/Shift','capacity_per_shift',f,set,'number')}{inp('Cost Rate','cost_rate',f,set,'number')}<button onClick={()=>void run(()=>mrpResourceService.upsertResource(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ مورد</button><WorkCenterLookup value={f.work_center_id} onChange={id=>set({work_center_id:id})}/><ResourceLookup value={f.resource_id} onChange={id=>set({resource_id:id})}/>{inp('Required Qty','required_quantity',f,set,'number')}<button onClick={()=>void run(()=>mrpResourceService.linkToWorkCenter(f))} className="bg-slate-700 text-white rounded-xl p-2">ربط بمركز عمل</button><Msg msg={msg}/></div></Box>;
 if(type==='asset')return <Box title="إنشاء/تحديث أصل إنتاجي"><div className="grid md:grid-cols-3 gap-3">{inp('Asset Code اختياري','asset_code',f,set)}{inp('اسم الأصل','name_ar',f,set)}<PlantLookup value={f.plant_id} onChange={id=>set({plant_id:id})}/><WorkCenterLookup value={f.work_center_id} onChange={id=>set({work_center_id:id})}/>{select('Criticality','criticality',f,set,['A','B','C'])}<button onClick={()=>void run(()=>mrpAssetService.upsertAsset(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ أصل</button><Msg msg={msg}/></div></Box>;
 if(type==='calendar')return <Box title="إنشاء تقويم"><div className="grid md:grid-cols-3 gap-3">{inp('Code اختياري','calendar_code',f,set)}{inp('الاسم','name_ar',f,set)}{inp('Timezone','timezone',f,set)}<button onClick={()=>void run(()=>mrpCalendarService.createCalendar(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء تقويم</button><Msg msg={msg}/></div></Box>;
 if(type==='shift')return <Box title="إنشاء وردية"><div className="grid md:grid-cols-3 gap-3">{inp('Shift Code اختياري','shift_code',f,set)}{inp('الاسم','name_ar',f,set)}{inp('البداية','starts_at_time',f,set,'time')}{inp('النهاية','ends_at_time',f,set,'time')}{inp('Break Minutes','break_minutes',f,set,'number')}<button onClick={()=>void run(()=>mrpShiftService.createShift(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء وردية</button><Msg msg={msg}/></div></Box>;
 if(type==='capacity')return <Box title="توليد طاقة مركز عمل"><div className="grid md:grid-cols-3 gap-3"><WorkCenterLookup value={f.work_center_id} onChange={id=>set({work_center_id:id})}/><CalendarLookup value={f.calendar_id} onChange={id=>set({calendar_id:id})}/><ShiftLookup value={f.shift_id} onChange={id=>set({shift_id:id})}/>{inp('Start Date','start_date',f,set,'date')}{inp('End Date','end_date',f,set,'date')}{inp('Available Minutes','available_minutes',f,set,'number')}<button onClick={()=>void run(()=>mrpCapacityService.generate(f))} className="bg-indigo-600 text-white rounded-xl p-2">توليد الطاقة</button><Msg msg={msg}/></div></Box>;
 if(type==='operation')return <Box title="إضافة عملية"><div className="grid md:grid-cols-3 gap-3">{inp('Code اختياري','operation_code',f,set)}{inp('الاسم','name_ar',f,set)}{select('النوع','operation_type',f,set,['production','setup','inspection','packaging','maintenance','subcontract'])}{inp('Setup min','standard_setup_minutes',f,set,'number')}{inp('Run min/unit','standard_run_minutes_per_unit',f,set,'number')}<button onClick={()=>void run(()=>mrpOperationService.upsertOperation(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ عملية</button><Msg msg={msg}/></div></Box>;
 if(type==='routing')return <Box title="Routing"><div className="grid md:grid-cols-3 gap-3">{inp('Routing Code اختياري','routing_code',f,set)}<ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})}/>{select('Type','routing_type',f,set,['manufacturing','rework','repair','subcontract'])}{inp('Version','version_no',f,set)}<button onClick={()=>void run(()=>mrpRoutingService.createRouting(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء Routing</button><RoutingLookup value={f.routing_id} onChange={id=>set({routing_id:id})}/><OperationLookup value={f.operation_id} onChange={id=>set({operation_id:id})}/><WorkCenterLookup value={f.routing_wc_id} onChange={id=>set({work_center_id:id,routing_wc_id:id})}/>{inp('Sequence','sequence_no',f,set,'number')}{inp('Operation Name','operation_name',f,set)}{inp('Setup','setup_minutes',f,set,'number')}{inp('Run/unit','run_minutes_per_unit',f,set,'number')}<button onClick={()=>void run(()=>mrpRoutingService.addOperation(f))} className="bg-slate-700 text-white rounded-xl p-2">إضافة عملية للـ Routing</button><button onClick={()=>void run(()=>mrpRoutingService.approve(f.routing_id))} className="bg-emerald-600 text-white rounded-xl p-2">اعتماد Routing</button><Msg msg={msg}/></div></Box>;
 if(type==='numbering')return <Box title="قاعدة ترقيم"><div className="grid md:grid-cols-3 gap-3">{inp('Entity Type','entity_type',f,set)}{inp('Prefix','prefix',f,set)}{inp('Padding','padding',f,set,'number')}{inp('Next','next_number',f,set,'number')}<button onClick={()=>void run(()=>mrpNumberingService.upsert(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ القاعدة</button><button onClick={()=>void run(async()=>mrpNumberingService.preview(f.entity_type))} className="bg-slate-700 text-white rounded-xl p-2">معاينة التالي</button><Msg msg={msg}/></div></Box>;
 return null}
export function MrpPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{type==='dashboard'&&<MrpUnitNav unit="foundation" />}{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">أدوات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
