import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Loader2, Plus, Search, TrendingUp } from 'lucide-react';
import { useAuthStore, useUIStore } from '../../core/stores';
import { managerWorkloadItemService, userService } from '../../services/sdk';
import Card from '../../shared/components/ui/Card';
import Button from '../../shared/components/ui/Button';
import { getErrorMessage } from '../../services/errors';

export default function ManagerWorkloadPage(){
 const {user}=useAuthStore(); const {addToast}=useUIStore(); const [loading,setLoading]=useState(true); const [items,setItems]=useState<any[]>([]); const [team,setTeam]=useState<any[]>([]); const [search,setSearch]=useState(''); const [show,setShow]=useState(false); const [form,setForm]=useState({employee_id:'',title:'',description:'',workload_type:'task',estimated_hours:1,priority:'medium',due_at:''});
 const load=useCallback(async()=>{if(!user?.id)return; setLoading(true); try{const [rows,users]=await Promise.all([managerWorkloadItemService.findByManager(user.id),userService.findAllUsers(user.department?{department:user.department}:undefined)]); setItems(rows||[]); setTeam((users||[]).filter((u:any)=>u.id!==user.id&&(u.manager_id===user.id||u.department===user.department)))}catch(e){addToast(getErrorMessage(e),'error')}finally{setLoading(false)}},[addToast,user?.department,user?.id]); useEffect(()=>{load()},[load]);
 const filtered=items.filter(i=>!search||[i.title,i.description,i.priority,i.status].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase())); const hours=useMemo(()=>items.filter(i=>i.status!=='completed').reduce((s,i)=>s+Number(i.estimated_hours||0),0),[items]);
 const create=async()=>{if(!form.title.trim())return addToast('يرجى إدخال عنوان العمل','warning'); try{await managerWorkloadItemService.createItem({manager_id:user?.id,employee_id:form.employee_id||undefined,title:form.title,description:form.description||undefined,workload_type:form.workload_type as any,estimated_hours:Number(form.estimated_hours),priority:form.priority as any,due_at:form.due_at||undefined}); addToast('تمت إضافة عنصر عبء العمل','success'); setShow(false); setForm({employee_id:'',title:'',description:'',workload_type:'task',estimated_hours:1,priority:'medium',due_at:''}); await load()}catch(e){addToast(getErrorMessage(e),'error')}};
 const complete=async(id:string)=>{try{await managerWorkloadItemService.complete(id); addToast('تم الإكمال','success'); await load()}catch(e){addToast(getErrorMessage(e),'error')}};
 if(loading)return <div className="flex items-center justify-center py-20"><Loader2 className="animate-spin text-amber-600" size={36}/></div>;
 return <div className="space-y-6 animate-fade-in" dir="rtl"><div className="bg-gradient-to-br from-amber-500 to-orange-600 rounded-2xl p-6 text-white flex items-center justify-between"><div><p className="text-white/75 text-sm">Workload</p><h2 className="text-2xl font-extrabold mt-1 flex items-center gap-2"><TrendingUp/> عبء العمل والموارد</h2><p className="text-white/80 mt-2 text-sm">توزيع العمل وساعات الحمل على الفريق.</p></div><Button onClick={()=>setShow(true)} className="!bg-white/15 hover:!bg-white/25 !text-white !border-none" icon={<Plus size={16}/>} iconPosition="left">عمل جديد</Button></div><div className="grid grid-cols-3 gap-3"><Card><p className="text-2xl font-extrabold">{items.length}</p><p className="text-xs text-slate-500">العناصر</p></Card><Card><p className="text-2xl font-extrabold text-amber-600">{hours}</p><p className="text-xs text-slate-500">ساعات مفتوحة</p></Card><Card><p className="text-2xl font-extrabold text-emerald-600">{items.filter(i=>i.status==='completed').length}</p><p className="text-xs text-slate-500">منجزة</p></Card></div><div className="relative"><Search size={16} className="absolute right-3 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث في عبء العمل..." className="w-full pr-9 pl-3 py-2.5 rounded-xl border border-slate-200 text-sm outline-none focus:border-amber-400"/></div><div className="grid gap-3">{filtered.map(item=><Card key={item.id}><div className="flex items-center justify-between"><div><p className="font-bold text-slate-900">{item.title}</p><p className="text-xs text-slate-500 mt-1">{item.workload_type} • {item.estimated_hours||0}س • {item.priority} • {item.status}</p></div>{item.status!=='completed'?<Button size="sm" variant="success" onClick={()=>complete(item.id)} icon={<CheckCircle2 size={14}/>} iconPosition="left">إكمال</Button>:<span className="text-xs font-bold bg-emerald-50 text-emerald-700 px-2 py-1 rounded-full">مكتمل</span>}</div></Card>)}{filtered.length===0&&<Card><p className="text-center py-8 text-slate-400">لا توجد عناصر</p></Card>}</div>{show&&<WorkloadModal form={form} setForm={setForm} team={team} onClose={()=>setShow(false)} onSubmit={create}/>}</div>
}
function WorkloadModal({form,setForm,team,onClose,onSubmit}:any){return <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={onClose}><div className="bg-white rounded-2xl p-6 w-full max-w-md" onClick={e=>e.stopPropagation()}><h3 className="font-bold text-lg mb-4">عنصر عمل جديد</h3><div className="space-y-3"><select value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})} className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-amber-400"><option value="">غير مخصص</option>{team.map((e:any)=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="العنوان" className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-amber-400"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={3} placeholder="الوصف" className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-amber-400"/><select value={form.workload_type} onChange={e=>setForm({...form,workload_type:e.target.value})} className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-amber-400"><option value="task">مهمة</option><option value="project">مشروع</option><option value="support">دعم</option><option value="training">تدريب</option><option value="other">آخر</option></select><input type="number" min={0} value={form.estimated_hours} onChange={e=>setForm({...form,estimated_hours:Number(e.target.value)})} className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-amber-400"/><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-amber-400"><option value="low">منخفض</option><option value="medium">متوسط</option><option value="high">عالٍ</option><option value="critical">حرج</option></select><input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})} className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-amber-400"/><div className="flex gap-2"><Button variant="secondary" fullWidth onClick={onClose}>إلغاء</Button><Button fullWidth onClick={onSubmit}>حفظ</Button></div></div></div></div>}
