import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, Loader2, Search, XCircle } from 'lucide-react';
import { useAuthStore, useUIStore } from '../../core/stores';
import { approvalActionService, approvalRequestService } from '../../services/sdk';
import Card from '../../shared/components/ui/Card';
import Button from '../../shared/components/ui/Button';
import { getErrorMessage } from '../../services/errors';

export default function ManagerApprovalsPage(){
 const {user}=useAuthStore(); const {addToast}=useUIStore(); const [loading,setLoading]=useState(true); const [rows,setRows]=useState<any[]>([]); const [search,setSearch]=useState('');
 const load=useCallback(async()=>{if(!user?.id)return; setLoading(true); try{setRows(await approvalRequestService.findForApprover(user.id))}catch(e){addToast(getErrorMessage(e),'error')}finally{setLoading(false)}},[addToast,user?.id]); useEffect(()=>{load()},[load]);
 const decide=async(row:any,status:'approved'|'rejected')=>{const note=prompt(status==='approved'?'ملاحظة الموافقة:':'سبب الرفض:')||''; try{await approvalRequestService.decide(row.id,status,user?.id,note); await approvalActionService.addAction({approval_request_id:row.id,actor_id:user?.id,action:status,note} as any); addToast(status==='approved'?'تمت الموافقة':'تم الرفض','success'); await load()}catch(e){addToast(getErrorMessage(e),'error')}};
 const filtered=rows.filter(r=>!search||[r.title,r.description,r.requester_name,r.request_type].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase()));
 if(loading)return <div className="flex items-center justify-center py-20"><Loader2 className="animate-spin text-amber-600" size={36}/></div>;
 return <div className="space-y-6 animate-fade-in" dir="rtl"><div className="bg-gradient-to-br from-amber-500 to-orange-600 rounded-2xl p-6 text-white"><p className="text-white/75 text-sm">Approval Center</p><h2 className="text-2xl font-extrabold mt-1">مركز موافقات المدير</h2></div><div className="relative"><Search size={16} className="absolute right-3 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث في الموافقات..." className="w-full pr-9 pl-3 py-2.5 rounded-xl border border-slate-200 text-sm outline-none focus:border-amber-400"/></div><div className="grid gap-3">{filtered.length===0?<Card><p className="text-center py-8 text-slate-400">لا توجد موافقات</p></Card>:filtered.map(r=><Card key={r.id}><div className="flex items-center justify-between gap-3 flex-wrap"><div><p className="font-bold text-slate-900">{r.title}</p><p className="text-xs text-slate-500 mt-1">{r.request_type} • {r.requester_name||'مستخدم'} • {r.priority}</p>{r.description&&<p className="text-sm text-slate-600 mt-2">{r.description}</p>}</div>{r.status==='pending'?<div className="flex gap-2"><Button size="sm" variant="success" onClick={()=>decide(r,'approved')} icon={<CheckCircle2 size={14}/>} iconPosition="left">موافقة</Button><Button size="sm" variant="danger" onClick={()=>decide(r,'rejected')} icon={<XCircle size={14}/>} iconPosition="left">رفض</Button></div>:<span className="text-xs font-bold px-3 py-1 rounded-full bg-slate-100 text-slate-700">{r.status}</span>}</div></Card>)}</div></div>
}
