import { useCallback, useEffect, useState } from 'react';
import { Award, Loader2, Search, Target, Users } from 'lucide-react';
import { useAuthStore, useUIStore } from '../../core/stores';
import { employeeGoalService, employeeSkillService, userService } from '../../services/sdk';
import Card from '../../shared/components/ui/Card';
import { getErrorMessage } from '../../services/errors';

export default function ManagerTeamPerformancePage(){
 const {user}=useAuthStore(); const {addToast}=useUIStore(); const [loading,setLoading]=useState(true); const [team,setTeam]=useState<any[]>([]); const [goals,setGoals]=useState<any[]>([]); const [skills,setSkills]=useState<any[]>([]); const [search,setSearch]=useState('');
 const load=useCallback(async()=>{if(!user?.id)return; setLoading(true); try{const users=await userService.findAllUsers(user.department?{department:user.department}:undefined); const mine=(users||[]).filter((u:any)=>u.id!==user.id&&(u.manager_id===user.id||u.department===user.department)); setTeam(mine); const goalSets=await Promise.all(mine.map((m:any)=>employeeGoalService.findByEmployee(m.id).catch(()=>[]))); const skillSets=await Promise.all(mine.map((m:any)=>employeeSkillService.findByEmployee(m.id).catch(()=>[]))); setGoals(goalSets.flat()); setSkills(skillSets.flat());}catch(e){addToast(getErrorMessage(e),'error')}finally{setLoading(false)}},[addToast,user?.department,user?.id]); useEffect(()=>{load()},[load]);
 const filtered=team.filter(t=>!search||[t.full_name,t.email,t.position].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase()));
 if(loading)return <div className="flex items-center justify-center py-20"><Loader2 className="animate-spin text-amber-600" size={36}/></div>;
 return <div className="space-y-6 animate-fade-in" dir="rtl"><div className="bg-gradient-to-br from-amber-500 to-orange-600 rounded-2xl p-6 text-white"><p className="text-white/75 text-sm">Team Performance</p><h2 className="text-2xl font-extrabold mt-1">أداء الفريق</h2></div><div className="grid grid-cols-3 gap-3"><Card><Users className="text-amber-600"/><p className="text-2xl font-extrabold mt-2">{team.length}</p><p className="text-xs text-slate-500">أعضاء الفريق</p></Card><Card><Target className="text-blue-600"/><p className="text-2xl font-extrabold mt-2">{goals.filter(g=>g.status==='active').length}</p><p className="text-xs text-slate-500">أهداف نشطة</p></Card><Card><Award className="text-purple-600"/><p className="text-2xl font-extrabold mt-2">{skills.length}</p><p className="text-xs text-slate-500">مهارات مسجلة</p></Card></div><div className="relative"><Search size={16} className="absolute right-3 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث في الفريق..." className="w-full pr-9 pl-3 py-2.5 rounded-xl border border-slate-200 text-sm outline-none focus:border-amber-400"/></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{filtered.map(emp=>{const empGoals=goals.filter(g=>g.employee_id===emp.id); const avg=empGoals.length?Math.round(empGoals.reduce((s,g)=>s+Number(g.progress_percent||0),0)/empGoals.length):0; return <Card key={emp.id}><p className="font-bold text-slate-900">{emp.full_name}</p><p className="text-xs text-slate-500 mt-1">{emp.position||'—'} • {emp.department||'—'}</p><div className="mt-4"><div className="flex justify-between text-xs font-bold text-slate-500 mb-1"><span>متوسط الأهداف</span><span>{avg}%</span></div><div className="h-2 bg-slate-100 rounded-full overflow-hidden"><div className="h-full bg-amber-500" style={{width:`${avg}%`}}/></div></div><p className="text-xs text-slate-500 mt-3">الأهداف: {empGoals.length} • المهارات: {skills.filter(s=>s.employee_id===emp.id).length}</p></Card>})}</div></div>
}
