import { useEffect, useState } from 'react';
import { ItemLookup } from '../../inventory/shared/InventoryLookups';
import { InventoryRecordTools } from '../../inventory/shared/InventoryRecordTools';
import { mrpDemandHistoryService, mrpForecastingAnalyticsService, mrpForecastLineService, mrpForecastModelService, mrpForecastRunService, mrpMpsLineService, mrpMpsPlanService, mrpProductPolicyService } from '../../../../services/sdk';
import { supabase } from '../../../../services/supabase/supabase';
import { MrpUnitNav } from '../shared/MrpUnitNav';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void,type='text'){return <label className="text-xs font-bold"><span>{l}</span><input type={type} value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function select(l:string,n:string,f:Form,set:(p:Form)=>void,ops:string[]){return <label className="text-xs font-bold"><span>{l}</span><select value={f[n]||ops[0]} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1 bg-white">{ops.map(o=><option key={o}>{o}</option>)}</select></label>}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 rounded-xl p-2">{msg}</div>:null}
function PlantLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('manufacturing_plants').select('id,plant_code,name_ar,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Plant</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.plant_code)} — {String(r.name_ar)} — {String(r.status)}</option>)}</select></label>}
function WorkCenterLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('work_centers').select('id,work_center_code,name_ar,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Default Work Center</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.work_center_code)} — {String(r.name_ar)} — {String(r.status)}</option>)}</select></label>}
function ForecastRunLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_forecast_runs').select('id,run_number,method,bucket,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Forecast Run</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.run_number)} — {String(r.method)} — {String(r.status)}</option>)}</select></label>}
function ForecastModelLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_forecast_models').select('id,model_code,method,bucket,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Forecast Model</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.model_code)} — {String(r.method)} — {String(r.status)}</option>)}</select></label>}
function MpsPlanLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_mps_plans').select('id,plan_number,plan_name,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>MPS Plan</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.plan_number)} — {String(r.plan_name)} — {String(r.status)}</option>)}</select></label>}
function MpsLineLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_mps_board').select('mps_line_id,item_code,bucket_start,mps_qty,status').limit(300).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>MPS Line</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.mps_line_id)} value={String(r.mps_line_id)}>{String(r.item_code)} — {String(r.bucket_start)} — {String(r.mps_qty)}</option>)}</select></label>}
function ForecastLineLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_forecast_line_board').select('id,run_number,item_code,bucket_start,final_forecast_qty').limit(300).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Forecast Line</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.run_number)} — {String(r.item_code)} — {String(r.bucket_start)} — {String(r.final_forecast_qty)}</option>)}</select></label>}
function MpsAlertLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_mps_alerts').select('id,alert_type,severity,title,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>MPS Alert</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.alert_type)} — {String(r.severity)} — {String(r.status)} — {String(r.title).slice(0,40)}</option>)}</select></label>}
const cfgs:Record<string,Config>={
 dashboard:{title:'التنبؤ بالطلب وMPS',subtitle:'نماذج التنبؤ، MPS، RCCP، التنبيهات، وMAPE.',load:()=>mrpForecastingAnalyticsService.dashboard() as Promise<Row[]>,columns:[{key:'active_models',label:'نماذج نشطة'},{key:'forecast_runs',label:'تشغيلات'},{key:'avg_mape',label:'MAPE'},{key:'open_mps_plans',label:'MPS مفتوحة'}]},
 history:{title:'Demand History',subtitle:'مصادر الطلب التاريخي والمؤكد',load:()=>mrpDemandHistoryService.findAll({orderBy:'demand_date',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'history',columns:[{key:'demand_date',label:'التاريخ'},{key:'demand_type',label:'النوع'},{key:'quantity',label:'الكمية'},{key:'demand_bucket',label:'Bucket'}]},
 models:{title:'Forecast Models',subtitle:'SMA/WMA/Exponential/Seasonal/AI external',load:()=>mrpForecastModelService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'model',columns:[{key:'model_code',label:'الكود'},{key:'method',label:'الطريقة'},{key:'bucket',label:'Bucket'},{key:'horizon_periods',label:'الأفق'},{key:'status',label:'الحالة'}]},
 runs:{title:'Forecast Runs',subtitle:'تشغيلات التنبؤ وخطوطها',load:()=>mrpForecastRunService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'run',columns:[{key:'run_number',label:'Run'},{key:'method',label:'الطريقة'},{key:'bucket',label:'Bucket'},{key:'horizon_start',label:'البداية'},{key:'mape_percent',label:'MAPE'}]},
 accuracy:{title:'Forecast Accuracy',subtitle:'MAPE وشرائح الجودة',load:()=>mrpForecastingAnalyticsService.accuracy() as Promise<Row[]>,columns:[{key:'item_code',label:'الصنف'},{key:'period_start',label:'من'},{key:'period_end',label:'إلى'},{key:'forecast_qty',label:'توقع'},{key:'actual_qty',label:'فعلي'},{key:'mape_percent',label:'MAPE'},{key:'quality_band',label:'الجودة'}]},
 policies:{title:'Product Planning Policies',subtitle:'MTS/MTO/ATO/ETO ومخزون الأمان',load:()=>mrpProductPolicyService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'policy',columns:[{key:'item_id',label:'الصنف'},{key:'strategy',label:'الاستراتيجية'},{key:'safety_stock_qty',label:'Safety'},{key:'forecast_horizon_weeks',label:'Horizon'}]},
 mpsPlans:{title:'MPS Plans',subtitle:'خطط MPS وأفقها وحالتها',load:()=>mrpMpsPlanService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'mps',columns:[{key:'plan_number',label:'الخطة'},{key:'plan_name',label:'الاسم'},{key:'horizon_start',label:'من'},{key:'horizon_end',label:'إلى'},{key:'status',label:'الحالة'}]},
 mpsBoard:{title:'MPS Board',subtitle:'لوحة MPS الزمنية',load:()=>mrpForecastingAnalyticsService.mpsBoard() as Promise<Row[]>,action:'mpsGenerate',columns:[{key:'plan_number',label:'الخطة'},{key:'item_code',label:'الصنف'},{key:'bucket_start',label:'الفترة'},{key:'forecast_qty',label:'توقع'},{key:'confirmed_order_qty',label:'مؤكد'},{key:'mps_qty',label:'MPS'},{key:'ending_inventory_qty',label:'نهائي'}]},
 rccp:{title:'RCCP',subtitle:'تحقق الطاقة الخشنة',load:()=>mrpForecastingAnalyticsService.rccp() as Promise<Row[]>,action:'rccp',columns:[{key:'run_number',label:'Run'},{key:'work_center_code',label:'مركز العمل'},{key:'bucket_start',label:'الفترة'},{key:'required_minutes',label:'مطلوب'},{key:'available_minutes',label:'متاح'},{key:'utilization_percent',label:'استغلال %'},{key:'status',label:'الحالة'}]},
 alerts:{title:'MPS Alerts',subtitle:'فجوات الطاقة والمواد والتجميد',load:()=>mrpForecastingAnalyticsService.alerts() as Promise<Row[]>,action:'alerts',columns:[{key:'alert_type',label:'النوع'},{key:'severity',label:'الشدة'},{key:'title',label:'العنوان'},{key:'status',label:'الحالة'}]},
 reports:{title:'MPS KPIs',subtitle:'مؤشرات MPS والتغطية والتنبيهات',load:()=>mrpForecastingAnalyticsService.kpis() as Promise<Row[]>,columns:[{key:'mps_plans',label:'خطط'},{key:'mps_lines',label:'بنود'},{key:'total_mps_qty',label:'إجمالي MPS'},{key:'inventory_coverage_index',label:'تغطية'},{key:'open_alerts',label:'تنبيهات'}]},
};
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({method:'simple_moving_average',bucket:'weekly',horizon_periods:'13',demand_type:'historical_sales',demand_bucket:'daily',quantity:'100',strategy:'MTS',safety_stock_qty:'0',plan_name:'MPS تجريبي',frozen_horizon_days:'7'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r||'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='history')return <Box title="تسجيل طلب"><div className="grid md:grid-cols-3 gap-3"><ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})} required />{inp('التاريخ','demand_date',f,set,'date')}{inp('الكمية','quantity',f,set,'number')}{select('Demand Type','demand_type',f,set,['historical_sales','confirmed_order','inventory_consumption','sales_plan','external_indicator'])}{select('Bucket','demand_bucket',f,set,['daily','weekly','monthly'])}<button onClick={()=>void run(()=>mrpDemandHistoryService.record(f))} className="bg-indigo-600 text-white rounded-xl p-2">Record</button><Msg msg={msg}/></div></Box>;
 if(type==='model')return <Box title="إنشاء نموذج تنبؤ"><div className="grid md:grid-cols-3 gap-3"><ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})} required />{select('Method','method',f,set,['simple_moving_average','weighted_moving_average','exponential_smoothing','seasonal_index','ai_external'])}{select('Bucket','bucket',f,set,['daily','weekly','monthly'])}{inp('Horizon Periods','horizon_periods',f,set,'number')}{inp('Model Code اختياري','model_code',f,set)}{inp('Model Name','model_name',f,set)}<button onClick={()=>void run(()=>mrpForecastModelService.createModel(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create</button><Msg msg={msg}/></div></Box>;
 if(type==='run')return <Box title="تشغيل/تعديل التنبؤ"><div className="grid md:grid-cols-3 gap-3"><ForecastModelLookup value={f.model_id} onChange={id=>set({model_id:id})}/>{inp('Start','horizon_start',f,set,'date')}{inp('Periods','horizon_periods',f,set,'number')}<button onClick={()=>void run(()=>mrpForecastModelService.run(f.model_id,f.horizon_start,Number(f.horizon_periods||13)))} className="bg-indigo-600 text-white rounded-xl p-2">Run Forecast</button><ForecastRunLookup value={f.forecast_run_id} onChange={id=>set({forecast_run_id:id})}/><button onClick={()=>void run(()=>mrpForecastRunService.accuracy(f.forecast_run_id))} className="bg-emerald-600 text-white rounded-xl p-2">Calculate MAPE</button><ForecastLineLookup value={f.forecast_line_id} onChange={id=>set({forecast_line_id:id})}/>{inp('New Forecast Qty','new_forecast_qty',f,set,'number')}{inp('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpForecastLineService.override(f.forecast_line_id,Number(f.new_forecast_qty||0),f.reason))} className="bg-slate-700 text-white rounded-xl p-2">Override Forecast Line</button><Msg msg={msg}/></div></Box>;
 if(type==='policy')return <Box title="سياسة تخطيط منتج"><div className="grid md:grid-cols-3 gap-3"><ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})}/>{select('Strategy','strategy',f,set,['MTS','MTO','ATO','ETO'])}{inp('Safety Stock','safety_stock_qty',f,set,'number')}{inp('Min MPS Qty','min_mps_qty',f,set,'number')}{inp('Order Multiple','order_multiple',f,set,'number')}{inp('Lead Time Days','manufacturing_lead_time_days',f,set,'number')}{inp('Horizon weeks','forecast_horizon_weeks',f,set,'number')}{inp('Frozen days','frozen_horizon_days',f,set,'number')}<WorkCenterLookup value={f.default_work_center_id} onChange={id=>set({default_work_center_id:id})}/><button onClick={()=>void run(()=>mrpProductPolicyService.upsertPolicy(f))} className="bg-indigo-600 text-white rounded-xl p-2">Save Policy</button><Msg msg={msg}/></div></Box>;
 if(type==='mps')return <Box title="إنشاء/إدارة MPS"><div className="grid md:grid-cols-3 gap-3">{inp('Plan Name','plan_name',f,set)}{inp('From','horizon_start',f,set,'date')}{inp('To','horizon_end',f,set,'date')}<PlantLookup value={f.plant_id} onChange={id=>set({plant_id:id})}/>{select('Bucket','bucket',f,set,['daily','weekly','monthly'])}{inp('Frozen days','frozen_horizon_days',f,set,'number')}<button onClick={()=>void run(()=>mrpMpsPlanService.createPlan(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create MPS</button><MpsPlanLookup value={f.mps_plan_id} onChange={id=>set({mps_plan_id:id})}/><button onClick={()=>void run(()=>mrpMpsPlanService.release(f.mps_plan_id))} className="bg-emerald-600 text-white rounded-xl p-2">Release MPS</button>{inp('Cancel Reason','cancel_reason',f,set)}<button onClick={()=>void run(()=>mrpMpsPlanService.cancel(f.mps_plan_id,f.cancel_reason))} className="bg-red-600 text-white rounded-xl p-2">Cancel MPS</button><Msg msg={msg}/></div></Box>;
 if(type==='mpsGenerate')return <Box title="توليد/تعديل MPS"><div className="grid md:grid-cols-3 gap-3"><MpsPlanLookup value={f.mps_plan_id} onChange={id=>set({mps_plan_id:id})}/><ForecastRunLookup value={f.forecast_run_id} onChange={id=>set({forecast_run_id:id})}/><button onClick={()=>void run(()=>mrpMpsPlanService.generate(f.mps_plan_id,f.forecast_run_id))} className="bg-indigo-600 text-white rounded-xl p-2">Generate Lines</button><MpsLineLookup value={f.mps_line_id} onChange={id=>set({mps_line_id:id})}/>{inp('New MPS Qty','new_mps_qty',f,set,'number')}{inp('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpMpsLineService.override(f.mps_line_id,Number(f.new_mps_qty||0),f.reason))} className="bg-emerald-600 text-white rounded-xl p-2">Override</button><Msg msg={msg}/></div></Box>;
 if(type==='rccp')return <Box title="RCCP"><div className="grid md:grid-cols-3 gap-3"><MpsPlanLookup value={f.mps_plan_id} onChange={id=>set({mps_plan_id:id})}/><button onClick={()=>void run(()=>mrpMpsPlanService.rccp(f.mps_plan_id))} className="bg-indigo-600 text-white rounded-xl p-2">Run RCCP</button><button onClick={()=>void run(()=>mrpMpsPlanService.approve(f.mps_plan_id))} className="bg-emerald-600 text-white rounded-xl p-2">Approve MPS</button><Msg msg={msg}/></div></Box>;
 if(type==='alerts')return <Box title="تنبيهات MPS"><div className="grid md:grid-cols-3 gap-3"><MpsPlanLookup value={f.mps_plan_id} onChange={id=>set({mps_plan_id:id})}/><button onClick={()=>void run(()=>mrpMpsPlanService.alerts(f.mps_plan_id))} className="bg-indigo-600 text-white rounded-xl p-2">Generate Alerts</button><MpsAlertLookup value={f.alert_id} onChange={id=>set({alert_id:id})}/>{inp('Close Reason','close_reason',f,set)}<button onClick={()=>void run(()=>mrpMpsPlanService.closeAlert(f.alert_id,f.close_reason))} className="bg-emerald-600 text-white rounded-xl p-2">Close Alert</button><Msg msg={msg}/></div></Box>;
 return null}
export function MrpForecastingPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{type==='dashboard'&&<MrpUnitNav unit="forecasting" />}{['mpsPlans','mpsBoard','rccp','alerts','reports'].includes(String(type))&&<MrpUnitNav unit="mps" />}{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
