import { supabase } from '../supabase/supabase';
import type { JournalEntryRecord } from '../../shared/types/sdk';

export interface FinanceIntegrationConnectorRecord { id:string; tenant_id:string; legal_entity_id:string; connector_code:string; connector_name:string; source_system:string; direction:string; status:'active'|'paused'|'archived'; settings:Record<string,unknown>; entity_code?:string; entity_name?:string; }
export interface FinanceIntegrationEventRecord { id:string; tenant_id:string; legal_entity_id:string; connector_id?:string|null; source_system:string; source_type:string; source_id?:string|null; idempotency_key?:string|null; event_type:string; event_date:string; amount:number; currency_code:string; status:'received'|'reviewed'|'converted'|'rejected'|'ignored'|'failed'; payload:Record<string,unknown>; journal_entry_id?:string|null; entry_number?:string|null; connector_code?:string|null; connector_name?:string|null; }
export interface FinanceIntegrationDashboardRecord { tenant_id:string; legal_entity_id:string; entity_code:string; entity_name:string; active_connectors:number; received_events:number; reviewed_events:number; converted_events:number; failed_or_rejected_events:number; }

class FinanceIntegrationService {
  async findConnectors(legalEntityId:string): Promise<FinanceIntegrationConnectorRecord[]> { const {data,error}=await supabase.from('finance_integration_connector_board').select('*').eq('legal_entity_id',legalEntityId).order('connector_code'); if(error) throw new Error(error.message); return (data||[]) as FinanceIntegrationConnectorRecord[]; }
  async findEvents(legalEntityId:string): Promise<FinanceIntegrationEventRecord[]> { const {data,error}=await supabase.from('finance_integration_event_board').select('*').eq('legal_entity_id',legalEntityId).order('created_at',{ascending:false}); if(error) throw new Error(error.message); return (data||[]) as FinanceIntegrationEventRecord[]; }
  async findDashboard(legalEntityId?:string): Promise<FinanceIntegrationDashboardRecord[]> { let q=supabase.from('finance_integration_dashboard').select('*').order('entity_code'); if(legalEntityId) q=q.eq('legal_entity_id',legalEntityId); const {data,error}=await q; if(error) throw new Error(error.message); return (data||[]) as FinanceIntegrationDashboardRecord[]; }
  async upsertConnector(input:{legalEntityId:string; connectorCode:string; connectorName:string; sourceSystem:string; direction?:string; status?:string; settings?:Record<string,unknown>}): Promise<FinanceIntegrationConnectorRecord>{ const {data,error}=await supabase.rpc('upsert_finance_integration_connector',{p_legal_entity_id:input.legalEntityId,p_connector_code:input.connectorCode,p_connector_name:input.connectorName,p_source_system:input.sourceSystem,p_direction:input.direction||'inbound',p_status:input.status||'active',p_settings:input.settings||{}}); if(error) throw new Error(error.message); return data as FinanceIntegrationConnectorRecord; }
  async ingestEvent(input:{legalEntityId:string; connectorId?:string; sourceSystem:string; sourceType:string; sourceId?:string; eventType:string; eventDate:string; amount:number; currencyCode:string; idempotencyKey?:string; payload?:Record<string,unknown>}): Promise<FinanceIntegrationEventRecord>{ const {data,error}=await supabase.rpc('ingest_finance_integration_event',{p_legal_entity_id:input.legalEntityId,p_connector_id:input.connectorId||null,p_source_system:input.sourceSystem,p_source_type:input.sourceType,p_source_id:input.sourceId||null,p_event_type:input.eventType,p_event_date:input.eventDate,p_amount:input.amount,p_currency_code:input.currencyCode,p_idempotency_key:input.idempotencyKey||null,p_payload:input.payload||{}}); if(error) throw new Error(error.message); return data as FinanceIntegrationEventRecord; }
  async reviewEvent(id:string,status:'reviewed'|'rejected'|'ignored',reason:string): Promise<FinanceIntegrationEventRecord>{ const {data,error}=await supabase.rpc('review_finance_integration_event',{p_event_id:id,p_status:status,p_reason:reason}); if(error) throw new Error(error.message); return data as FinanceIntegrationEventRecord; }
  async createJournalFromEvent(input:{eventId:string; accountingPeriodId:string; description:string; lines:Array<Record<string,unknown>>; reason:string}): Promise<JournalEntryRecord>{ const {data,error}=await supabase.rpc('create_finance_journal_from_integration_event',{p_event_id:input.eventId,p_accounting_period_id:input.accountingPeriodId,p_description:input.description,p_lines:input.lines,p_reason:input.reason}); if(error) throw new Error(error.message); return data as JournalEntryRecord; }
}
export const financeIntegrationService = new FinanceIntegrationService();
