import { BaseService } from './BaseService';
import { supabase } from '../supabase/supabase';

type Row=Record<string,unknown>;
export class MrpManufacturingKpiTargetService extends BaseService<Row>{constructor(){super('mrp_manufacturing_kpi_targets')} async upsert(input:Row):Promise<string>{const{data,error}=await supabase.rpc('upsert_mrp_manufacturing_kpi_target',{p_target_code:input.target_code||null,p_kpi_key:input.kpi_key,p_target_value:Number(input.target_value||0),p_scope_type:input.scope_type||'enterprise',p_scope_id:input.scope_id||null,p_warning_threshold:input.warning_threshold?Number(input.warning_threshold):null,p_critical_threshold:input.critical_threshold?Number(input.critical_threshold):null,p_direction:input.direction||'higher_better'}); if(error) throw new Error(error.message); return data as string;} async updateStatus(id:string,status:string,reason:string):Promise<void>{const{error}=await supabase.rpc('update_mrp_manufacturing_kpi_target_status',{p_target_id:id,p_status:status,p_reason:reason}); if(error) throw new Error(error.message);}}
export class MrpManufacturingSnapshotService extends BaseService<Row>{constructor(){super('mrp_manufacturing_kpi_snapshots')} async refresh(input:Row):Promise<number>{const{data,error}=await supabase.rpc('refresh_mrp_manufacturing_kpi_snapshots',{p_snapshot_date:input.snapshot_date||null,p_period_type:input.period_type||'daily'}); if(error) throw new Error(error.message); return Number(data||0);}}
export class MrpManufacturingAlertService extends BaseService<Row>{constructor(){super('mrp_manufacturing_analytics_alerts')} async generate():Promise<number>{const{data,error}=await supabase.rpc('generate_mrp_manufacturing_predictive_alerts'); if(error) throw new Error(error.message); return Number(data||0);} async close(id:string,reason:string):Promise<void>{const{error}=await supabase.rpc('close_mrp_manufacturing_analytics_alert',{p_alert_id:id,p_reason:reason}); if(error) throw new Error(error.message);} async updateStatus(id:string,status:string,reason?:string):Promise<void>{const{error}=await supabase.rpc('update_mrp_manufacturing_analytics_alert_status',{p_alert_id:id,p_status:status,p_reason:reason||null}); if(error) throw new Error(error.message);}}
export class MrpManufacturingRcaService extends BaseService<Row>{constructor(){super('mrp_manufacturing_root_cause_analyses')} async createRca(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_manufacturing_root_cause_analysis',{p_source_type:input.source_type||'manual',p_source_id:input.source_id||null,p_title:input.title,p_problem_statement:input.problem_statement,p_method:input.method||'5_whys',p_root_cause_category:input.root_cause_category||null,p_root_cause_text:input.root_cause_text||null,p_corrective_action:input.corrective_action||null,p_preventive_action:input.preventive_action||null,p_due_date:input.due_date||null}); if(error) throw new Error(error.message); return data as string;} async close(id:string,note?:string):Promise<void>{const{error}=await supabase.rpc('close_mrp_manufacturing_root_cause_analysis',{p_rca_id:id,p_close_note:note||null}); if(error) throw new Error(error.message);} async updateStatus(id:string,status:string,reason?:string):Promise<void>{const{error}=await supabase.rpc('update_mrp_manufacturing_rca_status',{p_rca_id:id,p_status:status,p_reason:reason||null}); if(error) throw new Error(error.message);}}
export class MrpManufacturingReportService extends BaseService<Row>{constructor(){super('mrp_manufacturing_report_runs')} async generate(input:Row):Promise<string>{const{data,error}=await supabase.rpc('generate_mrp_manufacturing_periodic_report',{p_report_type:input.report_type||'executive',p_period_start:input.period_start,p_period_end:input.period_end}); if(error) throw new Error(error.message); return data as string;} async cancel(id:string,reason:string):Promise<void>{const{error}=await supabase.rpc('cancel_mrp_manufacturing_report_run',{p_report_run_id:id,p_reason:reason}); if(error) throw new Error(error.message);} async export(input:Row):Promise<string>{const{data,error}=await supabase.rpc('request_mrp_manufacturing_report_export',{p_report_run_id:input.report_run_id,p_export_format:input.export_format||'xlsx'}); if(error) throw new Error(error.message); return data as string;} async updateExport(input:Row):Promise<void>{const{error}=await supabase.rpc('update_mrp_manufacturing_export_status',{p_export_id:input.export_id,p_status:input.export_status,p_file_url:input.file_url||null,p_reason:input.reason||null}); if(error) throw new Error(error.message);}}
class MrpManufacturingAnalyticsService{async executive(){const{data,error}=await supabase.from('mrp_manufacturing_executive_dashboard').select('*').limit(10); if(error) throw new Error(error.message); return data||[]} async operations(){const{data,error}=await supabase.from('mrp_production_performance_dashboard').select('*').limit(200); if(error) throw new Error(error.message); return data||[]} async oee(){const{data,error}=await supabase.from('mrp_oee_trend_report').select('*').limit(200); if(error) throw new Error(error.message); return data||[]} async schedule(){const{data,error}=await supabase.from('mrp_schedule_attainment_report').select('*').limit(50); if(error) throw new Error(error.message); return data||[]} async bottlenecks(){const{data,error}=await supabase.from('mrp_bottleneck_analysis').select('*').limit(200); if(error) throw new Error(error.message); return data||[]} async qualityCost(){const{data,error}=await supabase.from('mrp_quality_cost_dashboard').select('*').limit(20); if(error) throw new Error(error.message); return data||[]} async costVariance(){const{data,error}=await supabase.from('mrp_cost_variance_dashboard').select('*').limit(200); if(error) throw new Error(error.message); return data||[]} async maintenance(){const{data,error}=await supabase.from('mrp_maintenance_reliability_dashboard').select('*').limit(200); if(error) throw new Error(error.message); return data||[]} async scorecard(){const{data,error}=await supabase.from('mrp_manufacturing_kpi_scorecard').select('*').limit(200); if(error) throw new Error(error.message); return data||[]} async alerts(){const{data,error}=await supabase.from('mrp_predictive_alert_queue').select('*').limit(200); if(error) throw new Error(error.message); return data||[]} async rca(){const{data,error}=await supabase.from('mrp_root_cause_analysis_board').select('*').limit(200); if(error) throw new Error(error.message); return data||[]} async reports(){const{data,error}=await supabase.from('mrp_manufacturing_report_center').select('*').limit(200); if(error) throw new Error(error.message); return data||[]} async exports(){const{data,error}=await supabase.from('mrp_manufacturing_export_queue').select('*').limit(200); if(error) throw new Error(error.message); return data||[]}}
export const mrpManufacturingKpiTargetService=new MrpManufacturingKpiTargetService();
export const mrpManufacturingSnapshotService=new MrpManufacturingSnapshotService();
export const mrpManufacturingAlertService=new MrpManufacturingAlertService();
export const mrpManufacturingRcaService=new MrpManufacturingRcaService();
export const mrpManufacturingReportService=new MrpManufacturingReportService();
export const mrpManufacturingAnalyticsService=new MrpManufacturingAnalyticsService();
