import { BaseService } from './BaseService';
import { supabase } from '../supabase/supabase';

export interface MrpBomHeaderRecord { id:string; tenant_id:string; bom_code:string; item_id:string; bom_type:string; structure_type:string; status:string; created_at:string; }
export interface MrpBomVersionRecord { id:string; tenant_id:string; bom_id:string; version_no:string; status:string; effective_from?:string|null; created_at:string; }
export interface MrpBomLineRecord { id:string; tenant_id:string; bom_version_id:string; line_no:number; component_item_id:string; quantity_per:number; scrap_percent:number; net_quantity:number; material_type:string; supply_type:string; created_at:string; }
export interface MrpEcrRecord { id:string; tenant_id:string; ecr_number:string; reason:string; proposed_change:string; status:string; created_at:string; }
export interface MrpEcoRecord { id:string; tenant_id:string; eco_number:string; status:string; effectivity_date?:string|null; created_at:string; }
export interface MrpBomExplosionRunRecord { id:string; tenant_id:string; run_number:string; demand_quantity:number; status:string; created_at:string; }
export interface MrpBomAvailabilityCheckRecord { id:string; tenant_id:string; check_number:string; demand_quantity:number; can_build:boolean; shortage_count:number; created_at:string; }
export interface MrpBomImportBatchRecord { id:string; tenant_id:string; batch_number:string; file_name?:string|null; status:string; created_at:string; }
export interface MrpBomExportRequestRecord { id:string; tenant_id:string; request_number:string; export_type:string; status:string; requested_at:string; }

type Row=Record<string,unknown>;
export class MrpBomHeaderService extends BaseService<MrpBomHeaderRecord>{constructor(){super('mrp_bom_headers')} async createBom(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_bom',{p_bom_code:input.bom_code||null,p_item_id:input.item_id,p_bom_type:input.bom_type||'MBOM',p_structure_type:input.structure_type||'multi_level',p_name_ar:input.name_ar||null,p_version_no:input.version_no||'1.0'}); if(error) throw new Error(error.message); return data as string;}}
export class MrpBomVersionService extends BaseService<MrpBomVersionRecord>{constructor(){super('mrp_bom_versions')} async approve(id:string,effectiveFrom?:string):Promise<void>{const{error}=await supabase.rpc('approve_mrp_bom_version',{p_bom_version_id:id,p_effective_from:effectiveFrom||null}); if(error) throw new Error(error.message);} async duplicate(id:string,newVersion:string,reason:string):Promise<string>{const{data,error}=await supabase.rpc('duplicate_mrp_bom_version',{p_bom_version_id:id,p_new_version_no:newVersion,p_reason:reason}); if(error) throw new Error(error.message); return data as string;}}
export class MrpBomLineService extends BaseService<MrpBomLineRecord>{constructor(){super('mrp_bom_lines')} async addLine(input:Row):Promise<string>{const{data,error}=await supabase.rpc('add_mrp_bom_line',{p_bom_version_id:input.bom_version_id,p_parent_line_id:input.parent_line_id||null,p_line_no:Number(input.line_no||10),p_component_item_id:input.component_item_id,p_quantity_per:Number(input.quantity_per||1),p_uom:input.uom||'PCS',p_scrap_percent:Number(input.scrap_percent||0),p_material_type:input.material_type||'raw',p_supply_type:input.supply_type||'buy',p_lead_time_days:Number(input.lead_time_days||0),p_safety_stock:Number(input.safety_stock||0),p_minimum_order_qty:Number(input.minimum_order_qty||0),p_order_multiple:Number(input.order_multiple||1),p_operation_sequence_no:input.operation_sequence_no?Number(input.operation_sequence_no):null,p_is_phantom:Boolean(input.is_phantom),p_notes:input.notes||null}); if(error) throw new Error(error.message); return data as string;} async addSubstitute(input:Row):Promise<string>{const{data,error}=await supabase.rpc('add_mrp_bom_line_substitute',{p_bom_line_id:input.bom_line_id,p_substitute_item_id:input.substitute_item_id,p_priority:Number(input.priority||1),p_conversion_factor:Number(input.conversion_factor||1),p_notes:input.notes||null}); if(error) throw new Error(error.message); return data as string;} async addSupplier(input:Row):Promise<string>{const{data,error}=await supabase.rpc('add_mrp_bom_line_supplier',{p_bom_line_id:input.bom_line_id,p_supplier_id:input.supplier_id||null,p_supplier_part_number:input.supplier_part_number||null,p_lead_time_days:input.lead_time_days?Number(input.lead_time_days):null,p_unit_price:input.unit_price?Number(input.unit_price):null,p_currency_code:input.currency_code||'SAR',p_is_preferred:Boolean(input.is_preferred)}); if(error) throw new Error(error.message); return data as string;}}
export class MrpEcrService extends BaseService<MrpEcrRecord>{constructor(){super('mrp_engineering_change_requests')} async createEcr(reason:string,change:string,source='manual'):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_ecr',{p_reason:reason,p_proposed_change:change,p_request_source:source}); if(error) throw new Error(error.message); return data as string;} async close(id:string,status:string,reason:string):Promise<void>{const{error}=await supabase.rpc('close_mrp_ecr',{p_ecr_id:id,p_status:status,p_reason:reason}); if(error) throw new Error(error.message);}}
export class MrpEcoService extends BaseService<MrpEcoRecord>{constructor(){super('mrp_engineering_change_orders')} async createEco(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_eco',{p_ecr_id:input.ecr_id||null,p_bom_version_id:input.bom_version_id||null,p_effectivity_date:input.effectivity_date||null,p_impact_summary:input.impact_summary||null,p_implementation_plan:input.implementation_plan||null}); if(error) throw new Error(error.message); return data as string;} async implement(id:string):Promise<void>{const{error}=await supabase.rpc('implement_mrp_eco',{p_eco_id:id}); if(error) throw new Error(error.message);}}
export class MrpBomExplosionService extends BaseService<MrpBomExplosionRunRecord>{constructor(){super('mrp_bom_explosion_runs')} async explode(versionId:string,qty:number):Promise<string>{const{data,error}=await supabase.rpc('explode_mrp_bom',{p_bom_version_id:versionId,p_demand_quantity:qty}); if(error) throw new Error(error.message); return data as string;}}
export class MrpBomAvailabilityService extends BaseService<MrpBomAvailabilityCheckRecord>{constructor(){super('mrp_bom_availability_checks')} async check(versionId:string,qty:number):Promise<string>{const{data,error}=await supabase.rpc('check_mrp_bom_availability',{p_bom_version_id:versionId,p_demand_quantity:qty}); if(error) throw new Error(error.message); return data as string;}}
export class MrpBomImportBatchService extends BaseService<MrpBomImportBatchRecord>{constructor(){super('mrp_bom_import_batches')} async createBatch(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_bom_import_batch',{p_file_name:input.file_name,p_file_url:input.file_url||null,p_import_type:input.import_type||'excel'}); if(error) throw new Error(error.message); return data as string;}}
export class MrpBomExportRequestService extends BaseService<MrpBomExportRequestRecord>{constructor(){super('mrp_bom_export_requests')} async request(versionId:string,exportType='excel'):Promise<string>{const{data,error}=await supabase.rpc('request_mrp_bom_export',{p_bom_version_id:versionId,p_export_type:exportType}); if(error) throw new Error(error.message); return data as string;}}
class MrpBomAnalyticsService{async dashboard(){const{data,error}=await supabase.from('mrp_bom_dashboard').select('*').limit(10); if(error) throw new Error(error.message); return data||[]} async kpis(){const{data,error}=await supabase.from('mrp_bom_kpis').select('*').limit(10); if(error) throw new Error(error.message); return data||[]} async tree(){const{data,error}=await supabase.from('mrp_bom_tree').select('*').limit(500); if(error) throw new Error(error.message); return data||[]} async eco(){const{data,error}=await supabase.from('mrp_eco_dashboard').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async explosion(){const{data,error}=await supabase.from('mrp_bom_explosion_summary').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async shortages(){const{data,error}=await supabase.from('mrp_bom_availability_shortages').select('*').limit(100); if(error) throw new Error(error.message); return data||[]}}
export const mrpBomHeaderService=new MrpBomHeaderService();
export const mrpBomVersionService=new MrpBomVersionService();
export const mrpBomLineService=new MrpBomLineService();
export const mrpEcrService=new MrpEcrService();
export const mrpEcoService=new MrpEcoService();
export const mrpBomExplosionService=new MrpBomExplosionService();
export const mrpBomAvailabilityService=new MrpBomAvailabilityService();
export const mrpBomImportBatchService=new MrpBomImportBatchService();
export const mrpBomExportRequestService=new MrpBomExportRequestService();
export const mrpBomAnalyticsService=new MrpBomAnalyticsService();
