import { BaseService } from './BaseService';
import { supabase } from '../supabase/supabase';
export interface MrpDemandHistoryRecord{ id:string; tenant_id:string; item_id:string; demand_date:string; demand_type:string; quantity:number; created_at:string }
export interface MrpForecastModelRecord{ id:string; tenant_id:string; item_id:string; model_code:string; method:string; bucket:string; horizon_periods:number; status:string; created_at:string }
export interface MrpForecastRunRecord{ id:string; tenant_id:string; run_number:string; method:string; bucket:string; horizon_start:string; status:string; mape_percent?:number|null; created_at:string }
export interface MrpMpsPlanRecord{ id:string; tenant_id:string; plan_number:string; plan_name:string; status:string; horizon_start:string; horizon_end:string; created_at:string }
export interface MrpMpsLineRecord{ id:string; tenant_id:string; item_id:string; bucket_start:string; bucket_end:string; mps_qty:number; status:string }
type Row=Record<string,unknown>;
export class MrpDemandHistoryService extends BaseService<MrpDemandHistoryRecord>{constructor(){super('mrp_demand_history')} async record(input:Row):Promise<string>{const{data,error}=await supabase.rpc('record_mrp_demand_history',{p_item_id:input.item_id,p_demand_date:input.demand_date,p_quantity:Number(input.quantity||0),p_demand_type:input.demand_type||'historical_sales',p_demand_bucket:input.demand_bucket||'daily',p_payload:{}}); if(error) throw new Error(error.message); return data as string;}}
export class MrpForecastModelService extends BaseService<MrpForecastModelRecord>{constructor(){super('mrp_forecast_models')} async createModel(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_forecast_model',{p_item_id:input.item_id,p_method:input.method,p_bucket:input.bucket||'weekly',p_horizon_periods:Number(input.horizon_periods||13),p_parameters:input.parameters||{},p_model_code:input.model_code||null,p_model_name:input.model_name||null}); if(error) throw new Error(error.message); return data as string;} async run(id:string,start?:string,periods?:number):Promise<string>{const{data,error}=await supabase.rpc('run_mrp_forecast',{p_model_id:id,p_horizon_start:start||null,p_horizon_periods:periods||null}); if(error) throw new Error(error.message); return data as string;}}
export class MrpForecastRunService extends BaseService<MrpForecastRunRecord>{constructor(){super('mrp_forecast_runs')} async accuracy(id:string):Promise<number>{const{data,error}=await supabase.rpc('calculate_mrp_forecast_accuracy',{p_forecast_run_id:id}); if(error) throw new Error(error.message); return Number(data||0);}}
export class MrpProductPolicyService extends BaseService<Record<string,unknown>>{constructor(){super('mrp_product_planning_policies')} async upsertPolicy(input:Row):Promise<string>{const{data,error}=await supabase.rpc('upsert_mrp_product_planning_policy',{p_item_id:input.item_id,p_strategy:input.strategy||'MTS',p_safety_stock_qty:Number(input.safety_stock_qty||0),p_min_mps_qty:Number(input.min_mps_qty||0),p_order_multiple:Number(input.order_multiple||1),p_manufacturing_lead_time_days:Number(input.manufacturing_lead_time_days||0),p_forecast_horizon_weeks:Number(input.forecast_horizon_weeks||13),p_frozen_horizon_days:Number(input.frozen_horizon_days||7),p_planning_time_fence_days:Number(input.planning_time_fence_days||28),p_default_work_center_id:input.default_work_center_id||null}); if(error) throw new Error(error.message); return data as string;}}
export class MrpMpsPlanService extends BaseService<MrpMpsPlanRecord>{constructor(){super('mrp_mps_plans')} async createPlan(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_mps_plan',{p_plan_name:input.plan_name,p_horizon_start:input.horizon_start,p_horizon_end:input.horizon_end,p_bucket:input.bucket||'weekly',p_plant_id:input.plant_id||null,p_frozen_horizon_days:Number(input.frozen_horizon_days||7)}); if(error) throw new Error(error.message); return data as string;} async generate(planId:string,forecastRunId:string):Promise<number>{const{data,error}=await supabase.rpc('generate_mps_from_forecast',{p_mps_plan_id:planId,p_forecast_run_id:forecastRunId}); if(error) throw new Error(error.message); return Number(data||0);} async approve(id:string):Promise<void>{const{error}=await supabase.rpc('approve_mps_plan',{p_mps_plan_id:id}); if(error) throw new Error(error.message);} async release(id:string):Promise<void>{const{error}=await supabase.rpc('release_mrp_mps_plan',{p_mps_plan_id:id}); if(error) throw new Error(error.message);} async cancel(id:string,reason:string):Promise<void>{const{error}=await supabase.rpc('cancel_mrp_mps_plan',{p_mps_plan_id:id,p_reason:reason}); if(error) throw new Error(error.message);} async rccp(id:string):Promise<string>{const{data,error}=await supabase.rpc('run_mps_rccp',{p_mps_plan_id:id}); if(error) throw new Error(error.message); return data as string;} async alerts(id:string):Promise<number>{const{data,error}=await supabase.rpc('generate_mps_alerts',{p_mps_plan_id:id}); if(error) throw new Error(error.message); return Number(data||0);} async closeAlert(alertId:string,reason:string):Promise<void>{const{error}=await supabase.rpc('close_mrp_mps_alert',{p_alert_id:alertId,p_reason:reason}); if(error) throw new Error(error.message);}}
export class MrpMpsLineService extends BaseService<MrpMpsLineRecord>{constructor(){super('mrp_mps_lines')} async override(id:string,qty:number,reason:string):Promise<void>{const{error}=await supabase.rpc('override_mps_line',{p_mps_line_id:id,p_new_mps_qty:qty,p_reason:reason}); if(error) throw new Error(error.message);}}
export class MrpForecastLineService extends BaseService<Row>{constructor(){super('mrp_forecast_lines')} async override(id:string,qty:number,reason:string):Promise<void>{const{error}=await supabase.rpc('override_mrp_forecast_line',{p_forecast_line_id:id,p_new_qty:qty,p_reason:reason}); if(error) throw new Error(error.message);}}
class MrpForecastingAnalyticsService{async dashboard(){const{data,error}=await supabase.from('mrp_forecast_dashboard').select('*').limit(10); if(error) throw new Error(error.message); return data||[]} async forecastLines(){const{data,error}=await supabase.from('mrp_forecast_line_board').select('*').limit(200); if(error) throw new Error(error.message); return data||[]} async accuracy(){const{data,error}=await supabase.from('mrp_forecast_accuracy_report').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async mpsBoard(){const{data,error}=await supabase.from('mrp_mps_board').select('*').limit(200); if(error) throw new Error(error.message); return data||[]} async rccp(){const{data,error}=await supabase.from('mrp_rccp_load_report').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async alerts(){const{data,error}=await supabase.from('mrp_mps_alert_queue').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async kpis(){const{data,error}=await supabase.from('mrp_mps_kpis').select('*').limit(10); if(error) throw new Error(error.message); return data||[]}}
export const mrpDemandHistoryService=new MrpDemandHistoryService();
export const mrpForecastModelService=new MrpForecastModelService();
export const mrpForecastRunService=new MrpForecastRunService();
export const mrpForecastLineService=new MrpForecastLineService();
export const mrpProductPolicyService=new MrpProductPolicyService();
export const mrpMpsPlanService=new MrpMpsPlanService();
export const mrpMpsLineService=new MrpMpsLineService();
export const mrpForecastingAnalyticsService=new MrpForecastingAnalyticsService();
