import { BaseService } from './BaseService';
import { supabase } from '../supabase/supabase';
type Row=Record<string,unknown>;
export class MrpInventoryValuationPolicyService extends BaseService<Row>{constructor(){super('mrp_inventory_valuation_policies')} async upsert(input:Row):Promise<string>{const{data,error}=await supabase.rpc('upsert_mrp_inventory_valuation_policy',{p_item_id:input.item_id,p_method:input.valuation_method,p_carrying_cost_percent:Number(input.carrying_cost_percent||25),p_service_level_percent:Number(input.service_level_percent||95),p_z_factor:Number(input.z_factor||1.65)}); if(error) throw new Error(error.message); return data as string;} async deactivate(id:string,reason:string):Promise<void>{const{error}=await supabase.rpc('deactivate_mrp_inventory_valuation_policy',{p_policy_id:id,p_reason:reason}); if(error) throw new Error(error.message);}}
export class MrpWipLocationService extends BaseService<Row>{constructor(){super('mrp_wip_locations')} async createWipLocation(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_wip_location',{p_wip_code:input.wip_code||null,p_name_ar:input.name_ar,p_work_center_id:input.work_center_id||null,p_inventory_location_id:input.inventory_location_id||null}); if(error) throw new Error(error.message); return data as string;} async updateStatus(id:string,status:string,reason:string):Promise<void>{const{error}=await supabase.rpc('update_mrp_wip_location_status',{p_wip_location_id:id,p_status:status,p_reason:reason}); if(error) throw new Error(error.message);}}
export class MrpWipMovementService extends BaseService<Row>{constructor(){super('mrp_wip_movements')} async record(input:Row):Promise<string>{const{data,error}=await supabase.rpc('record_mrp_wip_movement',{p_work_order_id:input.work_order_id,p_from_operation_id:input.from_operation_id||null,p_to_operation_id:input.to_operation_id||null,p_item_id:input.item_id,p_quantity:Number(input.quantity||0),p_movement_type:input.movement_type,p_cost_delta:Number(input.cost_delta||0),p_notes:input.notes||null}); if(error) throw new Error(error.message); return data as string;} async adjust(input:Row):Promise<string>{const{data,error}=await supabase.rpc('adjust_mrp_wip_balance',{p_work_order_id:input.work_order_id,p_operation_id:input.operation_id||null,p_item_id:input.item_id,p_wip_location_id:input.wip_location_id||null,p_quantity_delta:Number(input.quantity_delta||0),p_cost_delta:Number(input.cost_delta||0),p_reason:input.reason||null}); if(error) throw new Error(error.message); return data as string;}}
export class MrpLotTraceService extends BaseService<Row>{constructor(){super('mrp_lot_trace_links')} async link(input:Row):Promise<string>{const{data,error}=await supabase.rpc('link_mrp_lot_trace',{p_work_order_id:input.work_order_id,p_raw_item_id:input.raw_item_id||null,p_raw_lot_id:input.raw_lot_id||null,p_finished_item_id:input.finished_item_id||null,p_finished_lot_id:input.finished_lot_id||null,p_consumed:Number(input.quantity_consumed||0),p_produced:Number(input.quantity_produced||0)}); if(error) throw new Error(error.message); return data as string;}}
export class MrpInventoryOptimizationService extends BaseService<Row>{constructor(){super('mrp_inventory_optimization_runs')} async calculate(input:Row):Promise<string>{const{data,error}=await supabase.rpc('calculate_mrp_inventory_optimization',{p_item_id:input.item_id,p_average_daily_demand:Number(input.average_daily_demand||0),p_demand_stddev:Number(input.demand_stddev||0),p_lead_time_days:Number(input.lead_time_days||0),p_annual_demand:Number(input.annual_demand||0),p_order_cost:Number(input.order_cost||0),p_holding_cost:Number(input.holding_cost_per_unit||0),p_service_level_percent:Number(input.service_level_percent||95),p_z_factor:Number(input.z_factor||1.65)}); if(error) throw new Error(error.message); return data as string;}}
class MrpInventoryAnalyticsService{async raw(){const{data,error}=await supabase.from('mrp_raw_materials_inventory').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async wipLocations(){const{data,error}=await supabase.from('mrp_wip_location_lookup').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async wip(){const{data,error}=await supabase.from('mrp_wip_dashboard').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async fg(){const{data,error}=await supabase.from('mrp_finished_goods_inventory').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async trace(){const{data,error}=await supabase.from('mrp_lot_forward_traceability').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async reconciliation(){const{data,error}=await supabase.from('mrp_work_order_material_reconciliation').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async optimization(){const{data,error}=await supabase.from('mrp_inventory_optimization_report').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async kpis(){const{data,error}=await supabase.from('mrp_manufacturing_inventory_kpis').select('*').limit(10); if(error) throw new Error(error.message); return data||[]}}
export const mrpInventoryValuationPolicyService=new MrpInventoryValuationPolicyService();
export const mrpWipLocationService=new MrpWipLocationService();
export const mrpWipMovementService=new MrpWipMovementService();
export const mrpLotTraceService=new MrpLotTraceService();
export const mrpInventoryOptimizationService=new MrpInventoryOptimizationService();
export const mrpInventoryAnalyticsService=new MrpInventoryAnalyticsService();
