import { BaseService } from './BaseService';
import { supabase } from '../supabase/supabase';
type Row=Record<string,unknown>;
export class MrpProcurementRecommendationService extends BaseService<Row>{constructor(){super('mrp_procurement_recommendations')} async createRecommendation(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_procurement_recommendation',{p_item_id:input.item_id,p_required_qty:Number(input.required_qty||0),p_required_date:input.required_date||null,p_priority:input.priority||'normal',p_source_type:input.source_type||'manual',p_source_id:input.source_id||null,p_supplier_id:input.supplier_id||null,p_unit_price:Number(input.estimated_unit_price||0),p_reason:input.reason||null}); if(error) throw new Error(error.message); return data as string;} async review(input:Row):Promise<void>{const{error}=await supabase.rpc('review_mrp_procurement_recommendation',{p_recommendation_id:input.recommendation_id,p_status:input.review_status||'reviewed',p_supplier_id:input.supplier_id||null,p_reason:input.reason||null}); if(error) throw new Error(error.message);} async fromShortages(runId:string):Promise<number>{const{data,error}=await supabase.rpc('generate_mrp_procurement_recommendations_from_shortages',{p_explosion_run_id:runId}); if(error) throw new Error(error.message); return Number(data||0);} async convertToPr(id:string):Promise<string>{const{data,error}=await supabase.rpc('convert_mrp_recommendation_to_pr',{p_recommendation_id:id}); if(error) throw new Error(error.message); return data as string;}}
export class MrpSupplierTcoService extends BaseService<Row>{constructor(){super('mrp_supplier_tco_evaluations')} async addCandidate(input:Row):Promise<string>{const{data,error}=await supabase.rpc('add_mrp_supplier_tco_candidate',{p_recommendation_id:input.recommendation_id,p_supplier_id:input.supplier_id,p_quoted_unit_price:Number(input.quoted_unit_price||0),p_lead_time_days:Number(input.lead_time_days||0),p_quality_score:Number(input.quality_score||0),p_otif_score:Number(input.otif_score||0),p_delay_risk_cost:Number(input.delay_risk_cost||0),p_quality_risk_cost:Number(input.quality_risk_cost||0)}); if(error) throw new Error(error.message); return data as string;} async award(tcoId:string,reason?:string):Promise<void>{const{error}=await supabase.rpc('award_mrp_supplier_tco_candidate',{p_tco_id:tcoId,p_reason:reason||null}); if(error) throw new Error(error.message);}}
export class MrpProcurementAlertService extends BaseService<Row>{constructor(){super('mrp_procurement_alerts')} async generate():Promise<number>{const{data,error}=await supabase.rpc('generate_mrp_procurement_alerts'); if(error) throw new Error(error.message); return Number(data||0);} async close(alertId:string,status='resolved',reason?:string):Promise<void>{const{error}=await supabase.rpc('close_mrp_procurement_alert',{p_alert_id:alertId,p_status:status,p_reason:reason||null}); if(error) throw new Error(error.message);}}
class MrpProcurementAnalyticsService{async dashboard(){const{data,error}=await supabase.from('mrp_procurement_dashboard').select('*').limit(10); if(error) throw new Error(error.message); return data||[]} async queue(){const{data,error}=await supabase.from('mrp_procurement_recommendation_queue').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async tco(){const{data,error}=await supabase.from('mrp_supplier_tco_candidate_board').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async pr(){const{data,error}=await supabase.from('mrp_procurement_pr_status').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async po(){const{data,error}=await supabase.from('mrp_procurement_po_status').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async gr(){const{data,error}=await supabase.from('mrp_procurement_gr_status').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async invoices(){const{data,error}=await supabase.from('mrp_procurement_invoice_match_status').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async suppliers(){const{data,error}=await supabase.from('mrp_supplier_scorecard').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async contracts(){const{data,error}=await supabase.from('mrp_procurement_contract_alerts').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async alerts(){const{data,error}=await supabase.from('mrp_procurement_alert_queue').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async kpis(){const{data,error}=await supabase.from('mrp_procurement_kpis').select('*').limit(10); if(error) throw new Error(error.message); return data||[]}}
export const mrpProcurementRecommendationService=new MrpProcurementRecommendationService();
export const mrpSupplierTcoService=new MrpSupplierTcoService();
export const mrpProcurementAlertService=new MrpProcurementAlertService();
export const mrpProcurementAnalyticsService=new MrpProcurementAnalyticsService();
