import { BaseService } from './BaseService';
import { supabase } from '../supabase/supabase';
type Row=Record<string,unknown>;
export class MrpQualityPlanService extends BaseService<Row>{constructor(){super('mrp_quality_inspection_plans')} async createPlan(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_quality_inspection_plan',{p_plan_code:input.plan_code||null,p_item_id:input.item_id||null,p_stage:input.inspection_stage,p_name_ar:input.name_ar,p_aql_level:input.aql_level||'AQL_1_0'}); if(error) throw new Error(error.message); return data as string;} async createPoint(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_quality_inspection_point',{p_plan_id:input.plan_id,p_point_code:input.point_code||null,p_name_ar:input.point_name_ar||input.name_ar,p_operation_id:input.operation_id||null,p_routing_operation_id:input.routing_operation_id||null,p_ccp:Boolean(input.ccp),p_specification:input.specification||null,p_lower_spec_limit:input.lower_spec_limit?Number(input.lower_spec_limit):null,p_upper_spec_limit:input.upper_spec_limit?Number(input.upper_spec_limit):null,p_target_value:input.target_value?Number(input.target_value):null,p_frequency_text:input.frequency_text||null}); if(error) throw new Error(error.message); return data as string;}}
export class MrpQualityChecklistService extends BaseService<Row>{constructor(){super('mrp_quality_checklist_templates')} async createTemplate(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_quality_checklist_template',{p_template_code:input.template_code||null,p_name_ar:input.name_ar,p_inspection_stage:input.inspection_stage||'IPQC'}); if(error) throw new Error(error.message); return data as string;} async addItem(input:Row):Promise<string>{const{data,error}=await supabase.rpc('add_mrp_quality_checklist_item',{p_template_id:input.template_id,p_sequence_no:Number(input.sequence_no||1),p_check_text:input.check_text,p_response_type:input.response_type||'pass_fail',p_required:input.required!==false,p_lower_spec_limit:input.lower_spec_limit?Number(input.lower_spec_limit):null,p_upper_spec_limit:input.upper_spec_limit?Number(input.upper_spec_limit):null}); if(error) throw new Error(error.message); return data as string;}}
export class MrpQualityInspectionService extends BaseService<Row>{constructor(){super('mrp_quality_inspections')} async start(input:Row):Promise<string>{const{data,error}=await supabase.rpc('start_mrp_quality_inspection',{p_plan_id:input.plan_id||null,p_stage:input.inspection_stage,p_source_table:input.source_table||null,p_source_id:input.source_id||null,p_item_id:input.item_id||null,p_lot_id:input.lot_id||null,p_work_order_id:input.work_order_id||null,p_operation_id:input.operation_id||null,p_batch_qty:Number(input.batch_qty||0)}); if(error) throw new Error(error.message); return data as string;} async recordResult(input:Row):Promise<string>{const{data,error}=await supabase.rpc('record_mrp_quality_result',{p_inspection_id:input.inspection_id,p_result_value:input.result_value||null,p_numeric_value:input.numeric_value?Number(input.numeric_value):null,p_pass_fail:input.pass_fail,p_defect_class:input.defect_class||null,p_defect_description:input.defect_description||null}); if(error) throw new Error(error.message); return data as string;} async complete(id:string,decision:string):Promise<void>{const{error}=await supabase.rpc('complete_mrp_quality_inspection',{p_inspection_id:id,p_decision:decision}); if(error) throw new Error(error.message);} async cancel(id:string,reason:string):Promise<void>{const{error}=await supabase.rpc('cancel_mrp_quality_inspection',{p_inspection_id:id,p_reason:reason}); if(error) throw new Error(error.message);}}
export class MrpAqlService extends BaseService<Row>{constructor(){super('mrp_quality_aql_rules')} async sample(lotSize:number,aql='AQL_1_0',defect='major'):Promise<Row[]>{const{data,error}=await supabase.rpc('calculate_mrp_aql_sample',{p_lot_size:lotSize,p_aql_code:aql,p_defect_class:defect}); if(error) throw new Error(error.message); return data||[];}}
export class MrpNcrService extends BaseService<Row>{constructor(){super('mrp_quality_ncrs')} async createNcr(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_quality_ncr',{p_inspection_id:input.inspection_id||null,p_item_id:input.item_id||null,p_lot_id:input.lot_id||null,p_work_order_id:input.work_order_id||null,p_defect_class:input.defect_class,p_defect_type:input.defect_type,p_description:input.description,p_affected_qty:Number(input.affected_qty||0),p_immediate_action:input.immediate_action||null}); if(error) throw new Error(error.message); return data as string;} async decide(id:string,disposition:string,reason:string):Promise<void>{const{error}=await supabase.rpc('decide_mrp_quality_ncr',{p_ncr_id:id,p_disposition:disposition,p_reason:reason}); if(error) throw new Error(error.message);}}
export class MrpCapaService extends BaseService<Row>{constructor(){super('mrp_quality_capa_actions')} async createCapa(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_capa',{p_ncr_id:input.ncr_id,p_capa_type:input.capa_type,p_root_cause_method:input.root_cause_method||'5_whys',p_root_cause_category:input.root_cause_category||null,p_root_cause_text:input.root_cause_text||null,p_corrective_action:input.corrective_action,p_preventive_action:input.preventive_action||null,p_due_date:input.due_date||null}); if(error) throw new Error(error.message); return data as string;} async close(id:string,reason:string):Promise<void>{const{error}=await supabase.rpc('close_mrp_capa',{p_capa_id:id,p_reason:reason}); if(error) throw new Error(error.message);}}
export class MrpCalibrationService extends BaseService<Row>{constructor(){super('mrp_quality_measurement_devices')} async upsertDevice(input:Row):Promise<string>{const{data,error}=await supabase.rpc('upsert_mrp_quality_measurement_device',{p_device_code:input.device_code||null,p_name_ar:input.name_ar,p_device_type:input.device_type||'gauge',p_standard_reference:input.standard_reference||null,p_calibration_frequency_days:Number(input.calibration_frequency_days||180),p_next_calibration_date:input.next_calibration_date||null}); if(error) throw new Error(error.message); return data as string;} async recordEvent(input:Row):Promise<string>{const{data,error}=await supabase.rpc('record_mrp_calibration_event',{p_device_id:input.device_id,p_calibration_date:input.calibration_date,p_result:input.result,p_next_due_date:input.next_due_date,p_certificate_url:input.certificate_url||null,p_notes:input.notes||null}); if(error) throw new Error(error.message); return data as string;}}
export class MrpSpcService extends BaseService<Row>{constructor(){super('mrp_quality_spc_measurements')} async record(input:Row):Promise<string>{const{data,error}=await supabase.rpc('record_mrp_spc_measurement',{p_inspection_point_id:input.inspection_point_id||null,p_work_order_id:input.work_order_id||null,p_operation_id:input.operation_id||null,p_measured_value:Number(input.measured_value||0),p_center_line:input.center_line?Number(input.center_line):null,p_ucl:input.ucl?Number(input.ucl):null,p_lcl:input.lcl?Number(input.lcl):null}); if(error) throw new Error(error.message); return data as string;}}
export class MrpQuarantineService extends BaseService<Row>{constructor(){super('mrp_quality_quarantine_decisions')} async decide(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_quality_quarantine_decision',{p_ncr_id:input.ncr_id||null,p_item_id:input.item_id||null,p_lot_id:input.lot_id||null,p_quantity:Number(input.quantity||0),p_decision:input.decision,p_reason:input.reason}); if(error) throw new Error(error.message); return data as string;}}
class MrpQualityAnalyticsService{async dashboard(){const{data,error}=await supabase.from('mrp_quality_dashboard').select('*').limit(10); if(error) throw new Error(error.message); return data||[]} async checklists(){const{data,error}=await supabase.from('mrp_quality_checklist_template_board').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async inspections(){const{data,error}=await supabase.from('mrp_quality_inspection_queue').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async ncr(){const{data,error}=await supabase.from('mrp_quality_ncr_dashboard').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async capa(){const{data,error}=await supabase.from('mrp_quality_capa_dashboard').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async calibration(){const{data,error}=await supabase.from('mrp_quality_calibration_due').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async spc(){const{data,error}=await supabase.from('mrp_quality_spc_alerts').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async quarantine(){const{data,error}=await supabase.from('mrp_quality_quarantine_queue').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async kpis(){const{data,error}=await supabase.from('mrp_quality_kpis').select('*').limit(10); if(error) throw new Error(error.message); return data||[]}}
export const mrpQualityPlanService=new MrpQualityPlanService();
export const mrpQualityChecklistService=new MrpQualityChecklistService();
export const mrpQualityInspectionService=new MrpQualityInspectionService();
export const mrpAqlService=new MrpAqlService();
export const mrpNcrService=new MrpNcrService();
export const mrpCapaService=new MrpCapaService();
export const mrpCalibrationService=new MrpCalibrationService();
export const mrpSpcService=new MrpSpcService();
export const mrpQuarantineService=new MrpQuarantineService();
export const mrpQualityAnalyticsService=new MrpQualityAnalyticsService();
