import { BaseService } from './BaseService';
import { supabase } from '../supabase/supabase';

export interface MrpPlantRecord { id:string; tenant_id:string; plant_code:string; name_ar:string; plant_type:string; status:string; created_at:string; }
export interface MrpAreaRecord { id:string; tenant_id:string; plant_id:string; area_code:string; name_ar:string; area_type:string; status:string; created_at:string; }
export interface MrpLineRecord { id:string; tenant_id:string; plant_id:string; line_code:string; name_ar:string; line_type:string; status:string; created_at:string; }
export interface MrpWorkCenterRecord { id:string; tenant_id:string; plant_id:string; work_center_code:string; name_ar:string; work_center_type:string; status:string; created_at:string; }
export interface MrpResourceRecord { id:string; tenant_id:string; resource_code:string; resource_type:string; name_ar:string; status:string; created_at:string; }
export interface MrpAssetRecord { id:string; tenant_id:string; asset_code:string; name_ar:string; criticality:string; status:string; created_at:string; }
export interface MrpCalendarRecord { id:string; tenant_id:string; calendar_code:string; name_ar:string; timezone:string; status:string; created_at:string; }
export interface MrpShiftRecord { id:string; tenant_id:string; shift_code:string; name_ar:string; starts_at_time:string; ends_at_time:string; status:string; created_at:string; }
export interface MrpOperationRecord { id:string; tenant_id:string; operation_code:string; name_ar:string; operation_type:string; status:string; created_at:string; }
export interface MrpRoutingRecord { id:string; tenant_id:string; routing_code:string; version_no:string; status:string; created_at:string; }
export interface MrpNumberingRecord { id:string; tenant_id:string; entity_type:string; prefix:string; next_number:number; is_default:boolean; }

type Row=Record<string,unknown>;
export class MrpPlantService extends BaseService<MrpPlantRecord>{constructor(){super('manufacturing_plants')} async createPlant(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_plant',{p_plant_code:input.plant_code||null,p_name_ar:input.name_ar,p_name_en:input.name_en||null,p_plant_type:input.plant_type||'manufacturing',p_address:input.address||null}); if(error) throw new Error(error.message); return data as string;}}
export class MrpAreaService extends BaseService<MrpAreaRecord>{constructor(){super('manufacturing_areas')} async createArea(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_area',{p_plant_id:input.plant_id,p_area_code:input.area_code||null,p_name_ar:input.name_ar,p_area_type:input.area_type||'production'}); if(error) throw new Error(error.message); return data as string;}}
export class MrpLineService extends BaseService<MrpLineRecord>{constructor(){super('production_lines')} async createLine(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_line',{p_plant_id:input.plant_id,p_area_id:input.area_id||null,p_line_code:input.line_code||null,p_name_ar:input.name_ar,p_line_type:input.line_type||'discrete'}); if(error) throw new Error(error.message); return data as string;}}
export class MrpWorkCenterService extends BaseService<MrpWorkCenterRecord>{constructor(){super('work_centers')} async createWorkCenter(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_work_center',{p_plant_id:input.plant_id,p_line_id:input.line_id||null,p_work_center_code:input.work_center_code||null,p_name_ar:input.name_ar,p_work_center_type:input.work_center_type||'machine'}); if(error) throw new Error(error.message); return data as string;}}
export class MrpResourceService extends BaseService<MrpResourceRecord>{constructor(){super('manufacturing_resources')} async upsertResource(input:Row):Promise<string>{const{data,error}=await supabase.rpc('upsert_mrp_resource',{p_resource_code:input.resource_code||null,p_resource_type:input.resource_type,p_name_ar:input.name_ar,p_capacity_per_shift:input.capacity_per_shift?Number(input.capacity_per_shift):null,p_cost_rate:Number(input.cost_rate||0)}); if(error) throw new Error(error.message); return data as string;} async linkToWorkCenter(input:Row):Promise<string>{const{data,error}=await supabase.rpc('link_mrp_work_center_resource',{p_work_center_id:input.work_center_id,p_resource_id:input.resource_id,p_required_quantity:Number(input.required_quantity||1),p_is_primary:Boolean(input.is_primary)}); if(error) throw new Error(error.message); return data as string;}}
export class MrpAssetService extends BaseService<MrpAssetRecord>{constructor(){super('manufacturing_assets')} async upsertAsset(input:Row):Promise<string>{const{data,error}=await supabase.rpc('upsert_mrp_asset',{p_asset_code:input.asset_code||null,p_name_ar:input.name_ar,p_plant_id:input.plant_id||null,p_work_center_id:input.work_center_id||null,p_criticality:input.criticality||'B',p_linked_maintenance_asset_id:input.linked_maintenance_asset_id||null}); if(error) throw new Error(error.message); return data as string;}}
export class MrpCalendarService extends BaseService<MrpCalendarRecord>{constructor(){super('manufacturing_calendars')} async createCalendar(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_calendar',{p_calendar_code:input.calendar_code||null,p_name_ar:input.name_ar,p_timezone:input.timezone||'Asia/Baghdad'}); if(error) throw new Error(error.message); return data as string;}}
export class MrpShiftService extends BaseService<MrpShiftRecord>{constructor(){super('manufacturing_shifts')} async createShift(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_mrp_shift',{p_shift_code:input.shift_code||null,p_name_ar:input.name_ar,p_starts_at_time:input.starts_at_time,p_ends_at_time:input.ends_at_time,p_break_minutes:Number(input.break_minutes||0)}); if(error) throw new Error(error.message); return data as string;}}
export class MrpOperationService extends BaseService<MrpOperationRecord>{constructor(){super('manufacturing_operation_catalog')} async upsertOperation(input:Row):Promise<string>{const{data,error}=await supabase.rpc('upsert_operation_catalog',{p_operation_code:input.operation_code||null,p_name_ar:input.name_ar,p_operation_type:input.operation_type||'production',p_setup:Number(input.standard_setup_minutes||0),p_run:Number(input.standard_run_minutes_per_unit||0),p_quality:Boolean(input.requires_quality_check)}); if(error) throw new Error(error.message); return data as string;}}
export class MrpRoutingService extends BaseService<MrpRoutingRecord>{constructor(){super('routing_headers')} async createRouting(input:Row):Promise<string>{const{data,error}=await supabase.rpc('create_routing_header',{p_routing_code:input.routing_code||null,p_item_id:input.item_id||null,p_routing_type:input.routing_type||'manufacturing',p_version_no:input.version_no||'1.0'}); if(error) throw new Error(error.message); return data as string;} async addOperation(input:Row):Promise<string>{const{data,error}=await supabase.rpc('add_routing_operation',{p_routing_id:input.routing_id,p_sequence_no:Number(input.sequence_no||10),p_operation_id:input.operation_id||null,p_work_center_id:input.work_center_id||null,p_operation_name:input.operation_name,p_setup:Number(input.setup_minutes||0),p_run:Number(input.run_minutes_per_unit||0),p_quality:Boolean(input.quality_gate_required),p_instructions:input.instructions||null}); if(error) throw new Error(error.message); return data as string;} async approve(id:string):Promise<void>{const{error}=await supabase.rpc('approve_routing',{p_routing_id:id}); if(error) throw new Error(error.message);}}
export class MrpNumberingService extends BaseService<MrpNumberingRecord>{constructor(){super('mrp_numbering_rules')} async upsert(input:Row):Promise<string>{const{data,error}=await supabase.rpc('upsert_mrp_numbering_rule',{p_entity_type:input.entity_type,p_prefix:input.prefix,p_padding:Number(input.padding||4),p_next_number:Number(input.next_number||1),p_separator:input.separator||'-',p_is_default:input.is_default??true}); if(error) throw new Error(error.message); return data as string;} async preview(entityType:string):Promise<string>{const{data,error}=await supabase.rpc('preview_mrp_next_code',{p_entity_type:entityType}); if(error) throw new Error(error.message); return data as string;}}
export class MrpCapacityService{async generate(input:Row):Promise<number>{const{data,error}=await supabase.rpc('generate_work_center_capacity',{p_work_center_id:input.work_center_id,p_calendar_id:input.calendar_id||null,p_shift_id:input.shift_id||null,p_start:input.start_date,p_end:input.end_date,p_minutes:Number(input.available_minutes||480)}); if(error) throw new Error(error.message); return Number(data||0);}}
class MrpAnalyticsService{async dashboard(){const{data,error}=await supabase.from('mrp_foundation_dashboard').select('*').limit(10); if(error) throw new Error(error.message); return data||[]} async capacity(){const{data,error}=await supabase.from('mrp_work_center_capacity_calendar').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async resources(){const{data,error}=await supabase.from('mrp_resource_matrix').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async routings(){const{data,error}=await supabase.from('mrp_routing_overview').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async issues(){const{data,error}=await supabase.from('mrp_open_masterdata_issues').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async audit(){const{data,error}=await supabase.from('mrp_audit_activity').select('*').limit(100); if(error) throw new Error(error.message); return data||[]} async integrations(){const{data,error}=await supabase.from('mrp_integration_health').select('*').limit(10); if(error) throw new Error(error.message); return data||[]}}
export const mrpPlantService=new MrpPlantService();
export const mrpAreaService=new MrpAreaService();
export const mrpLineService=new MrpLineService();
export const mrpWorkCenterService=new MrpWorkCenterService();
export const mrpResourceService=new MrpResourceService();
export const mrpAssetService=new MrpAssetService();
export const mrpCalendarService=new MrpCalendarService();
export const mrpShiftService=new MrpShiftService();
export const mrpOperationService=new MrpOperationService();
export const mrpRoutingService=new MrpRoutingService();
export const mrpNumberingService=new MrpNumberingService();
export const mrpCapacityService=new MrpCapacityService();
export const mrpAnalyticsService=new MrpAnalyticsService();
