import { BaseService } from './BaseService';
import { supabase } from '../supabase/supabase';
import type { FinanceProjectRecord } from './FinanceFoundationService';

export interface ProjectAccountingRecord extends FinanceProjectRecord { project_type:string; budget_amount:number; billing_method:string; budget_lines_total:number; latest_actual_cost:number; latest_actual_revenue:number; latest_snapshot_date?:string|null; entity_code?:string; entity_name?:string; }
export interface ProjectBudgetLineRecord { id:string; tenant_id:string; legal_entity_id:string; project_id:string; account_id:string; cost_center_id?:string|null; line_type:'cost'|'revenue'|'capex'; period_start?:string|null; period_end?:string|null; budget_amount:number; notes?:string|null; project_code?:string; project_name?:string; account_code?:string; account_name?:string; cost_center_code?:string|null; cost_center_name?:string|null; }
export interface ProjectActualSnapshotRecord { id:string; tenant_id:string; legal_entity_id:string; project_id:string; as_of_date:string; actual_cost:number; actual_revenue:number; budget_amount:number; variance_amount:number; project_code?:string; project_name?:string; }
export interface ProjectAccountingDashboardRecord { tenant_id:string; legal_entity_id:string; entity_code:string; entity_name:string; active_projects:number; on_hold_projects:number; closed_projects:number; project_budget_total:number; latest_actual_cost:number; latest_actual_revenue:number; }

class ProjectAccountingService extends BaseService<ProjectAccountingRecord> {
  constructor(){ super('finance_projects'); }
  async findBoard(legalEntityId:string): Promise<ProjectAccountingRecord[]> { const {data,error}=await supabase.from('finance_project_accounting_board').select('*').eq('legal_entity_id',legalEntityId).order('code'); if(error) throw new Error(error.message); return (data||[]) as ProjectAccountingRecord[]; }
  async findDashboard(legalEntityId?:string): Promise<ProjectAccountingDashboardRecord[]> { let q=supabase.from('finance_project_accounting_dashboard').select('*').order('entity_code'); if(legalEntityId) q=q.eq('legal_entity_id',legalEntityId); const {data,error}=await q; if(error) throw new Error(error.message); return (data||[]) as ProjectAccountingDashboardRecord[]; }
  async findBudgetLines(projectId:string): Promise<ProjectBudgetLineRecord[]> { const {data,error}=await supabase.from('finance_project_budget_line_board').select('*').eq('project_id',projectId).order('created_at',{ascending:false}); if(error) throw new Error(error.message); return (data||[]) as ProjectBudgetLineRecord[]; }
  async findActuals(projectId:string): Promise<ProjectActualSnapshotRecord[]> { const {data,error}=await supabase.from('finance_project_actuals_board').select('*').eq('project_id',projectId).order('as_of_date',{ascending:false}); if(error) throw new Error(error.message); return (data||[]) as ProjectActualSnapshotRecord[]; }
  async upsertProject(input:{legalEntityId:string; code:string; nameAr:string; nameEn?:string; projectType?:string; budgetAmount?:number; billingMethod?:string; startDate?:string; endDate?:string; projectId?:string|null}): Promise<ProjectAccountingRecord>{ const {data,error}=await supabase.rpc('upsert_project_accounting_project',{p_legal_entity_id:input.legalEntityId,p_code:input.code,p_name_ar:input.nameAr,p_name_en:input.nameEn||null,p_project_type:input.projectType||'operational',p_budget_amount:input.budgetAmount||0,p_billing_method:input.billingMethod||'none',p_start_date:input.startDate||null,p_end_date:input.endDate||null,p_project_id:input.projectId||null}); if(error) throw new Error(error.message); return data as ProjectAccountingRecord; }
  async upsertBudgetLine(input:{projectId:string; accountId:string; budgetAmount:number; lineType?:'cost'|'revenue'|'capex'; costCenterId?:string; periodStart?:string; periodEnd?:string; notes?:string; lineId?:string|null}): Promise<ProjectBudgetLineRecord>{ const {data,error}=await supabase.rpc('upsert_project_budget_line',{p_project_id:input.projectId,p_account_id:input.accountId,p_budget_amount:input.budgetAmount,p_line_type:input.lineType||'cost',p_cost_center_id:input.costCenterId||null,p_period_start:input.periodStart||null,p_period_end:input.periodEnd||null,p_notes:input.notes||null,p_line_id:input.lineId||null}); if(error) throw new Error(error.message); return data as ProjectBudgetLineRecord; }
  async generateSnapshot(projectId:string,asOfDate:string): Promise<ProjectActualSnapshotRecord>{ const {data,error}=await supabase.rpc('generate_project_actuals_snapshot',{p_project_id:projectId,p_as_of_date:asOfDate}); if(error) throw new Error(error.message); return data as ProjectActualSnapshotRecord; }
  async updateStatus(projectId:string,status:'active'|'on_hold'|'closed'|'archived',reason:string): Promise<ProjectAccountingRecord>{ const {data,error}=await supabase.rpc('update_project_accounting_status',{p_project_id:projectId,p_status:status,p_reason:reason}); if(error) throw new Error(error.message); return data as ProjectAccountingRecord; }
}

export const projectAccountingService = new ProjectAccountingService();
