/**
 * ═════════════════════════════════════════════════════════════════════════
 *  Legacy view → URL path mapping
 *
 *  الغرض: التوافق العكسي — أي مستخدم عنده bookmark لـ ?view=xxx القديم
 *  يجب أن يُوجَّه للمسار الجديد بدون كسر تجربته.
 * ═════════════════════════════════════════════════════════════════════════
 */

export const VIEW_TO_PATH: Record<string, string> = {
  // Notifications
  'notifications':                '/app/notifications',
  'my-notifications':             '/app/my-notifications',

  // Employee
  'employee-dashboard':           '/app/employee',
  'employee-problems':            '/app/employee/problems',
  'new-problem':                  '/app/employee/problems/new',
  'employee-wellness':            '/app/employee/wellness',
  'employee-ai-chat':             '/app/employee/ai-chat',
  'employee-survey':              '/app/employee/survey',
  'employee-training':            '/app/employee/training',
  'employee-goals':               '/app/employee/goals',
  'employee-sops':                '/app/employee/sops',
  'employee-profile':             '/app/employee/profile',
  'employee-contact':             '/app/employee/contact',
  'employee-attendance':          '/app/employee/attendance',
  'employee-requests':            '/app/employee/leave-requests',
  'employee-leave-requests':      '/app/employee/leave-requests',
  'employee-permissions':         '/app/employee/permissions',
  'employee-payroll':             '/app/employee/payroll',
  'employee-loans':               '/app/employee/loans',
  'employee-expenses':            '/app/employee/expenses',
  'employee-ai-insights':         '/app/employee/insights',
  'insights':                     '/app/insights',

  // Kiosk
  'kiosk-mode':                   '/app/kiosk',

  // Manager
  'manager-dashboard':            '/app/manager',
  'manager-attendance':           '/app/manager/attendance',
  'manager-approvals':            '/app/manager/approvals',
  'manager-performance':          '/app/manager/performance',
  'manager-workload':             '/app/manager/workload',
  'manager-leave-requests':       '/app/employee/leave-requests',

  // Supervisor
  'supervisor-dashboard':         '/app/supervisor',
  'supervisor-breaks':            '/app/supervisor/breaks',
  'supervisor-shift':             '/app/supervisor/shift',
  'supervisor-tasks':             '/app/supervisor/tasks',
  'supervisor-checklists':        '/app/supervisor/checklists',
  'supervisor-leave-requests':    '/app/employee/leave-requests',

  // HR
  'hr-dashboard':                 '/app/hr',
  'hr-problems':                  '/app/hr/problems',
  'hr-analytics':                 '/app/hr/analytics',
  'hr-sentiment':                 '/app/hr/analytics',
  'hr-predictions':               '/app/hr/analytics',
  'hr-team':                      '/app/hr/team',
  'hr-reports':                   '/app/hr/reports',
  'hr-attendance':                '/app/hr/attendance',
  'hr-talent-market':             '/app/hr/talent-market',
  'hr-movement-analysis':         '/app/hr/movement-analysis',
  'hr-manage-training':           '/app/hr/training/manage',
  'hr-training-reports':          '/app/hr/training/reports',
  'hr-payroll':                   '/app/hr/payroll',
  'hr-loans':                     '/app/hr/loans',
  'hr-bonuses':                   '/app/hr/bonuses',
  'hr-expenses':                  '/app/hr/expenses',
  'hr-recruitment':               '/app/hr/recruitment',
  'hr-onboarding':                '/app/hr/onboarding',
  'hr-documents':                 '/app/hr/documents',
  'hr-contracts':                 '/app/hr/contracts',
  'hr-succession':                '/app/hr/succession',
  'hr-performance':               '/app/hr/performance',
  'hr-disciplinary':              '/app/hr/disciplinary',
  'hr-shifts':                    '/app/hr/shifts',
  'hr-communication':             '/app/hr/communication',
  'hr-service-center':            '/app/hr/service-center',
  'hr-health-safety':             '/app/hr/health-safety',
  'hr-leave-requests':            '/app/hr/leave-requests',
  'hr-sops':                      '/app/hr/sops',
  'hr-manage-surveys':            '/app/employee/survey',
  'hr-ai-insights':               '/app/insights',

  // Admin
  'admin-dashboard':              '/app/admin',
  'admin-employees':              '/app/admin/employees',
  'admin-permissions':            '/app/admin/permissions',
  'admin-permissions-management': '/app/admin/permissions-management',
  'admin-audit-log':              '/app/admin/audit-log',
  'admin-settings':               '/app/admin/settings',
  'admin-company-profile':       '/app/admin/company-profile',
  'admin-branches':              '/app/admin/branches',
  'admin-org-structure':         '/app/admin/org-structure',
  'admin-compliance':            '/app/admin/compliance',
  'admin-ai-config':              '/app/admin/ai-config',
  'admin-cms':                    '/app/admin/cms',
  'admin-gatekeeper-permissions': '/app/admin/gatekeeper-permissions',
  'admin-sops':                   '/app/admin/sops',
  'admin-sops-reports':           '/app/admin/sops-reports',
  'admin-attendance':             '/app/hr/attendance',
  'admin-reports':                '/app/hr/reports',

  // Other portals
  'gatekeeper-portal':            '/app/gatekeeper',
  'gatekeeper-movements':         '/app/gatekeeper/movements',
  'movement-portal':              '/app/gatekeeper/movements',
  'tech-portal':                  '/app/tech-portal',
  'tech-dashboard':               '/app/tech-portal/dashboard',
  'biometric-devices':            '/app/tech-portal/biometric',
  'sync-logs':                    '/app/tech-portal/sync-logs',
  'attendance-analytics':         '/app/tech-portal/attendance-analytics',
  'system-health':                '/app/tech-portal/system-health',
  'security-events':              '/app/tech-portal/security-events',
  'tech-settings':                '/app/tech-portal/settings',
  'tawathul-portal':              '/app/tawathul',
  'tawathul-admin':               '/app/tawathul/admin',
  'developer-dashboard':          '/dev',

  // Finance Portal
  'finance-dashboard':            '/app/finance',
  'finance-coa':                  '/app/finance/chart-of-accounts',
  'finance-journal':              '/app/finance/journal-entries',
  'finance-trial-balance':        '/app/finance/trial-balance',
  'finance-ledger':               '/app/finance/general-ledger',
  'finance-reports':              '/app/finance/financial-reports',
  'finance-periods':              '/app/finance/accounting-periods',
  'finance-vendors':              '/app/finance/vendors',
  'finance-payable':              '/app/finance/accounts-payable',
  'finance-setup':                '/app/finance/setup',

  // Procurement Portal
  'procurement-dashboard':        '/app/procurement',
  'procurement-pr':               '/app/procurement/requisitions',
  'procurement-suppliers':        '/app/procurement/suppliers',
  'procurement-sourcing':         '/app/procurement/sourcing',
  'procurement-orders':           '/app/procurement/orders',
  'procurement-gr':               '/app/procurement/orders/goods-receipts',
  'procurement-invoices':         '/app/procurement/invoices',
  'procurement-contracts':        '/app/procurement/contracts',
  'procurement-analytics':        '/app/procurement/analytics',

  // Inventory / Warehouse Portal
  'inventory-dashboard':          '/app/inventory',
  'inventory-foundation':         '/app/inventory/foundation',
  'inventory-items':              '/app/inventory/items',
  'inventory-warehouses':         '/app/inventory/warehouses',
  'inventory-stock':              '/app/inventory/stock',
  'inventory-movements':          '/app/inventory/movements',
  'inventory-numbering':          '/app/inventory/numbering',
  'inventory-receiving':          '/app/inventory/receiving',
  'inventory-asn':                '/app/inventory/receiving/asn',
  'inventory-dock-schedule':      '/app/inventory/receiving/dock-schedule',
  'inventory-receiving-sessions': '/app/inventory/receiving/sessions',
  'inventory-osd':                '/app/inventory/receiving/osd',
  'inventory-quarantine':         '/app/inventory/receiving/quarantine',
  'inventory-putaway':            '/app/inventory/receiving/putaway',
  'inventory-cross-dock':         '/app/inventory/receiving/cross-dock',
  'inventory-mobile-scan':        '/app/inventory/receiving/mobile-scan',
  'inventory-lpn-labels':         '/app/inventory/receiving/lpn-labels',
  'inventory-receiving-reports':  '/app/inventory/receiving/reports',
  'inventory-inbound-notifications': '/app/inventory/receiving/notifications',
  'inventory-receiving-attachments': '/app/inventory/receiving/attachments',
  'inventory-quality-ncr':        '/app/inventory/receiving/ncr',
  'inventory-storage':            '/app/inventory/storage',
  'inventory-location-map':       '/app/inventory/storage/map',
  'inventory-visual-map':         '/app/inventory/storage/visual-map',
  'inventory-storage-heatmap':    '/app/inventory/storage/heatmap',
  'inventory-slotting':           '/app/inventory/storage/slotting',
  'inventory-abc':                '/app/inventory/storage/abc',
  'inventory-replenishment':      '/app/inventory/storage/replenishment',
  'inventory-capacity':           '/app/inventory/storage/capacity',
  'inventory-slow-moving':        '/app/inventory/storage/slow-moving',
  'inventory-location-labels':    '/app/inventory/storage/location-labels',
  'inventory-affinity':           '/app/inventory/storage/affinity',
  'inventory-seasonal-slotting':  '/app/inventory/storage/seasonal',
  'inventory-task-interleaving':  '/app/inventory/storage/interleaving',
  'inventory-slow-moving-reports':'/app/inventory/storage/slow-moving-reports',
  'inventory-picking':            '/app/inventory/picking',
  'inventory-pick-orders':        '/app/inventory/picking/orders',
  'inventory-pick-tasks':         '/app/inventory/picking/tasks',
  'inventory-pick-waves':         '/app/inventory/picking/waves',
  'inventory-pick-exceptions':    '/app/inventory/picking/exceptions',
  'inventory-pick-scans':         '/app/inventory/picking/scans',
  'inventory-picking-productivity':'/app/inventory/picking/productivity',
  'inventory-picking-kpis':       '/app/inventory/picking/kpis',
  'inventory-pick-route-map':     '/app/inventory/picking/route-map',
  'inventory-voice-picking':      '/app/inventory/picking/voice',
  'inventory-pick-to-light':      '/app/inventory/picking/pick-to-light',
  'inventory-rfid-picking':       '/app/inventory/picking/rfid',
  'inventory-pick-sorting':       '/app/inventory/picking/sorting',
  'inventory-zone-handoffs':      '/app/inventory/picking/handoffs',
  'inventory-shipping':           '/app/inventory/shipping',
  'inventory-shipping-packages':  '/app/inventory/shipping/packages',
  'inventory-shipments':          '/app/inventory/shipping/shipments',
  'inventory-carriers':           '/app/inventory/shipping/carriers',
  'inventory-shipping-documents': '/app/inventory/shipping/documents',
  'inventory-manifests':          '/app/inventory/shipping/manifests',
  'inventory-manifest-completion':'/app/inventory/shipping/manifest-completion',
  'inventory-rate-quotes':        '/app/inventory/shipping/rate-quotes',
  'inventory-rate-rules':         '/app/inventory/shipping/rate-rules',
  'inventory-shipment-tracking':  '/app/inventory/shipping/tracking',
  'inventory-carrier-webhooks':   '/app/inventory/shipping/webhooks',
  'inventory-shipping-kpis':      '/app/inventory/shipping/kpis',
  'inventory-counting':           '/app/inventory/counting',
  'inventory-count-plans':        '/app/inventory/counting/plans',
  'inventory-count-tasks':        '/app/inventory/counting/tasks',
  'inventory-count-variances':    '/app/inventory/counting/variances',
  'inventory-adjustment-approvals':'/app/inventory/counting/approvals',
  'inventory-count-completion':   '/app/inventory/counting/completion',
  'inventory-expiry-count-report':'/app/inventory/counting/expiry',
  'inventory-mobile-count':       '/app/inventory/counting/mobile',
  'inventory-recount':            '/app/inventory/counting/recount',
  'inventory-count-freeze':       '/app/inventory/counting/freeze',
  'inventory-annual-count':       '/app/inventory/counting/annual',
  'inventory-returns':            '/app/inventory/returns',
  'inventory-rma':                '/app/inventory/returns/rma',
  'inventory-return-receiving':   '/app/inventory/returns/receiving',
  'inventory-return-grading':     '/app/inventory/returns/grading',
  'inventory-return-disposition': '/app/inventory/returns/disposition',
  'inventory-production-returns': '/app/inventory/returns/production',
  'inventory-return-rtv':         '/app/inventory/returns/rtv',
  'inventory-return-notifications':'/app/inventory/returns/notifications',
  'inventory-supplier-rtv-reports':'/app/inventory/returns/supplier-reports',
  'inventory-return-analytics':   '/app/inventory/returns/analytics',
  'inventory-return-quality':     '/app/inventory/returns/quality',
  'inventory-return-value-recovery':'/app/inventory/returns/value-recovery',
  'inventory-return-capa':        '/app/inventory/returns/capa',
  'inventory-labor':              '/app/inventory/labor',
  'inventory-labor-standards':    '/app/inventory/labor/standards',
  'inventory-workforce-planning': '/app/inventory/labor/planning',
  'inventory-worker-availability':'/app/inventory/labor/availability',
  'inventory-labor-dispatch':     '/app/inventory/labor/dispatch',
  'inventory-labor-interleaving': '/app/inventory/labor/interleaving',
  'inventory-labor-time-tracking':'/app/inventory/labor/time-tracking',
  'inventory-employee-performance':'/app/inventory/labor/employee-performance',
  'inventory-labor-manager-dashboard':'/app/inventory/labor/manager-dashboard',
  'inventory-non-productive-time':'/app/inventory/labor/non-productive',
  'inventory-skills-training':    '/app/inventory/labor/skills-training',
  'inventory-labor-incentives':   '/app/inventory/labor/incentives',
  'inventory-labor-reports':      '/app/inventory/labor/reports',
  'inventory-labor-safety-kpis':  '/app/inventory/labor/safety-kpis',
  'inventory-labor-leaderboard':  '/app/inventory/labor/leaderboard',
  'inventory-analytics':          '/app/inventory/analytics',
  'inventory-analytics-executive':'/app/inventory/analytics/executive',
  'inventory-analytics-operations':'/app/inventory/analytics/operations',
  'inventory-analytics-supervisor':'/app/inventory/analytics/supervisor',
  'inventory-kpi-scorecard':      '/app/inventory/analytics/scorecard',
  'inventory-kpi-trends':         '/app/inventory/analytics/trends',
  'inventory-analytics-heatmap':  '/app/inventory/analytics/heatmap',
  'inventory-seasonal-patterns':  '/app/inventory/analytics/seasonal',
  'inventory-root-cause':         '/app/inventory/analytics/root-cause',
  'inventory-predictive-alerts':  '/app/inventory/analytics/alerts',
  'inventory-periodic-reports':   '/app/inventory/analytics/reports',
  'inventory-report-exports':     '/app/inventory/analytics/exports',
  'inventory-operating-costs':    '/app/inventory/analytics/costs',
  'inventory-kpi-targets':        '/app/inventory/analytics/targets',

  'mrp-dashboard':              '/app/mrp',
  'mrp-foundation':             '/app/mrp/foundation',
  'mrp-plants':                 '/app/mrp/foundation/plants',
  'mrp-areas':                  '/app/mrp/foundation/areas',
  'mrp-lines':                  '/app/mrp/foundation/lines',
  'mrp-work-centers':           '/app/mrp/foundation/work-centers',
  'mrp-resources':              '/app/mrp/foundation/resources',
  'mrp-assets':                 '/app/mrp/foundation/assets',
  'mrp-calendars':              '/app/mrp/foundation/calendars',
  'mrp-shifts':                 '/app/mrp/foundation/shifts',
  'mrp-capacity':               '/app/mrp/foundation/capacity',
  'mrp-operations':             '/app/mrp/foundation/operations',
  'mrp-routings':               '/app/mrp/foundation/routings',
  'mrp-numbering':              '/app/mrp/foundation/numbering',
  'mrp-audit':                  '/app/mrp/foundation/audit',
  'mrp-integrations':           '/app/mrp/foundation/integrations',

  'mrp-bom':                    '/app/mrp/bom',
  'mrp-bom-builder':            '/app/mrp/bom/builder',
  'mrp-bom-headers':            '/app/mrp/bom/headers',
  'mrp-bom-versions':           '/app/mrp/bom/versions',
  'mrp-bom-lines':              '/app/mrp/bom/lines',
  'mrp-bom-explosion':          '/app/mrp/bom/explosion',
  'mrp-bom-availability':       '/app/mrp/bom/availability',
  'mrp-ecr':                    '/app/mrp/bom/ecr',
  'mrp-eco':                    '/app/mrp/bom/eco',
  'mrp-bom-import-export':      '/app/mrp/bom/import-export',
  'mrp-bom-reports':            '/app/mrp/bom/reports',

  'mrp-forecasting':            '/app/mrp/forecasting',
  'mrp-demand-history':         '/app/mrp/forecasting/history',
  'mrp-forecast-models':        '/app/mrp/forecasting/models',
  'mrp-forecast-runs':          '/app/mrp/forecasting/runs',
  'mrp-forecast-accuracy':      '/app/mrp/forecasting/accuracy',
  'mrp-planning-policies':      '/app/mrp/forecasting/policies',
  'mrp-mps':                    '/app/mrp/mps',
  'mrp-mps-board':              '/app/mrp/mps/board',
  'mrp-mps-plans':              '/app/mrp/mps/plans',
  'mrp-mps-lines':              '/app/mrp/mps/lines',
  'mrp-rccp':                   '/app/mrp/mps/rccp',
  'mrp-mps-alerts':             '/app/mrp/mps/alerts',
  'mrp-mps-reports':            '/app/mrp/mps/reports',

  'mrp-planning':               '/app/mrp/planning',
  'mrp-runs':                   '/app/mrp/planning/mrp-runs',
  'mrp-planned-orders':         '/app/mrp/planning/proposals',
  'mrp-work-orders':            '/app/mrp/planning/work-orders',
  'mrp-wo-materials':           '/app/mrp/planning/materials',
  'mrp-wo-operations':          '/app/mrp/planning/operations',
  'mrp-production-scheduling':  '/app/mrp/planning/scheduling',
  'mrp-dispatch':               '/app/mrp/planning/dispatch',
  'mrp-wo-alerts':              '/app/mrp/planning/alerts',
  'mrp-planning-reports':       '/app/mrp/planning/reports',

  'mrp-inventory':              '/app/mrp/inventory',
  'mrp-raw-materials':          '/app/mrp/inventory/raw-materials',
  'mrp-wip':                    '/app/mrp/inventory/wip',
  'mrp-finished-goods':         '/app/mrp/inventory/finished-goods',
  'mrp-valuation':              '/app/mrp/inventory/valuation',
  'mrp-lots-traceability':      '/app/mrp/inventory/lots-traceability',
  'mrp-safety-stock':           '/app/mrp/inventory/safety-stock',
  'mrp-material-issues':        '/app/mrp/inventory/material-issues',
  'mrp-reconciliation':         '/app/mrp/inventory/reconciliation',
  'mrp-inventory-reports':      '/app/mrp/inventory/reports',

  'mrp-procurement':            '/app/mrp/procurement',
  'mrp-proc-recommendations':   '/app/mrp/procurement/recommendations',
  'mrp-proc-pr':                '/app/mrp/procurement/pr',
  'mrp-proc-rfq':               '/app/mrp/procurement/rfq',
  'mrp-proc-po':                '/app/mrp/procurement/po',
  'mrp-proc-gr':                '/app/mrp/procurement/gr',
  'mrp-proc-invoices':          '/app/mrp/procurement/invoices',
  'mrp-proc-suppliers':         '/app/mrp/procurement/suppliers',
  'mrp-proc-contracts':         '/app/mrp/procurement/contracts',
  'mrp-proc-alerts':            '/app/mrp/procurement/alerts',
  'mrp-proc-reports':           '/app/mrp/procurement/reports',

  'mrp-quality':                '/app/mrp/quality',
  'mrp-quality-plans':          '/app/mrp/quality/plans',
  'mrp-quality-checklists':     '/app/mrp/quality/checklists',
  'mrp-quality-inspections':    '/app/mrp/quality/inspections',
  'mrp-quality-aql':            '/app/mrp/quality/aql',
  'mrp-quality-ncr':            '/app/mrp/quality/ncr',
  'mrp-quality-capa':           '/app/mrp/quality/capa',
  'mrp-quality-calibration':    '/app/mrp/quality/calibration',
  'mrp-quality-spc':            '/app/mrp/quality/spc',
  'mrp-quality-quarantine':     '/app/mrp/quality/quarantine',
  'mrp-quality-reports':        '/app/mrp/quality/reports',

  'mrp-shopfloor':              '/app/mrp/shopfloor',
  'mrp-shopfloor-workstations': '/app/mrp/shopfloor/workstations',
  'mrp-shopfloor-terminals':    '/app/mrp/shopfloor/terminals',
  'mrp-shopfloor-tracking':     '/app/mrp/shopfloor/tracking',
  'mrp-shopfloor-consumption':  '/app/mrp/shopfloor/consumption',
  'mrp-shopfloor-oee':          '/app/mrp/shopfloor/oee',
  'mrp-shopfloor-downtime':     '/app/mrp/shopfloor/downtime',
  'mrp-shopfloor-pareto':       '/app/mrp/shopfloor/pareto',
  'mrp-shopfloor-progress':     '/app/mrp/shopfloor/work-order-progress',
  'mrp-shopfloor-labor':        '/app/mrp/shopfloor/labor-shifts',
  'mrp-shopfloor-andon':        '/app/mrp/shopfloor/andon',
  'mrp-shopfloor-supervisor':   '/app/mrp/shopfloor/supervisor',
  'mrp-shopfloor-manager':      '/app/mrp/shopfloor/manager',
  'mrp-shopfloor-maintenance':  '/app/mrp/shopfloor/maintenance',
  'mrp-shopfloor-reports':      '/app/mrp/shopfloor/reports',

  'mrp-maintenance':            '/app/mrp/maintenance',
  'mrp-maintenance-assets':     '/app/mrp/maintenance/assets',
  'mrp-maintenance-criticality':'/app/mrp/maintenance/criticality',
  'mrp-maintenance-pm-plans':   '/app/mrp/maintenance/pm-plans',
  'mrp-maintenance-pm-calendar':'/app/mrp/maintenance/pm-calendar',
  'mrp-maintenance-work-orders':'/app/mrp/maintenance/work-orders',
  'mrp-maintenance-spare-parts':'/app/mrp/maintenance/spare-parts',
  'mrp-maintenance-condition':  '/app/mrp/maintenance/condition',
  'mrp-maintenance-breakdowns': '/app/mrp/maintenance/breakdowns',
  'mrp-maintenance-shutdowns':  '/app/mrp/maintenance/shutdowns',
  'mrp-maintenance-reports':    '/app/mrp/maintenance/reports',

  'mrp-costing':                '/app/mrp/costing',
  'mrp-cost-elements':          '/app/mrp/costing/cost-elements',
  'mrp-costing-profiles':       '/app/mrp/costing/profiles',
  'mrp-standard-costs':         '/app/mrp/costing/standard-costs',
  'mrp-cost-rollup':            '/app/mrp/costing/rollup',
  'mrp-work-order-costs':       '/app/mrp/costing/work-order-costs',
  'mrp-cost-variances':         '/app/mrp/costing/variances',
  'mrp-wip-valuation':          '/app/mrp/costing/wip',
  'mrp-fg-valuation':           '/app/mrp/costing/finished-goods',
  'mrp-cost-postings':          '/app/mrp/costing/postings',
  'mrp-costing-reports':        '/app/mrp/costing/reports',

  'mrp-analytics':              '/app/mrp/analytics',
  'mrp-analytics-executive':    '/app/mrp/analytics/executive',
  'mrp-analytics-operations':   '/app/mrp/analytics/operations',
  'mrp-analytics-scorecard':    '/app/mrp/analytics/scorecard',
  'mrp-analytics-oee':          '/app/mrp/analytics/oee',
  'mrp-analytics-schedule':     '/app/mrp/analytics/schedule',
  'mrp-analytics-bottlenecks':  '/app/mrp/analytics/bottlenecks',
  'mrp-analytics-quality-cost': '/app/mrp/analytics/quality-cost',
  'mrp-analytics-cost-variance':'/app/mrp/analytics/cost-variance',
  'mrp-analytics-maintenance':  '/app/mrp/analytics/maintenance',
  'mrp-analytics-alerts':       '/app/mrp/analytics/alerts',
  'mrp-analytics-root-cause':   '/app/mrp/analytics/root-cause',
  'mrp-analytics-reports':      '/app/mrp/analytics/reports',
  'mrp-analytics-exports':      '/app/mrp/analytics/exports',
  'mrp-analytics-kpi-targets':  '/app/mrp/analytics/kpi-targets',
};

/**
 * محاولة تحويل view قديم إلى المسار الجديد.
 * يعيد null إن كان view غير معروف.
 */
export function legacyViewToPath(view: string | null | undefined): string | null {
  if (!view) return null;
  return VIEW_TO_PATH[view] ?? null;
}
