import { useEffect, useState } from 'react';
import { InventoryRecordTools } from '../shared/InventoryRecordTools';
import { LocationLookup, ProductionReturnLookup, ReturnAssessmentLookup, ReturnDispositionTaskLookup, ReturnReceiptLineLookup, RmaLookup, SupplierLookup, WarehouseLookup } from '../shared/InventoryLookups';
import { ProductionReturnLinesBuilder, ReturnReceiveLinesBuilder, RmaLinesBuilder } from '../shared/InventoryLineBuilders';
import { inventoryProductionReturnService, inventoryReturnConditionAssessmentService, inventoryReturnCustomerNotificationService, inventoryReturnDispositionTaskService, inventoryReturnReceiptService, inventoryReturnRtvClaimService, inventoryReturnsAnalyticsService, inventoryRmaService, inventorySupplierRtvReportService, inventoryReturnCapaActionService } from '../../../../services/sdk';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
const cfgs:Record<string,Config>={
 dashboard:{title:'المرتجعات واللوجستيات العكسية',subtitle:'RMA، الاستلام، التقييم A/B/C/D، التوجيه، القيمة المستردة',load:()=>inventoryReturnsAnalyticsService.dashboard() as Promise<Row[]>,columns:[{key:'total_rmas',label:'إجمالي RMA'},{key:'expected_returns',label:'متوقع'},{key:'active_returns',label:'نشط'},{key:'closed_returns',label:'مغلق'},{key:'total_expected_value',label:'القيمة'}]},
 rmas:{title:'إدارة RMA',subtitle:'إصدار إذن إرجاع مع سياسة/ضمان وصلاحية 30 يوماً وتعليمات الشحن',load:()=>inventoryRmaService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'rma',columns:[{key:'rma_number',label:'RMA'},{key:'return_type',label:'النوع'},{key:'reason_code',label:'السبب'},{key:'status',label:'الحالة'},{key:'expected_total_value',label:'القيمة'}]},
 receiving:{title:'استلام المرتجعات',subtitle:'مسح RMA، فحص الطرد، مقارنة المتوقع، وتحويل إلى الحجر/الفرز',load:()=>inventoryReturnReceiptService.findAll({orderBy:'received_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'receive',columns:[{key:'receipt_number',label:'الإيصال'},{key:'status',label:'الحالة'},{key:'package_condition',label:'حالة الطرد'},{key:'tracking_number',label:'Tracking'},{key:'received_at',label:'تاريخ'}]},
 grading:{title:'التقييم والفرز A/B/C/D',subtitle:'A Restock، B Repack، C Repair/RTV، D Scrap مع إنشاء NCR عند وجود عيب',load:()=>inventoryReturnConditionAssessmentService.findAll({orderBy:'assessed_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'grade',columns:[{key:'condition_grade',label:'Grade'},{key:'condition_label_ar',label:'الوصف'},{key:'defect_source',label:'مصدر العيب'},{key:'recommended_disposition',label:'المسار'},{key:'estimated_recovered_value',label:'قيمة مستردة'}]},
 disposition:{title:'مسارات التوجيه Disposition',subtitle:'Restock / Repack & Resell / Repair / RTV / Scrap',load:()=>inventoryReturnDispositionTaskService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'disposition',columns:[{key:'task_number',label:'المهمة'},{key:'disposition',label:'المسار'},{key:'quantity',label:'الكمية'},{key:'status',label:'الحالة'},{key:'actual_recovered_value',label:'المسترد'}]},
 production:{title:'المرتجعات الداخلية من الإنتاج',subtitle:'إرجاع مواد من WO مع فحص جودة وتعديل تكلفة ممثل بسجل',load:()=>inventoryProductionReturnService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'production',columns:[{key:'production_return_number',label:'PRR'},{key:'work_order_id',label:'WO'},{key:'reason_code',label:'السبب'},{key:'status',label:'الحالة'}]},
 rtv:{title:'Returns to Vendor - RTV',subtitle:'مطالبات الموردين، Credit Note/Replacement، وتجميع التقارير',load:()=>inventoryReturnRtvClaimService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,columns:[{key:'rtv_number',label:'RTV'},{key:'supplier_id',label:'المورد'},{key:'quantity',label:'الكمية'},{key:'claim_value',label:'القيمة'},{key:'status',label:'الحالة'}]},
 notifications:{title:'إشعارات العملاء',subtitle:'تحديث تلقائي لحالة RMA: موافقة، استلام، تقييم، توجيه، إغلاق',load:()=>inventoryReturnCustomerNotificationService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'notify',columns:[{key:'notification_type',label:'النوع'},{key:'channel',label:'القناة'},{key:'recipient',label:'المستلم'},{key:'status',label:'الحالة'}]},
 supplierReports:{title:'تقارير الموردين RTV',subtitle:'تجميع مرتجعات الموردين للمطالبة والاستبدال أو Credit Note',load:()=>inventoryReturnsAnalyticsService.supplierRtvSummary() as Promise<Row[]>,action:'supplierReport',columns:[{key:'supplier_id',label:'المورد'},{key:'claim_count',label:'المطالبات'},{key:'total_quantity',label:'الكمية'},{key:'total_claim_value',label:'القيمة'},{key:'open_claims',label:'مفتوحة'}]},
 analytics:{title:'تحليلات المرتجعات',subtitle:'Return Rate، Processing Time، Value Recovery، Grading Accuracy، Cost/Return',load:()=>inventoryReturnsAnalyticsService.kpis() as Promise<Row[]>,columns:[{key:'return_cases',label:'الحالات'},{key:'return_rate_percent',label:'Return Rate %'},{key:'avg_processing_days',label:'أيام المعالجة'},{key:'value_recovery_percent',label:'Recovery %'},{key:'grading_accuracy_percent',label:'Accuracy %'},{key:'cost_per_return',label:'Cost/Return'}]},
 quality:{title:'الجودة وCAPA',subtitle:'كل defect من المرتجعات يغذي NCR وCAPA لتحسين الجودة',load:()=>inventoryReturnsAnalyticsService.qualityDefects() as Promise<Row[]>,columns:[{key:'defect_source',label:'المصدر'},{key:'defect_type',label:'العيب'},{key:'defect_count',label:'عدد'},{key:'capa_count',label:'CAPA'},{key:'closed_capa_count',label:'مغلق'}]},
 value:{title:'استرداد القيمة وتوزيع الحالات',subtitle:'توزيع A/B/C/D والقيمة المستردة شهرياً حسب المسار',load:()=>inventoryReturnsAnalyticsService.valueRecovery() as Promise<Row[]>,columns:[{key:'recommended_disposition',label:'المسار'},{key:'units',label:'الوحدات'},{key:'original_value',label:'الأصلية'},{key:'recovered_value',label:'المستردة'},{key:'recovery_percent',label:'%'}]},
 capa:{title:'إجراءات CAPA',subtitle:'إجراءات تصحيحية ووقائية مرتبطة بتقييم المرتجع وNCR',load:()=>inventoryReturnCapaActionService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,columns:[{key:'root_cause',label:'سبب جذري'},{key:'corrective_action',label:'تصحيحي'},{key:'preventive_action',label:'وقائي'},{key:'status',label:'الحالة'}]}
};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void){return <label className="text-xs font-bold"><span>{l}</span><input value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function area(l:string,n:string,f:Form,set:(p:Form)=>void){return <label className="text-xs font-bold md:col-span-2"><span>{l}</span><textarea value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1" rows={3}/></label>}
function parseLines(s:string){try{return s?JSON.parse(s):[]}catch{return []}}
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({return_type:'customer_return',reason_code:'defective',valid_days:'30',package_condition:'intact',condition_grade:'A',disposition:'restock',quality_status:'approved',channel:'portal',notification_type:'manual'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r||'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='rma')return <Box title="إصدار/اعتماد RMA"><div className="grid md:grid-cols-3 gap-3">{inp('Return Type','return_type',f,set)}{inp('Customer Name','customer_name',f,set)}{inp('Reason Code','reason_code',f,set)}{inp('Original Shipment ID','original_shipment_id',f,set)}{inp('Valid Days','valid_days',f,set)}<RmaLinesBuilder value={f.lines} onChange={(json)=>set({lines:json})} /><button onClick={()=>void run(()=>inventoryRmaService.createRma({...f,valid_days:Number(f.valid_days||30),lines:parseLines(f.lines)}))} className="bg-indigo-600 text-white rounded-xl p-2">Create RMA</button><RmaLookup label="اختر RMA" value={f.rma_id} onChange={(id)=>set({rma_id:id})} />{inp('Decision approved/rejected','decision',f,set)}<button onClick={()=>void run(()=>inventoryRmaService.approve(f.rma_id,f.decision||'approved',f.return_label_url,f.instructions,Number(f.valid_days||30)))} className="bg-emerald-600 text-white rounded-xl p-2">Approve/Reject</button><Msg msg={msg}/></div></Box>;
 if(type==='receive')return <Box title="استلام مرتجع"><div className="grid md:grid-cols-3 gap-3"><RmaLookup label="اختر RMA" value={f.rma_id} onChange={(id)=>set({rma_id:id})} /><WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} /><LocationLookup label="موقع الحجر" value={f.quarantine_location_id} onChange={(id)=>set({quarantine_location_id:id})} />{inp('Package Condition','package_condition',f,set)}{inp('Carrier','carrier_name',f,set)}{inp('Tracking','tracking_number',f,set)}<ReturnReceiveLinesBuilder value={f.lines} onChange={(json)=>set({lines:json})} /><button onClick={()=>void run(()=>inventoryReturnReceiptService.receive({...f,lines:parseLines(f.lines)}))} className="bg-indigo-600 text-white rounded-xl p-2">Receive</button>{inp('Receipt ID للScan','receipt_id',f,set)}{inp('Scanned Value','scanned_value',f,set)}<button onClick={()=>void run(()=>inventoryReturnReceiptService.scan(f.receipt_id,f.scanned_value,'barcode'))} className="bg-slate-700 text-white rounded-xl p-2">Scan</button><Msg msg={msg}/></div></Box>;
 if(type==='grade')return <Box title="تقييم A/B/C/D"><div className="grid md:grid-cols-3 gap-3"><ReturnReceiptLineLookup label="اختر سطر استلام المرتجع" value={f.receipt_line_id} onChange={(id)=>set({receipt_line_id:id})} />{inp('Grade A/B/C/D','condition_grade',f,set)}{inp('Defect Source','defect_source',f,set)}{inp('Defect Type','defect_type',f,set)}{inp('Original Value','estimated_original_value',f,set)}{inp('Recovered Value','estimated_recovered_value',f,set)}{area('Defect Description','defect_description',f,set)}<button onClick={()=>void run(()=>inventoryReturnConditionAssessmentService.grade({...f,estimated_original_value:Number(f.estimated_original_value||0),estimated_recovered_value:Number(f.estimated_recovered_value||0)}))} className="bg-indigo-600 text-white rounded-xl p-2">Grade</button><Msg msg={msg}/></div></Box>;
 if(type==='disposition')return <Box title="توجيه/إغلاق المسار"><div className="grid md:grid-cols-3 gap-3"><ReturnAssessmentLookup label="اختر تقييم المرتجع" value={f.assessment_id} onChange={(id)=>set({assessment_id:id})} />{inp('Disposition','disposition',f,set)}{inp('Target Warehouse ID','target_warehouse_id',f,set)}{inp('Target Location ID','target_location_id',f,set)}<SupplierLookup label="اختر المورد لـ RTV" value={f.supplier_id} onChange={(id)=>set({supplier_id:id})} /><button onClick={()=>void run(()=>inventoryReturnDispositionTaskService.route(f))} className="bg-indigo-600 text-white rounded-xl p-2">Route</button><ReturnDispositionTaskLookup label="اختر مهمة التوجيه" value={f.task_id} onChange={(id)=>set({task_id:id})} />{inp('Recovered Value','actual_recovered_value',f,set)}{inp('Credit Note','credit_note_number',f,set)}<button onClick={()=>void run(()=>inventoryReturnDispositionTaskService.complete(f.task_id,Number(f.actual_recovered_value||0),f.environmental_doc_url,f.credit_note_number))} className="bg-emerald-600 text-white rounded-xl p-2">Complete</button><Msg msg={msg}/></div></Box>;
 if(type==='production')return <Box title="إرجاع من الإنتاج"><div className="grid md:grid-cols-3 gap-3">{inp('Work Order ID','work_order_id',f,set)}<WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} />{inp('Return Location ID','return_location_id',f,set)}{inp('Reason Code','reason_code',f,set)}<ProductionReturnLinesBuilder value={f.lines} onChange={(json)=>set({lines:json})} /><button onClick={()=>void run(()=>inventoryProductionReturnService.createReturn({...f,lines:parseLines(f.lines)}))} className="bg-indigo-600 text-white rounded-xl p-2">Create PRR</button><ProductionReturnLookup label="اختر إرجاع الإنتاج" value={f.production_return_id} onChange={(id)=>set({production_return_id:id})} />{inp('Quality Status','quality_status',f,set)}<button onClick={()=>void run(()=>inventoryProductionReturnService.receive(f.production_return_id,f.quality_status,f.notes))} className="bg-emerald-600 text-white rounded-xl p-2">Receive/Post</button><Msg msg={msg}/></div></Box>;
 if(type==='notify')return <Box title="إرسال إشعار"><div className="grid md:grid-cols-3 gap-3"><RmaLookup label="اختر RMA" value={f.rma_id} onChange={(id)=>set({rma_id:id})} />{inp('Type','notification_type',f,set)}{inp('Channel','channel',f,set)}{inp('Recipient','recipient',f,set)}{area('Message','message',f,set)}<button onClick={()=>void run(()=>inventoryReturnCustomerNotificationService.send(f.rma_id,f.notification_type,f.channel,f.recipient,f.message||'Return update'))} className="bg-indigo-600 text-white rounded-xl p-2">Queue Notification</button><Msg msg={msg}/></div></Box>;
 if(type==='supplierReport')return <Box title="توليد تقرير RTV للمورد"><div className="grid md:grid-cols-3 gap-3"><SupplierLookup label="اختر المورد" value={f.supplier_id} onChange={(id)=>set({supplier_id:id})} />{inp('From YYYY-MM-DD','from',f,set)}{inp('To YYYY-MM-DD','to',f,set)}<button onClick={()=>void run(()=>inventorySupplierRtvReportService.generate(f.supplier_id,f.from,f.to))} className="bg-indigo-600 text-white rounded-xl p-2">Generate</button><Msg msg={msg}/></div></Box>;
 return null}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 p-2 rounded-xl">{msg}</div>:null}
export function ReturnsPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
