import { FormEvent, useEffect, useState } from 'react';
import { InventoryRecordTools } from '../shared/InventoryRecordTools';
import { PickListLookup, PickTaskLookup, PickWaveLookup } from '../shared/InventoryLookups';
import { PickOrderIdsBuilder, PickOrderLinesBuilder, TagValuesBuilder } from '../shared/InventoryLineBuilders';
import {
  inventoryPickingAnalyticsService,
  inventoryPickingTechnologyEventService,
  inventoryPickExceptionService,
  inventoryPickOrderService,
  inventoryPickScanService,
  inventoryPickSortingSessionService,
  inventoryPickTaskService,
  inventoryPickWaveService,
  inventoryPickZoneHandoffService,
} from '../../../../services/sdk';

type Row = Record<string, unknown>;
type Form = Record<string, string>;
type Config = { title: string; subtitle: string; load: () => Promise<Row[]>; columns: { key: string; label: string }[]; action?: string };

const configs: Record<string, Config> = {
  orders: { title: 'أوامر السحب', subtitle: 'Production / Sales / Replenishment / Transfer', load: () => inventoryPickOrderService.findAll({ orderBy: 'created_at', ascending: false, limit: 100 }) as unknown as Promise<Row[]>, action: 'order', columns: [{ key: 'pick_order_number', label: 'الأمر' }, { key: 'source_type', label: 'المصدر' }, { key: 'picking_method', label: 'الطريقة' }, { key: 'priority', label: 'الأولوية' }, { key: 'critical_ratio', label: 'CR' }, { key: 'status', label: 'الحالة' }] },
  tasks: { title: 'مهام السحب', subtitle: 'قائمة مهام مرتبة بالمسار الأمثل', load: () => inventoryPickingAnalyticsService.taskQueue(), action: 'scan', columns: [{ key: 'task_number', label: 'المهمة' }, { key: 'item_code', label: 'الصنف' }, { key: 'full_location_code', label: 'الموقع' }, { key: 'required_qty', label: 'الكمية' }, { key: 'priority', label: 'الأولوية' }, { key: 'status', label: 'الحالة' }] },
  route: { title: 'خريطة مسار السحب', subtitle: 'Route Optimization: S-Shape / Largest Gap / Combined', load: () => inventoryPickingAnalyticsService.routeMap(), columns: [{ key: 'task_number', label: 'المهمة' }, { key: 'sequence_no', label: 'التسلسل' }, { key: 'route_algorithm', label: 'الخوارزمية' }, { key: 'full_location_code', label: 'الموقع' }, { key: 'item_code', label: 'الصنف' }, { key: 'required_qty', label: 'الكمية' }] },
  waves: { title: 'Wave Management', subtitle: 'إطلاق وإدارة موجات السحب', load: () => inventoryPickingAnalyticsService.waveDashboard(), action: 'wave', columns: [{ key: 'wave_number', label: 'الموجة' }, { key: 'wave_type', label: 'النوع' }, { key: 'order_count', label: 'الأوامر' }, { key: 'open_tasks', label: 'مهام مفتوحة' }, { key: 'picked_tasks', label: 'منجزة' }, { key: 'status', label: 'الحالة' }] },
  exceptions: { title: 'استثناءات السحب', subtitle: 'Short Pick / Location Empty / Wrong Item / Wrong Lot', load: () => inventoryPickExceptionService.findAll({ orderBy: 'created_at', ascending: false, limit: 100 }) as unknown as Promise<Row[]>, action: 'exception', columns: [{ key: 'exception_number', label: 'الاستثناء' }, { key: 'exception_type', label: 'النوع' }, { key: 'expected_qty', label: 'المطلوب' }, { key: 'actual_qty', label: 'الفعلي' }, { key: 'status', label: 'الحالة' }] },
  scans: { title: 'Scan-to-Confirm', subtitle: 'سجل مسح الموقع والصنف وLPN', load: () => inventoryPickScanService.findAll({ orderBy: 'scanned_at', ascending: false, limit: 100 }) as unknown as Promise<Row[]>, columns: [{ key: 'scanned_value', label: 'القيمة' }, { key: 'scan_type', label: 'النوع' }, { key: 'scan_result', label: 'النتيجة' }, { key: 'result_message', label: 'الرسالة' }] },
  voice: { title: 'Voice Picking', subtitle: 'تأكيد السحب بالصوت عبر check digit', load: () => inventoryPickingTechnologyEventService.findAll({ orderBy: 'created_at', ascending: false, limit: 100 }) as unknown as Promise<Row[]>, action: 'voice', columns: [{ key: 'technology_type', label: 'التقنية' }, { key: 'event_type', label: 'الحدث' }, { key: 'created_at', label: 'التاريخ' }] },
  light: { title: 'Pick-to-Light', subtitle: 'تشغيل إشارة ضوئية للموقع المطلوب', load: () => inventoryPickingAnalyticsService.technologyEventsReport(), action: 'light', columns: [{ key: 'technology_type', label: 'التقنية' }, { key: 'event_type', label: 'الحدث' }, { key: 'event_count', label: 'العدد' }] },
  rfid: { title: 'RFID Picking', subtitle: 'استقبال أحداث RFID للتأكيد الجماعي', load: () => inventoryPickingAnalyticsService.technologyEventsReport(), action: 'rfid', columns: [{ key: 'technology_type', label: 'التقنية' }, { key: 'event_type', label: 'الحدث' }, { key: 'event_count', label: 'العدد' }] },
  sorting: { title: 'Batch/Cluster Sorting', subtitle: 'محطة فرز للحاويات بعد Batch/Cluster Picking', load: () => inventoryPickingAnalyticsService.sortingDashboard(), action: 'sorting', columns: [{ key: 'sorting_number', label: 'الجلسة' }, { key: 'station_code', label: 'المحطة' }, { key: 'line_count', label: 'البنود' }, { key: 'sorted_count', label: 'مفرز' }, { key: 'status', label: 'الحالة' }] },
  handoffs: { title: 'Zone Handoffs', subtitle: 'تسليم أوامر السحب بين المناطق في Zone Picking', load: () => inventoryPickingAnalyticsService.handoffQueue(), action: 'handoff', columns: [{ key: 'handoff_number', label: 'التسليم' }, { key: 'task_number', label: 'المهمة' }, { key: 'item_code', label: 'الصنف' }, { key: 'status', label: 'الحالة' }] },
  productivity: { title: 'إنتاجية السحب', subtitle: 'معدل السحب والدقة لكل موظف', load: () => inventoryPickingAnalyticsService.productivity(), columns: [{ key: 'employee_id', label: 'الموظف' }, { key: 'picked_tasks', label: 'مهام' }, { key: 'picked_qty', label: 'كمية' }, { key: 'avg_minutes_per_task', label: 'دقائق/مهمة' }] },
  kpis: { title: 'مؤشرات السحب', subtitle: 'Pick Accuracy / Short Pick / Cycle Time / On-time', load: () => inventoryPickingAnalyticsService.kpis(), columns: [{ key: 'total_pick_orders', label: 'الأوامر' }, { key: 'processed_orders', label: 'معالجة' }, { key: 'pick_accuracy_percent', label: 'الدقة %' }, { key: 'short_pick_rate_percent', label: 'Short %' }, { key: 'avg_order_cycle_hours', label: 'Cycle Hours' }, { key: 'on_time_orders', label: 'On-time' }] },
};

function input(label: string, name: string, form: Form, set: (p: Form) => void, required = false) {
  return <label className="text-xs font-bold text-slate-600 space-y-1"><span>{label}</span><input required={required} value={form[name] || ''} onChange={(e) => set({ [name]: e.target.value })} className="w-full border rounded-xl px-3 py-2 text-sm" /></label>;
}
function Box({ title, children }: { title: string; children: React.ReactNode }) { return <div className="bg-white border rounded-2xl p-4 shadow-sm"><h3 className="font-black mb-3">{title}</h3>{children}</div>; }
function Submit({ busy, label='تنفيذ' }: { busy: boolean; label?: string }) { return <button disabled={busy} className="bg-indigo-600 text-white rounded-xl px-3 py-2 font-bold text-sm">{busy ? '...' : label}</button>; }
function Msg({ msg }: { msg: string }) { return msg ? <div className="md:col-span-3 text-xs bg-slate-100 p-2 rounded-xl">{msg}</div> : null; }

function Action({ type, onDone }: { type: string; onDone: () => void }) {
  const [form, setF] = useState<Form>({ lines_json: '[{"item_id":"","requested_qty":1,"uom":"PCS"}]', pick_order_ids: '[]', tag_values: '[]', picking_method: 'discrete', source_type: 'manual', exception_type: 'short_pick' });
  const [msg, setMsg] = useState(''); const [busy, setBusy] = useState(false);
  const set = (p: Form) => setF((x) => ({ ...x, ...p }));
  const run = async (fn: () => Promise<unknown>) => { setBusy(true); try { const r = await fn(); setMsg('تم: ' + String(r || 'ok')); onDone(); } catch (e) { setMsg(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } };

  if (type === 'order') return <Box title="إنشاء أمر سحب"><form onSubmit={(e: FormEvent) => { e.preventDefault(); void run(() => inventoryPickOrderService.createFull({ ...form, lines: JSON.parse(form.lines_json || '[]'), critical_ratio: form.critical_ratio ? Number(form.critical_ratio) : null })); }} className="grid md:grid-cols-3 gap-3">{input('Source Type', 'source_type', form, set, true)}{input('Picking Method', 'picking_method', form, set)}{input('Priority', 'priority', form, set)}{input('Critical Ratio', 'critical_ratio', form, set)}<PickOrderLinesBuilder value={form.lines_json} onChange={(json)=>set({lines_json:json})} /><Submit busy={busy} label="حفظ" /><Msg msg={msg} /></form></Box>;
  if (type === 'scan') return <Box title="تأكيد السحب بالمسح"><div className="grid md:grid-cols-3 gap-3"><PickTaskLookup label="اختر مهمة السحب" value={form.pick_task_id} onChange={(id)=>set({pick_task_id:id})} required />{input('Location Barcode', 'location_barcode', form, set)}{input('Item Barcode', 'item_barcode', form, set)}{input('LPN Barcode', 'lpn_barcode', form, set)}{input('Quantity', 'quantity', form, set, true)}<button disabled={busy} onClick={() => void run(() => inventoryPickTaskService.confirmScan({ ...form, quantity: Number(form.quantity || 0) }))} className="bg-indigo-600 text-white rounded-xl px-3 py-2 font-bold text-sm">Confirm</button><Msg msg={msg} /></div></Box>;
  if (type === 'voice') return <Box title="Voice Picking"><div className="grid md:grid-cols-3 gap-3"><PickTaskLookup label="اختر مهمة السحب" value={form.pick_task_id} onChange={(id)=>set({pick_task_id:id})} required />{input('Check Digit', 'check_digit', form, set, true)}{input('Quantity', 'quantity', form, set, true)}<button disabled={busy} onClick={() => void run(() => inventoryPickTaskService.confirmVoice(form.pick_task_id, form.check_digit, Number(form.quantity || 0)))} className="bg-indigo-600 text-white rounded-xl px-3 py-2 font-bold text-sm">Voice Confirm</button><Msg msg={msg} /></div></Box>;
  if (type === 'light') return <Box title="Pick-to-Light"><div className="grid md:grid-cols-3 gap-3"><PickTaskLookup label="اختر مهمة السحب" value={form.pick_task_id} onChange={(id)=>set({pick_task_id:id})} required /><button disabled={busy} onClick={() => void run(() => inventoryPickTaskService.triggerPickToLight(form.pick_task_id))} className="bg-indigo-600 text-white rounded-xl px-3 py-2 font-bold text-sm">Trigger Light</button><Msg msg={msg} /></div></Box>;
  if (type === 'rfid') return <Box title="RFID Event"><div className="grid md:grid-cols-3 gap-3"><PickTaskLookup label="اختر مهمة السحب" value={form.pick_task_id} onChange={(id)=>set({pick_task_id:id})} required /><TagValuesBuilder value={form.tag_values} onChange={(json)=>set({tag_values:json})} />{input('Quantity', 'quantity', form, set, true)}<button disabled={busy} onClick={() => void run(() => inventoryPickTaskService.ingestRfid(form.pick_task_id, JSON.parse(form.tag_values || '[]'), Number(form.quantity || 0)))} className="bg-indigo-600 text-white rounded-xl px-3 py-2 font-bold text-sm">Ingest RFID</button><Msg msg={msg} /></div></Box>;
  if (type === 'wave') return <Box title="إنشاء/إطلاق موجة"><div className="grid md:grid-cols-3 gap-3">{input('Wave Type', 'wave_type', form, set)}<PickOrderIdsBuilder value={form.pick_order_ids} onChange={(json)=>set({pick_order_ids:json})} /><button disabled={busy} onClick={() => void run(() => inventoryPickWaveService.createWave({ ...form, pick_order_ids: JSON.parse(form.pick_order_ids || '[]') }))} className="bg-indigo-600 text-white rounded-xl px-3 py-2 font-bold text-sm">Create Wave</button><PickWaveLookup label="موجة للإطلاق" value={form.wave_id} onChange={(id)=>set({wave_id:id})} /><button disabled={busy || !form.wave_id} onClick={() => void run(() => inventoryPickWaveService.release(form.wave_id))} className="bg-emerald-600 text-white rounded-xl px-3 py-2 font-bold text-sm">Release</button><Msg msg={msg} /></div></Box>;
  if (type === 'exception') return <Box title="تسجيل استثناء"><div className="grid md:grid-cols-3 gap-3"><PickTaskLookup label="اختر مهمة السحب" value={form.pick_task_id} onChange={(id)=>set({pick_task_id:id})} required />{input('Exception Type', 'exception_type', form, set, true)}{input('Actual Qty', 'actual_qty', form, set)}{input('Description', 'description', form, set)}<button disabled={busy} onClick={() => void run(() => inventoryPickExceptionService.report({ ...form, actual_qty: form.actual_qty ? Number(form.actual_qty) : null }))} className="bg-red-600 text-white rounded-xl px-3 py-2 font-bold text-sm">Report</button><Msg msg={msg} /></div></Box>;
  if (type === 'sorting') return <Box title="محطة الفرز"><div className="grid md:grid-cols-3 gap-3"><PickListLookup label="اختر قائمة السحب" value={form.pick_list_id} onChange={(id)=>set({pick_list_id:id})} required />{input('Station Code', 'station_code', form, set)}<button disabled={busy} onClick={() => void run(() => inventoryPickSortingSessionService.createSession(form.pick_list_id, form.station_code))} className="bg-indigo-600 text-white rounded-xl px-3 py-2 font-bold text-sm">Create Sorting</button>{input('Sorting Line ID', 'sorting_line_id', form, set)}<button disabled={busy || !form.sorting_line_id} onClick={() => void run(() => inventoryPickSortingSessionService.confirmLine(form.sorting_line_id, form.container_id || undefined))} className="bg-emerald-600 text-white rounded-xl px-3 py-2 font-bold text-sm">Confirm Line</button><Msg msg={msg} /></div></Box>;
  if (type === 'handoff') return <Box title="Zone Handoff"><div className="grid md:grid-cols-3 gap-3"><PickTaskLookup label="اختر مهمة السحب" value={form.pick_task_id} onChange={(id)=>set({pick_task_id:id})} required />{input('From Zone ID', 'from_zone_id', form, set)}{input('To Zone ID', 'to_zone_id', form, set)}<button disabled={busy} onClick={() => void run(() => inventoryPickZoneHandoffService.createHandoff(form))} className="bg-indigo-600 text-white rounded-xl px-3 py-2 font-bold text-sm">Create Handoff</button>{input('Handoff ID', 'handoff_id', form, set)}<button disabled={busy || !form.handoff_id} onClick={() => void run(() => inventoryPickZoneHandoffService.complete(form.handoff_id))} className="bg-emerald-600 text-white rounded-xl px-3 py-2 font-bold text-sm">Complete</button><Msg msg={msg} /></div></Box>;
  return null;
}

export function PickingPage({ type }: { type: keyof typeof configs }) {
  const cfg = configs[type]; const [rows, setRows] = useState<Row[]>([]); const [refresh, setRefresh] = useState(0);
  useEffect(() => { cfg.load().then(setRows).catch(() => setRows([])); }, [type, refresh]);
  return <div className="space-y-5" dir="rtl"><div><h1 className="text-3xl font-black">{cfg.title}</h1><p className="text-slate-500">{cfg.subtitle}</p></div>{cfg.action && <Action type={cfg.action} onDone={() => setRefresh(x => x + 1)} />}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{cfg.columns.map(c => <th className="p-3 text-right" key={c.key}>{c.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((r, i) => <tr className="border-t" key={String(r.id ?? i)}>{cfg.columns.map(c => <td className="p-3" key={c.key}>{String(r[c.key] ?? '—')}</td>)}<td className="p-3"><InventoryRecordTools row={r}/></td></tr>)}{!rows.length && <tr><td colSpan={cfg.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>;
}
