import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { MrpUnitNav } from '../shared/MrpUnitNav';
import { ItemLookup } from '../../inventory/shared/InventoryLookups';
import { InventoryRecordTools } from '../../inventory/shared/InventoryRecordTools';
import { mrpActualCostingService, mrpCostElementService, mrpCostingAnalyticsService, mrpCostingProfileService, mrpCostPostingService, mrpCostRollupService, mrpStandardCostService, mrpWipCostService } from '../../../../services/sdk';
import { supabase } from '../../../../services/supabase/supabase';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Option={id:string;code:string;name?:string;meta?:string};
type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
const unitRoutes=[['cost-elements','عناصر التكلفة'],['profiles','Profiles'],['standard-costs','التكاليف القياسية'],['rollup','BOM/Routing Rollup'],['work-order-costs','تكلفة أمر العمل'],['variances','الفروقات'],['wip','WIP'],['finished-goods','Finished Goods'],['postings','قيود مالية مسودة'],['reports','التقارير']];
function input(l:string,n:string,f:Form,set:(p:Form)=>void,type='text'){return <label className="text-xs font-bold text-slate-600"><span>{l}</span><input type={type} value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function select(l:string,n:string,f:Form,set:(p:Form)=>void,opts:string[]){return <label className="text-xs font-bold text-slate-600"><span>{l}</span><select value={f[n]||opts[0]} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1 bg-white">{opts.map(o=><option key={o}>{o}</option>)}</select></label>}
function Box({title,children}:{title:string;children:ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 rounded-xl p-2 whitespace-pre-wrap">{msg}</div>:null}
function useOptions(table:string,cols:string,map:(r:Row)=>Option){const[rows,setRows]=useState<Option[]>([]);const[loading,setLoading]=useState(false);const[q,setQ]=useState('');useEffect(()=>{let ok=true;const load=async()=>{setLoading(true);try{const db=supabase as unknown as {from:(t:string)=>{select:(c:string)=>{limit:(n:number)=>Promise<{data:unknown[]|null}>}}};const{data}=await db.from(table).select(cols).limit(500);if(ok)setRows(((data||[]) as Row[]).map(map))}finally{if(ok)setLoading(false)}};void load();return()=>{ok=false}},[table,cols]);const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return(!s?rows:rows.filter(o=>`${o.code} ${o.name||''} ${o.meta||''}`.toLowerCase().includes(s))).slice(0,80)},[rows,q]);return{filtered,loading,q,setQ}}
function Lookup({label,table,cols,map,value,onChange}:{label:string;table:string;cols:string;map:(r:Row)=>Option;value?:string;onChange:(id:string)=>void}){const{filtered,loading,q,setQ}=useOptions(table,cols,map);return <label className="text-xs font-bold text-slate-600 space-y-1 block"><span>{label}</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث..." className="w-full border rounded-xl p-2"/><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 bg-white"><option value="">{loading?'جاري التحميل...':'-- اختر --'}</option>{filtered.map(o=><option key={o.id} value={o.id}>{o.code}{o.name?` — ${o.name}`:''}{o.meta?` — ${o.meta}`:''}</option>)}</select></label>}
const PlantLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="المصنع" table="manufacturing_plants" cols="id,plant_code,name_ar,status" map={r=>({id:String(r.id),code:String(r.plant_code||''),name:String(r.name_ar||''),meta:String(r.status||'')})}{...p}/>;
const ProfileLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="Costing Profile" table="mrp_costing_profiles" cols="id,profile_code,name_ar,costing_method" map={r=>({id:String(r.id),code:String(r.profile_code||''),name:String(r.name_ar||''),meta:String(r.costing_method||'')})}{...p}/>;
const StdVersionLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="Standard Cost Version" table="mrp_standard_cost_versions" cols="id,version_code,name_ar,status" map={r=>({id:String(r.id),code:String(r.version_code||''),name:String(r.name_ar||''),meta:String(r.status||'')})}{...p}/>;
const BomVersionLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="BOM Version" table="mrp_bom_versions" cols="id,version_no,status" map={r=>({id:String(r.id),code:String(r.version_no||''),name:String(r.status||'')})}{...p}/>;
const RoutingLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="Routing" table="routing_headers" cols="id,routing_code,version_no,status" map={r=>({id:String(r.id),code:String(r.routing_code||''),name:String(r.version_no||''),meta:String(r.status||'')})}{...p}/>;
const WorkOrderLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="أمر العمل" table="mrp_work_orders" cols="id,work_order_number,status,quantity_completed" map={r=>({id:String(r.id),code:String(r.work_order_number||''),name:String(r.status||''),meta:String(r.quantity_completed||'')})}{...p}/>;
const PostingLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="Posting Draft" table="mrp_cost_posting_drafts" cols="id,posting_number,status,amount" map={r=>({id:String(r.id),code:String(r.posting_number||''),name:String(r.status||''),meta:String(r.amount||'')})}{...p}/>;
const CostElementLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="Cost Element" table="mrp_cost_element_lookup" cols="id,element_code,name_ar,status" map={r=>({id:String(r.id),code:String(r.element_code||''),name:String(r.name_ar||''),meta:String(r.status||'')})}{...p}/>;
const CostVarianceLookup=(p:{value?:string;onChange:(id:string)=>void})=><Lookup label="Cost Variance" table="mrp_cost_variance_review_queue" cols="id,variance_type,severity,status,variance_amount" map={r=>({id:String(r.id),code:String(r.variance_type||''),name:String(r.severity||''),meta:String(r.variance_amount||'')})}{...p}/>;
const cfgs:Record<string,Config>={
 dashboard:{title:'تكاليف التصنيع',subtitle:'Standard/Actual Costing، Rollup، فروقات، WIP، FG، وقيود مالية مسودة.',load:()=>mrpCostingAnalyticsService.dashboard() as Promise<Row[]>,columns:[{key:'effective_standard_versions',label:'إصدارات فعالة'},{key:'costed_work_orders',label:'أوامر محسوبة'},{key:'total_variance',label:'إجمالي الفروقات'},{key:'open_postings',label:'قيود مفتوحة'}]},
 elements:{title:'عناصر التكلفة',subtitle:'Material/Labor/Machine/Overhead/Quality/Maintenance/Scrap/Rework.',load:()=>mrpCostElementService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'element',columns:[{key:'element_code',label:'الكود'},{key:'name_ar',label:'العنصر'},{key:'cost_category',label:'الفئة'},{key:'finance_account_code',label:'حساب مالي'},{key:'status',label:'الحالة'}]},
 profiles:{title:'Costing Profiles',subtitle:'طريقة التكلفة والعملة وقاعدة التحميل لكل مصنع.',load:()=>mrpCostingProfileService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'profile',columns:[{key:'profile_code',label:'الكود'},{key:'name_ar',label:'الاسم'},{key:'costing_method',label:'الطريقة'},{key:'currency_code',label:'العملة'},{key:'overhead_method',label:'Overhead'}]},
 standard:{title:'Standard Costs',subtitle:'إصدارات التكلفة القياسية وتكاليف الأصناف.',load:()=>mrpStandardCostService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'standard',columns:[{key:'version_code',label:'الإصدار'},{key:'name_ar',label:'الاسم'},{key:'status',label:'الحالة'},{key:'effective_from',label:'فعال من'}]},
 rollup:{title:'BOM/Routing Cost Rollup',subtitle:'احتساب تكلفة المنتج القياسية من BOM وRouting.',load:()=>mrpCostingAnalyticsService.rollups() as Promise<Row[]>,action:'rollup',columns:[{key:'run_number',label:'التشغيل'},{key:'item_code',label:'الصنف'},{key:'material_cost',label:'مواد'},{key:'labor_cost',label:'عمالة'},{key:'machine_cost',label:'آلة'},{key:'overhead_cost',label:'تحميل'},{key:'total_unit_cost',label:'الإجمالي'}]},
 workOrders:{title:'Actual Work Order Costing',subtitle:'جمع التكلفة الفعلية من MES/عمالة/آلة/صيانة/خردة.',load:()=>mrpCostingAnalyticsService.workOrders() as Promise<Row[]>,action:'actual',columns:[{key:'work_order_number',label:'أمر العمل'},{key:'item_code',label:'الصنف'},{key:'good_qty',label:'جيد'},{key:'total_actual_cost',label:'فعلي'},{key:'actual_unit_cost',label:'تكلفة/وحدة'},{key:'total_variance_cost',label:'فرق'}]},
 variances:{title:'Variance Analysis',subtitle:'Material/Labor/Machine/Overhead/Scrap/Rework/Maintenance variances.',load:()=>mrpCostingAnalyticsService.variances() as Promise<Row[]>,action:'variance',columns:[{key:'work_order_number',label:'أمر العمل'},{key:'variance_type',label:'نوع الفرق'},{key:'standard_amount',label:'قياسي'},{key:'actual_amount',label:'فعلي'},{key:'variance_amount',label:'الفرق'},{key:'severity',label:'الشدة'}]},
 wip:{title:'WIP Valuation',subtitle:'دفتر تكلفة WIP debit/credit لأوامر العمل.',load:()=>mrpCostingAnalyticsService.wip() as Promise<Row[]>,action:'wip',columns:[{key:'work_order_number',label:'أمر العمل'},{key:'wip_balance',label:'رصيد WIP'},{key:'last_posted_at',label:'آخر قيد'}]},
 fg:{title:'Finished Goods Valuation',subtitle:'تحويل تكلفة WIP إلى Finished Goods عند الاكتمال.',load:()=>mrpCostingAnalyticsService.fg() as Promise<Row[]>,action:'fg',columns:[{key:'fg_cost_number',label:'FG Cost'},{key:'work_order_number',label:'أمر العمل'},{key:'item_code',label:'الصنف'},{key:'good_qty',label:'الكمية'},{key:'unit_cost',label:'تكلفة الوحدة'}]},
 postings:{title:'Cost Posting Drafts',subtitle:'مسودات ترحيل مالية للمراجعة قبل القيود النهائية.',load:()=>mrpCostingAnalyticsService.postings() as Promise<Row[]>,action:'posting',columns:[{key:'posting_number',label:'المسودة'},{key:'source_type',label:'المصدر'},{key:'description',label:'الوصف'},{key:'amount',label:'المبلغ'},{key:'status',label:'الحالة'}]},
 reports:{title:'تقارير تكلفة التصنيع',subtitle:'Cost per unit، فروقات، Scrap/Rework، Maintenance absorbed.',load:()=>mrpCostingAnalyticsService.kpis() as Promise<Row[]>,columns:[{key:'avg_actual_unit_cost',label:'متوسط تكلفة الوحدة'},{key:'avg_variance',label:'متوسط الفرق'},{key:'scrap_rework_cost',label:'خردة/Rework'},{key:'maintenance_absorbed_cost',label:'صيانة محملة'}]},
};
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({cost_category:'material',costing_method:'standard',currency_code:'IQD',overhead_method:'work_center_rate',overhead_rate:'0',material_cost:'0',labor_cost:'0',machine_cost:'0',overhead_cost:'0',rollup_qty:'1',entry_type:'material_issue',debit_amount:'0',credit_amount:'0',source_type:'work_order_cost',amount:'0'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r??'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='element')return <Box title="عنصر تكلفة"><div className="grid md:grid-cols-3 gap-3">{input('Code اختياري','element_code',f,set)}{input('الاسم','name_ar',f,set)}{select('Category','cost_category',f,set,['material','labor','machine','overhead','subcontract','quality','maintenance','scrap','rework'])}{input('Finance Account Code','finance_account_code',f,set)}<button onClick={()=>void run(()=>mrpCostElementService.upsert(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ</button><CostElementLookup value={f.cost_element_id} onChange={id=>set({cost_element_id:id})}/>{select('Status','element_status',f,set,['active','inactive','archived'])}{input('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpCostElementService.updateStatus(f.cost_element_id,f.element_status,f.reason))} className="bg-slate-700 text-white rounded-xl p-2">تحديث الحالة</button><Msg msg={msg}/></div></Box>;
 if(type==='profile')return <Box title="Costing Profile"><div className="grid md:grid-cols-3 gap-3">{input('Code اختياري','profile_code',f,set)}{input('الاسم','name_ar',f,set)}<PlantLookup value={f.plant_id} onChange={id=>set({plant_id:id})}/>{select('Method','costing_method',f,set,['standard','actual','wac','hybrid'])}{input('Currency','currency_code',f,set)}{select('Overhead Method','overhead_method',f,set,['work_center_rate','labor_percent','machine_hour','flat_percent','manual'])}{input('Overhead Rate','overhead_rate',f,set,'number')}<button onClick={()=>void run(()=>mrpCostingProfileService.upsert(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ</button><ProfileLookup value={f.profile_id} onChange={id=>set({profile_id:id})}/>{select('Status','profile_status',f,set,['draft','active','inactive','archived'])}{input('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpCostingProfileService.updateStatus(f.profile_id,f.profile_status,f.reason))} className="bg-slate-700 text-white rounded-xl p-2">تحديث Profile</button><Msg msg={msg}/></div></Box>;
 if(type==='standard')return <Box title="Standard Cost Version / Item Cost"><div className="grid md:grid-cols-3 gap-3">{input('Version Code اختياري','version_code',f,set)}{input('Name','name_ar',f,set)}<ProfileLookup value={f.profile_id} onChange={id=>set({profile_id:id})}/>{input('Effective From','effective_from',f,set,'date')}<button onClick={()=>void run(()=>mrpStandardCostService.createVersion(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء إصدار</button><StdVersionLookup value={f.standard_cost_version_id} onChange={id=>set({standard_cost_version_id:id})}/><ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})}/>{input('Material','material_cost',f,set,'number')}{input('Labor','labor_cost',f,set,'number')}{input('Machine','machine_cost',f,set,'number')}{input('Overhead','overhead_cost',f,set,'number')}<button onClick={()=>void run(()=>mrpStandardCostService.upsertItemCost(f))} className="bg-slate-700 text-white rounded-xl p-2">حفظ تكلفة صنف</button><button onClick={()=>void run(()=>mrpStandardCostService.approve(f.standard_cost_version_id))} className="bg-emerald-600 text-white rounded-xl p-2">اعتماد الإصدار</button>{select('Version Status','version_status',f,set,['approved','effective','superseded','archived'])}{input('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpStandardCostService.updateStatus(f.standard_cost_version_id,f.version_status,f.reason))} className="bg-slate-700 text-white rounded-xl p-2">تحديث حالة الإصدار</button><Msg msg={msg}/></div></Box>;
 if(type==='rollup')return <Box title="Rollup"><div className="grid md:grid-cols-3 gap-3"><StdVersionLookup value={f.standard_cost_version_id} onChange={id=>set({standard_cost_version_id:id})}/><ItemLookup label="المنتج" value={f.item_id} onChange={id=>set({item_id:id})}/><BomVersionLookup value={f.bom_version_id} onChange={id=>set({bom_version_id:id})}/><RoutingLookup value={f.routing_id} onChange={id=>set({routing_id:id})}/>{input('Qty','rollup_qty',f,set,'number')}<button onClick={()=>void run(()=>mrpCostRollupService.run(f))} className="bg-indigo-600 text-white rounded-xl p-2">تشغيل Rollup</button><Msg msg={msg}/></div></Box>;
 if(type==='actual')return <Box title="Actual Costing"><div className="grid md:grid-cols-3 gap-3"><WorkOrderLookup value={f.work_order_id} onChange={id=>set({work_order_id:id})}/><StdVersionLookup value={f.standard_cost_version_id} onChange={id=>set({standard_cost_version_id:id})}/><button onClick={()=>void run(()=>mrpActualCostingService.runWorkOrder(f))} className="bg-indigo-600 text-white rounded-xl p-2">احسب التكلفة الفعلية</button><Msg msg={msg}/></div></Box>;
 if(type==='variance')return <Box title="احتساب/مراجعة الفروقات"><div className="grid md:grid-cols-3 gap-3"><WorkOrderLookup value={f.work_order_id} onChange={id=>set({work_order_id:id})}/><button onClick={()=>void run(()=>mrpActualCostingService.variances(f.work_order_id))} className="bg-indigo-600 text-white rounded-xl p-2">احسب الفروقات</button><CostVarianceLookup value={f.variance_id} onChange={id=>set({variance_id:id})}/>{select('Status','variance_status',f,set,['reviewed','resolved','dismissed'])}{input('Resolution','resolution_notes',f,set)}<button onClick={()=>void run(()=>mrpActualCostingService.reviewVariance(f))} className="bg-emerald-600 text-white rounded-xl p-2">مراجعة/إغلاق الفرق</button><Msg msg={msg}/></div></Box>;
 if(type==='wip')return <Box title="قيد WIP"><div className="grid md:grid-cols-3 gap-3"><WorkOrderLookup value={f.work_order_id} onChange={id=>set({work_order_id:id})}/>{select('Entry Type','entry_type',f,set,['material_issue','labor_absorb','machine_absorb','overhead_absorb','maintenance_absorb','scrap','rework','fg_receipt','adjustment'])}{input('Debit','debit_amount',f,set,'number')}{input('Credit','credit_amount',f,set,'number')}<button onClick={()=>void run(()=>mrpWipCostService.post(f))} className="bg-indigo-600 text-white rounded-xl p-2">حفظ قيد WIP</button><Msg msg={msg}/></div></Box>;
 if(type==='fg')return <Box title="تقييم Finished Goods"><div className="grid md:grid-cols-3 gap-3"><WorkOrderLookup value={f.work_order_id} onChange={id=>set({work_order_id:id})}/>{select('Method','valuation_method',f,set,['actual','standard','hybrid'])}<button onClick={()=>void run(()=>mrpWipCostService.valueFinishedGoods(f))} className="bg-indigo-600 text-white rounded-xl p-2">تقييم FG</button><Msg msg={msg}/></div></Box>;
 if(type==='posting')return <Box title="Posting Draft"><div className="grid md:grid-cols-3 gap-3">{select('Source Type','source_type',f,set,['work_order_cost','wip_ledger','fg_valuation','variance','manual_adjustment'])}{input('Source ID','source_id',f,set)}{input('Description','description',f,set)}{input('Amount','amount',f,set,'number')}{input('Debit Account','debit_account_code',f,set)}{input('Credit Account','credit_account_code',f,set)}<button onClick={()=>void run(()=>mrpCostPostingService.createDraft(f))} className="bg-indigo-600 text-white rounded-xl p-2">إنشاء مسودة</button><PostingLookup value={f.posting_id} onChange={id=>set({posting_id:id})}/><button onClick={()=>void run(()=>mrpCostPostingService.review(f.posting_id))} className="bg-slate-700 text-white rounded-xl p-2">مراجعة</button><button onClick={()=>void run(()=>mrpCostPostingService.post(f.posting_id))} className="bg-emerald-600 text-white rounded-xl p-2">تعليم كمرحل</button>{input('Cancel Reason','cancel_reason',f,set)}<button onClick={()=>void run(()=>mrpCostPostingService.cancel(f.posting_id,f.cancel_reason))} className="bg-red-600 text-white rounded-xl p-2">إلغاء المسودة</button><Msg msg={msg}/></div></Box>;
 return null}
export function MrpCostingPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[refresh,setRefresh]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,refresh]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{type==='dashboard'&&<MrpUnitNav unit="costing" />}{c.action&&<Action type={c.action} onDone={()=>setRefresh(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(col=><th key={col.key} className="p-3 text-right">{col.label}</th>)}<th className="p-3 text-right">أدوات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(col=><td key={col.key} className="p-3 max-w-[220px] truncate">{String(row[col.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات حتى الآن</td></tr>}</tbody></table></div></div>}
