import { useEffect, useState } from 'react';
import { ItemLookup, LocationLookup, WarehouseLookup } from '../../inventory/shared/InventoryLookups';
import { InventoryRecordTools } from '../../inventory/shared/InventoryRecordTools';
import { mrpLookupService, mrpInventoryAnalyticsService, mrpInventoryOptimizationService, mrpInventoryValuationPolicyService, mrpLotTraceService, mrpWipLocationService, mrpWipMovementService, mrpWorkOrderMaterialService } from '../../../../services/sdk';
import { MrpUnitNav } from '../shared/MrpUnitNav';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void,type='text'){return <label className="text-xs font-bold"><span>{l}</span><input type={type} value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function select(l:string,n:string,f:Form,set:(p:Form)=>void,ops:string[]){return <label className="text-xs font-bold"><span>{l}</span><select value={f[n]||ops[0]} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1 bg-white">{ops.map(o=><option key={o}>{o}</option>)}</select></label>}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 rounded-xl p-2">{msg}</div>:null}
function WorkOrderLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('workOrder').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>Work Order</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.work_order_number)} — {String(r.status)}</option>)}</select></label>}
function WorkCenterLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('workCenter').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>Work Center</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.work_center_code)} — {String(r.name_ar)} — {String(r.status)}</option>)}</select></label>}
function WipLocationLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('wipLocation').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>WIP Location</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.wip_code)} — {String(r.name_ar)} — {String(r.status)}</option>)}</select></label>}
function WoMaterialLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('workOrderMaterialDetailed').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>WO Material</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.id).slice(0,8)} — {String(r.issued_qty||0)}/{String(r.required_qty||0)} — {String(r.status)}</option>)}</select></label>}
function ValuationPolicyLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('valuationPolicy').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>Valuation Policy</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.valuation_method)} — {String(r.is_active)} — {String(r.id).slice(0,8)}</option>)}</select></label>}
function WoOperationLookup({value,onChange,label='Operation'}:{value?:string;onChange:(id:string)=>void;label?:string}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('workOrderOperation').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>{label}</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.sequence_no)} — {String(r.operation_name)} — {String(r.status)}</option>)}</select></label>}
function LotLookup({value,onChange,label='Lot'}:{value?:string;onChange:(id:string)=>void;label?:string}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('inventoryLot').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>{label}</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.lot_number)} — {String(r.status)} — {String(r.quality_status)}</option>)}</select></label>}
const cfgs:Record<string,Config>={
 dashboard:{title:'إدارة المخزون التصنيعي وWIP',subtitle:'Raw/WIP/FG، التقييم، التتبع، Safety Stock/EOQ والتسويات.',load:()=>mrpInventoryAnalyticsService.kpis() as Promise<Row[]>,columns:[{key:'raw_available_qty',label:'Raw متاح'},{key:'wip_qty',label:'WIP'},{key:'fg_available_qty',label:'FG متاح'},{key:'trace_links',label:'Trace Links'}]},
 raw:{title:'Raw Materials',subtitle:'الخامات عبر بوابة المخزون',load:()=>mrpInventoryAnalyticsService.raw() as Promise<Row[]>,columns:[{key:'item_code',label:'الصنف'},{key:'item_name',label:'الاسم'},{key:'available_qty',label:'متاح'},{key:'reserved_qty',label:'محجوز'},{key:'valuation_method',label:'تقييم'}]},
 wip:{title:'WIP',subtitle:'مخزون تحت التشغيل حسب أمر العمل والعملية',load:()=>mrpInventoryAnalyticsService.wip() as Promise<Row[]>,action:'wip',columns:[{key:'work_order_number',label:'WO'},{key:'item_code',label:'الصنف'},{key:'work_center_code',label:'مركز العمل'},{key:'quantity_in_process',label:'WIP Qty'},{key:'accumulated_cost',label:'التكلفة'}]},
 fg:{title:'Finished Goods',subtitle:'البضائع التامة من إكمال أوامر العمل',load:()=>mrpInventoryAnalyticsService.fg() as Promise<Row[]>,columns:[{key:'item_code',label:'الصنف'},{key:'item_name',label:'الاسم'},{key:'on_hand_qty',label:'On hand'},{key:'available_qty',label:'متاح'},{key:'average_cost',label:'تكلفة'}]},
 valuation:{title:'سياسات التقييم',subtitle:'FIFO / FEFO / WAC / Actual',load:()=>mrpInventoryValuationPolicyService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'valuation',columns:[{key:'item_id',label:'الصنف'},{key:'valuation_method',label:'الطريقة'},{key:'carrying_cost_percent',label:'Carrying %'},{key:'service_level_percent',label:'Service %'}]},
 trace:{title:'Lot Traceability',subtitle:'تتبع أمامي وعكسي',load:()=>mrpInventoryAnalyticsService.trace() as Promise<Row[]>,action:'trace',columns:[{key:'raw_lot_number',label:'Lot خام'},{key:'raw_item_code',label:'مادة'},{key:'work_order_number',label:'WO'},{key:'finished_lot_number',label:'Lot تام'},{key:'finished_item_code',label:'منتج'}]},
 safety:{title:'Safety Stock / EOQ',subtitle:'حسابات ROP وEOQ',load:()=>mrpInventoryAnalyticsService.optimization() as Promise<Row[]>,action:'opt',columns:[{key:'item_code',label:'الصنف'},{key:'safety_stock_qty',label:'Safety'},{key:'reorder_point_qty',label:'ROP'},{key:'eoq_qty',label:'EOQ'},{key:'created_at',label:'تاريخ'}]},
 issues:{title:'Material Issues',subtitle:'حجز وإصدار المواد لأوامر العمل',load:()=>mrpInventoryAnalyticsService.reconciliation() as Promise<Row[]>,action:'issue',columns:[{key:'work_order_number',label:'WO'},{key:'item_code',label:'المادة'},{key:'required_qty',label:'مطلوب'},{key:'issued_qty',label:'مصروف'},{key:'consumption_variance',label:'فرق'}]},
 reconciliation:{title:'Reconciliation',subtitle:'مطابقة المطلوب/المستهلك وتحليل الفروق',load:()=>mrpInventoryAnalyticsService.reconciliation() as Promise<Row[]>,columns:[{key:'work_order_number',label:'WO'},{key:'item_code',label:'المادة'},{key:'required_qty',label:'قياسي'},{key:'consumed_qty',label:'فعلي'},{key:'consumption_variance',label:'فرق'}]},
 reports:{title:'Inventory KPIs',subtitle:'Turns/DIO/Accuracy foundation عبر views',load:()=>mrpInventoryAnalyticsService.kpis() as Promise<Row[]>,columns:[{key:'raw_available_qty',label:'Raw'},{key:'wip_qty',label:'WIP'},{key:'fg_available_qty',label:'FG'},{key:'trace_links',label:'Trace'}]},
};
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({valuation_method:'WAC',movement_type:'start',quantity:'1',cost_delta:'0',average_daily_demand:'100',demand_stddev:'15',lead_time_days:'7',annual_demand:'12000',order_cost:'500',holding_cost_per_unit:'20',service_level_percent:'95',z_factor:'1.65'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r||'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='valuation')return <Box title="سياسة تقييم"><div className="grid md:grid-cols-3 gap-3"><ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})}/>{select('Method','valuation_method',f,set,['FIFO','FEFO','WAC','ACTUAL'])}{inp('Carrying %','carrying_cost_percent',f,set,'number')}{inp('Service %','service_level_percent',f,set,'number')}{inp('Z factor','z_factor',f,set,'number')}<button onClick={()=>void run(()=>mrpInventoryValuationPolicyService.upsert(f))} className="bg-indigo-600 text-white rounded-xl p-2">Save</button><ValuationPolicyLookup value={f.policy_id} onChange={id=>set({policy_id:id})}/>{inp('Deactivate Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpInventoryValuationPolicyService.deactivate(f.policy_id,f.reason))} className="bg-red-600 text-white rounded-xl p-2">Deactivate</button><Msg msg={msg}/></div></Box>;
 if(type==='wip')return <Box title="WIP Location / Movement"><div className="grid md:grid-cols-3 gap-3">{inp('WIP Code اختياري','wip_code',f,set)}{inp('WIP Name','name_ar',f,set)}<WorkCenterLookup value={f.work_center_id} onChange={id=>set({work_center_id:id})}/><WarehouseLookup label="مستودع الموقع" value={f.warehouse_id} onChange={id=>set({warehouse_id:id})}/><LocationLookup label="Inventory Location" value={f.inventory_location_id} warehouseId={f.warehouse_id} onChange={id=>set({inventory_location_id:id})}/><button onClick={()=>void run(()=>mrpWipLocationService.createWipLocation(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create WIP Location</button><WipLocationLookup value={f.wip_location_id} onChange={id=>set({wip_location_id:id})}/>{select('WIP Location Status','wip_status',f,set,['active','blocked','closed'])}{inp('Status Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpWipLocationService.updateStatus(f.wip_location_id,f.wip_status,f.reason))} className="bg-slate-700 text-white rounded-xl p-2">Update Location</button><WorkOrderLookup value={f.work_order_id} onChange={id=>set({work_order_id:id})}/><WoOperationLookup label="From Operation" value={f.from_operation_id} onChange={id=>set({from_operation_id:id,operation_id:id})}/><WoOperationLookup label="To Operation" value={f.to_operation_id} onChange={id=>set({to_operation_id:id})}/><ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})}/>{select('Movement','movement_type',f,set,['start','move','complete','scrap','rework','adjustment'])}{inp('Quantity','quantity',f,set,'number')}{inp('Cost Delta','cost_delta',f,set,'number')}<button onClick={()=>void run(()=>mrpWipMovementService.record(f))} className="bg-emerald-600 text-white rounded-xl p-2">Record Movement</button>{inp('Adjustment Qty Delta','quantity_delta',f,set,'number')}<button onClick={()=>void run(()=>mrpWipMovementService.adjust(f))} className="bg-amber-600 text-white rounded-xl p-2">Adjust WIP</button><Msg msg={msg}/></div></Box>;
 if(type==='trace')return <Box title="ربط تتبع Lot"><div className="grid md:grid-cols-3 gap-3"><WorkOrderLookup value={f.work_order_id} onChange={id=>set({work_order_id:id})}/><ItemLookup label="Raw Item" value={f.raw_item_id} onChange={id=>set({raw_item_id:id})}/><LotLookup label="Raw Lot" value={f.raw_lot_id} onChange={id=>set({raw_lot_id:id})}/><ItemLookup label="Finished Item" value={f.finished_item_id} onChange={id=>set({finished_item_id:id})}/><LotLookup label="Finished Lot" value={f.finished_lot_id} onChange={id=>set({finished_lot_id:id})}/>{inp('Consumed','quantity_consumed',f,set,'number')}{inp('Produced','quantity_produced',f,set,'number')}<button onClick={()=>void run(()=>mrpLotTraceService.link(f))} className="bg-indigo-600 text-white rounded-xl p-2">Link</button><Msg msg={msg}/></div></Box>;
 if(type==='issue')return <Box title="إصدار مادة لأمر العمل"><div className="grid md:grid-cols-3 gap-3"><WoMaterialLookup value={f.material_id} onChange={id=>set({material_id:id})}/>{inp('Issue Qty','issue_qty',f,set,'number')}<button onClick={()=>void run(()=>mrpWorkOrderMaterialService.issue(f.material_id,Number(f.issue_qty||0)))} className="bg-indigo-600 text-white rounded-xl p-2">Issue Material</button><Msg msg={msg}/></div></Box>;
 if(type==='opt')return <Box title="حساب Safety/ROP/EOQ"><div className="grid md:grid-cols-3 gap-3"><ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})}/>{inp('Avg daily demand','average_daily_demand',f,set,'number')}{inp('Stddev','demand_stddev',f,set,'number')}{inp('Lead time days','lead_time_days',f,set,'number')}{inp('Annual demand','annual_demand',f,set,'number')}{inp('Order cost','order_cost',f,set,'number')}{inp('Holding cost/unit','holding_cost_per_unit',f,set,'number')}<button onClick={()=>void run(()=>mrpInventoryOptimizationService.calculate(f))} className="bg-indigo-600 text-white rounded-xl p-2">Calculate</button><Msg msg={msg}/></div></Box>;
 return null}
export function MrpInventoryPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{type==='dashboard'&&<MrpUnitNav unit="inventory" />}{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
