import { useEffect, useState } from 'react';
import { ItemLookup, LocationLookup, WarehouseLookup } from '../../inventory/shared/InventoryLookups';
import { InventoryRecordTools } from '../../inventory/shared/InventoryRecordTools';
import { mrpDispatchService, mrpMpsPlanService, mrpPlanningAnalyticsService, mrpPlannedOrderService, mrpRunService, mrpWorkOrderMaterialService, mrpWorkOrderOperationService, mrpWorkOrderService } from '../../../../services/sdk';
import { supabase } from '../../../../services/supabase/supabase';
import { MrpUnitNav } from '../shared/MrpUnitNav';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void,type='text'){return <label className="text-xs font-bold"><span>{l}</span><input type={type} value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function select(l:string,n:string,f:Form,set:(p:Form)=>void,ops:string[]){return <label className="text-xs font-bold"><span>{l}</span><select value={f[n]||ops[0]} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1 bg-white">{ops.map(o=><option key={o}>{o}</option>)}</select></label>}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 rounded-xl p-2">{msg}</div>:null}
function MpsPlanLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_mps_plans').select('id,plan_number,plan_name,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>MPS Plan</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.plan_number)} — {String(r.plan_name)} — {String(r.status)}</option>)}</select></label>}
function PlannedOrderLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_planned_orders').select('id,planned_order_number,status,suggested_qty').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Planned Order</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.planned_order_number)} — {String(r.status)} — {String(r.suggested_qty)}</option>)}</select></label>}
function WorkOrderLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_work_orders').select('id,work_order_number,status,quantity_to_produce').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Work Order</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.work_order_number)} — {String(r.status)} — {String(r.quantity_to_produce)}</option>)}</select></label>}
function WoMaterialLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_work_order_materials').select('id,item_id,required_qty,status').limit(300).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>WO Material</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.id).slice(0,8)} — {String(r.required_qty)} — {String(r.status)}</option>)}</select></label>}
function WoOperationLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_work_order_operations').select('id,operation_name,sequence_no,status').limit(300).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>WO Operation</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.sequence_no)} — {String(r.operation_name)} — {String(r.status)}</option>)}</select></label>}
function BomVersionLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_bom_versions').select('id,version_no,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>BOM Version</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- تلقائي --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>v{String(r.version_no)} — {String(r.status)} — {String(r.id).slice(0,8)}</option>)}</select></label>}
function RoutingLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('routing_headers').select('id,routing_code,version_no,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Routing</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- تلقائي --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.routing_code)} — v{String(r.version_no)} — {String(r.status)}</option>)}</select></label>}
function DispatchLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_dispatch_lookup').select('id,dispatch_number,status,operation_name').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>Dispatch</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.dispatch_number)} — {String(r.operation_name)} — {String(r.status)}</option>)}</select></label>}
function WoAlertLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('mrp_work_order_alerts').select('id,alert_type,severity,title,status').limit(200).then(({data})=>setRows((data||[]) as Row[]))},[]);return <label className="text-xs font-bold"><span>WO Alert</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.alert_type)} — {String(r.severity)} — {String(r.status)} — {String(r.title).slice(0,40)}</option>)}</select></label>}
const cfgs:Record<string,Config>={
 dashboard:{title:'تخطيط الإنتاج وأوامر العمل',subtitle:'MRP Run، المقترحات، أوامر العمل، الحجز، الجدولة، CR والتنبيهات.',load:()=>mrpPlanningAnalyticsService.dashboard() as Promise<Row[]>,columns:[{key:'mrp_runs',label:'MRP Runs'},{key:'open_planned_orders',label:'مقترحات مفتوحة'},{key:'open_work_orders',label:'أوامر عمل'},{key:'open_alerts',label:'تنبيهات'}]},
 runs:{title:'MRP Runs',subtitle:'تشغيل MRP من MPS',load:()=>mrpRunService.findAll({orderBy:'started_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'run',columns:[{key:'run_number',label:'Run'},{key:'status',label:'الحالة'},{key:'started_at',label:'بدأ'},{key:'completed_at',label:'انتهى'}]},
 proposals:{title:'Planned Orders',subtitle:'مقترحات الإنتاج والشراء',load:()=>mrpPlanningAnalyticsService.proposals() as Promise<Row[]>,action:'proposal',columns:[{key:'planned_order_number',label:'المقترح'},{key:'item_code',label:'الصنف'},{key:'suggested_qty',label:'الكمية'},{key:'due_date',label:'الاستحقاق'},{key:'status',label:'الحالة'}]},
 workOrders:{title:'Work Orders',subtitle:'إنشاء وإصدار وتنفيذ أوامر العمل',load:()=>mrpPlanningAnalyticsService.workOrders() as Promise<Row[]>,action:'wo',columns:[{key:'work_order_number',label:'WO'},{key:'item_code',label:'الصنف'},{key:'quantity_to_produce',label:'الكمية'},{key:'quantity_completed',label:'منجز'},{key:'critical_ratio',label:'CR'},{key:'status',label:'الحالة'}]},
 materials:{title:'مواد أوامر العمل',subtitle:'الحجز والإصدار والمطابقة',load:()=>mrpPlanningAnalyticsService.materials() as Promise<Row[]>,action:'material',columns:[{key:'work_order_number',label:'WO'},{key:'item_code',label:'المادة'},{key:'required_qty',label:'مطلوب'},{key:'reserved_qty',label:'محجوز'},{key:'issued_qty',label:'مصروف'},{key:'status',label:'الحالة'}]},
 operations:{title:'عمليات أوامر العمل',subtitle:'بدء/إكمال عمليات Routing',load:()=>mrpPlanningAnalyticsService.operations() as Promise<Row[]>,action:'operation',columns:[{key:'work_order_number',label:'WO'},{key:'sequence_no',label:'تسلسل'},{key:'operation_name',label:'العملية'},{key:'work_center_code',label:'مركز العمل'},{key:'status',label:'الحالة'}]},
 scheduling:{title:'الجدولة الإنتاجية',subtitle:'Forward/Backward/FCS',load:()=>mrpPlanningAnalyticsService.schedule() as Promise<Row[]>,action:'schedule',columns:[{key:'schedule_number',label:'الجدولة'},{key:'work_order_number',label:'WO'},{key:'scheduling_method',label:'الطريقة'},{key:'scheduled_start_at',label:'البداية'},{key:'scheduled_end_at',label:'النهاية'}]},
 dispatch:{title:'Dispatch Queue',subtitle:'قائمة الإرسال حسب الأولوية',load:()=>mrpPlanningAnalyticsService.dispatch() as Promise<Row[]>,action:'dispatch',columns:[{key:'dispatch_number',label:'Dispatch'},{key:'work_order_number',label:'WO'},{key:'operation_name',label:'العملية'},{key:'work_center_code',label:'مركز العمل'},{key:'priority_rank',label:'الأولوية'},{key:'status',label:'الحالة'}]}, 
 alerts:{title:'تنبيهات أوامر العمل',subtitle:'CR/تأخير/مواد/طاقة',load:()=>mrpPlanningAnalyticsService.alerts() as Promise<Row[]>,action:'alerts',columns:[{key:'work_order_number',label:'WO'},{key:'alert_type',label:'النوع'},{key:'severity',label:'الشدة'},{key:'title',label:'العنوان'},{key:'status',label:'الحالة'}]},
 reports:{title:'KPIs التخطيط',subtitle:'مؤشرات أوامر العمل',load:()=>mrpPlanningAnalyticsService.kpis() as Promise<Row[]>,columns:[{key:'total_work_orders',label:'WO'},{key:'completed_work_orders',label:'مكتمل'},{key:'critical_work_orders',label:'حرج'},{key:'avg_critical_ratio',label:'Avg CR'}]},
};
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({status:'reviewed',work_order_type:'standard',quantity_to_produce:'1',method:'forward',sequence_rule:'CR',completed_qty:'1',scrap_qty:'0',issue_qty:'1'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r||'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='run')return <Box title="تشغيل MRP"><div className="grid md:grid-cols-3 gap-3"><MpsPlanLookup value={f.mps_plan_id} onChange={id=>set({mps_plan_id:id})}/><button onClick={()=>void run(()=>mrpRunService.runFromMps(f.mps_plan_id))} className="bg-indigo-600 text-white rounded-xl p-2">Run MRP</button><Msg msg={msg}/></div></Box>;
 if(type==='proposal')return <Box title="مراجعة/تحويل مقترح"><div className="grid md:grid-cols-3 gap-3"><PlannedOrderLookup value={f.planned_order_id} onChange={id=>set({planned_order_id:id})}/>{select('Status','status',f,set,['reviewed','firmed','cancelled'])}{inp('Notes','notes',f,set)}<button onClick={()=>void run(()=>mrpPlannedOrderService.review(f.planned_order_id,f.status,f.notes))} className="bg-indigo-600 text-white rounded-xl p-2">Review</button><button onClick={()=>void run(()=>mrpPlannedOrderService.convert(f.planned_order_id))} className="bg-emerald-600 text-white rounded-xl p-2">Convert to WO</button><Msg msg={msg}/></div></Box>;
 if(type==='wo')return <Box title="أمر العمل"><div className="grid md:grid-cols-3 gap-3"><ItemLookup label="المنتج" value={f.item_id} onChange={id=>set({item_id:id})}/>{inp('Quantity','quantity_to_produce',f,set)}{select('Type','work_order_type',f,set,['standard','custom_eto','rework','subcontract'])}<BomVersionLookup value={f.bom_version_id} onChange={id=>set({bom_version_id:id})}/><RoutingLookup value={f.routing_id} onChange={id=>set({routing_id:id})}/>{inp('Due At','due_at',f,set,'datetime-local')}<button onClick={()=>void run(()=>mrpWorkOrderService.createWo(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create WO</button><WorkOrderLookup value={f.work_order_id} onChange={id=>set({work_order_id:id})}/><button onClick={()=>void run(()=>mrpWorkOrderService.release(f.work_order_id))} className="bg-amber-600 text-white rounded-xl p-2">Release/Reserve</button><button onClick={()=>void run(()=>mrpWorkOrderService.start(f.work_order_id))} className="bg-slate-700 text-white rounded-xl p-2">Start</button>{inp('Completed Qty','completed_qty',f,set,'number')}{inp('Scrap Qty','scrap_qty',f,set,'number')}<WarehouseLookup label="مستودع الاستلام" value={f.receipt_warehouse_id} onChange={id=>set({receipt_warehouse_id:id})}/><LocationLookup label="موقع الاستلام" value={f.receipt_location_id} warehouseId={f.receipt_warehouse_id} onChange={id=>set({receipt_location_id:id})}/><button onClick={()=>void run(()=>mrpWorkOrderService.complete(f))} className="bg-emerald-600 text-white rounded-xl p-2">Complete</button>{inp('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpWorkOrderService.close(f.work_order_id,f.reason))} className="bg-green-700 text-white rounded-xl p-2">Close</button><button onClick={()=>void run(()=>mrpWorkOrderService.hold(f.work_order_id,f.reason))} className="bg-yellow-600 text-white rounded-xl p-2">Hold</button><button onClick={()=>void run(()=>mrpWorkOrderService.resume(f.work_order_id,f.reason))} className="bg-blue-600 text-white rounded-xl p-2">Resume</button><button onClick={()=>void run(()=>mrpWorkOrderService.cancel(f.work_order_id,f.reason))} className="bg-red-600 text-white rounded-xl p-2">Cancel</button><button onClick={()=>void run(()=>mrpWorkOrderService.refreshCr(f.work_order_id))} className="bg-slate-600 text-white rounded-xl p-2">Refresh CR</button><Msg msg={msg}/></div></Box>;
 if(type==='material')return <Box title="إصدار مادة"><div className="grid md:grid-cols-3 gap-3"><WoMaterialLookup value={f.material_id} onChange={id=>set({material_id:id})}/>{inp('Issue Qty','issue_qty',f,set)}<button onClick={()=>void run(()=>mrpWorkOrderMaterialService.issue(f.material_id,Number(f.issue_qty||0)))} className="bg-indigo-600 text-white rounded-xl p-2">Issue</button><Msg msg={msg}/></div></Box>;
 if(type==='operation')return <Box title="إكمال عملية"><div className="grid md:grid-cols-3 gap-3"><WoOperationLookup value={f.operation_id} onChange={id=>set({operation_id:id})}/>{inp('Completed Qty','completed_qty',f,set)}{inp('Scrap Qty','scrap_qty',f,set)}<button onClick={()=>void run(()=>mrpWorkOrderOperationService.complete(f.operation_id,Number(f.completed_qty||0),Number(f.scrap_qty||0)))} className="bg-indigo-600 text-white rounded-xl p-2">Complete Operation</button><Msg msg={msg}/></div></Box>;
 if(type==='schedule')return <Box title="جدولة أمر عمل"><div className="grid md:grid-cols-3 gap-3"><WorkOrderLookup value={f.work_order_id} onChange={id=>set({work_order_id:id})}/>{select('Method','method',f,set,['forward','backward','finite_capacity'])}{select('Rule','sequence_rule',f,set,['FIFO','EDD','SPT','CR','setup_minimization'])}{inp('Start','start_at',f,set,'datetime-local')}{inp('Due','due_at',f,set,'datetime-local')}<button onClick={()=>void run(()=>mrpWorkOrderService.schedule(f))} className="bg-indigo-600 text-white rounded-xl p-2">Schedule</button><Msg msg={msg}/></div></Box>;
 if(type==='dispatch')return <Box title="إرسال عملية للإنتاج"><div className="grid md:grid-cols-3 gap-3"><WoOperationLookup value={f.operation_id} onChange={id=>set({operation_id:id})}/>{inp('Priority Rank','priority_rank',f,set,'number')}<button onClick={()=>void run(()=>mrpDispatchService.createDispatch(f.operation_id,Number(f.priority_rank||100)))} className="bg-indigo-600 text-white rounded-xl p-2">Create Dispatch</button><DispatchLookup value={f.dispatch_id} onChange={id=>set({dispatch_id:id})}/>{select('Dispatch Status','dispatch_status',f,set,['open','dispatched','started','completed','cancelled'])}{inp('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpDispatchService.updateStatus(f.dispatch_id,f.dispatch_status,f.reason))} className="bg-emerald-600 text-white rounded-xl p-2">Update Dispatch</button><Msg msg={msg}/></div></Box>;
 if(type==='alerts')return <Box title="تنبيهات أوامر العمل"><div className="grid md:grid-cols-3 gap-3"><button onClick={()=>void run(()=>mrpWorkOrderService.alerts())} className="bg-indigo-600 text-white rounded-xl p-2">Generate Alerts</button><WoAlertLookup value={f.alert_id} onChange={id=>set({alert_id:id})}/>{select('Alert Status','alert_status',f,set,['resolved','acknowledged','dismissed'])}{inp('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpWorkOrderService.closeAlert(f.alert_id,f.alert_status||'resolved',f.reason))} className="bg-emerald-600 text-white rounded-xl p-2">Close/Ack Alert</button><Msg msg={msg}/></div></Box>;
 return null}
export function MrpPlanningPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{type==='dashboard'&&<MrpUnitNav unit="planning" />}{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
