import { useEffect, useState } from 'react';
import { InventoryRecordTools } from '../shared/InventoryRecordTools';
import { CountLineLookup, CountTaskLookup, ItemLookup, WarehouseLookup } from '../shared/InventoryLookups';
import { inventoryAdjustmentApprovalService, inventoryAnnualCountPlanService, inventoryCountingAnalyticsService, inventoryCountFreezeService, inventoryCountTaskService, inventoryCountVarianceService, inventoryCycleCountPlanService } from '../../../../services/sdk';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
const cfgs:Record<string,Config>={
 dashboard:{title:'الجرد ودقة المخزون',subtitle:'IRA وCompletion وVariance',load:()=>inventoryCountingAnalyticsService.ira(),columns:[{key:'counted_lines',label:'بنود معدودة'},{key:'total_abs_variance',label:'الانحراف'},{key:'ira_percent',label:'IRA %'},{key:'major_variances',label:'فروق كبيرة'}]},
 plans:{title:'خطط الجرد',subtitle:'ABC / Location / Event / Control Group / Annual',load:()=>inventoryCycleCountPlanService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'plan',columns:[{key:'plan_number',label:'الخطة'},{key:'plan_type',label:'النوع'},{key:'status',label:'الحالة'}]},
 tasks:{title:'مهام العد المحمولة',subtitle:'Blind count: لا تعرض الكمية المتوقعة للعداد',load:()=>inventoryCountTaskService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'count',columns:[{key:'task_number',label:'المهمة'},{key:'count_round',label:'الجولة'},{key:'status',label:'الحالة'}]},
 mobile:{title:'واجهة العد المحمولة Blind Count',subtitle:'مسح الموقع والصنف واللوت ثم إدخال الكمية فقط دون expected_qty',load:()=>inventoryCountTaskService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'count',columns:[{key:'task_number',label:'المهمة'},{key:'count_round',label:'الجولة'},{key:'status',label:'الحالة'}]},
 recount:{title:'طلبات العد الثاني/الثالث',subtitle:'Double/Triple count عند الفروقات',load:()=>inventoryCountTaskService.findAll({filters:{status:'variance_review'},orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'recount',columns:[{key:'task_number',label:'المهمة'},{key:'count_round',label:'الجولة'},{key:'status',label:'الحالة'}]},
 variances:{title:'تحليل الفروق',subtitle:'أسباب الفروق ومراجعتها',load:()=>inventoryCountVarianceService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,columns:[{key:'variance_qty',label:'الفرق'},{key:'variance_percent',label:'%'},{key:'status',label:'الحالة'}]},
 approvals:{title:'اعتماد التسويات',subtitle:'صلاحيات متدرجة حسب الكمية والقيمة',load:()=>inventoryAdjustmentApprovalService.findAll({orderBy:'created_at',ascending:false,limit:100}) as unknown as Promise<Row[]>,action:'approval',columns:[{key:'required_role',label:'الدور'},{key:'decision',label:'القرار'},{key:'created_at',label:'تاريخ'}]},
 freezes:{title:'تجميد الجرد',subtitle:'Freeze/Unfreeze للمستودع أو الموقع أثناء الجرد السنوي',load:()=>inventoryCountingAnalyticsService.freezes(),action:'freeze',columns:[{key:'freeze_scope',label:'النطاق'},{key:'status',label:'الحالة'},{key:'reason',label:'السبب'},{key:'created_at',label:'تاريخ'}]},
 annual:{title:'الجرد السنوي Wall-to-Wall',subtitle:'تخطيط الجرد الكامل السنوي وإشعار الأطراف',load:()=>inventoryAnnualCountPlanService.findAll({orderBy:'planned_start',ascending:false,limit:100}) as unknown as Promise<Row[]>,columns:[{key:'fiscal_year',label:'السنة'},{key:'planned_start',label:'البداية'},{key:'planned_end',label:'النهاية'},{key:'status',label:'الحالة'}]},
 completion:{title:'اكتمال الجرد',subtitle:'نسبة المهام المنجزة لكل خطة',load:()=>inventoryCountingAnalyticsService.completion(),columns:[{key:'plan_number',label:'الخطة'},{key:'task_count',label:'المهام'},{key:'counted_count',label:'منجز'},{key:'completion_percent',label:'%'}]},
 expiry:{title:'تقرير المنتهي الصلاحية',subtitle:'مواد قاربت الانتهاء ضمن رقابة الجرد',load:()=>inventoryCountingAnalyticsService.expiry(),columns:[{key:'item_code',label:'الصنف'},{key:'lot_number',label:'Lot'},{key:'expiry_date',label:'الانتهاء'},{key:'days_left',label:'أيام'}]}
};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void){return <label className="text-xs font-bold"><span>{l}</span><input value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({plan_type:'abc',days:'30',decision:'approved',round:'2'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r||'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='plan')return <Box title="إنشاء خطة جرد"><div className="grid md:grid-cols-3 gap-3">{inp('Plan Type','plan_type',f,set)}<WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} />{inp('Days','days',f,set)}<button onClick={()=>void run(()=>inventoryCycleCountPlanService.generate(f.plan_type,f.warehouse_id||undefined,Number(f.days||30)))} className="bg-indigo-600 text-white rounded-xl p-2">Generate</button>{inp('Plan ID للترحيل','plan_id',f,set)}<button onClick={()=>void run(()=>inventoryCycleCountPlanService.post(f.plan_id))} className="bg-emerald-600 text-white rounded-xl p-2">Post Adjustments</button><Msg msg={msg}/></div></Box>;
 if(type==='count')return <Box title="إدخال عد Blind"><div className="grid md:grid-cols-3 gap-3"><CountTaskLookup label="اختر مهمة العد" value={f.task_id} onChange={(id)=>set({task_id:id})} /><ItemLookup label="اختر الصنف" value={f.item_id} onChange={(id)=>set({item_id:id})} />{inp('Counted Qty','counted_qty',f,set)}{inp('Location Scan','scan_location',f,set)}{inp('Item Scan','scan_item',f,set)}<button onClick={()=>void run(()=>inventoryCountTaskService.submit({...f,counted_qty:Number(f.counted_qty||0)}))} className="bg-indigo-600 text-white rounded-xl p-2">Submit</button><Msg msg={msg}/></div></Box>;
 if(type==='recount')return <Box title="طلب عدّ ثانٍ/ثالث"><div className="grid md:grid-cols-3 gap-3"><CountLineLookup label="اختر سطر العد" value={f.count_line_id} onChange={(id)=>set({count_line_id:id})} />{inp('Round 2/3','round',f,set)}<button onClick={()=>void run(()=>inventoryCountTaskService.requestRecount(f.count_line_id,Number(f.round||2)))} className="bg-indigo-600 text-white rounded-xl p-2">Request Recount</button><Msg msg={msg}/></div></Box>;
 if(type==='approval')return <Box title="قرار اعتماد"><div className="grid md:grid-cols-3 gap-3">{inp('Approval ID','approval_id',f,set)}{inp('Decision','decision',f,set)}{inp('Comments','comments',f,set)}<button onClick={()=>void run(()=>inventoryAdjustmentApprovalService.decide(f.approval_id,f.decision,f.comments))} className="bg-indigo-600 text-white rounded-xl p-2">Decide</button><Msg msg={msg}/></div></Box>;
 if(type==='freeze')return <Box title="تجميد/فك تجميد"><div className="grid md:grid-cols-3 gap-3">{inp('Plan ID','plan_id',f,set)}<WarehouseLookup label="اختر المستودع" value={f.warehouse_id} onChange={(id)=>set({warehouse_id:id})} />{inp('Location ID','location_id',f,set)}{inp('Reason','reason',f,set)}<button onClick={()=>void run(()=>inventoryCountFreezeService.freeze(f))} className="bg-indigo-600 text-white rounded-xl p-2">Freeze</button>{inp('Freeze ID','freeze_id',f,set)}<button onClick={()=>void run(()=>inventoryCountFreezeService.unfreeze(f.freeze_id))} className="bg-emerald-600 text-white rounded-xl p-2">Unfreeze</button><Msg msg={msg}/></div></Box>;
 return null}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 p-2 rounded-xl">{msg}</div>:null}
export function CountingPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[type,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
