import { type FormEvent, type ReactNode, useCallback, useEffect, useState } from 'react';
import { Loader2, Plus, RefreshCw, TrendingUp, X } from 'lucide-react';
import { forecastScenarioService, type ForecastScenarioRecord } from '../../../services/sdk/BudgetService';
import { legalEntityService, type LegalEntityRecord } from '../../../services/sdk/FinanceFoundationService';
import { getErrorMessage } from '../../../services/errors';
import { useUIStore } from '../../../core/stores';
import { FinanceUnitNav } from './shared/FinanceUnitNav';

type Action={type:'submitted'|'approved'|'closed'|'voided';scenario:ForecastScenarioRecord};
export default function CashForecastPage(){
 const {addToast}=useUIStore(); const [entities,setEntities]=useState<LegalEntityRecord[]>([]),[entityId,setEntityId]=useState(''),[rows,setRows]=useState<ForecastScenarioRecord[]>([]),[loading,setLoading]=useState(true),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[action,setAction]=useState<Action|null>(null),[reason,setReason]=useState('');
 const [form,setForm]=useState({scenario_name:'',start_date:'',end_date:'',projected_cash:'',scenario_type:'cash',confidence_level:'base'});
 const load=useCallback(async()=>{setLoading(true);try{const es=await legalEntityService.findActive();setEntities(es);const id=entityId||es[0]?.id||'';if(!entityId&&id)setEntityId(id);setRows(id?await forecastScenarioService.findBoard(id):[])}catch(e){addToast(`تعذر التحميل: ${getErrorMessage(e)}`,'error')}finally{setLoading(false)}},[addToast,entityId]);
 useEffect(()=>{void load()},[load]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!entityId)return;setSaving(true);try{await forecastScenarioService.upsert({legalEntityId:entityId,scenarioName:form.scenario_name,startDate:form.start_date,endDate:form.end_date,projectedCash:Number(form.projected_cash),scenarioType:form.scenario_type,confidenceLevel:form.confidence_level});addToast('تم إنشاء سيناريو التنبؤ عبر RPC','success');setShow(false);setForm({scenario_name:'',start_date:'',end_date:'',projected_cash:'',scenario_type:'cash',confidence_level:'base'});await load()}catch(e){addToast(getErrorMessage(e),'error')}finally{setSaving(false)}};
 const execute=async()=>{if(!action||!reason.trim())return addToast('السبب مطلوب','error');try{await forecastScenarioService.updateStatus(action.scenario.id,action.type,reason.trim());addToast('تم تحديث الحالة','success');setAction(null);setReason('');await load()}catch(e){addToast(getErrorMessage(e),'error')}};
 return <div className="space-y-5 max-w-[1600px] mx-auto" dir="rtl"><FinanceUnitNav unit="budget"/><div className="flex justify-between flex-wrap gap-3"><div><p className="text-sm font-bold text-blue-700">Finance Unit 08 · Forecasting</p><h1 className="text-3xl font-black">التنبؤ المالي والنقدي</h1><p className="text-slate-500 mt-2">سيناريوهات توقع مرتبطة بالكيان القانوني ودورة اعتماد.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="border rounded-xl px-4 py-2 font-bold bg-white"><RefreshCw size={15} className="inline ml-1"/>تحديث</button><button onClick={()=>setShow(true)} className="bg-blue-600 text-white rounded-xl px-4 py-2 font-bold"><Plus size={15} className="inline ml-1"/>سيناريو جديد</button></div></div>
 <div className="grid md:grid-cols-2 gap-3"><select value={entityId} onChange={e=>setEntityId(e.target.value)} className="border rounded-xl p-3 bg-white">{entities.map(e=><option key={e.id} value={e.id}>{e.code} — {e.name_ar}</option>)}</select><div className="bg-blue-50 border border-blue-200 rounded-xl p-4 text-sm text-blue-900 flex gap-2"><TrendingUp size={16}/><span>يمكن استخدام السيناريوهات لاحقاً مع AR/AP/Cash لتوقع السيولة.</span></div></div>
 {loading?<div className="py-24 text-center"><Loader2 className="animate-spin mx-auto mb-3"/>جارٍ التحميل...</div>:<div className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-right">السيناريو</th><th className="p-3 text-right">الفترة</th><th className="p-3 text-right">النقد المتوقع</th><th className="p-3 text-right">النوع</th><th className="p-3 text-right">الثقة</th><th className="p-3 text-right">الحالة</th><th className="p-3"/></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="p-3 font-bold">{r.scenario_name}</td><td className="p-3">{r.start_date} — {r.end_date}</td><td className="p-3 font-black">{Number(r.projected_cash).toLocaleString()}</td><td className="p-3">{r.scenario_type}</td><td className="p-3">{r.confidence_level}</td><td className="p-3">{r.status}</td><td className="p-3"><Actions scenario={r} onAction={(type)=>{setAction({type,scenario:r});setReason('')}}/></td></tr>)}{!rows.length&&<tr><td colSpan={7} className="p-16 text-center text-slate-500"><TrendingUp className="mx-auto mb-3 text-slate-300"/>لا توجد سيناريوهات.</td></tr>}</tbody></table></div>}
 {show&&<Modal title="سيناريو تنبؤ جديد" onClose={()=>setShow(false)}><form onSubmit={submit} className="space-y-3"><input required placeholder="اسم السيناريو" value={form.scenario_name} onChange={e=>setForm(f=>({...f,scenario_name:e.target.value}))} className="w-full border rounded-xl p-2.5"/><div className="grid grid-cols-2 gap-3"><input required type="date" value={form.start_date} onChange={e=>setForm(f=>({...f,start_date:e.target.value}))} className="border rounded-xl p-2.5"/><input required type="date" value={form.end_date} onChange={e=>setForm(f=>({...f,end_date:e.target.value}))} className="border rounded-xl p-2.5"/></div><div className="grid grid-cols-3 gap-3"><input required type="number" placeholder="النقد المتوقع" value={form.projected_cash} onChange={e=>setForm(f=>({...f,projected_cash:e.target.value}))} className="border rounded-xl p-2.5"/><select value={form.scenario_type} onChange={e=>setForm(f=>({...f,scenario_type:e.target.value}))} className="border rounded-xl p-2.5"><option value="cash">Cash</option><option value="revenue">Revenue</option><option value="expense">Expense</option><option value="working_capital">Working Capital</option><option value="custom">Custom</option></select><select value={form.confidence_level} onChange={e=>setForm(f=>({...f,confidence_level:e.target.value}))} className="border rounded-xl p-2.5"><option value="low">Low</option><option value="base">Base</option><option value="high">High</option><option value="stress">Stress</option></select></div><button disabled={saving} className="w-full bg-blue-600 text-white rounded-xl py-3 font-bold">حفظ</button></form></Modal>}
 {action&&<Modal title="سبب تغيير الحالة" onClose={()=>setAction(null)}><textarea value={reason} onChange={e=>setReason(e.target.value)} className="w-full min-h-28 border rounded-xl p-3" placeholder="سبب إلزامي..."/><button disabled={!reason.trim()} onClick={()=>void execute()} className="w-full bg-blue-600 text-white rounded-xl py-3 font-bold mt-3 disabled:opacity-50">تنفيذ</button></Modal>}
 </div>;
}
function Actions({scenario,onAction}:{scenario:ForecastScenarioRecord;onAction:(t:Action['type'])=>void}){return <div className="flex gap-2 justify-center flex-wrap">{scenario.status==='draft'&&<button onClick={()=>onAction('submitted')} className="text-blue-700 font-bold">إرسال</button>}{scenario.status==='submitted'&&<button onClick={()=>onAction('approved')} className="text-emerald-700 font-bold">اعتماد</button>}{scenario.status==='approved'&&<button onClick={()=>onAction('closed')} className="text-slate-700 font-bold">إغلاق</button>}{['draft','submitted'].includes(scenario.status)&&<button onClick={()=>onAction('voided')} className="text-rose-700 font-bold">إلغاء</button>}</div>}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50 bg-slate-950/50 flex items-center justify-center p-4"><div className="w-full max-w-lg bg-white rounded-2xl p-6 space-y-4"><div className="flex justify-between"><h2 className="font-black text-xl">{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}
