import { type FormEvent, type ReactNode, useCallback, useEffect, useState } from 'react';
import { Loader2, Plus, RefreshCw, X } from 'lucide-react';
import { financeIntegrationService, type FinanceIntegrationConnectorRecord, type FinanceIntegrationDashboardRecord, type FinanceIntegrationEventRecord } from '../../../services/sdk/FinanceIntegrationService';
import { accountingPeriodService, fiscalYearService, legalEntityService, type AccountingPeriodRecord, type LegalEntityRecord } from '../../../services/sdk/FinanceFoundationService';
import { getErrorMessage } from '../../../services/errors';
import { useUIStore } from '../../../core/stores';
import { FinanceUnitNav } from './shared/FinanceUnitNav';

type Action={type:'reviewed'|'rejected'|'ignored'|'convert';event:FinanceIntegrationEventRecord};
export default function FinanceIntegrationsPage(){
 const {addToast}=useUIStore();const [entities,setEntities]=useState<LegalEntityRecord[]>([]),[entityId,setEntityId]=useState(''),[connectors,setConnectors]=useState<FinanceIntegrationConnectorRecord[]>([]),[events,setEvents]=useState<FinanceIntegrationEventRecord[]>([]),[dashboard,setDashboard]=useState<FinanceIntegrationDashboardRecord|null>(null),[periods,setPeriods]=useState<AccountingPeriodRecord[]>([]),[loading,setLoading]=useState(true),[showConnector,setShowConnector]=useState(false),[showEvent,setShowEvent]=useState(false),[action,setAction]=useState<Action|null>(null),[reason,setReason]=useState(''),[periodId,setPeriodId]=useState('');
 const [connectorForm,setConnectorForm]=useState({connector_code:'',connector_name:'',source_system:'procurement',direction:'inbound'}); const [eventForm,setEventForm]=useState({connector_id:'',source_system:'procurement',source_type:'supplier_invoice',event_type:'invoice_approved',amount:'',currency_code:'IQD',idempotency_key:'',payload:'{}'});
 const load=useCallback(async()=>{setLoading(true);try{const es=await legalEntityService.findActive();setEntities(es);const id=entityId||es[0]?.id||'';if(!entityId&&id)setEntityId(id);if(!id)return;const [c,e,d,years]=await Promise.all([financeIntegrationService.findConnectors(id),financeIntegrationService.findEvents(id),financeIntegrationService.findDashboard(id),fiscalYearService.findForEntity(id)]);setConnectors(c);setEvents(e);setDashboard(d[0]||null);const groups=await Promise.all(years.map(y=>accountingPeriodService.findForFiscalYear(y.id)));const open=groups.flat().filter(p=>p.status==='open');setPeriods(open);setPeriodId(cur=>cur||open[0]?.id||'')}catch(e){addToast(`تعذر التحميل: ${getErrorMessage(e)}`,'error')}finally{setLoading(false)}},[addToast,entityId]);useEffect(()=>{void load()},[load]);
 const saveConnector=async(e:FormEvent)=>{e.preventDefault();if(!entityId)return;try{await financeIntegrationService.upsertConnector({legalEntityId:entityId,connectorCode:connectorForm.connector_code,connectorName:connectorForm.connector_name,sourceSystem:connectorForm.source_system,direction:connectorForm.direction});addToast('تم حفظ Connector','success');setShowConnector(false);await load()}catch(err){addToast(getErrorMessage(err),'error')}};
 const saveEvent=async(e:FormEvent)=>{e.preventDefault();if(!entityId)return;try{await financeIntegrationService.ingestEvent({legalEntityId:entityId,connectorId:eventForm.connector_id||undefined,sourceSystem:eventForm.source_system,sourceType:eventForm.source_type,eventType:eventForm.event_type,eventDate:new Date().toISOString().slice(0,10),amount:Number(eventForm.amount||0),currencyCode:eventForm.currency_code,idempotencyKey:eventForm.idempotency_key||undefined,payload:JSON.parse(eventForm.payload||'{}')});addToast('تم استقبال الحدث','success');setShowEvent(false);await load()}catch(err){addToast(getErrorMessage(err),'error')}};
 const execute=async()=>{if(!action||!reason.trim())return addToast('السبب مطلوب','error');try{if(action.type==='convert'){if(!periodId)return addToast('اختر فترة مفتوحة','error');const payloadLines=Array.isArray(action.event.payload?.lines)?action.event.payload.lines as Array<Record<string,unknown>>:[];await financeIntegrationService.createJournalFromEvent({eventId:action.event.id,accountingPeriodId:periodId,description:action.event.event_type,reason:reason.trim(),lines:payloadLines});}else await financeIntegrationService.reviewEvent(action.event.id,action.type,reason.trim());addToast('تم تنفيذ العملية','success');setAction(null);setReason('');await load()}catch(e){addToast(getErrorMessage(e),'error')}};
 return <div className="space-y-5 max-w-[1700px] mx-auto" dir="rtl"><FinanceUnitNav unit="integrations"/><div className="flex justify-between flex-wrap gap-3"><div><p className="text-sm font-bold text-sky-700">Finance Unit 14 · Integrations</p><h1 className="text-3xl font-black">التكاملات المالية</h1><p className="text-slate-500 mt-2">Connectors وIntegration Inbox وPosting Bridge إلى GL.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="border rounded-xl px-4 py-2 font-bold bg-white"><RefreshCw size={15} className="inline ml-1"/>تحديث</button><button onClick={()=>setShowConnector(true)} className="bg-sky-600 text-white rounded-xl px-4 py-2 font-bold"><Plus size={15} className="inline ml-1"/>Connector</button><button onClick={()=>setShowEvent(true)} className="bg-slate-900 text-white rounded-xl px-4 py-2 font-bold">Ingest Event</button></div></div>
 <section className="grid md:grid-cols-5 gap-3"><Metric title="Connectors" value={dashboard?.active_connectors||0}/><Metric title="Received" value={dashboard?.received_events||0}/><Metric title="Reviewed" value={dashboard?.reviewed_events||0}/><Metric title="Converted" value={dashboard?.converted_events||0}/><Metric title="Failed/Rejected" value={dashboard?.failed_or_rejected_events||0}/></section>
 <select value={entityId} onChange={e=>setEntityId(e.target.value)} className="border rounded-xl p-3 bg-white w-full md:w-96">{entities.map(e=><option key={e.id} value={e.id}>{e.code} — {e.name_ar}</option>)}</select>
 {loading?<div className="py-24 text-center"><Loader2 className="animate-spin mx-auto mb-3"/>جارٍ التحميل...</div>:<section className="grid xl:grid-cols-[360px_1fr] gap-4"><aside className="bg-white border rounded-2xl p-5"><h2 className="font-black">Connectors</h2><div className="space-y-2 mt-3">{connectors.map(c=><div key={c.id} className="bg-slate-50 border rounded-xl p-3 text-sm"><b>{c.connector_code}</b><p>{c.connector_name}</p><p className="text-xs text-slate-400">{c.source_system} · {c.status}</p></div>)}</div></aside><div className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-right">المصدر</th><th className="p-3 text-right">الحدث</th><th className="p-3 text-right">المبلغ</th><th className="p-3 text-right">الحالة</th><th className="p-3 text-right">القيد</th><th className="p-3"/></tr></thead><tbody className="divide-y">{events.map(ev=><tr key={ev.id}><td className="p-3">{ev.source_system}/{ev.source_type}</td><td className="p-3 font-bold">{ev.event_type}</td><td className="p-3">{Number(ev.amount).toLocaleString()} {ev.currency_code}</td><td className="p-3">{ev.status}</td><td className="p-3 font-mono">{ev.entry_number||'—'}</td><td className="p-3"><Actions event={ev} onAction={(type)=>{setAction({type,event:ev});setReason('')}}/></td></tr>)}</tbody></table></div></section>}
 {showConnector&&<Modal title="Connector" onClose={()=>setShowConnector(false)}><form onSubmit={saveConnector} className="space-y-3"><input required placeholder="CODE" value={connectorForm.connector_code} onChange={e=>setConnectorForm(f=>({...f,connector_code:e.target.value.toUpperCase()}))} className="w-full border rounded-xl p-2.5"/><input required placeholder="Name" value={connectorForm.connector_name} onChange={e=>setConnectorForm(f=>({...f,connector_name:e.target.value}))} className="w-full border rounded-xl p-2.5"/><div className="grid grid-cols-2 gap-3"><select value={connectorForm.source_system} onChange={e=>setConnectorForm(f=>({...f,source_system:e.target.value}))} className="border rounded-xl p-2.5"><option value="procurement">Procurement</option><option value="inventory">Inventory</option><option value="mrp">MRP</option><option value="crm">CRM</option><option value="external">External</option><option value="manual">Manual</option></select><select value={connectorForm.direction} onChange={e=>setConnectorForm(f=>({...f,direction:e.target.value}))} className="border rounded-xl p-2.5"><option value="inbound">Inbound</option><option value="outbound">Outbound</option><option value="bidirectional">Bidirectional</option></select></div><button className="w-full bg-sky-600 text-white rounded-xl py-3 font-bold">حفظ</button></form></Modal>}
 {showEvent&&<Modal title="Ingest Event" onClose={()=>setShowEvent(false)}><form onSubmit={saveEvent} className="space-y-3"><select value={eventForm.connector_id} onChange={e=>setEventForm(f=>({...f,connector_id:e.target.value}))} className="w-full border rounded-xl p-2.5"><option value="">بدون Connector</option>{connectors.map(c=><option key={c.id} value={c.id}>{c.connector_code}</option>)}</select><div className="grid grid-cols-2 gap-3"><input placeholder="source_type" value={eventForm.source_type} onChange={e=>setEventForm(f=>({...f,source_type:e.target.value}))} className="border rounded-xl p-2.5"/><input placeholder="event_type" value={eventForm.event_type} onChange={e=>setEventForm(f=>({...f,event_type:e.target.value}))} className="border rounded-xl p-2.5"/></div><input type="number" placeholder="amount" value={eventForm.amount} onChange={e=>setEventForm(f=>({...f,amount:e.target.value}))} className="w-full border rounded-xl p-2.5"/><input placeholder="idempotency_key" value={eventForm.idempotency_key} onChange={e=>setEventForm(f=>({...f,idempotency_key:e.target.value}))} className="w-full border rounded-xl p-2.5"/><textarea value={eventForm.payload} onChange={e=>setEventForm(f=>({...f,payload:e.target.value}))} className="w-full min-h-28 border rounded-xl p-2.5"/><button className="w-full bg-slate-900 text-white rounded-xl py-3 font-bold">استقبال</button></form></Modal>}
 {action&&<Modal title={action.type==='convert'?'تحويل إلى قيد':'مراجعة الحدث'} onClose={()=>setAction(null)}>{action.type==='convert'&&<select value={periodId} onChange={e=>setPeriodId(e.target.value)} className="w-full border rounded-xl p-3 mb-3"><option value="">فترة مفتوحة</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}<textarea value={reason} onChange={e=>setReason(e.target.value)} className="w-full min-h-28 border rounded-xl p-3" placeholder="سبب إلزامي..."/><button disabled={!reason.trim()} onClick={()=>void execute()} className="w-full bg-sky-600 text-white rounded-xl py-3 font-bold mt-3 disabled:opacity-50">تنفيذ</button></Modal>}
 </div>}
function Actions({event,onAction}:{event:FinanceIntegrationEventRecord;onAction:(t:Action['type'])=>void}){return <div className="flex gap-2 flex-wrap">{['received','failed'].includes(event.status)&&<button onClick={()=>onAction('reviewed')} className="text-blue-700 font-bold">Review</button>}{['received','reviewed','failed'].includes(event.status)&&<button onClick={()=>onAction('convert')} className="text-emerald-700 font-bold">Post</button>}{['received','reviewed'].includes(event.status)&&<button onClick={()=>onAction('rejected')} className="text-rose-700 font-bold">Reject</button>}</div>}
function Metric({title,value}:{title:string;value:ReactNode}){return <div className="bg-white border rounded-2xl p-4"><p className="text-2xl font-black">{value}</p><p className="text-sm font-bold text-slate-500 mt-1">{title}</p></div>}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50 bg-slate-950/50 flex items-center justify-center p-4"><div className="w-full max-w-lg bg-white rounded-2xl p-6 space-y-4"><div className="flex justify-between"><h2 className="font-black text-xl">{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}
