import { type ReactNode, useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, Building2, Download, Loader2, RefreshCw, X } from 'lucide-react';
import { legalEntityService, type LegalEntityRecord } from '../../../services/sdk/FinanceFoundationService';
import { financialReportService, type FinanceExecutiveKpiRecord, type FinanceReportRunRecord, type TrialBalanceRow } from '../../../services/sdk/FinancialReportService';
import { getErrorMessage } from '../../../services/errors';
import { useUIStore } from '../../../core/stores';
import { FinanceUnitNav } from './shared/FinanceUnitNav';

type Action={type:'export'|'cancel';run:FinanceReportRunRecord};
export default function FinancialReportsPage(){
 const {addToast}=useUIStore();const [entities,setEntities]=useState<LegalEntityRecord[]>([]),[entityId,setEntityId]=useState(''),[rows,setRows]=useState<TrialBalanceRow[]>([]),[runs,setRuns]=useState<FinanceReportRunRecord[]>([]),[kpi,setKpi]=useState<FinanceExecutiveKpiRecord|null>(null),[loading,setLoading]=useState(true),[reportType,setReportType]=useState('executive_kpi'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[action,setAction]=useState<Action|null>(null),[reason,setReason]=useState(''),[format,setFormat]=useState<'xlsx'|'pdf'|'csv'|'json'>('xlsx');
 const load=useCallback(async()=>{setLoading(true);try{const es=await legalEntityService.findActive();setEntities(es);const id=entityId||es[0]?.id||'';if(!entityId&&id)setEntityId(id);const [tb,rs,kpis]=id?await Promise.all([financialReportService.getTrialBalance(id,from||undefined,to||undefined),financialReportService.findReportRuns(id),financialReportService.findExecutiveKpis(id)]):[[],[],[]];setRows(tb);setRuns(rs);setKpi(kpis[0]||null)}catch(e){addToast(`تعذر تحميل التقارير: ${getErrorMessage(e)}`,'error')}finally{setLoading(false)}},[addToast,entityId,from,to]);useEffect(()=>{void load()},[load]);
 const totals=useMemo(()=>{const net=(type:string,normal:'debit'|'credit')=>rows.filter(r=>r.account_type===type).reduce((s,r)=>s+(normal==='debit'?Number(r.debit_balance)-Number(r.credit_balance):Number(r.credit_balance)-Number(r.debit_balance)),0);const revenue=net('Revenue','credit'),expenses=net('Expense','debit'),assets=net('Asset','debit'),liabilities=net('Liability','credit'),equity=net('Equity','credit');return{revenue,expenses,profit:revenue-expenses,assets,liabilities,equity}},[rows]);
 const generate=async()=>{if(!entityId)return;try{await financialReportService.generateReportRun({legalEntityId:entityId,reportType,periodStart:from||undefined,periodEnd:to||undefined});addToast('تم توليد Report Run','success');await load()}catch(e){addToast(getErrorMessage(e),'error')}};
 const execute=async()=>{if(!action)return;try{if(action.type==='export')await financialReportService.requestExport(action.run.id,format);else{if(!reason.trim())return addToast('السبب مطلوب','error');await financialReportService.cancelReportRun(action.run.id,reason.trim())}addToast('تم تنفيذ العملية','success');setAction(null);setReason('');await load()}catch(e){addToast(getErrorMessage(e),'error')}};
 return <div className="space-y-5 max-w-[1700px] mx-auto" dir="rtl"><FinanceUnitNav unit="reporting"/><div className="flex justify-between items-center gap-3 flex-wrap"><div><p className="text-sm font-bold text-violet-700">Finance Unit 13 · Reporting & Analytics</p><h1 className="text-3xl font-black">التقارير المالية والتحليلات</h1><p className="text-slate-500 mt-2">Report Runs وتصدير وKPIs من الوحدات المالية.</p></div><button onClick={()=>void load()} className="border rounded-xl px-4 py-2 font-bold bg-white"><RefreshCw size={15} className="inline ml-1"/>تحديث</button></div>
 <section className="grid md:grid-cols-4 gap-3"><Metric title="Cash" value={Number(kpi?.cash_balance||0).toLocaleString()}/><Metric title="AR" value={Number(kpi?.ar_outstanding||0).toLocaleString()}/><Metric title="AP" value={Number(kpi?.ap_outstanding||0).toLocaleString()}/><Metric title="Recognized Revenue" value={Number(kpi?.recognized_revenue||0).toLocaleString()}/></section>
 <div className="grid md:grid-cols-5 gap-3"><label className="bg-white border rounded-xl p-3 flex gap-2"><Building2 size={17}/><select className="w-full outline-none" value={entityId} onChange={e=>setEntityId(e.target.value)}>{entities.map(e=><option key={e.id} value={e.id}>{e.code} — {e.name_ar}</option>)}</select></label><select value={reportType} onChange={e=>setReportType(e.target.value)} className="border rounded-xl p-3 bg-white"><option value="executive_kpi">Executive KPI</option><option value="trial_balance">Trial Balance</option><option value="profit_loss">P&L</option><option value="budget_variance">Budget Variance</option><option value="tax_summary">Tax Summary</option><option value="fixed_assets">Fixed Assets</option><option value="revenue_recognition">Revenue</option><option value="intercompany">Intercompany</option><option value="project_accounting">Projects</option></select><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="border rounded-xl p-3"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="border rounded-xl p-3"/><button onClick={()=>void generate()} className="bg-violet-600 text-white rounded-xl p-3 font-bold">توليد Report Run</button></div>
 {loading?<div className="py-24 text-center"><Loader2 className="animate-spin mx-auto mb-3"/>جارٍ احتساب التقارير…</div>:<div className="grid lg:grid-cols-2 gap-6"><section className="bg-white border rounded-2xl p-6"><h2 className="font-black flex gap-2"><BarChart3 className="text-emerald-600"/>قائمة الربح أو الخسارة</h2><Row label="الإيرادات" value={totals.revenue}/><Row label="المصروفات" value={totals.expenses}/><Row label="صافي الربح / الخسارة" value={totals.profit} strong/></section><section className="bg-white border rounded-2xl p-6"><h2 className="font-black flex gap-2"><BarChart3 className="text-blue-600"/>ملخص المركز المالي</h2><Row label="الأصول" value={totals.assets}/><Row label="الالتزامات" value={totals.liabilities}/><Row label="حقوق الملكية" value={totals.equity}/><Row label="الالتزامات + الملكية" value={totals.liabilities+totals.equity} strong/></section></div>}
 <section className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-right">التقرير</th><th className="p-3 text-right">الفترة</th><th className="p-3 text-right">الحالة</th><th className="p-3 text-right">تصديرات</th><th className="p-3"/></tr></thead><tbody className="divide-y">{runs.map(r=><tr key={r.id}><td className="p-3 font-bold">{r.report_name}</td><td className="p-3">{r.period_start||'—'} — {r.period_end||'—'}</td><td className="p-3">{r.status}</td><td className="p-3">{r.export_count||0}</td><td className="p-3"><div className="flex gap-2"><button onClick={()=>{setAction({type:'export',run:r});setFormat('xlsx')}} className="text-violet-700 font-bold"><Download size={14} className="inline"/>تصدير</button>{r.status==='generated'&&<button onClick={()=>{setAction({type:'cancel',run:r});setReason('')}} className="text-rose-700 font-bold">إلغاء</button>}</div></td></tr>)}</tbody></table></section>
 {action&&<Modal title={action.type==='export'?'طلب تصدير':'إلغاء Report Run'} onClose={()=>setAction(null)}>{action.type==='export'?<select value={format} onChange={e=>setFormat(e.target.value as typeof format)} className="w-full border rounded-xl p-3"><option value="xlsx">XLSX</option><option value="pdf">PDF</option><option value="csv">CSV</option><option value="json">JSON</option></select>:<textarea value={reason} onChange={e=>setReason(e.target.value)} className="w-full min-h-28 border rounded-xl p-3" placeholder="سبب إلزامي..."/>}<button onClick={()=>void execute()} className="w-full bg-violet-600 text-white rounded-xl py-3 font-bold mt-3">تنفيذ</button></Modal>}
 </div>};
function Row({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <div className={`flex justify-between border-b py-4 ${strong?'font-black text-lg':''}`}><span>{label}</span><span>{value.toLocaleString()}</span></div>}
function Metric({title,value}:{title:string;value:ReactNode}){return <div className="bg-white border rounded-2xl p-4"><p className="text-2xl font-black">{value}</p><p className="text-sm font-bold text-slate-500 mt-1">{title}</p></div>}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50 bg-slate-950/50 flex items-center justify-center p-4"><div className="w-full max-w-lg bg-white rounded-2xl p-6 space-y-4"><div className="flex justify-between"><h2 className="font-black text-xl">{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}
