import { type FormEvent, type ReactNode, useCallback, useEffect, useState } from 'react';
import { CheckCircle, FileCheck, Loader2, Plus, RefreshCw, X } from 'lucide-react';
import { revenueRecognitionService, type RevenueContractBoardRecord, type RevenueDashboardRecord, type RevenueScheduleRecord } from '../../../services/sdk/RevenueRecognitionService';
import { customerService, type CustomerRecord } from '../../../services/sdk/AccountsReceivableService';
import { currencyService, legalEntityService, type CurrencyRecord, type LegalEntityRecord } from '../../../services/sdk/FinanceFoundationService';
import { getErrorMessage } from '../../../services/errors';
import { useUIStore } from '../../../core/stores';
import { FinanceUnitNav } from './shared/FinanceUnitNav';

type Action={type:'schedule'|'recognize'|'status';contract?:RevenueContractBoardRecord;schedule?:RevenueScheduleRecord};
export default function RevenueRecognitionPage(){
 const {addToast}=useUIStore(); const [entities,setEntities]=useState<LegalEntityRecord[]>([]),[entityId,setEntityId]=useState(''),[customers,setCustomers]=useState<CustomerRecord[]>([]),[currencies,setCurrencies]=useState<CurrencyRecord[]>([]),[contracts,setContracts]=useState<RevenueContractBoardRecord[]>([]),[schedules,setSchedules]=useState<RevenueScheduleRecord[]>([]),[dashboard,setDashboard]=useState<RevenueDashboardRecord|null>(null),[selectedId,setSelectedId]=useState(''),[loading,setLoading]=useState(true),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[action,setAction]=useState<Action|null>(null),[reason,setReason]=useState(''),[status,setStatus]=useState<'completed'|'cancelled'|'voided'|'active'>('completed');
 const [form,setForm]=useState({contract_number:'',customer_id:'',customer_name:'',total_amount:'',contract_start:new Date().toISOString().slice(0,10),contract_end:'',recognition_method:'straight_line',currency_code:'IQD'});
 const load=useCallback(async()=>{setLoading(true);try{const [es,cs]=await Promise.all([legalEntityService.findActive(),currencyService.findActive()]);setEntities(es);setCurrencies(cs);const id=entityId||es[0]?.id||'';if(!entityId&&id)setEntityId(id);if(!id)return;const [cust,con,dash]=await Promise.all([customerService.findActiveForEntity(id),revenueRecognitionService.findBoard(id),revenueRecognitionService.findDashboard(id)]);setCustomers(cust);setContracts(con);setDashboard(dash[0]||null);const cid=selectedId&&con.some(c=>c.id===selectedId)?selectedId:con[0]?.id||'';setSelectedId(cid);setSchedules(cid?await revenueRecognitionService.findSchedule(cid):[])}catch(e){addToast(`تعذر التحميل: ${getErrorMessage(e)}`,'error')}finally{setLoading(false)}},[addToast,entityId,selectedId]);
 useEffect(()=>{void load()},[load]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!entityId)return;setSaving(true);try{const customer=customers.find(c=>c.id===form.customer_id);const c=await revenueRecognitionService.upsertContract({legalEntityId:entityId,contractNumber:form.contract_number,customerId:form.customer_id||undefined,customerName:customer?.name_ar||form.customer_name,totalAmount:Number(form.total_amount),contractStart:form.contract_start,contractEnd:form.contract_end||undefined,recognitionMethod:form.recognition_method,currencyCode:form.currency_code});addToast('تم حفظ عقد الإيراد عبر RPC','success');setShow(false);setSelectedId(c.id);setForm({contract_number:'',customer_id:'',customer_name:'',total_amount:'',contract_start:new Date().toISOString().slice(0,10),contract_end:'',recognition_method:'straight_line',currency_code:'IQD'});await load()}catch(e){addToast(getErrorMessage(e),'error')}finally{setSaving(false)}};
 const execute=async()=>{if(!action)return; if(action.type!=='schedule'&&!reason.trim())return addToast('السبب مطلوب للتدقيق','error');try{if(action.type==='schedule'&&action.contract)await revenueRecognitionService.generateSchedule(action.contract.id);else if(action.type==='recognize'&&action.schedule)await revenueRecognitionService.recognizeLine(action.schedule.id,reason.trim());else if(action.contract)await revenueRecognitionService.updateStatus(action.contract.id,status,reason.trim());addToast('تم تنفيذ العملية وتسجيلها','success');setAction(null);setReason('');await load()}catch(e){addToast(getErrorMessage(e),'error')}};
 return <div className="space-y-5 max-w-[1700px] mx-auto" dir="rtl"><FinanceUnitNav unit="revenue"/><div className="flex justify-between flex-wrap gap-3"><div><p className="text-sm font-bold text-emerald-700">Finance Unit 10 · Revenue Recognition</p><h1 className="text-3xl font-black">الاعتراف بالإيرادات IFRS 15</h1><p className="text-slate-500 mt-2">عقود + جداول اعتراف + تشغيل بسبب وتدقيق.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="border rounded-xl px-4 py-2 font-bold bg-white"><RefreshCw size={15} className="inline ml-1"/>تحديث</button><button onClick={()=>setShow(true)} className="bg-emerald-600 text-white rounded-xl px-4 py-2 font-bold"><Plus size={15} className="inline ml-1"/>عقد جديد</button></div></div>
 <section className="grid md:grid-cols-5 gap-3"><Metric title="عقود نشطة" value={dashboard?.active_contracts||0}/><Metric title="مكتملة" value={dashboard?.completed_contracts||0}/><Metric title="قيمة العقود" value={Number(dashboard?.contracted_revenue||0).toLocaleString()}/><Metric title="معترف به" value={Number(dashboard?.recognized_revenue||0).toLocaleString()}/><Metric title="سطور مجدولة" value={dashboard?.scheduled_lines||0}/></section>
 <select value={entityId} onChange={e=>setEntityId(e.target.value)} className="border rounded-xl p-3 bg-white w-full md:w-96">{entities.map(e=><option key={e.id} value={e.id}>{e.code} — {e.name_ar}</option>)}</select>
 {loading?<div className="py-24 text-center"><Loader2 className="animate-spin mx-auto mb-3"/>جارٍ التحميل...</div>:<section className="grid xl:grid-cols-[1fr_430px] gap-4"><div className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-right">العقد</th><th className="p-3 text-right">العميل</th><th className="p-3 text-right">المبلغ</th><th className="p-3 text-right">المعترف</th><th className="p-3 text-right">الطريقة</th><th className="p-3 text-right">الحالة</th><th className="p-3"/></tr></thead><tbody className="divide-y">{contracts.map(c=><tr key={c.id} className={selectedId===c.id?'bg-emerald-50/50':''}><td className="p-3"><button onClick={()=>setSelectedId(c.id)} className="font-mono font-bold text-emerald-700">{c.contract_number}</button></td><td className="p-3">{c.customer_name||'—'}</td><td className="p-3 font-black">{Number(c.total_amount).toLocaleString()} {c.currency_code}</td><td className="p-3">{Number(c.recognized_amount||0).toLocaleString()}</td><td className="p-3">{c.recognition_method}</td><td className="p-3"><span className="inline-flex items-center gap-1"><CheckCircle size={12}/>{c.status}</span></td><td className="p-3"><div className="flex gap-2 flex-wrap"><button onClick={()=>{setAction({type:'schedule',contract:c});setReason('')}} className="text-blue-700 font-bold">جدولة</button>{c.status==='active'&&<button onClick={()=>{setAction({type:'status',contract:c});setStatus('completed');setReason('')}} className="text-rose-700 font-bold">حالة</button>}</div></td></tr>)}{!contracts.length&&<tr><td colSpan={7} className="p-16 text-center text-slate-500"><FileCheck className="mx-auto mb-3 text-slate-300"/>لا توجد عقود.</td></tr>}</tbody></table></div><aside className="bg-white border rounded-2xl p-5"><h2 className="font-black">جدول الاعتراف</h2><div className="space-y-2 mt-3 max-h-[520px] overflow-auto">{schedules.map(s=><div key={s.id} className="bg-slate-50 border rounded-xl p-3 text-sm"><b>{s.period_start} — {s.period_end}</b><p>مبلغ: {Number(s.recognized_amount).toLocaleString()} · تراكمي: {Number(s.cumulative_amount).toLocaleString()}</p><p className="text-xs text-slate-400">{s.status}</p>{s.status==='scheduled'&&<button onClick={()=>{setAction({type:'recognize',schedule:s});setReason('')}} className="text-emerald-700 font-bold mt-2">اعتراف</button>}</div>)}</div></aside></section>}
 {show&&<Modal title="عقد إيراد جديد" onClose={()=>setShow(false)}><form onSubmit={submit} className="space-y-3"><input required placeholder="رقم العقد" value={form.contract_number} onChange={e=>setForm(f=>({...f,contract_number:e.target.value.toUpperCase()}))} className="w-full border rounded-xl p-2.5"/><select value={form.customer_id} onChange={e=>setForm(f=>({...f,customer_id:e.target.value}))} className="w-full border rounded-xl p-2.5"><option value="">اختر عميلاً أو اكتب اسم</option>{customers.map(c=><option key={c.id} value={c.id}>{c.customer_code} — {c.name_ar}</option>)}</select><input placeholder="اسم العميل" value={form.customer_name} onChange={e=>setForm(f=>({...f,customer_name:e.target.value}))} className="w-full border rounded-xl p-2.5"/><div className="grid grid-cols-2 gap-3"><input required type="number" placeholder="المبلغ" value={form.total_amount} onChange={e=>setForm(f=>({...f,total_amount:e.target.value}))} className="border rounded-xl p-2.5"/><select value={form.currency_code} onChange={e=>setForm(f=>({...f,currency_code:e.target.value}))} className="border rounded-xl p-2.5">{currencies.map(c=><option key={c.code}>{c.code}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><input required type="date" value={form.contract_start} onChange={e=>setForm(f=>({...f,contract_start:e.target.value}))} className="border rounded-xl p-2.5"/><input type="date" value={form.contract_end} onChange={e=>setForm(f=>({...f,contract_end:e.target.value}))} className="border rounded-xl p-2.5"/></div><select value={form.recognition_method} onChange={e=>setForm(f=>({...f,recognition_method:e.target.value}))} className="w-full border rounded-xl p-2.5"><option value="straight_line">Straight Line</option><option value="milestone">Milestone</option><option value="usage_based">Usage Based</option></select><button disabled={saving} className="w-full bg-emerald-600 text-white rounded-xl py-3 font-bold">حفظ</button></form></Modal>}
 {action&&<Modal title={action.type==='schedule'?'توليد جدول الاعتراف':action.type==='recognize'?'تشغيل الاعتراف':'تغيير حالة العقد'} onClose={()=>setAction(null)}>{action.type==='status'&&<select value={status} onChange={e=>setStatus(e.target.value as typeof status)} className="w-full border rounded-xl p-3 mb-3"><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="voided">Voided</option><option value="active">Active</option></select>}{action.type!=='schedule'&&<textarea value={reason} onChange={e=>setReason(e.target.value)} className="w-full min-h-28 border rounded-xl p-3" placeholder="سبب إلزامي..."/>}<button disabled={action.type!=='schedule'&&!reason.trim()} onClick={()=>void execute()} className="w-full bg-emerald-600 text-white rounded-xl py-3 font-bold mt-3 disabled:opacity-50">تنفيذ</button></Modal>}
 </div>;
}
function Metric({title,value}:{title:string;value:ReactNode}){return <div className="bg-white border rounded-2xl p-4"><p className="text-2xl font-black">{value}</p><p className="text-sm font-bold text-slate-500 mt-1">{title}</p></div>}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50 bg-slate-950/50 flex items-center justify-center p-4"><div className="w-full max-w-lg bg-white rounded-2xl p-6 space-y-4"><div className="flex justify-between"><h2 className="font-black text-xl">{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}
