import { useCallback, useEffect, useState } from 'react';
import { ClipboardCheck, Loader2, Plus } from 'lucide-react';
import { useAuthStore, useUIStore } from '../../core/stores';
import { operationalChecklistService } from '../../services/sdk';
import Card from '../../shared/components/ui/Card';
import Button from '../../shared/components/ui/Button';
import { getErrorMessage } from '../../services/errors';

const defaultItems = ['نظافة منطقة العمل', 'توفر معدات السلامة', 'عمل المعدات بشكل طبيعي', 'عدم وجود مخاطر ظاهرة'];
export default function SupervisorChecklistsPage(){
 const {user}=useAuthStore(); const {addToast}=useUIStore(); const [loading,setLoading]=useState(true); const [rows,setRows]=useState<any[]>([]); const [show,setShow]=useState(false); const [form,setForm]=useState({checklist_type:'safety',title:'فحص السلامة اليومي',items:defaultItems.map(t=>({text:t,ok:false,note:''}))});
 const load=useCallback(async()=>{if(!user?.id)return; setLoading(true); try{setRows(await operationalChecklistService.findBySupervisor(user.id))}catch(e){addToast(getErrorMessage(e),'error')}finally{setLoading(false)}},[addToast,user?.id]); useEffect(()=>{load()},[load]);
 const submit=async()=>{const okCount=form.items.filter((i:any)=>i.ok).length; const score=Math.round((okCount/form.items.length)*100); try{await operationalChecklistService.createChecklist({supervisor_id:user?.id, checklist_type:form.checklist_type as any, title:form.title, items:form.items, score}); addToast('تم إرسال قائمة الفحص','success'); setShow(false); setForm({checklist_type:'safety',title:'فحص السلامة اليومي',items:defaultItems.map(t=>({text:t,ok:false,note:''}))}); await load()}catch(e){addToast(getErrorMessage(e),'error')}};
 if(loading)return <div className="flex items-center justify-center py-20"><Loader2 className="animate-spin text-blue-600" size={36}/></div>;
 return <div className="space-y-6 animate-fade-in" dir="rtl"><div className="bg-gradient-to-br from-blue-600 to-blue-800 rounded-2xl p-6 text-white flex items-center justify-between"><div><p className="text-white/70 text-sm">Operational Checklists</p><h2 className="text-2xl font-extrabold mt-1 flex items-center gap-2"><ClipboardCheck/> قوائم الفحص</h2></div><Button onClick={()=>setShow(true)} className="!bg-white/15 hover:!bg-white/25 !text-white !border-none" icon={<Plus size={16}/>} iconPosition="left">فحص جديد</Button></div><div className="grid gap-3">{rows.length===0?<Card><p className="text-center py-8 text-slate-400">لا توجد قوائم فحص</p></Card>:rows.map(r=><Card key={r.id}><div className="flex items-center justify-between"><div><p className="font-bold text-slate-900">{r.title}</p><p className="text-xs text-slate-500 mt-1">{r.checklist_type} • {new Date(r.created_at).toLocaleDateString('ar')}</p></div><span className={`text-xs font-bold px-3 py-1 rounded-full ${r.score>=80?'bg-emerald-50 text-emerald-700':r.score>=50?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700'}`}>{r.score||0}%</span></div></Card>)}</div>{show&&<ChecklistModal form={form} setForm={setForm} onClose={()=>setShow(false)} onSubmit={submit}/>}</div>
}
function ChecklistModal({form,setForm,onClose,onSubmit}:any){const update=(idx:number,key:string,val:any)=>{const items=[...form.items]; items[idx]={...items[idx],[key]:val}; setForm({...form,items})}; return <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={onClose}><div className="bg-white rounded-2xl p-6 w-full max-w-md" onClick={e=>e.stopPropagation()}><h3 className="font-bold text-lg mb-4">قائمة فحص</h3><div className="space-y-3"><select value={form.checklist_type} onChange={e=>setForm({...form,checklist_type:e.target.value})} className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-blue-400"><option value="safety">سلامة</option><option value="quality">جودة</option><option value="opening">افتتاح وردية</option><option value="closing">إغلاق وردية</option><option value="equipment">معدات</option></select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-blue-400"/>{form.items.map((it:any,i:number)=><div key={i} className="p-3 rounded-xl bg-slate-50"><label className="flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={it.ok} onChange={e=>update(i,'ok',e.target.checked)}/>{it.text}</label><input value={it.note} onChange={e=>update(i,'note',e.target.value)} placeholder="ملاحظة" className="input mt-2"/></div>)}<div className="flex gap-2"><Button variant="secondary" fullWidth onClick={onClose}>إلغاء</Button><Button fullWidth onClick={onSubmit}>إرسال</Button></div></div></div></div>}
