import { useCallback, useEffect, useState } from 'react';
import { CalendarClock, Loader2, Plus, StickyNote } from 'lucide-react';
import { useAuthStore, useUIStore } from '../../core/stores';
import { shiftNoteService } from '../../services/sdk';
import Card from '../../shared/components/ui/Card';
import Button from '../../shared/components/ui/Button';
import { getErrorMessage } from '../../services/errors';
import { format } from 'date-fns';

export default function SupervisorShiftPage() {
  const { user } = useAuthStore();
  const { addToast } = useUIStore();
  const [loading, setLoading] = useState(true);
  const [notes, setNotes] = useState<any[]>([]);
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ shift_type: 'morning', note_type: 'general', title: '', content: '', severity: 'info' });
  const loadData = useCallback(async()=>{ if(!user?.id)return; setLoading(true); try{ setNotes(await shiftNoteService.findBySupervisor(user.id)); }catch(err){addToast(getErrorMessage(err),'error')} finally{setLoading(false)}},[addToast,user?.id]);
  useEffect(()=>{loadData()},[loadData]);
  const createNote=async()=>{ if(!form.title.trim()) return addToast('يرجى إدخال عنوان الملاحظة','warning'); try{ await shiftNoteService.createNote({ supervisor_id:user?.id, shift_date:format(new Date(),'yyyy-MM-dd'), shift_type:form.shift_type, note_type:form.note_type as any, title:form.title, content:form.content||undefined, severity:form.severity as any }); addToast('تم حفظ ملاحظة الوردية','success'); setShowCreate(false); setForm({shift_type:'morning',note_type:'general',title:'',content:'',severity:'info'}); await loadData();}catch(err){addToast(getErrorMessage(err),'error')}};
  if(loading)return <div className="flex items-center justify-center py-20"><Loader2 className="animate-spin text-blue-600" size={36}/></div>;
  return <div className="space-y-6 animate-fade-in" dir="rtl"><div className="bg-gradient-to-br from-blue-600 to-blue-800 rounded-2xl p-6 text-white flex items-center justify-between"><div><p className="text-white/70 text-sm">Shift Operations</p><h2 className="text-2xl font-extrabold mt-1 flex items-center gap-2"><CalendarClock/> إدارة الوردية</h2><p className="text-white/75 mt-2 text-sm">تسجيل ملاحظات وتسليمات الوردية.</p></div><Button onClick={()=>setShowCreate(true)} className="!bg-white/15 hover:!bg-white/25 !text-white !border-none" icon={<Plus size={16}/>} iconPosition="left">ملاحظة</Button></div><div className="grid gap-3">{notes.length===0?<Card><p className="text-center py-8 text-slate-400">لا توجد ملاحظات وردية</p></Card>:notes.map(n=><Card key={n.id}><div className="flex items-start gap-3"><StickyNote className={n.severity==='critical'?'text-red-600':n.severity==='warning'?'text-amber-600':'text-blue-600'} /><div><p className="font-bold text-slate-900">{n.title}</p><p className="text-xs text-slate-500 mt-1">{n.shift_date} • {n.shift_type} • {n.note_type} • {n.severity}</p>{n.content&&<p className="text-sm text-slate-600 mt-2">{n.content}</p>}</div></div></Card>)}</div>{showCreate&&<NoteModal form={form} setForm={setForm} onClose={()=>setShowCreate(false)} onSubmit={createNote}/>}</div>
}
function NoteModal({form,setForm,onClose,onSubmit}:any){return <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={onClose}><div className="bg-white rounded-2xl p-6 w-full max-w-md" onClick={e=>e.stopPropagation()}><h3 className="font-bold text-lg mb-4">ملاحظة وردية</h3><div className="space-y-3"><select value={form.shift_type} onChange={e=>setForm({...form,shift_type:e.target.value})} className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-blue-400"><option value="morning">صباحية</option><option value="evening">مسائية</option><option value="night">ليلية</option></select><select value={form.note_type} onChange={e=>setForm({...form,note_type:e.target.value})} className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-blue-400"><option value="general">عام</option><option value="handover">تسليم وردية</option><option value="issue">مشكلة</option><option value="safety">سلامة</option><option value="quality">جودة</option></select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="العنوان" className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-blue-400"/><textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} rows={3} placeholder="التفاصيل" className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-blue-400"/><select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})} className="w-full border border-slate-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-blue-400"><option value="info">معلومة</option><option value="warning">تحذير</option><option value="critical">حرج</option></select><div className="flex gap-2"><Button variant="secondary" fullWidth onClick={onClose}>إلغاء</Button><Button fullWidth onClick={onSubmit}>حفظ</Button></div></div></div></div>}
