import { useEffect, useState } from 'react';
import { ItemLookup, SupplierLookup } from '../../inventory/shared/InventoryLookups';
import { InventoryRecordTools } from '../../inventory/shared/InventoryRecordTools';
import { mrpLookupService, mrpProcurementAlertService, mrpProcurementAnalyticsService, mrpProcurementRecommendationService, mrpSupplierTcoService } from '../../../../services/sdk';
import { MrpUnitNav } from '../shared/MrpUnitNav';

type Row=Record<string,unknown>; type Form=Record<string,string>; type Config={title:string;subtitle:string;load:()=>Promise<Row[]>;columns:{key:string;label:string}[];action?:string};
function inp(l:string,n:string,f:Form,set:(p:Form)=>void,type='text'){return <label className="text-xs font-bold"><span>{l}</span><input type={type} value={f[n]||''} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1"/></label>}
function select(l:string,n:string,f:Form,set:(p:Form)=>void,ops:string[]){return <label className="text-xs font-bold"><span>{l}</span><select value={f[n]||ops[0]} onChange={e=>set({[n]:e.target.value})} className="w-full border rounded-xl p-2 mt-1 bg-white">{ops.map(o=><option key={o}>{o}</option>)}</select></label>}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-white border rounded-2xl p-4"><h3 className="font-black mb-3">{title}</h3>{children}</div>}
function Msg({msg}:{msg:string}){return msg?<div className="md:col-span-3 text-xs bg-slate-100 rounded-xl p-2">{msg}</div>:null}
function RecommendationLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('procurementRecommendation').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>Recommendation</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.recommendation_number)} — {String(r.description)} — {String(r.status)}</option>)}</select></label>}
function ExplosionRunLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('bomExplosionRun').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>BOM Explosion Run</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.run_number)} — {String(r.demand_quantity)} — {String(r.status)}</option>)}</select></label>}
function TcoLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('supplierTcoCandidate').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>TCO Candidate</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.recommendation_number)} — {String(r.supplier_name)} — {String(r.tco_score)} — {String(r.status)}</option>)}</select></label>}
function ProcurementAlertLookup({value,onChange}:{value?:string;onChange:(id:string)=>void}){const[rows,setRows]=useState<Row[]>([]);useEffect(()=>{mrpLookupService.find('procurementAlert').then(data=>setRows(data as Row[])).catch(()=>setRows([]))},[]);return <label className="text-xs font-bold"><span>Procurement Alert</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="w-full border rounded-xl p-2 mt-1 bg-white"><option value="">-- اختر --</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.alert_type)} — {String(r.severity)} — {String(r.status)} — {String(r.title).slice(0,40)}</option>)}</select></label>}
const cfgs:Record<string,Config>={
 dashboard:{title:'تكامل المشتريات مع MRP',subtitle:'توصيات شراء، PR، PO، GR، الموردين والعقود.',load:()=>mrpProcurementAnalyticsService.dashboard() as Promise<Row[]>,columns:[{key:'open_recommendations',label:'توصيات مفتوحة'},{key:'mrp_pr_count',label:'PR من MRP'},{key:'open_pos',label:'PO مفتوحة'},{key:'open_alerts',label:'تنبيهات'}]},
 recommendations:{title:'توصيات الشراء',subtitle:'نواقص MRP قابلة للتحويل إلى PR',load:()=>mrpProcurementAnalyticsService.queue() as Promise<Row[]>,action:'recommendation',columns:[{key:'recommendation_number',label:'التوصية'},{key:'description',label:'الوصف'},{key:'required_qty',label:'الكمية'},{key:'required_date',label:'تاريخ الحاجة'},{key:'priority',label:'الأولوية'},{key:'status',label:'الحالة'}]},
 pr:{title:'طلبات الشراء من MRP',subtitle:'PRs المحولة إلى بوابة المشتريات',load:()=>mrpProcurementAnalyticsService.pr() as Promise<Row[]>,columns:[{key:'pr_number',label:'PR'},{key:'recommendation_number',label:'التوصية'},{key:'status',label:'الحالة'},{key:'needed_by_date',label:'تاريخ الحاجة'},{key:'total_estimated',label:'المبلغ'}]},
 rfq:{title:'RFQ / TCO',subtitle:'مرشحو الموردين وتقييم TCO',load:()=>mrpProcurementAnalyticsService.tco() as Promise<Row[]>,action:'tco',columns:[{key:'supplier_id',label:'المورد'},{key:'quoted_unit_price',label:'السعر'},{key:'lead_time_days',label:'Lead Time'},{key:'quality_score',label:'الجودة'},{key:'otif_score',label:'OTIF'},{key:'tco_score',label:'TCO'}]},
 po:{title:'أوامر الشراء',subtitle:'حالة PO المرتبطة بالمشتريات',load:()=>mrpProcurementAnalyticsService.po() as Promise<Row[]>,columns:[{key:'po_number',label:'PO'},{key:'supplier_name',label:'المورد'},{key:'status',label:'الحالة'},{key:'delivery_date',label:'التسليم'},{key:'total_amount',label:'المبلغ'}]},
 gr:{title:'استلام البضائع',subtitle:'GR المرتبط بالـ PO',load:()=>mrpProcurementAnalyticsService.gr() as Promise<Row[]>,columns:[{key:'gr_number',label:'GR'},{key:'po_number',label:'PO'},{key:'status',label:'الحالة'},{key:'received_date',label:'تاريخ الاستلام'}]},
 invoices:{title:'الفواتير والمطابقة',subtitle:'3-Way Matching status',load:()=>mrpProcurementAnalyticsService.invoices() as Promise<Row[]>,columns:[{key:'invoice_number',label:'الفاتورة'},{key:'supplier_name',label:'المورد'},{key:'po_number',label:'PO'},{key:'status',label:'الحالة'},{key:'total_amount',label:'المبلغ'}]},
 suppliers:{title:'Supplier Scorecard',subtitle:'OTIF/Quality/TCO',load:()=>mrpProcurementAnalyticsService.suppliers() as Promise<Row[]>,columns:[{key:'supplier_code',label:'الكود'},{key:'legal_name',label:'المورد'},{key:'otif_proxy_percent',label:'OTIF'},{key:'quality_proxy_percent',label:'Quality'},{key:'supplier_grade',label:'التصنيف'}]},
 contracts:{title:'تنبيهات العقود',subtitle:'عقود الموردين التي تقترب من الانتهاء',load:()=>mrpProcurementAnalyticsService.contracts() as Promise<Row[]>,columns:[{key:'contract_number',label:'العقد'},{key:'title',label:'العنوان'},{key:'end_date',label:'النهاية'},{key:'days_to_expiry',label:'أيام'}]},
 alerts:{title:'تنبيهات المشتريات',subtitle:'نقص مواد، عقود، موردين',load:()=>mrpProcurementAnalyticsService.alerts() as Promise<Row[]>,action:'alerts',columns:[{key:'alert_type',label:'النوع'},{key:'severity',label:'الشدة'},{key:'title',label:'العنوان'},{key:'status',label:'الحالة'}]},
 reports:{title:'KPIs المشتريات',subtitle:'Cycle time، طوارئ، موردين ممتازين',load:()=>mrpProcurementAnalyticsService.kpis() as Promise<Row[]>,columns:[{key:'mrp_pr_count',label:'MRP PR'},{key:'avg_pr_to_po_days',label:'PR→PO أيام'},{key:'emergency_pr_count',label:'طوارئ'},{key:'excellent_suppliers',label:'موردون ممتازون'}]},
};
function Action({type,onDone}:{type:string;onDone:()=>void}){const[f,setF]=useState<Form>({priority:'normal',source_type:'manual',required_qty:'1',estimated_unit_price:'0'});const[msg,setMsg]=useState('');const set=(p:Form)=>setF(x=>({...x,...p}));const run=async(fn:()=>Promise<unknown>)=>{try{const r=await fn();setMsg('تم: '+String(r||'ok'));onDone()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 if(type==='recommendation')return <Box title="إنشاء/تحويل توصية"><div className="grid md:grid-cols-3 gap-3"><ItemLookup label="الصنف" value={f.item_id} onChange={id=>set({item_id:id})}/>{inp('Required Qty','required_qty',f,set,'number')}{inp('Required Date','required_date',f,set,'date')}{select('Priority','priority',f,set,['normal','urgent','emergency'])}<SupplierLookup label="المورد المقترح" value={f.supplier_id} onChange={id=>set({supplier_id:id})}/>{inp('Estimated Unit Price','estimated_unit_price',f,set,'number')}{inp('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpProcurementRecommendationService.createRecommendation(f))} className="bg-indigo-600 text-white rounded-xl p-2">Create Recommendation</button><RecommendationLookup value={f.recommendation_id} onChange={id=>set({recommendation_id:id})}/>{select('Review Status','review_status',f,set,['reviewed','rfq_required','cancelled'])}<button onClick={()=>void run(()=>mrpProcurementRecommendationService.review(f))} className="bg-blue-600 text-white rounded-xl p-2">Review/Cancel</button><button onClick={()=>void run(()=>mrpProcurementRecommendationService.convertToPr(f.recommendation_id))} className="bg-emerald-600 text-white rounded-xl p-2">Convert to PR</button><ExplosionRunLookup value={f.explosion_run_id} onChange={id=>set({explosion_run_id:id})}/><button onClick={()=>void run(()=>mrpProcurementRecommendationService.fromShortages(f.explosion_run_id))} className="bg-slate-700 text-white rounded-xl p-2">From Shortages</button><Msg msg={msg}/></div></Box>;
 if(type==='tco')return <Box title="مرشح TCO"><div className="grid md:grid-cols-3 gap-3"><RecommendationLookup value={f.recommendation_id} onChange={id=>set({recommendation_id:id})}/><SupplierLookup label="المورد" value={f.supplier_id} onChange={id=>set({supplier_id:id})}/>{inp('Unit Price','quoted_unit_price',f,set,'number')}{inp('Lead Time','lead_time_days',f,set,'number')}{inp('Quality Score','quality_score',f,set,'number')}{inp('OTIF Score','otif_score',f,set,'number')}{inp('Delay Risk Cost','delay_risk_cost',f,set,'number')}{inp('Quality Risk Cost','quality_risk_cost',f,set,'number')}<button onClick={()=>void run(()=>mrpSupplierTcoService.addCandidate(f))} className="bg-indigo-600 text-white rounded-xl p-2">Add Candidate</button><TcoLookup value={f.tco_id} onChange={id=>set({tco_id:id})}/>{inp('Award Reason','award_reason',f,set)}<button onClick={()=>void run(()=>mrpSupplierTcoService.award(f.tco_id,f.award_reason))} className="bg-emerald-600 text-white rounded-xl p-2">Award Supplier</button><Msg msg={msg}/></div></Box>;
 if(type==='alerts')return <Box title="تنبيهات المشتريات"><div className="grid md:grid-cols-3 gap-3"><button onClick={()=>void run(()=>mrpProcurementAlertService.generate())} className="bg-indigo-600 text-white rounded-xl p-2">Generate Alerts</button><ProcurementAlertLookup value={f.alert_id} onChange={id=>set({alert_id:id})}/>{select('Status','alert_status',f,set,['resolved','acknowledged','dismissed'])}{inp('Reason','reason',f,set)}<button onClick={()=>void run(()=>mrpProcurementAlertService.close(f.alert_id,f.alert_status||'resolved',f.reason))} className="bg-emerald-600 text-white rounded-xl p-2">Close/Ack Alert</button><Msg msg={msg}/></div></Box>;
 return null}
export function MrpProcurementPage({type}:{type:keyof typeof cfgs}){const c=cfgs[type];const[rows,setRows]=useState<Row[]>([]);const[r,setR]=useState(0);useEffect(()=>{c.load().then(setRows).catch(()=>setRows([]))},[c,r]);return <div dir="rtl" className="space-y-5"><div><h1 className="text-3xl font-black">{c.title}</h1><p className="text-slate-500">{c.subtitle}</p></div>{type==='dashboard'&&<MrpUnitNav unit="procurement" />}{c.action&&<Action type={c.action} onDone={()=>setR(x=>x+1)}/>}<div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{c.columns.map(x=><th key={x.key} className="p-3 text-right">{x.label}</th>)}<th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??i)} className="border-t">{c.columns.map(x=><td key={x.key} className="p-3">{String(row[x.key]??'—')}</td>)}<td className="p-3"><InventoryRecordTools row={row}/></td></tr>)}{!rows.length&&<tr><td colSpan={c.columns.length+1} className="p-10 text-center text-slate-400">لا توجد بيانات</td></tr>}</tbody></table></div></div>}
