CREATE TABLE IF NOT EXISTS public.vendor_payments (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE, legal_entity_id UUID NOT NULL REFERENCES public.legal_entities(id) ON DELETE CASCADE, vendor_id UUID NOT NULL REFERENCES public.vendors(id) ON DELETE RESTRICT, payment_number TEXT NOT NULL, payment_date DATE NOT NULL DEFAULT CURRENT_DATE, amount NUMERIC(15,2) NOT NULL CHECK(amount>0), currency_code CHAR(3) NOT NULL REFERENCES public.currencies(code), reference TEXT, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','posted','voided')), created_by UUID REFERENCES public.profiles(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(legal_entity_id,payment_number));
CREATE TABLE IF NOT EXISTS public.vendor_payment_allocations (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE, legal_entity_id UUID NOT NULL REFERENCES public.legal_entities(id) ON DELETE CASCADE, payment_id UUID NOT NULL REFERENCES public.vendor_payments(id) ON DELETE CASCADE, ap_invoice_id UUID NOT NULL REFERENCES public.accounts_payable(id) ON DELETE RESTRICT, allocated_amount NUMERIC(15,2) NOT NULL CHECK(allocated_amount>0), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(payment_id,ap_invoice_id));
ALTER TABLE public.vendor_payments ENABLE ROW LEVEL SECURITY; ALTER TABLE public.vendor_payment_allocations ENABLE ROW LEVEL SECURITY;
CREATE POLICY finance_vendor_payments_access ON public.vendor_payments FOR ALL TO authenticated USING(public.current_user_can_access_legal_entity(legal_entity_id)) WITH CHECK(public.current_user_can_manage_legal_entity(legal_entity_id));
CREATE POLICY finance_vendor_payment_allocations_access ON public.vendor_payment_allocations FOR ALL TO authenticated USING(public.current_user_can_access_legal_entity(legal_entity_id)) WITH CHECK(public.current_user_can_manage_legal_entity(legal_entity_id));
CREATE OR REPLACE FUNCTION public.post_vendor_payment(p_payment_id UUID) RETURNS public.vendor_payments LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE p public.vendor_payments%ROWTYPE; total NUMERIC; BEGIN SELECT * INTO p FROM public.vendor_payments WHERE id=p_payment_id FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'Payment not found'; END IF; IF NOT public.current_user_can_manage_legal_entity(p.legal_entity_id) OR p.status<>'draft' THEN RAISE EXCEPTION 'Payment cannot be posted'; END IF; SELECT COALESCE(SUM(allocated_amount),0) INTO total FROM public.vendor_payment_allocations WHERE payment_id=p.id; IF total<>p.amount THEN RAISE EXCEPTION 'Payment allocations must equal payment amount'; END IF; IF EXISTS(SELECT 1 FROM public.vendor_payment_allocations a JOIN public.accounts_payable i ON i.id=a.ap_invoice_id WHERE a.payment_id=p.id AND (i.legal_entity_id<>p.legal_entity_id OR i.vendor_id<>p.vendor_id OR i.status NOT IN ('approved','partially_paid') OR i.amount_paid+a.allocated_amount>i.amount)) THEN RAISE EXCEPTION 'Invalid payment allocation'; END IF; UPDATE public.accounts_payable i SET amount_paid=i.amount_paid+a.allocated_amount,status=CASE WHEN i.amount_paid+a.allocated_amount=i.amount THEN 'paid' ELSE 'partially_paid' END FROM public.vendor_payment_allocations a WHERE a.payment_id=p.id AND a.ap_invoice_id=i.id; UPDATE public.vendor_payments SET status='posted' WHERE id=p.id RETURNING * INTO p; INSERT INTO public.finance_audit_events(tenant_id,legal_entity_id,event_type,aggregate_type,aggregate_id,actor_id,after_data) VALUES(p.tenant_id,p.legal_entity_id,'vendor_payment_posted','vendor_payment',p.id,auth.uid(),to_jsonb(p)); RETURN p; END; $$;
REVOKE ALL ON FUNCTION public.post_vendor_payment(UUID) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.post_vendor_payment(UUID) TO authenticated;
